.TH "apollo::hdmap::ObjectOverlapInfo::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::hdmap::ObjectOverlapInfo::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBObjectOverlapInfo\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::hdmap::Id\fP & \fBid\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::LaneOverlapInfo\fP & \fBlane_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::SignalOverlapInfo\fP & \fBsignal_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::StopSignOverlapInfo\fP & \fBstop_sign_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::CrosswalkOverlapInfo\fP & \fBcrosswalk_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::JunctionOverlapInfo\fP & \fBjunction_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::YieldOverlapInfo\fP & \fByield_sign_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::ClearAreaOverlapInfo\fP & \fBclear_area_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::SpeedBumpOverlapInfo\fP & \fBspeed_bump_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::ParkingSpaceOverlapInfo\fP & \fBparking_space_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::PNCJunctionOverlapInfo\fP & \fBpnc_junction_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::RSUOverlapInfo\fP & \fBrsu_overlap_info\fP (const \fBObjectOverlapInfo\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
