.TH "apollo::hdmap::Lane::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::hdmap::Lane::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBLane\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::hdmap::Id\fP & \fBid\fP (const \fBLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::Curve\fP & \fBcentral_curve\fP (const \fBLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_central_curve\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::LaneBoundary\fP & \fBleft_boundary\fP (const \fBLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_left_boundary\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::LaneBoundary\fP & \fBright_boundary\fP (const \fBLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_right_boundary\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_length\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_limit\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_turn\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::hdmap::Id\fP & \fBjunction_id\fP (const \fBLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_junction_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_direction\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
