.TH "apollo::cyber::proto::ChunkHeader" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::ChunkHeader
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkBeginTimeFieldNumber\fP = 1, \fBkEndTimeFieldNumber\fP = 2, \fBkMessageNumberFieldNumber\fP = 3, \fBkRawSizeFieldNumber\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBChunkHeader\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBChunkHeader\fP (const \fBChunkHeader\fP &from)"
.br
.ti -1c
.RI "\fBChunkHeader\fP (\fBChunkHeader\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBChunkHeader\fP & \fBoperator=\fP (const \fBChunkHeader\fP &from)"
.br
.ti -1c
.RI "\fBChunkHeader\fP & \fBoperator=\fP (\fBChunkHeader\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBChunkHeader\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBChunkHeader\fP *other)"
.br
.ti -1c
.RI "\fBChunkHeader\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBChunkHeader\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBChunkHeader\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_begin_time\fP () const"
.br
.ti -1c
.RI "void \fBclear_begin_time\fP ()"
.br
.ti -1c
.RI "uint64_t \fBbegin_time\fP () const"
.br
.ti -1c
.RI "void \fBset_begin_time\fP (uint64_t value)"
.br
.ti -1c
.RI "bool \fBhas_end_time\fP () const"
.br
.ti -1c
.RI "void \fBclear_end_time\fP ()"
.br
.ti -1c
.RI "uint64_t \fBend_time\fP () const"
.br
.ti -1c
.RI "void \fBset_end_time\fP (uint64_t value)"
.br
.ti -1c
.RI "bool \fBhas_message_number\fP () const"
.br
.ti -1c
.RI "void \fBclear_message_number\fP ()"
.br
.ti -1c
.RI "uint64_t \fBmessage_number\fP () const"
.br
.ti -1c
.RI "void \fBset_message_number\fP (uint64_t value)"
.br
.ti -1c
.RI "bool \fBhas_raw_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_raw_size\fP ()"
.br
.ti -1c
.RI "uint64_t \fBraw_size\fP () const"
.br
.ti -1c
.RI "void \fBset_raw_size\fP (uint64_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBChunkHeader\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBChunkHeader\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBChunkHeader\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_cyber_2fproto_2frecord_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBChunkHeader\fP &a, \fBChunkHeader\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::cyber::proto::ChunkHeader::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ChunkHeader::MergeImpl
}
.fi
.SS "constexpr int apollo::cyber::proto::ChunkHeader::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    7
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
