.TH "apollo::common::PathPoint" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::common::PathPoint
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLaneIdFieldNumber\fP = 9, \fBkXFieldNumber\fP = 1, \fBkYFieldNumber\fP = 2, \fBkZFieldNumber\fP = 3, \fBkThetaFieldNumber\fP = 4, \fBkKappaFieldNumber\fP = 5, \fBkSFieldNumber\fP = 6, \fBkDkappaFieldNumber\fP = 7, \fBkDdkappaFieldNumber\fP = 8, \fBkXDerivativeFieldNumber\fP = 10, \fBkYDerivativeFieldNumber\fP = 11 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBPathPoint\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBPathPoint\fP (const \fBPathPoint\fP &from)"
.br
.ti -1c
.RI "\fBPathPoint\fP (\fBPathPoint\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBPathPoint\fP & \fBoperator=\fP (const \fBPathPoint\fP &from)"
.br
.ti -1c
.RI "\fBPathPoint\fP & \fBoperator=\fP (\fBPathPoint\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBPathPoint\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBPathPoint\fP *other)"
.br
.ti -1c
.RI "\fBPathPoint\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBPathPoint\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBPathPoint\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_lane_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_lane_id\fP ()"
.br
.ti -1c
.RI "const std::string & \fBlane_id\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_lane_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_lane_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_lane_id\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_lane_id\fP (std::string *lane_id)"
.br
.ti -1c
.RI "bool \fBhas_x\fP () const"
.br
.ti -1c
.RI "void \fBclear_x\fP ()"
.br
.ti -1c
.RI "double \fBx\fP () const"
.br
.ti -1c
.RI "void \fBset_x\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_y\fP () const"
.br
.ti -1c
.RI "void \fBclear_y\fP ()"
.br
.ti -1c
.RI "double \fBy\fP () const"
.br
.ti -1c
.RI "void \fBset_y\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_z\fP () const"
.br
.ti -1c
.RI "void \fBclear_z\fP ()"
.br
.ti -1c
.RI "double \fBz\fP () const"
.br
.ti -1c
.RI "void \fBset_z\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_theta\fP () const"
.br
.ti -1c
.RI "void \fBclear_theta\fP ()"
.br
.ti -1c
.RI "double \fBtheta\fP () const"
.br
.ti -1c
.RI "void \fBset_theta\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_kappa\fP () const"
.br
.ti -1c
.RI "void \fBclear_kappa\fP ()"
.br
.ti -1c
.RI "double \fBkappa\fP () const"
.br
.ti -1c
.RI "void \fBset_kappa\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_s\fP () const"
.br
.ti -1c
.RI "void \fBclear_s\fP ()"
.br
.ti -1c
.RI "double \fBs\fP () const"
.br
.ti -1c
.RI "void \fBset_s\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_dkappa\fP () const"
.br
.ti -1c
.RI "void \fBclear_dkappa\fP ()"
.br
.ti -1c
.RI "double \fBdkappa\fP () const"
.br
.ti -1c
.RI "void \fBset_dkappa\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_ddkappa\fP () const"
.br
.ti -1c
.RI "void \fBclear_ddkappa\fP ()"
.br
.ti -1c
.RI "double \fBddkappa\fP () const"
.br
.ti -1c
.RI "void \fBset_ddkappa\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_x_derivative\fP () const"
.br
.ti -1c
.RI "void \fBclear_x_derivative\fP ()"
.br
.ti -1c
.RI "double \fBx_derivative\fP () const"
.br
.ti -1c
.RI "void \fBset_x_derivative\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_y_derivative\fP () const"
.br
.ti -1c
.RI "void \fBclear_y_derivative\fP ()"
.br
.ti -1c
.RI "double \fBy_derivative\fP () const"
.br
.ti -1c
.RI "void \fBset_y_derivative\fP (double value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_lane_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBPathPoint\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBPathPoint\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPathPoint\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fpnc_5fpoint_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBPathPoint\fP &a, \fBPathPoint\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::common::PathPoint::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PathPoint::MergeImpl
}
.fi
.SS "constexpr int apollo::common::PathPoint::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    3
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
