.TH "apollo::cyber::PyParameterServer" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyParameterServer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyParameterServer\fP (const std::shared_ptr< \fBNode\fP > &node)"
.br
.ti -1c
.RI "void \fBset_parameter\fP (const \fBParameter\fP &parameter)"
.br
.ti -1c
.RI "bool \fBget_parameter\fP (const std::string &param_name, \fBParameter\fP *parameter)"
.br
.ti -1c
.RI "void \fBlist_parameters\fP (std::vector< \fBParameter\fP > *parameters)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
