.TH "apollo::cyber::record::PlayTaskBuffer" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::PlayTaskBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTaskPtr\fP = std::shared_ptr< \fBPlayTask\fP >"
.br
.ti -1c
.RI "using \fBTaskMap\fP = std::multimap< uint64_t, TaskPtr >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBSize\fP () const"
.br
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.ti -1c
.RI "void \fBPush\fP (const TaskPtr &task)"
.br
.ti -1c
.RI "TaskPtr \fBFront\fP ()"
.br
.ti -1c
.RI "void \fBPopFront\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
