.TH "apollo::canbus::Surround::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Surround::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBSurround\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_cross_traffic_alert_left\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cross_traffic_alert_left_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_blind_spot_left_alert\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_blind_spot_left_alert_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cross_traffic_alert_right\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cross_traffic_alert_right_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_blind_spot_right_alert\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_blind_spot_right_alert_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar00\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar01\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar02\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar03\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar04\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar05\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar06\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar07\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar08\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar09\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar10\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar11\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sonar_fault\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
