.TH "apollo::common::monitor::MonitorMessageItem" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::common::monitor::MonitorMessageItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkMsgFieldNumber\fP = 2, \fBkLogLevelFieldNumber\fP = 3, \fBkSourceFieldNumber\fP = 1 }"
.br
.ti -1c
.RI "typedef MonitorMessageItem_MessageSource \fBMessageSource\fP"
.br
.ti -1c
.RI "typedef MonitorMessageItem_LogLevel \fBLogLevel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBMonitorMessageItem\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBMonitorMessageItem\fP (const \fBMonitorMessageItem\fP &from)"
.br
.ti -1c
.RI "\fBMonitorMessageItem\fP (\fBMonitorMessageItem\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBMonitorMessageItem\fP & \fBoperator=\fP (const \fBMonitorMessageItem\fP &from)"
.br
.ti -1c
.RI "\fBMonitorMessageItem\fP & \fBoperator=\fP (\fBMonitorMessageItem\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBMonitorMessageItem\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBMonitorMessageItem\fP *other)"
.br
.ti -1c
.RI "\fBMonitorMessageItem\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBMonitorMessageItem\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBMonitorMessageItem\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_msg\fP () const"
.br
.ti -1c
.RI "void \fBclear_msg\fP ()"
.br
.ti -1c
.RI "const std::string & \fBmsg\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_msg\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_msg\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_msg\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_msg\fP (std::string *msg)"
.br
.ti -1c
.RI "bool \fBhas_log_level\fP () const"
.br
.ti -1c
.RI "void \fBclear_log_level\fP ()"
.br
.ti -1c
.RI "::apollo::common::monitor::MonitorMessageItem_LogLevel \fBlog_level\fP () const"
.br
.ti -1c
.RI "void \fBset_log_level\fP (::apollo::common::monitor::MonitorMessageItem_LogLevel value)"
.br
.ti -1c
.RI "bool \fBhas_source\fP () const"
.br
.ti -1c
.RI "void \fBclear_source\fP ()"
.br
.ti -1c
.RI "::apollo::common::monitor::MonitorMessageItem_MessageSource \fBsource\fP () const"
.br
.ti -1c
.RI "void \fBset_source\fP (::apollo::common::monitor::MonitorMessageItem_MessageSource value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_msg\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBMonitorMessageItem\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBMonitorMessageItem\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBMessageSource_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBMessageSource_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBMessageSource_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBMessageSource_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageSource *value)"
.br
.ti -1c
.RI "static bool \fBLogLevel_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBLogLevel_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBLogLevel_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBLogLevel_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogLevel *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBUNKNOWN\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBCANBUS\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBCONTROL\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBDECISION\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBLOCALIZATION\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBPLANNING\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBPREDICTION\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBSIMULATOR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBHWSYS\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBROUTING\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBMONITOR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBHMI\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBRELATIVE_MAP\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBGNSS\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBCONTI_RADAR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBRACOBIT_RADAR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBULTRASONIC_RADAR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBMOBILEYE\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBDELPHI_ESR\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBSTORYTELLING\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBTASK_MANAGER\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBMessageSource_MIN\fP"
.br
.ti -1c
.RI "static constexpr MessageSource \fBMessageSource_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBMessageSource_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBINFO\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBWARN\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBERROR\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBFATAL\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBLogLevel_MIN\fP"
.br
.ti -1c
.RI "static constexpr LogLevel \fBLogLevel_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBLogLevel_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMonitorMessageItem\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fmonitor_5flog_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBMonitorMessageItem\fP &a, \fBMonitorMessageItem\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::common::monitor::MonitorMessageItem::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    MonitorMessageItem::MergeImpl
}
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::CANBUS\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_CANBUS
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::CONTI_RADAR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_CONTI_RADAR
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::CONTROL\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_CONTROL
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::DECISION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_DECISION
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::DELPHI_ESR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_DELPHI_ESR
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::ERROR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_ERROR
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::FATAL\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_FATAL
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::GNSS\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_GNSS
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::HMI\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_HMI
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::HWSYS\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_HWSYS
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::INFO\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_INFO
.fi
.SS "constexpr int apollo::common::monitor::MonitorMessageItem::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::LOCALIZATION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_LOCALIZATION
.fi
.SS "constexpr int apollo::common::monitor::MonitorMessageItem::LogLevel_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_LogLevel_ARRAYSIZE
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::LogLevel_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_LogLevel_MAX
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::LogLevel_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_LogLevel_MIN
.fi
.SS "constexpr int apollo::common::monitor::MonitorMessageItem::MessageSource_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_MessageSource_ARRAYSIZE
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::MessageSource_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_MessageSource_MAX
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::MessageSource_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_MessageSource_MIN
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::MOBILEYE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_MOBILEYE
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::MONITOR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_MONITOR
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::PLANNING\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_PLANNING
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::PREDICTION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_PREDICTION
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::RACOBIT_RADAR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_RACOBIT_RADAR
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::RELATIVE_MAP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_RELATIVE_MAP
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::ROUTING\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_ROUTING
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::SIMULATOR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_SIMULATOR
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::STORYTELLING\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_STORYTELLING
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::TASK_MANAGER\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_TASK_MANAGER
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::ULTRASONIC_RADAR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_ULTRASONIC_RADAR
.fi
.SS "constexpr MonitorMessageItem_MessageSource apollo::common::monitor::MonitorMessageItem::UNKNOWN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_MessageSource_UNKNOWN
.fi
.SS "constexpr MonitorMessageItem_LogLevel apollo::common::monitor::MonitorMessageItem::WARN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MonitorMessageItem_LogLevel_WARN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
