.TH "apollo::simulation::Scenario_TL" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::simulation::Scenario_TL
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkStateGroupFieldNumber\fP = 6, \fBkIdFieldNumber\fP = 1, \fBkLocationFieldNumber\fP = 2, \fBkInitialStateFieldNumber\fP = 5, \fBkTriggerTypeFieldNumber\fP = 3, \fBkTriggerValueFieldNumber\fP = 4 }"
.br
.ti -1c
.RI "typedef \fBScenario_TL_Location\fP \fBLocation\fP"
.br
.ti -1c
.RI "typedef \fBScenario_TL_State\fP \fBState\fP"
.br
.ti -1c
.RI "typedef Scenario_TL_TriggerType \fBTriggerType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBScenario_TL\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBScenario_TL\fP (const \fBScenario_TL\fP &from)"
.br
.ti -1c
.RI "\fBScenario_TL\fP (\fBScenario_TL\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBScenario_TL\fP & \fBoperator=\fP (const \fBScenario_TL\fP &from)"
.br
.ti -1c
.RI "\fBScenario_TL\fP & \fBoperator=\fP (\fBScenario_TL\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBScenario_TL\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBScenario_TL\fP *other)"
.br
.ti -1c
.RI "\fBScenario_TL\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBScenario_TL\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBScenario_TL\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBstate_group_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_state_group\fP ()"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_State\fP * \fBmutable_state_group\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::simulation::Scenario_TL_State\fP > * \fBmutable_state_group\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::simulation::Scenario_TL_State\fP & \fBstate_group\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_State\fP * \fBadd_state_group\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::simulation::Scenario_TL_State\fP > & \fBstate_group\fP () const"
.br
.ti -1c
.RI "bool \fBhas_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_id\fP ()"
.br
.ti -1c
.RI "const std::string & \fBid\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_id\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_id\fP (std::string *id)"
.br
.ti -1c
.RI "bool \fBhas_location\fP () const"
.br
.ti -1c
.RI "void \fBclear_location\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::simulation::Scenario_TL_Location\fP & \fBlocation\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::simulation::Scenario_TL_Location\fP * \fBrelease_location\fP ()"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_Location\fP * \fBmutable_location\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_location\fP (::\fBapollo::simulation::Scenario_TL_Location\fP *location)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_location\fP (::\fBapollo::simulation::Scenario_TL_Location\fP *location)"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_Location\fP * \fBunsafe_arena_release_location\fP ()"
.br
.ti -1c
.RI "bool \fBhas_initial_state\fP () const"
.br
.ti -1c
.RI "void \fBclear_initial_state\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::simulation::Scenario_TL_State\fP & \fBinitial_state\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::simulation::Scenario_TL_State\fP * \fBrelease_initial_state\fP ()"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_State\fP * \fBmutable_initial_state\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_initial_state\fP (::\fBapollo::simulation::Scenario_TL_State\fP *initial_state)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_initial_state\fP (::\fBapollo::simulation::Scenario_TL_State\fP *initial_state)"
.br
.ti -1c
.RI "::\fBapollo::simulation::Scenario_TL_State\fP * \fBunsafe_arena_release_initial_state\fP ()"
.br
.ti -1c
.RI "bool \fBhas_trigger_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_trigger_type\fP ()"
.br
.ti -1c
.RI "::apollo::simulation::Scenario_TL_TriggerType \fBtrigger_type\fP () const"
.br
.ti -1c
.RI "void \fBset_trigger_type\fP (::apollo::simulation::Scenario_TL_TriggerType value)"
.br
.ti -1c
.RI "bool \fBhas_trigger_value\fP () const"
.br
.ti -1c
.RI "void \fBclear_trigger_value\fP ()"
.br
.ti -1c
.RI "double \fBtrigger_value\fP () const"
.br
.ti -1c
.RI "void \fBset_trigger_value\fP (double value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBScenario_TL\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBScenario_TL\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBTriggerType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBTriggerType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBTriggerType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBTriggerType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TriggerType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr TriggerType \fBNA\fP"
.br
.ti -1c
.RI "static constexpr TriggerType \fBDISTANCE\fP"
.br
.ti -1c
.RI "static constexpr TriggerType \fBTIME\fP"
.br
.ti -1c
.RI "static constexpr TriggerType \fBTriggerType_MIN\fP"
.br
.ti -1c
.RI "static constexpr TriggerType \fBTriggerType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBTriggerType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBScenario_TL\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsimulation_5fmsgs_2fscenario_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBScenario_TL\fP &a, \fBScenario_TL\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::simulation::Scenario_TL::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Scenario_TL::MergeImpl
}
.fi
.SS "constexpr Scenario_TL_TriggerType apollo::simulation::Scenario_TL::DISTANCE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_DISTANCE
.fi
.SS "constexpr int apollo::simulation::Scenario_TL::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    5
.fi
.SS "constexpr Scenario_TL_TriggerType apollo::simulation::Scenario_TL::NA\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_NA
.fi
.SS "constexpr Scenario_TL_TriggerType apollo::simulation::Scenario_TL::TIME\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_TIME
.fi
.SS "constexpr int apollo::simulation::Scenario_TL::TriggerType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_TriggerType_ARRAYSIZE
.fi
.SS "constexpr Scenario_TL_TriggerType apollo::simulation::Scenario_TL::TriggerType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_TriggerType_MAX
.fi
.SS "constexpr Scenario_TL_TriggerType apollo::simulation::Scenario_TL::TriggerType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Scenario_TL_TriggerType_TriggerType_MIN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
