.TH "apollo::drivers::Esr_status1_4e0" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Esr_status1_4e0
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkCanTxDspTimestampFieldNumber\fP = 1, \fBkCanTxYawRateCalcFieldNumber\fP = 3, \fBkCanTxCommErrorFieldNumber\fP = 2, \fBkCanTxScanIndexFieldNumber\fP = 5, \fBkCanTxVehicleSpeedCalcFieldNumber\fP = 4, \fBkCanTxRollingCount1FieldNumber\fP = 6, \fBkCanTxRadiusCurvatureCalcFieldNumber\fP = 7 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBEsr_status1_4e0\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBEsr_status1_4e0\fP (const \fBEsr_status1_4e0\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status1_4e0\fP (\fBEsr_status1_4e0\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBEsr_status1_4e0\fP & \fBoperator=\fP (const \fBEsr_status1_4e0\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status1_4e0\fP & \fBoperator=\fP (\fBEsr_status1_4e0\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBEsr_status1_4e0\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBEsr_status1_4e0\fP *other)"
.br
.ti -1c
.RI "\fBEsr_status1_4e0\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBEsr_status1_4e0\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBEsr_status1_4e0\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_can_tx_dsp_timestamp\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_dsp_timestamp\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_dsp_timestamp\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_dsp_timestamp\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_yaw_rate_calc\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_yaw_rate_calc\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_yaw_rate_calc\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_yaw_rate_calc\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_comm_error\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_comm_error\fP ()"
.br
.ti -1c
.RI "bool \fBcan_tx_comm_error\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_comm_error\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_scan_index\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_scan_index\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_scan_index\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_scan_index\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_vehicle_speed_calc\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_vehicle_speed_calc\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_vehicle_speed_calc\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_vehicle_speed_calc\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_rolling_count_1\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_rolling_count_1\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_rolling_count_1\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_rolling_count_1\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_radius_curvature_calc\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_radius_curvature_calc\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_radius_curvature_calc\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_radius_curvature_calc\fP (int32_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status1_4e0\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status1_4e0\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBEsr_status1_4e0\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBEsr_status1_4e0\fP &a, \fBEsr_status1_4e0\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Esr_status1_4e0::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Esr_status1_4e0::MergeImpl
}
.fi
.SS "constexpr int apollo::drivers::Esr_status1_4e0::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    15
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
