.TH "apollo::dreamview::Car" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::dreamview::Car
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLabelFieldNumber\fP = 1, \fBkColorFieldNumber\fP = 6, \fBkXFieldNumber\fP = 3, \fBkYFieldNumber\fP = 4, \fBkHeadingFieldNumber\fP = 5, \fBkHideLabelInLegendFieldNumber\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBCar\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBCar\fP (const \fBCar\fP &from)"
.br
.ti -1c
.RI "\fBCar\fP (\fBCar\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBCar\fP & \fBoperator=\fP (const \fBCar\fP &from)"
.br
.ti -1c
.RI "\fBCar\fP & \fBoperator=\fP (\fBCar\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBCar\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBCar\fP *other)"
.br
.ti -1c
.RI "\fBCar\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBCar\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBCar\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_label\fP () const"
.br
.ti -1c
.RI "void \fBclear_label\fP ()"
.br
.ti -1c
.RI "const std::string & \fBlabel\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_label\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_label\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_label\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_label\fP (std::string *label)"
.br
.ti -1c
.RI "bool \fBhas_color\fP () const"
.br
.ti -1c
.RI "void \fBclear_color\fP ()"
.br
.ti -1c
.RI "const std::string & \fBcolor\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_color\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_color\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_color\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_color\fP (std::string *color)"
.br
.ti -1c
.RI "bool \fBhas_x\fP () const"
.br
.ti -1c
.RI "void \fBclear_x\fP ()"
.br
.ti -1c
.RI "double \fBx\fP () const"
.br
.ti -1c
.RI "void \fBset_x\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_y\fP () const"
.br
.ti -1c
.RI "void \fBclear_y\fP ()"
.br
.ti -1c
.RI "double \fBy\fP () const"
.br
.ti -1c
.RI "void \fBset_y\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_heading\fP () const"
.br
.ti -1c
.RI "void \fBclear_heading\fP ()"
.br
.ti -1c
.RI "double \fBheading\fP () const"
.br
.ti -1c
.RI "void \fBset_heading\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_hide_label_in_legend\fP () const"
.br
.ti -1c
.RI "void \fBclear_hide_label_in_legend\fP ()"
.br
.ti -1c
.RI "bool \fBhide_label_in_legend\fP () const"
.br
.ti -1c
.RI "void \fBset_hide_label_in_legend\fP (bool value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_label\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_color\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBCar\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBCar\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCar\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fdreamview_5fmsgs_2fchart_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCar\fP &a, \fBCar\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::dreamview::Car::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Car::MergeImpl
}
.fi
.SS "constexpr int apollo::dreamview::Car::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    6
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
