.TH "apollo::cyber::transport::AttributesFiller" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::AttributesFiller
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBFillInPubAttr\fP (const std::string &channel_name, const \fBQosProfile\fP &qos, \fBeprosima::fastrtps::PublisherAttributes\fP *pub_attr)"
.br
.ti -1c
.RI "static bool \fBFillInSubAttr\fP (const std::string &channel_name, const \fBQosProfile\fP &qos, \fBeprosima::fastrtps::SubscriberAttributes\fP *sub_attr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
