.TH "apollo::cyber::Component_A< M0, M1, M2, M3 >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Component_A< M0, M1, M2, M3 >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::Component< M0, NullType, NullType, NullType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
