.TH "apollo::dreamview::Options::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::dreamview::Options::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBOptions\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_legend_display\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::dreamview::Options_Axis\fP & \fBx\fP (const \fBOptions\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_x\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::dreamview::Options_Axis\fP & \fBy\fP (const \fBOptions\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_y\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_aspect_ratio\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sync_xy_window_size\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
