.TH "apollo::cyber::ParameterServer" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::ParameterServer \- \fBParameter\fP \fBService\fP is a very important function of auto-driving\&. If you want to set a key-value, and hope other nodes to get the value, Routing, sensor internal/external references are set by \fBParameter\fP \fBService\fP \fBParameterServer\fP can set a parameter, and then you can get/list paramter(s) by start a \fBParameterClient\fP to send responding request\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parameter_server\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBParam\fP = apollo::cyber::proto::Param"
.br
.ti -1c
.RI "using \fBNodeName\fP = apollo::cyber::proto::NodeName"
.br
.ti -1c
.RI "using \fBParamName\fP = apollo::cyber::proto::ParamName"
.br
.ti -1c
.RI "using \fBBoolResult\fP = apollo::cyber::proto::BoolResult"
.br
.ti -1c
.RI "using \fBParams\fP = apollo::cyber::proto::Params"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterServer\fP (const std::shared_ptr< \fBNode\fP > &node)"
.br
.RI "Construct a new \fBParameterServer\fP object\&. "
.ti -1c
.RI "void \fBSetParameter\fP (const \fBParameter\fP &parmeter)"
.br
.RI "Set the \fBParameter\fP object\&. "
.ti -1c
.RI "bool \fBGetParameter\fP (const std::string &parameter_name, \fBParameter\fP *parameter)"
.br
.RI "Get the \fBParameter\fP object\&. "
.ti -1c
.RI "void \fBListParameters\fP (std::vector< \fBParameter\fP > *parameters)"
.br
.RI "get all the parameters "
.in -1c
.SH "Detailed Description"
.PP 
\fBParameter\fP \fBService\fP is a very important function of auto-driving\&. If you want to set a key-value, and hope other nodes to get the value, Routing, sensor internal/external references are set by \fBParameter\fP \fBService\fP \fBParameterServer\fP can set a parameter, and then you can get/list paramter(s) by start a \fBParameterClient\fP to send responding request\&. 


.PP
\fBWarning\fP
.RS 4
You should only have one \fBParameterServer\fP works 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::ParameterServer::ParameterServer (const std::shared_ptr< \fBNode\fP > & node)\fC [explicit]\fP"

.PP
Construct a new \fBParameterServer\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP shared_ptr of the node handler 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool apollo::cyber::ParameterServer::GetParameter (const std::string & parameter_name, \fBParameter\fP * parameter)"

.PP
Get the \fBParameter\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIparameter_name\fP name of the parameer want to get 
.br
\fIparameter\fP pointer to store parameter want to get 
.RE
.PP
\fBReturns\fP
.RS 4
true get parameter success 
.PP
false parameter not exists 
.RE
.PP

.SS "void apollo::cyber::ParameterServer::ListParameters (std::vector< \fBParameter\fP > * parameters)"

.PP
get all the parameters 
.PP
\fBParameters\fP
.RS 4
\fIparameters\fP result Paramter vector 
.RE
.PP

.SS "void apollo::cyber::ParameterServer::SetParameter (const \fBParameter\fP & parmeter)"

.PP
Set the \fBParameter\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIparmeter\fP parameter to be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
