.TH "apollo::cyber::PyParameterClient" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyParameterClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyParameterClient\fP (const std::shared_ptr< \fBNode\fP > &node, const std::string &service_node_name)"
.br
.ti -1c
.RI "bool \fBset_parameter\fP (const \fBParameter\fP &parameter)"
.br
.ti -1c
.RI "bool \fBget_parameter\fP (const std::string &param_name, \fBParameter\fP *parameter)"
.br
.ti -1c
.RI "bool \fBlist_parameters\fP (std::vector< \fBParameter\fP > *parameters)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
