.TH "apollo::cyber::io::PollRequest" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::io::PollRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP = \-1"
.br
.ti -1c
.RI "uint32_t \fBevents\fP = 0"
.br
.ti -1c
.RI "int \fBtimeout_ms\fP = \-1"
.br
.ti -1c
.RI "std::function< void(const \fBPollResponse\fP &)> \fBcallback\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
