.TH "apollo::cyber::Writer< MessageT >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Writer< MessageT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::WriterBase\fP\&.
.PP
Inherited by \fBapollo::cyber::blocker::IntraWriter< MessageT >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTransmitterPtr\fP = std::shared_ptr< \fBtransport::Transmitter\fP< MessageT > >"
.br
.ti -1c
.RI "using \fBChangeConnection\fP = typename \fBservice_discovery::Manager::ChangeConnection\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriter\fP (const \fBproto::RoleAttributes\fP &role_attr)"
.br
.RI "Construct a new \fBWriter\fP object\&. "
.ti -1c
.RI "bool \fBInit\fP () override"
.br
.RI "Init the \fBWriter\fP\&. "
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.RI "Shutdown the \fBWriter\fP\&. "
.ti -1c
.RI "virtual bool \fBWrite\fP (const MessageT &msg)"
.br
.RI "Write a MessageT instance\&. "
.ti -1c
.RI "virtual bool \fBWrite\fP (const std::shared_ptr< MessageT > &msg_ptr)"
.br
.RI "Write a shared ptr of MessageT\&. "
.ti -1c
.RI "bool \fBHasReader\fP () override"
.br
.RI "Is there any \fBReader\fP that subscribes our Channel? You can publish message when this return true\&. "
.ti -1c
.RI "void \fBGetReaders\fP (std::vector< \fBproto::RoleAttributes\fP > *readers) override"
.br
.RI "Get all Readers that subscriber our writing channel\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename MessageT > \fBapollo::cyber::Writer\fP< MessageT >::\fBWriter\fP (const \fBproto::RoleAttributes\fP & role_attr)\fC [explicit]\fP"

.PP
Construct a new \fBWriter\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrole_attr\fP we use RoleAttributes to identify a \fBWriter\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename MessageT > void \fBapollo::cyber::Writer\fP< MessageT >::GetReaders (std::vector< \fBproto::RoleAttributes\fP > * readers)\fC [override]\fP, \fC [virtual]\fP"

.PP
Get all Readers that subscriber our writing channel\&. 
.PP
\fBParameters\fP
.RS 4
\fIreaders\fP vector result of RoleAttributes 
.RE
.PP

.PP
Reimplemented from \fBapollo::cyber::WriterBase\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::Writer\fP< MessageT >::HasReader\fC [override]\fP, \fC [virtual]\fP"

.PP
Is there any \fBReader\fP that subscribes our Channel? You can publish message when this return true\&. 
.PP
\fBReturns\fP
.RS 4
true if the channel has reader 
.PP
false if the channel has no reader 
.RE
.PP

.PP
Reimplemented from \fBapollo::cyber::WriterBase\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::Writer\fP< MessageT >::Init\fC [override]\fP, \fC [virtual]\fP"

.PP
Init the \fBWriter\fP\&. 
.PP
\fBReturns\fP
.RS 4
true if init successfully 
.PP
false if init failed 
.RE
.PP

.PP
Implements \fBapollo::cyber::WriterBase\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::Writer\fP< MessageT >::Write (const MessageT & msg)\fC [virtual]\fP"

.PP
Write a MessageT instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP the message we want to write 
.RE
.PP
\fBReturns\fP
.RS 4
true if write successfully 
.PP
false if write failed 
.RE
.PP

.PP
Reimplemented in \fBapollo::cyber::blocker::IntraWriter< MessageT >\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::Writer\fP< MessageT >::Write (const std::shared_ptr< MessageT > & msg_ptr)\fC [virtual]\fP"

.PP
Write a shared ptr of MessageT\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_ptr\fP the message shared ptr we want to write 
.RE
.PP
\fBReturns\fP
.RS 4
true if write successfully 
.PP
false if write failed 
.RE
.PP

.PP
Reimplemented in \fBapollo::cyber::blocker::IntraWriter< MessageT >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
