.TH "apollo::cyber::blocker::BlockerBase" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::blocker::BlockerBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::blocker::Blocker< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBReset\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBClearObserved\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBClearPublished\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBObserve\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBIsObservedEmpty\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBIsPublishedEmpty\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBUnsubscribe\fP (const std::string &callback_id)=0"
.br
.ti -1c
.RI "virtual size_t \fBcapacity\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBset_capacity\fP (size_t capacity)=0"
.br
.ti -1c
.RI "virtual const std::string & \fBchannel_name\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
