.TH "apollo::cyber::ParameterTest" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::ParameterTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::unique_ptr< \fBParameter\fP > \fBbool_param_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBParameter\fP > \fBint_param_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBParameter\fP > \fBdouble_param_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBParameter\fP > \fBstring_param_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBParameter\fP > \fBprotobuf_param_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
