.TH "apollo::cyber::message::PyMessageWrap" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::message::PyMessageWrap
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDescriptor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyMessageWrap\fP (const std::string &msg, const std::string &type_name)"
.br
.ti -1c
.RI "\fBPyMessageWrap\fP (const \fBPyMessageWrap\fP &msg)"
.br
.ti -1c
.RI "bool \fBSerializeToArray\fP (void *data, int size) const"
.br
.ti -1c
.RI "bool \fBSerializeToString\fP (std::string *output) const"
.br
.ti -1c
.RI "bool \fBParseFromArray\fP (const void *data, int size)"
.br
.ti -1c
.RI "bool \fBParseFromString\fP (const std::string &msgstr)"
.br
.ti -1c
.RI "int \fBByteSize\fP () const"
.br
.ti -1c
.RI "const std::string & \fBdata\fP () const"
.br
.ti -1c
.RI "void \fBset_data\fP (const std::string &msg)"
.br
.ti -1c
.RI "const std::string & \fBtype_name\fP ()"
.br
.ti -1c
.RI "void \fBset_type_name\fP (const std::string &type_name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBDescriptor\fP * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static std::string \fBTypeName\fP ()"
.br
.ti -1c
.RI "static void \fBGetDescriptorString\fP (const std::string &type, std::string *desc_str)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
