.TH "apollo::cyber::data::DataVisitorBase" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::DataVisitorBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::data::DataVisitor< M0, M1, M2, M3 >\fP, \fBapollo::cyber::data::DataVisitor< M0, M1, M2, NullType >\fP, \fBapollo::cyber::data::DataVisitor< M0, M1, NullType, NullType >\fP, and \fBapollo::cyber::data::DataVisitor< M0, NullType, NullType, NullType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterNotifyCallback\fP (std::function< void()> &&callback)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDataVisitorBase\fP (const \fBDataVisitorBase\fP &)=delete"
.br
.ti -1c
.RI "\fBDataVisitorBase\fP & \fBoperator=\fP (const \fBDataVisitorBase\fP &)=delete"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBnext_msg_index_\fP = 0"
.br
.ti -1c
.RI "\fBDataNotifier\fP * \fBdata_notifier_\fP = DataNotifier::Instance()"
.br
.ti -1c
.RI "std::shared_ptr< \fBNotifier\fP > \fBnotifier_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
