.TH "apollo::drivers::RacobitRadar::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::RacobitRadar::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBRacobitRadar\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBRacobitRadar\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::RacobitRadarState_201\fP & \fBradar_state\fP (const \fBRacobitRadar\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_radar_state\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::RacobitClusterListStatus_600\fP & \fBcluster_list_status\fP (const \fBRacobitRadar\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_cluster_list_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::RacobitObjectListStatus_60A\fP & \fBobject_list_status\fP (const \fBRacobitRadar\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_object_list_status\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
