.TH "apollo::cyber::proto::SingleIndex::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::SingleIndex::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBSingleIndex\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ChannelCache\fP & \fBchannel_cache\fP (const \fBSingleIndex\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ChunkHeaderCache\fP & \fBchunk_header_cache\fP (const \fBSingleIndex\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ChunkBodyCache\fP & \fBchunk_body_cache\fP (const \fBSingleIndex\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
