.TH "apollo::cyber::scheduler::SchedulerClassic" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::scheduler::SchedulerClassic
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::scheduler::Scheduler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBRemoveCRoutine\fP (uint64_t crid) override"
.br
.ti -1c
.RI "bool \fBRemoveTask\fP (const std::string &name) override"
.br
.ti -1c
.RI "bool \fBDispatchTask\fP (const std::shared_ptr< \fBCRoutine\fP > &) override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBScheduler\fP * \fBInstance\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
