.TH "apollo::perception::TrafficLight" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::TrafficLight
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkIdFieldNumber\fP = 2, \fBkColorFieldNumber\fP = 1, \fBkBlinkFieldNumber\fP = 5, \fBkTrackingTimeFieldNumber\fP = 4, \fBkRemainingTimeFieldNumber\fP = 6, \fBkConfidenceFieldNumber\fP = 3 }"
.br
.ti -1c
.RI "typedef TrafficLight_Color \fBColor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBTrafficLight\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBTrafficLight\fP (const \fBTrafficLight\fP &from)"
.br
.ti -1c
.RI "\fBTrafficLight\fP (\fBTrafficLight\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBTrafficLight\fP & \fBoperator=\fP (const \fBTrafficLight\fP &from)"
.br
.ti -1c
.RI "\fBTrafficLight\fP & \fBoperator=\fP (\fBTrafficLight\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBTrafficLight\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBTrafficLight\fP *other)"
.br
.ti -1c
.RI "\fBTrafficLight\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBTrafficLight\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBTrafficLight\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_id\fP ()"
.br
.ti -1c
.RI "const std::string & \fBid\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_id\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_id\fP (std::string *id)"
.br
.ti -1c
.RI "bool \fBhas_color\fP () const"
.br
.ti -1c
.RI "void \fBclear_color\fP ()"
.br
.ti -1c
.RI "::apollo::perception::TrafficLight_Color \fBcolor\fP () const"
.br
.ti -1c
.RI "void \fBset_color\fP (::apollo::perception::TrafficLight_Color value)"
.br
.ti -1c
.RI "bool \fBhas_blink\fP () const"
.br
.ti -1c
.RI "void \fBclear_blink\fP ()"
.br
.ti -1c
.RI "bool \fBblink\fP () const"
.br
.ti -1c
.RI "void \fBset_blink\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_tracking_time\fP () const"
.br
.ti -1c
.RI "void \fBclear_tracking_time\fP ()"
.br
.ti -1c
.RI "double \fBtracking_time\fP () const"
.br
.ti -1c
.RI "void \fBset_tracking_time\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_remaining_time\fP () const"
.br
.ti -1c
.RI "void \fBclear_remaining_time\fP ()"
.br
.ti -1c
.RI "double \fBremaining_time\fP () const"
.br
.ti -1c
.RI "void \fBset_remaining_time\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_confidence\fP () const"
.br
.ti -1c
.RI "void \fBclear_confidence\fP ()"
.br
.ti -1c
.RI "double \fBconfidence\fP () const"
.br
.ti -1c
.RI "void \fBset_confidence\fP (double value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBTrafficLight\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBTrafficLight\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBColor_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBColor_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBColor_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBColor_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Color *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr Color \fBUNKNOWN\fP"
.br
.ti -1c
.RI "static constexpr Color \fBRED\fP"
.br
.ti -1c
.RI "static constexpr Color \fBYELLOW\fP"
.br
.ti -1c
.RI "static constexpr Color \fBGREEN\fP"
.br
.ti -1c
.RI "static constexpr Color \fBBLACK\fP"
.br
.ti -1c
.RI "static constexpr Color \fBColor_MIN\fP"
.br
.ti -1c
.RI "static constexpr Color \fBColor_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBColor_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTrafficLight\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fperception_5fmsgs_2ftraffic_5flight_5fdetection_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBTrafficLight\fP &a, \fBTrafficLight\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::perception::TrafficLight::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TrafficLight::MergeImpl
}
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::BLACK\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_BLACK
.fi
.SS "constexpr int apollo::perception::TrafficLight::Color_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_Color_ARRAYSIZE
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::Color_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_Color_MAX
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::Color_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_Color_MIN
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::GREEN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_GREEN
.fi
.SS "constexpr int apollo::perception::TrafficLight::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::RED\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_RED
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::UNKNOWN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_UNKNOWN
.fi
.SS "constexpr TrafficLight_Color apollo::perception::TrafficLight::YELLOW\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    TrafficLight_Color_YELLOW
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
