.TH "apollo::cyber::data::fusion::AllLatest< M0, M1, NullType, NullType >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::fusion::AllLatest< M0, M1, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::data::fusion::DataFusion< M0, M1 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAllLatest\fP (const \fBChannelBuffer\fP< M0 > &buffer_0, const \fBChannelBuffer\fP< M1 > &buffer_1)"
.br
.ti -1c
.RI "bool \fBFusion\fP (uint64_t *index, std::shared_ptr< M0 > &m0, std::shared_ptr< M1 > &m1) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
