.TH "apollo::drivers::Details_73b::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Details_73b::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBDetails_73b\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_obstacle_angle_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_obstacle_scale_change\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_object_accel_x\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_reserved_8\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_obstacle_replaced\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_reserved_9\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_obstacle_angle\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
