.TH "apollo::cyber::class_loader::ClassLoader" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::class_loader::ClassLoader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <class_loader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassLoader\fP (const std::string &library_path)"
.br
.ti -1c
.RI "bool \fBIsLibraryLoaded\fP ()"
.br
.ti -1c
.RI "bool \fBLoadLibrary\fP ()"
.br
.ti -1c
.RI "int \fBUnloadLibrary\fP ()"
.br
.ti -1c
.RI "const std::string \fBGetLibraryPath\fP () const"
.br
.ti -1c
.RI "template<typename Base > std::vector< std::string > \fBGetValidClassNames\fP ()"
.br
.ti -1c
.RI "template<typename Base > std::shared_ptr< \fBBase\fP > \fBCreateClassObj\fP (const std::string &class_name)"
.br
.ti -1c
.RI "template<typename Base > bool \fBIsClassValid\fP (const std::string &class_name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
for library load,createclass object 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
