.TH "apollo::drivers::Vehicle5_5f4::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle5_5f4::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicle5_5f4\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_can_rx_yaw_rate_bias_shift\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_steering_gear_ratio\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_wheelbase\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_distance_rear_axle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_cw_blockage_threshold\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_funnel_offset_right\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_funnel_offset_left\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_beamwidth_vert\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_oversteer_understeer\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
