.TH "apollo::planning::ObjectFollow::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::ObjectFollow::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBObjectFollow\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_distance_s\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::PointENU\fP & \fBfence_point\fP (const \fBObjectFollow\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_fence_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_fence_heading\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
