.TH "apollo::dreamview::Chart" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::dreamview::Chart
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLineFieldNumber\fP = 3, \fBkPolygonFieldNumber\fP = 4, \fBkCarFieldNumber\fP = 5, \fBkTitleFieldNumber\fP = 1, \fBkOptionsFieldNumber\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBChart\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBChart\fP (const \fBChart\fP &from)"
.br
.ti -1c
.RI "\fBChart\fP (\fBChart\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBChart\fP & \fBoperator=\fP (const \fBChart\fP &from)"
.br
.ti -1c
.RI "\fBChart\fP & \fBoperator=\fP (\fBChart\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBChart\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBChart\fP *other)"
.br
.ti -1c
.RI "\fBChart\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBChart\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBChart\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBline_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_line\fP ()"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Line\fP * \fBmutable_line\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Line\fP > * \fBmutable_line\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::dreamview::Line\fP & \fBline\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Line\fP * \fBadd_line\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Line\fP > & \fBline\fP () const"
.br
.ti -1c
.RI "int \fBpolygon_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_polygon\fP ()"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Polygon\fP * \fBmutable_polygon\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Polygon\fP > * \fBmutable_polygon\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::dreamview::Polygon\fP & \fBpolygon\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Polygon\fP * \fBadd_polygon\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Polygon\fP > & \fBpolygon\fP () const"
.br
.ti -1c
.RI "int \fBcar_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_car\fP ()"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Car\fP * \fBmutable_car\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Car\fP > * \fBmutable_car\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::dreamview::Car\fP & \fBcar\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Car\fP * \fBadd_car\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::dreamview::Car\fP > & \fBcar\fP () const"
.br
.ti -1c
.RI "bool \fBhas_title\fP () const"
.br
.ti -1c
.RI "void \fBclear_title\fP ()"
.br
.ti -1c
.RI "const std::string & \fBtitle\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_title\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_title\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_title\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_title\fP (std::string *title)"
.br
.ti -1c
.RI "bool \fBhas_options\fP () const"
.br
.ti -1c
.RI "void \fBclear_options\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::dreamview::Options\fP & \fBoptions\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::dreamview::Options\fP * \fBrelease_options\fP ()"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Options\fP * \fBmutable_options\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_options\fP (::\fBapollo::dreamview::Options\fP *options)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_options\fP (::\fBapollo::dreamview::Options\fP *options)"
.br
.ti -1c
.RI "::\fBapollo::dreamview::Options\fP * \fBunsafe_arena_release_options\fP ()"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_title\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBChart\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBChart\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBChart\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fdreamview_5fmsgs_2fchart_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBChart\fP &a, \fBChart\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::dreamview::Chart::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Chart::MergeImpl
}
.fi
.SS "constexpr int apollo::dreamview::Chart::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    7
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
