.TH "apollo::simulation::GradePlanning" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::simulation::GradePlanning
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkDurationFieldNumber\fP = 1, \fBkUpdateObstaclesFieldNumber\fP = 2, \fBkUsePlanningAsHistoryFieldNumber\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBGradePlanning\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBGradePlanning\fP (const \fBGradePlanning\fP &from)"
.br
.ti -1c
.RI "\fBGradePlanning\fP (\fBGradePlanning\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBGradePlanning\fP & \fBoperator=\fP (const \fBGradePlanning\fP &from)"
.br
.ti -1c
.RI "\fBGradePlanning\fP & \fBoperator=\fP (\fBGradePlanning\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBGradePlanning\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBGradePlanning\fP *other)"
.br
.ti -1c
.RI "\fBGradePlanning\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBGradePlanning\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBGradePlanning\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_duration\fP () const"
.br
.ti -1c
.RI "void \fBclear_duration\fP ()"
.br
.ti -1c
.RI "int32_t \fBduration\fP () const"
.br
.ti -1c
.RI "void \fBset_duration\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_update_obstacles\fP () const"
.br
.ti -1c
.RI "void \fBclear_update_obstacles\fP ()"
.br
.ti -1c
.RI "bool \fBupdate_obstacles\fP () const"
.br
.ti -1c
.RI "void \fBset_update_obstacles\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_use_planning_as_history\fP () const"
.br
.ti -1c
.RI "void \fBclear_use_planning_as_history\fP ()"
.br
.ti -1c
.RI "bool \fBuse_planning_as_history\fP () const"
.br
.ti -1c
.RI "void \fBset_use_planning_as_history\fP (bool value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBGradePlanning\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBGradePlanning\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBGradePlanning\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsimulation_5fmsgs_2fgrading_5fcondition_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBGradePlanning\fP &a, \fBGradePlanning\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::simulation::GradePlanning::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GradePlanning::MergeImpl
}
.fi
.SS "constexpr int apollo::simulation::GradePlanning::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    1
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
