.TH "apollo::control::Debug" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::control::Debug
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkSimpleLonDebugFieldNumber\fP = 1, \fBkSimpleLatDebugFieldNumber\fP = 2, \fBkInputDebugFieldNumber\fP = 3, \fBkSimpleMpcDebugFieldNumber\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBDebug\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBDebug\fP (const \fBDebug\fP &from)"
.br
.ti -1c
.RI "\fBDebug\fP (\fBDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBDebug\fP & \fBoperator=\fP (const \fBDebug\fP &from)"
.br
.ti -1c
.RI "\fBDebug\fP & \fBoperator=\fP (\fBDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBDebug\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBDebug\fP *other)"
.br
.ti -1c
.RI "\fBDebug\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBDebug\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBDebug\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_simple_lon_debug\fP () const"
.br
.ti -1c
.RI "void \fBclear_simple_lon_debug\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::control::SimpleLongitudinalDebug\fP & \fBsimple_lon_debug\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::control::SimpleLongitudinalDebug\fP * \fBrelease_simple_lon_debug\fP ()"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleLongitudinalDebug\fP * \fBmutable_simple_lon_debug\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_simple_lon_debug\fP (::\fBapollo::control::SimpleLongitudinalDebug\fP *simple_lon_debug)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_simple_lon_debug\fP (::\fBapollo::control::SimpleLongitudinalDebug\fP *simple_lon_debug)"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleLongitudinalDebug\fP * \fBunsafe_arena_release_simple_lon_debug\fP ()"
.br
.ti -1c
.RI "bool \fBhas_simple_lat_debug\fP () const"
.br
.ti -1c
.RI "void \fBclear_simple_lat_debug\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::control::SimpleLateralDebug\fP & \fBsimple_lat_debug\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::control::SimpleLateralDebug\fP * \fBrelease_simple_lat_debug\fP ()"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleLateralDebug\fP * \fBmutable_simple_lat_debug\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_simple_lat_debug\fP (::\fBapollo::control::SimpleLateralDebug\fP *simple_lat_debug)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_simple_lat_debug\fP (::\fBapollo::control::SimpleLateralDebug\fP *simple_lat_debug)"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleLateralDebug\fP * \fBunsafe_arena_release_simple_lat_debug\fP ()"
.br
.ti -1c
.RI "bool \fBhas_input_debug\fP () const"
.br
.ti -1c
.RI "void \fBclear_input_debug\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::control::InputDebug\fP & \fBinput_debug\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::control::InputDebug\fP * \fBrelease_input_debug\fP ()"
.br
.ti -1c
.RI "::\fBapollo::control::InputDebug\fP * \fBmutable_input_debug\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_input_debug\fP (::\fBapollo::control::InputDebug\fP *input_debug)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_input_debug\fP (::\fBapollo::control::InputDebug\fP *input_debug)"
.br
.ti -1c
.RI "::\fBapollo::control::InputDebug\fP * \fBunsafe_arena_release_input_debug\fP ()"
.br
.ti -1c
.RI "bool \fBhas_simple_mpc_debug\fP () const"
.br
.ti -1c
.RI "void \fBclear_simple_mpc_debug\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::control::SimpleMPCDebug\fP & \fBsimple_mpc_debug\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::control::SimpleMPCDebug\fP * \fBrelease_simple_mpc_debug\fP ()"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleMPCDebug\fP * \fBmutable_simple_mpc_debug\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_simple_mpc_debug\fP (::\fBapollo::control::SimpleMPCDebug\fP *simple_mpc_debug)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_simple_mpc_debug\fP (::\fBapollo::control::SimpleMPCDebug\fP *simple_mpc_debug)"
.br
.ti -1c
.RI "::\fBapollo::control::SimpleMPCDebug\fP * \fBunsafe_arena_release_simple_mpc_debug\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBDebug\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBDebug\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDebug\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fcontrol_5fmsgs_2fcontrol_5fcmd_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBDebug\fP &a, \fBDebug\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::control::Debug::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Debug::MergeImpl
}
.fi
.SS "constexpr int apollo::control::Debug::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    7
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
