.TH "apollo::cyber::Timer" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Timer \- Used to perform oneshot or periodic timing tasks\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimer\fP (\fBTimerOption\fP opt)"
.br
.RI "Construct a new \fBTimer\fP object\&. "
.ti -1c
.RI "\fBTimer\fP (uint32_t period, std::function< void()> callback, bool oneshot)"
.br
.RI "Construct a new \fBTimer\fP object\&. "
.ti -1c
.RI "void \fBSetTimerOption\fP (\fBTimerOption\fP opt)"
.br
.RI "Set the \fBTimer\fP Option object\&. "
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "Start the timer\&. "
.ti -1c
.RI "void \fBStop\fP ()"
.br
.RI "Stop the timer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Used to perform oneshot or periodic timing tasks\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::Timer::Timer (\fBTimerOption\fP opt)\fC [explicit]\fP"

.PP
Construct a new \fBTimer\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIopt\fP \fBTimer\fP option 
.RE
.PP

.SS "apollo::cyber::Timer::Timer (uint32_t period, std::function< void()> callback, bool oneshot)"

.PP
Construct a new \fBTimer\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP The period of the timer, unit is ms 
.br
\fIcallback\fP The tasks that the timer needs to perform 
.br
\fIoneshot\fP True: perform the callback only after the first timing cycle False: perform the callback every timed period 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void apollo::cyber::Timer::SetTimerOption (\fBTimerOption\fP opt)"

.PP
Set the \fBTimer\fP Option object\&. 
.PP
\fBParameters\fP
.RS 4
\fIopt\fP The timer option will be set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
