.TH "apollo::perception::LaneMarkers" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::LaneMarkers
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkNextLeftLaneMarkerFieldNumber\fP = 3, \fBkNextRightLaneMarkerFieldNumber\fP = 4, \fBkLeftLaneMarkerFieldNumber\fP = 1, \fBkRightLaneMarkerFieldNumber\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBLaneMarkers\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBLaneMarkers\fP (const \fBLaneMarkers\fP &from)"
.br
.ti -1c
.RI "\fBLaneMarkers\fP (\fBLaneMarkers\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBLaneMarkers\fP & \fBoperator=\fP (const \fBLaneMarkers\fP &from)"
.br
.ti -1c
.RI "\fBLaneMarkers\fP & \fBoperator=\fP (\fBLaneMarkers\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBLaneMarkers\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBLaneMarkers\fP *other)"
.br
.ti -1c
.RI "\fBLaneMarkers\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBLaneMarkers\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBLaneMarkers\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBnext_left_lane_marker_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_next_left_lane_marker\fP ()"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBmutable_next_left_lane_marker\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::perception::LaneMarker\fP > * \fBmutable_next_left_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::perception::LaneMarker\fP & \fBnext_left_lane_marker\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBadd_next_left_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::perception::LaneMarker\fP > & \fBnext_left_lane_marker\fP () const"
.br
.ti -1c
.RI "int \fBnext_right_lane_marker_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_next_right_lane_marker\fP ()"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBmutable_next_right_lane_marker\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::perception::LaneMarker\fP > * \fBmutable_next_right_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::perception::LaneMarker\fP & \fBnext_right_lane_marker\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBadd_next_right_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::perception::LaneMarker\fP > & \fBnext_right_lane_marker\fP () const"
.br
.ti -1c
.RI "bool \fBhas_left_lane_marker\fP () const"
.br
.ti -1c
.RI "void \fBclear_left_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::perception::LaneMarker\fP & \fBleft_lane_marker\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::perception::LaneMarker\fP * \fBrelease_left_lane_marker\fP ()"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBmutable_left_lane_marker\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_left_lane_marker\fP (::\fBapollo::perception::LaneMarker\fP *left_lane_marker)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_left_lane_marker\fP (::\fBapollo::perception::LaneMarker\fP *left_lane_marker)"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBunsafe_arena_release_left_lane_marker\fP ()"
.br
.ti -1c
.RI "bool \fBhas_right_lane_marker\fP () const"
.br
.ti -1c
.RI "void \fBclear_right_lane_marker\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::perception::LaneMarker\fP & \fBright_lane_marker\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::perception::LaneMarker\fP * \fBrelease_right_lane_marker\fP ()"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBmutable_right_lane_marker\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_right_lane_marker\fP (::\fBapollo::perception::LaneMarker\fP *right_lane_marker)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_right_lane_marker\fP (::\fBapollo::perception::LaneMarker\fP *right_lane_marker)"
.br
.ti -1c
.RI "::\fBapollo::perception::LaneMarker\fP * \fBunsafe_arena_release_right_lane_marker\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBLaneMarkers\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBLaneMarkers\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLaneMarkers\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fperception_5fmsgs_2fperception_5fobstacle_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBLaneMarkers\fP &a, \fBLaneMarkers\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::perception::LaneMarkers::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LaneMarkers::MergeImpl
}
.fi
.SS "constexpr int apollo::perception::LaneMarkers::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    8
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
