.TH "apollo::control::SimpleLongitudinalDebug::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::control::SimpleLongitudinalDebug::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBSimpleLongitudinalDebug\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_station_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_station_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_station_error_limited\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_preview_station_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_controller_input_limited\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_preview_speed_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_preview_speed_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_preview_acceleration_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_cmd_closeloop\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_cmd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_lookup\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_lookup\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_calibration_value\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_cmd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_brake_cmd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_full_stop\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_slope_offset_compensation\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_station\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_path_remain\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_pid_saturation_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_leadlag_saturation_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_speed_offset\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_speed\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_acceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_jerk_reference\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_jerk\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_jerk_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::TrajectoryPoint\fP & \fBcurrent_matched_point\fP (const \fBSimpleLongitudinalDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_current_matched_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::TrajectoryPoint\fP & \fBcurrent_reference_point\fP (const \fBSimpleLongitudinalDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_current_reference_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::TrajectoryPoint\fP & \fBpreview_reference_point\fP (const \fBSimpleLongitudinalDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_preview_reference_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acceleration_lookup_limit\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
