.TH "apollo::canbus::WheelSpeed::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::WheelSpeed::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBWheelSpeed\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_wheel_spd_rr_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_direction_rr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_rr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_wheel_spd_rl_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_direction_rl\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_rl\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_wheel_spd_fr_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_direction_fr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_fr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_wheel_spd_fl_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_direction_fl\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_fl\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
