.TH "apollo::perception::LaneMarker::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::LaneMarker::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBLaneMarker\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_lane_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_quality\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_model_degree\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_c0_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_c1_heading_angle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_c2_curvature\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_c3_curvature_derivative\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_view_range\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_longitude_start\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_longitude_end\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
