.TH "apollo::cyber::Clock" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Clock \- a singleton clock that can be used to get the current timestamp\&. The source can be either system(cyber) clock or a mock clock\&. Mock clock is for testing purpose mainly\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTime\fP \fBNow\fP ()"
.br
.RI "PRECISION >= 1000000 means the precision is at least 1us\&. "
.ti -1c
.RI "static double \fBNowInSeconds\fP ()"
.br
.RI "gets the current time in second\&. "
.ti -1c
.RI "static void \fBSetNow\fP (const \fBTime\fP &now)"
.br
.RI "This is for mock clock mode only\&. It will set the timestamp for the mock clock\&. "
.ti -1c
.RI "static void \fBSetMode\fP (ClockMode \fBmode\fP)"
.br
.ti -1c
.RI "static ClockMode \fBmode\fP ()"
.br
.RI "Gets the current clock mode\&. "
.ti -1c
.RI "static void \fBSetNowInSeconds\fP (const double seconds)"
.br
.RI "This is for mock clock mode only\&. It will set the timestamp for the mock clock with UNIX timestamp in seconds\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int64_t \fBPRECISION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a singleton clock that can be used to get the current timestamp\&. The source can be either system(cyber) clock or a mock clock\&. Mock clock is for testing purpose mainly\&. 
.SH "Member Function Documentation"
.PP 
.SS "ClockMode Clock::mode ()\fC [static]\fP"

.PP
Gets the current clock mode\&. 
.PP
\fBReturns\fP
.RS 4
The current clock mode\&. 
.RE
.PP

.SS "\fBTime\fP Clock::Now ()\fC [static]\fP"

.PP
PRECISION >= 1000000 means the precision is at least 1us\&. get current time\&. 
.PP
\fBReturns\fP
.RS 4
a \fBTime\fP object representing the current time\&. 
.RE
.PP

.SS "double Clock::NowInSeconds ()\fC [static]\fP"

.PP
gets the current time in second\&. 
.PP
\fBReturns\fP
.RS 4
the current time in second\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "constexpr int64_t apollo::cyber::Clock::PRECISION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
      std::chrono::system_clock::duration::period::den /
      std::chrono::system_clock::duration::period::num
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
