.TH "apollo::cyber::class_loader::utility::AbstractClassFactory< Base >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::class_loader::utility::AbstractClassFactory< Base >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::class_loader::utility::AbstractClassFactoryBase\fP\&.
.PP
Inherited by \fBapollo::cyber::class_loader::utility::ClassFactory< ClassObject, Base >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractClassFactory\fP (const std::string &class_name, const std::string &base_class_name)"
.br
.ti -1c
.RI "virtual \fBBase\fP * \fBCreateObj\fP () const =0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
