.TH "apollo::cyber::base::YieldWaitStrategy" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::YieldWaitStrategy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::base::WaitStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEmptyWait\fP () override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
