.TH "apollo::routing::RoutingResponse::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::routing::RoutingResponse::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBRoutingResponse\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBRoutingResponse\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::routing::Measurement\fP & \fBmeasurement\fP (const \fBRoutingResponse\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_measurement\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::routing::RoutingRequest\fP & \fBrouting_request\fP (const \fBRoutingResponse\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_routing_request\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_map_version\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::StatusPb\fP & \fBstatus\fP (const \fBRoutingResponse\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_status\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
