.TH "apollo::cyber::record::RecordFileBase" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::RecordFileBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::record::RecordFileReader\fP, and \fBapollo::cyber::record::RecordFileWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOpen\fP (const std::string &path)=0"
.br
.ti -1c
.RI "virtual void \fBClose\fP ()=0"
.br
.ti -1c
.RI "const std::string & \fBGetPath\fP () const"
.br
.ti -1c
.RI "const proto::Header & \fBGetHeader\fP () const"
.br
.ti -1c
.RI "const proto::Index & \fBGetIndex\fP () const"
.br
.ti -1c
.RI "int64_t \fBCurrentPosition\fP ()"
.br
.ti -1c
.RI "bool \fBSetPosition\fP (int64_t position)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::mutex \fBmutex_\fP"
.br
.ti -1c
.RI "std::string \fBpath_\fP"
.br
.ti -1c
.RI "proto::Header \fBheader_\fP"
.br
.ti -1c
.RI "proto::Index \fBindex_\fP"
.br
.ti -1c
.RI "int \fBfd_\fP = \-1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
