.TH "apollo::drivers::gnss::GlonassOrbit::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::gnss::GlonassOrbit::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBGlonassOrbit\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_gnss_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_slot_prn\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_gnss_time_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_toe\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_year\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_month\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_day\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_hour\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_minute\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_second_s\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_frequency_no\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_week_num\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_week_second_s\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_tk\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_clock_offset\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_clock_drift\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_health\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_position_x\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_position_y\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_position_z\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_velocity_x\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_velocity_y\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_velocity_z\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accelerate_x\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accelerate_y\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accelerate_z\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_infor_age\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sat_prn\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
