.TH "apollo::cyber::mainboard::ModuleController" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::mainboard::ModuleController
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleController\fP (const \fBModuleArgument\fP &args)"
.br
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.ti -1c
.RI "bool \fBLoadAll\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
