.TH "apollo::dreamview::HMIStatus_OtherComponentsEntry_DoNotUse" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::dreamview::HMIStatus_OtherComponentsEntry_DoNotUse
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::internal::MapEntry< HMIStatus_OtherComponentsEntry_DoNotUse, std::string, ::apollo::monitor::ComponentStatus, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry< \fBHMIStatus_OtherComponentsEntry_DoNotUse\fP, std::string, ::\fBapollo::monitor::ComponentStatus\fP, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE > \fBSuperType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBHMIStatus_OtherComponentsEntry_DoNotUse\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBHMIStatus_OtherComponentsEntry_DoNotUse\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBHMIStatus_OtherComponentsEntry_DoNotUse\fP &other)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const \fBHMIStatus_OtherComponentsEntry_DoNotUse\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBValidateKey\fP (std::string *s)"
.br
.ti -1c
.RI "static bool \fBValidateValue\fP (void *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
