.TH "apollo::cyber::Component< M0, M1, NullType, NullType >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Component< M0, M1, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::ComponentBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInitialize\fP (const \fBComponentConfig\fP &config) override"
.br
.ti -1c
.RI "bool \fBProcess\fP (const std::shared_ptr< M0 > &msg0, const std::shared_ptr< M1 > &msg1)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
