.TH "apollo::planning_internal::DpPolyGraphDebug" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning_internal::DpPolyGraphDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkSampleLayerFieldNumber\fP = 1, \fBkMinCostPointFieldNumber\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBDpPolyGraphDebug\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBDpPolyGraphDebug\fP (const \fBDpPolyGraphDebug\fP &from)"
.br
.ti -1c
.RI "\fBDpPolyGraphDebug\fP (\fBDpPolyGraphDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBDpPolyGraphDebug\fP & \fBoperator=\fP (const \fBDpPolyGraphDebug\fP &from)"
.br
.ti -1c
.RI "\fBDpPolyGraphDebug\fP & \fBoperator=\fP (\fBDpPolyGraphDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBDpPolyGraphDebug\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBDpPolyGraphDebug\fP *other)"
.br
.ti -1c
.RI "\fBDpPolyGraphDebug\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBDpPolyGraphDebug\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBDpPolyGraphDebug\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBsample_layer_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_sample_layer\fP ()"
.br
.ti -1c
.RI "::\fBapollo::planning_internal::SampleLayerDebug\fP * \fBmutable_sample_layer\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::planning_internal::SampleLayerDebug\fP > * \fBmutable_sample_layer\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::planning_internal::SampleLayerDebug\fP & \fBsample_layer\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::planning_internal::SampleLayerDebug\fP * \fBadd_sample_layer\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::planning_internal::SampleLayerDebug\fP > & \fBsample_layer\fP () const"
.br
.ti -1c
.RI "int \fBmin_cost_point_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_min_cost_point\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::SLPoint\fP * \fBmutable_min_cost_point\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SLPoint\fP > * \fBmutable_min_cost_point\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::SLPoint\fP & \fBmin_cost_point\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::common::SLPoint\fP * \fBadd_min_cost_point\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SLPoint\fP > & \fBmin_cost_point\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBDpPolyGraphDebug\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBDpPolyGraphDebug\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDpPolyGraphDebug\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fplanning_5finternal_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBDpPolyGraphDebug\fP &a, \fBDpPolyGraphDebug\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning_internal::DpPolyGraphDebug::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DpPolyGraphDebug::MergeImpl
}
.fi
.SS "constexpr int apollo::planning_internal::DpPolyGraphDebug::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    14
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
