.TH "apollo::canbus::Date_time_rpt_83::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Date_time_rpt_83::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBDate_time_rpt_83\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_time_second\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_time_minute\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_time_hour\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_date_day\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_date_month\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_date_year\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
