.TH "apollo::cyber::transport::ListenerHandlerBase" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::ListenerHandlerBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::transport::ListenerHandler< MessageT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDisconnect\fP (uint64_t self_id)=0"
.br
.ti -1c
.RI "virtual void \fBDisconnect\fP (uint64_t self_id, uint64_t oppo_id)=0"
.br
.ti -1c
.RI "bool \fBIsRawMessage\fP () const"
.br
.ti -1c
.RI "virtual void \fBRunFromString\fP (const std::string &str, const \fBMessageInfo\fP &msg_info)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBis_raw_message_\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
