.TH "apollo::routing::Landmark" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::routing::Landmark
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkWaypointFieldNumber\fP = 2, \fBkNameFieldNumber\fP = 1, \fBkParkingSpaceIdFieldNumber\fP = 3, \fBkParkingInfoFieldNumber\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBLandmark\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBLandmark\fP (const \fBLandmark\fP &from)"
.br
.ti -1c
.RI "\fBLandmark\fP (\fBLandmark\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBLandmark\fP & \fBoperator=\fP (const \fBLandmark\fP &from)"
.br
.ti -1c
.RI "\fBLandmark\fP & \fBoperator=\fP (\fBLandmark\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBLandmark\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBLandmark\fP *other)"
.br
.ti -1c
.RI "\fBLandmark\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBLandmark\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBLandmark\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBwaypoint_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_waypoint\fP ()"
.br
.ti -1c
.RI "::\fBapollo::routing::LaneWaypoint\fP * \fBmutable_waypoint\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::routing::LaneWaypoint\fP > * \fBmutable_waypoint\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::routing::LaneWaypoint\fP & \fBwaypoint\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::routing::LaneWaypoint\fP * \fBadd_waypoint\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::routing::LaneWaypoint\fP > & \fBwaypoint\fP () const"
.br
.ti -1c
.RI "bool \fBhas_name\fP () const"
.br
.ti -1c
.RI "void \fBclear_name\fP ()"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_name\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_name\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_name\fP (std::string *name)"
.br
.ti -1c
.RI "PROTOBUF_DEPRECATED bool \fBhas_parking_space_id\fP () const"
.br
.ti -1c
.RI "PROTOBUF_DEPRECATED void \fBclear_parking_space_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_DEPRECATED const std::string & \fBparking_space_id\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> PROTOBUF_DEPRECATED void \fBset_parking_space_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "PROTOBUF_DEPRECATED std::string * \fBmutable_parking_space_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD PROTOBUF_DEPRECATED std::string * \fBrelease_parking_space_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_DEPRECATED void \fBset_allocated_parking_space_id\fP (std::string *parking_space_id)"
.br
.ti -1c
.RI "bool \fBhas_parking_info\fP () const"
.br
.ti -1c
.RI "void \fBclear_parking_info\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::routing::ParkingInfo\fP & \fBparking_info\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::routing::ParkingInfo\fP * \fBrelease_parking_info\fP ()"
.br
.ti -1c
.RI "::\fBapollo::routing::ParkingInfo\fP * \fBmutable_parking_info\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_parking_info\fP (::\fBapollo::routing::ParkingInfo\fP *parking_info)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_parking_info\fP (::\fBapollo::routing::ParkingInfo\fP *parking_info)"
.br
.ti -1c
.RI "::\fBapollo::routing::ParkingInfo\fP * \fBunsafe_arena_release_parking_info\fP ()"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_parking_space_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBLandmark\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBLandmark\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLandmark\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBLandmark\fP &a, \fBLandmark\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::routing::Landmark::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Landmark::MergeImpl
}
.fi
.SS "constexpr int apollo::routing::Landmark::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
