.TH "apollo::cyber::transport::State" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::State
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (const uint64_t &ceiling_msg_size)"
.br
.ti -1c
.RI "void \fBDecreaseReferenceCounts\fP ()"
.br
.ti -1c
.RI "void \fBIncreaseReferenceCounts\fP ()"
.br
.ti -1c
.RI "uint32_t \fBFetchAddSeq\fP (uint32_t diff)"
.br
.ti -1c
.RI "uint32_t \fBseq\fP ()"
.br
.ti -1c
.RI "void \fBset_need_remap\fP (bool need)"
.br
.ti -1c
.RI "bool \fBneed_remap\fP ()"
.br
.ti -1c
.RI "uint64_t \fBceiling_msg_size\fP ()"
.br
.ti -1c
.RI "uint32_t \fBreference_counts\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
