.TH "apollo::hdmap::CurveSegment" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::hdmap::CurveSegment
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCurveTypeCase\fP { \fBkLineSegment\fP = 1, \fBCURVE_TYPE_NOT_SET\fP = 0 }"
.br
.ti -1c
.RI "enum : int { \fBkStartPositionFieldNumber\fP = 7, \fBkSFieldNumber\fP = 6, \fBkHeadingFieldNumber\fP = 8, \fBkLengthFieldNumber\fP = 9, \fBkLineSegmentFieldNumber\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBCurveSegment\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBCurveSegment\fP (const \fBCurveSegment\fP &from)"
.br
.ti -1c
.RI "\fBCurveSegment\fP (\fBCurveSegment\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBCurveSegment\fP & \fBoperator=\fP (const \fBCurveSegment\fP &from)"
.br
.ti -1c
.RI "\fBCurveSegment\fP & \fBoperator=\fP (\fBCurveSegment\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBCurveSegment\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBCurveSegment\fP *other)"
.br
.ti -1c
.RI "\fBCurveSegment\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBCurveSegment\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBCurveSegment\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_start_position\fP () const"
.br
.ti -1c
.RI "void \fBclear_start_position\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::PointENU\fP & \fBstart_position\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::PointENU\fP * \fBrelease_start_position\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::PointENU\fP * \fBmutable_start_position\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_start_position\fP (::\fBapollo::common::PointENU\fP *start_position)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_start_position\fP (::\fBapollo::common::PointENU\fP *start_position)"
.br
.ti -1c
.RI "::\fBapollo::common::PointENU\fP * \fBunsafe_arena_release_start_position\fP ()"
.br
.ti -1c
.RI "bool \fBhas_s\fP () const"
.br
.ti -1c
.RI "void \fBclear_s\fP ()"
.br
.ti -1c
.RI "double \fBs\fP () const"
.br
.ti -1c
.RI "void \fBset_s\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_heading\fP () const"
.br
.ti -1c
.RI "void \fBclear_heading\fP ()"
.br
.ti -1c
.RI "double \fBheading\fP () const"
.br
.ti -1c
.RI "void \fBset_heading\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_length\fP () const"
.br
.ti -1c
.RI "void \fBclear_length\fP ()"
.br
.ti -1c
.RI "double \fBlength\fP () const"
.br
.ti -1c
.RI "void \fBset_length\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_line_segment\fP () const"
.br
.ti -1c
.RI "void \fBclear_line_segment\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::hdmap::LineSegment\fP & \fBline_segment\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::hdmap::LineSegment\fP * \fBrelease_line_segment\fP ()"
.br
.ti -1c
.RI "::\fBapollo::hdmap::LineSegment\fP * \fBmutable_line_segment\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_line_segment\fP (::\fBapollo::hdmap::LineSegment\fP *line_segment)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_line_segment\fP (::\fBapollo::hdmap::LineSegment\fP *line_segment)"
.br
.ti -1c
.RI "::\fBapollo::hdmap::LineSegment\fP * \fBunsafe_arena_release_line_segment\fP ()"
.br
.ti -1c
.RI "void \fBclear_curve_type\fP ()"
.br
.ti -1c
.RI "CurveTypeCase \fBcurve_type_case\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBCurveSegment\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBCurveSegment\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCurveSegment\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCurveSegment\fP &a, \fBCurveSegment\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::hdmap::CurveSegment::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    CurveSegment::MergeImpl
}
.fi
.SS "constexpr int apollo::hdmap::CurveSegment::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
