.TH "apollo::planning::ObjectDecisionType::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::ObjectDecisionType::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectIgnore\fP & \fBignore\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectStop\fP & \fBstop\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectFollow\fP & \fBfollow\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectYield\fP & \fByield\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectOvertake\fP & \fBovertake\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectNudge\fP & \fBnudge\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectAvoid\fP & \fBavoid\fP (const \fBObjectDecisionType\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectSidePass\fP & \fBside_pass\fP (const \fBObjectDecisionType\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
