.TH "apollo::drivers::gnss::Ins::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::gnss::Ins::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBIns\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_measurement_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::PointLLH\fP & \fBposition\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBeuler_angles\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_euler_angles\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBlinear_velocity\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_linear_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBangular_velocity\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_angular_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBlinear_acceleration\fP (const \fBIns\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_linear_acceleration\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
