.TH "apollo::cyber::ClientBase" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::ClientBase \- \fBBase\fP class of \fBClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_base\&.h>\fP
.PP
Inherited by \fBapollo::cyber::Client< Request, Response >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClientBase\fP (const std::string &service_name)"
.br
.RI "Construct a new \fBClient\fP \fBBase\fP object\&. "
.ti -1c
.RI "virtual void \fBDestroy\fP ()=0"
.br
.RI "Destroy the \fBClient\fP\&. "
.ti -1c
.RI "const std::string & \fBServiceName\fP () const"
.br
.RI "Get the service name\&. "
.ti -1c
.RI "virtual bool \fBServiceIsReady\fP () const =0"
.br
.RI "Ensure whether there is any \fBService\fP named \fCservice_name_\fP "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBWaitForServiceNanoseconds\fP (std::chrono::nanoseconds time_out)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBservice_name_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBase\fP class of \fBClient\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::ClientBase::ClientBase (const std::string & service_name)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Construct a new \fBClient\fP \fBBase\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIservice_name\fP the service we can request 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
