.TH "apollo::drivers::Vehicle1_4f0::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle1_4f0::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicle1_4f0\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_can_rx_steering_angle_validity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_steering_angle_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_steering_angle_sign\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_steering_angle_rate_sign\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_steering_angle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_radius_curvature\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_yaw_rate_validity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_yaw_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_vehicle_speed_direction\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_vehicle_speed\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
