.TH "apollo::drivers::gnss::KepplerOrbit::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::gnss::KepplerOrbit::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBKepplerOrbit\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_gnss_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sat_prn\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_gnss_time_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_year\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_month\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_day\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_hour\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_minute\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_second_s\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_week_num\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_reserved\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_af0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_af1\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_af2\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_iode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_deltan\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_m0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_e\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_roota\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_toe\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_toc\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cic\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_crc\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cis\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_crs\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cuc\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cus\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_omega0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_omega\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_i0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_omegadot\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_idot\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_codesonl2channel\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_l2pdataflag\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accuracy\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_health\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_tgd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_iodc\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
