.TH "apollo::simulation::Condition::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::simulation::Condition::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBCondition\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::simulation::LogicalCondition\fP & \fBlogical_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::SpeedCondition\fP & \fBspeed_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::AccelerationCondition\fP & \fBacceleration_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::JerkCondition\fP & \fBjerk_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::ObjectOverlapCondition\fP & \fBobject_overlap_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RegionOverlapCondition\fP & \fBregion_overlap_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RegionOverlapLWCondition\fP & \fBregion_overlap_lw_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::SpinCondition\fP & \fBspin_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::OnRoadCondition\fP & \fBon_road_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RunRedLightCondition\fP & \fBrun_red_light_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::ChangeLaneAtJunctionCondition\fP & \fBchange_lane_at_junction_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RoutingCondition\fP & \fBrouting_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::CrosswalkYieldCondition\fP & \fBcrosswalk_yield_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::AbnormalStopCondition\fP & \fBabnormal_stop_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::BrakeTapCondition\fP & \fBbrake_tap_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RunStopSignCondition\fP & \fBrun_stop_sign_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::CheckpointCondition\fP & \fBcheckpoint_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::DistToEndCondition\fP & \fBdist_to_end_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::DistToLaneCenterCondition\fP & \fBdist_to_lane_center_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::CrosswalkStopCondition\fP & \fBcrosswalk_stop_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::RedLightStopCondition\fP & \fBred_light_stop_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::SpeedbumpLimitCondition\fP & \fBspeedbump_limit_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::WorkingZoneAvoidLimitCondition\fP & \fBworking_zone_avoid_limit_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::LimitedTimeParkingCondition\fP & \fBlimited_time_parking_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::FollowAndBypassCondition\fP & \fBfollow_and_bypass_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::ObstacleBypassCondition\fP & \fBobstacle_bypass_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::CentripetalAccelerationCondition\fP & \fBcentripetal_acceleration_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::TimeLimitCondition\fP & \fBtime_limit_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::AntiCheatingCondition\fP & \fBanti_cheating_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::KeyPointCondition\fP & \fBkey_point_condition\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::GradePlanning\fP & \fBgrade_planning\fP (const \fBCondition\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_grade_planning\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
