.TH "apollo::cyber::io::PollHandler" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::io::PollHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPollHandler\fP (int fd)"
.br
.ti -1c
.RI "bool \fBBlock\fP (int timeout_ms, bool is_read)"
.br
.ti -1c
.RI "bool \fBUnblock\fP ()"
.br
.ti -1c
.RI "int \fBfd\fP () const"
.br
.ti -1c
.RI "void \fBset_fd\fP (int fd)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
