.TH "apollo::planning::ObjectOvertake" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::ObjectOvertake
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkFencePointFieldNumber\fP = 2, \fBkDistanceSFieldNumber\fP = 1, \fBkFenceHeadingFieldNumber\fP = 3, \fBkTimeBufferFieldNumber\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBObjectOvertake\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBObjectOvertake\fP (const \fBObjectOvertake\fP &from)"
.br
.ti -1c
.RI "\fBObjectOvertake\fP (\fBObjectOvertake\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBObjectOvertake\fP & \fBoperator=\fP (const \fBObjectOvertake\fP &from)"
.br
.ti -1c
.RI "\fBObjectOvertake\fP & \fBoperator=\fP (\fBObjectOvertake\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBObjectOvertake\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBObjectOvertake\fP *other)"
.br
.ti -1c
.RI "\fBObjectOvertake\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBObjectOvertake\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBObjectOvertake\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_fence_point\fP () const"
.br
.ti -1c
.RI "void \fBclear_fence_point\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::PointENU\fP & \fBfence_point\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::PointENU\fP * \fBrelease_fence_point\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::PointENU\fP * \fBmutable_fence_point\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_fence_point\fP (::\fBapollo::common::PointENU\fP *fence_point)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_fence_point\fP (::\fBapollo::common::PointENU\fP *fence_point)"
.br
.ti -1c
.RI "::\fBapollo::common::PointENU\fP * \fBunsafe_arena_release_fence_point\fP ()"
.br
.ti -1c
.RI "bool \fBhas_distance_s\fP () const"
.br
.ti -1c
.RI "void \fBclear_distance_s\fP ()"
.br
.ti -1c
.RI "double \fBdistance_s\fP () const"
.br
.ti -1c
.RI "void \fBset_distance_s\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_fence_heading\fP () const"
.br
.ti -1c
.RI "void \fBclear_fence_heading\fP ()"
.br
.ti -1c
.RI "double \fBfence_heading\fP () const"
.br
.ti -1c
.RI "void \fBset_fence_heading\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_time_buffer\fP () const"
.br
.ti -1c
.RI "void \fBclear_time_buffer\fP ()"
.br
.ti -1c
.RI "double \fBtime_buffer\fP () const"
.br
.ti -1c
.RI "void \fBset_time_buffer\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBObjectOvertake\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBObjectOvertake\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectOvertake\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fdecision_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBObjectOvertake\fP &a, \fBObjectOvertake\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning::ObjectOvertake::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ObjectOvertake::MergeImpl
}
.fi
.SS "constexpr int apollo::planning::ObjectOvertake::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    6
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
