.TH "apollo::cyber::blocker::IntraWriter< MessageT >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::blocker::IntraWriter< MessageT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::Writer< MessageT >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< MessageT >"
.br
.ti -1c
.RI "using \fBBlockerManagerPtr\fP = std::shared_ptr< \fBBlockerManager\fP >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraWriter\fP (const \fBproto::RoleAttributes\fP &attr)"
.br
.ti -1c
.RI "bool \fBInit\fP () override"
.br
.RI "Init the \fBWriter\fP\&. "
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.RI "Shutdown the \fBWriter\fP\&. "
.ti -1c
.RI "bool \fBWrite\fP (const MessageT &msg) override"
.br
.RI "Write a MessageT instance\&. "
.ti -1c
.RI "bool \fBWrite\fP (const MessagePtr &msg_ptr) override"
.br
.RI "Write a shared ptr of MessageT\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<typename MessageT > bool \fBapollo::cyber::blocker::IntraWriter\fP< MessageT >::Init ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Init the \fBWriter\fP\&. 
.PP
\fBReturns\fP
.RS 4
true if init success 
.PP
false if init failed 
.RE
.PP

.PP
Implements \fBapollo::cyber::WriterBase\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::blocker::IntraWriter\fP< MessageT >::Write (const MessagePtr & msg_ptr)\fC [override]\fP, \fC [virtual]\fP"

.PP
Write a shared ptr of MessageT\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg_ptr\fP the message shared ptr we want to write 
.RE
.PP
\fBReturns\fP
.RS 4
true if write successfully 
.PP
false if write failed 
.RE
.PP

.PP
Reimplemented from \fBapollo::cyber::Writer< MessageT >\fP\&.
.SS "template<typename MessageT > bool \fBapollo::cyber::blocker::IntraWriter\fP< MessageT >::Write (const MessageT & msg)\fC [override]\fP, \fC [virtual]\fP"

.PP
Write a MessageT instance\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP the message we want to write 
.RE
.PP
\fBReturns\fP
.RS 4
true if write successfully 
.PP
false if write failed 
.RE
.PP

.PP
Reimplemented from \fBapollo::cyber::Writer< MessageT >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
