.TH "apollo::audio::AudioEvent::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::audio::AudioEvent::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBAudioEvent\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBAudioEvent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_moving_result\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_audio_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_siren_is_on\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_audio_direction\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::localization::Pose\fP & \fBpose\fP (const \fBAudioEvent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_pose\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
