.TH "apollo::cyber::transport::Endpoint" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Endpoint
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::transport::Receiver< M >\fP, and \fBapollo::cyber::transport::Transmitter< M >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEndpoint\fP (const \fBRoleAttributes\fP &attr)"
.br
.ti -1c
.RI "const \fBIdentity\fP & \fBid\fP () const"
.br
.ti -1c
.RI "const \fBRoleAttributes\fP & \fBattributes\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBenabled_\fP"
.br
.ti -1c
.RI "\fBIdentity\fP \fBid_\fP"
.br
.ti -1c
.RI "\fBRoleAttributes\fP \fBattr_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
