.TH "apollo::cyber::transport::ShmDispatcher" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::ShmDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Dispatcher\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBSegmentContainer\fP = std::unordered_map< uint64_t, SegmentPtr >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const \fBRoleAttributes\fP &self_attr, const MessageListener< MessageT > &listener)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const \fBRoleAttributes\fP &self_attr, const \fBRoleAttributes\fP &opposite_attr, const MessageListener< MessageT > &listener)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
