.TH "apollo::cyber::Service< Request, Response >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Service< Request, Response > \- \fBService\fP handles \fCRequest\fP from the \fBClient\fP, and send a \fCResponse\fP to it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <service\&.h>\fP
.PP
Inherits \fBapollo::cyber::ServiceBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBServiceCallback\fP = std::function< void(const std::shared_ptr< Request > &, std::shared_ptr< Response > &)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBService\fP (const std::string &node_name, const std::string &\fBservice_name\fP, const ServiceCallback &service_callback)"
.br
.RI "Construct a new \fBService\fP object\&. "
.ti -1c
.RI "\fBService\fP (const std::string &node_name, const std::string &\fBservice_name\fP, ServiceCallback &&service_callback)"
.br
.RI "Construct a new \fBService\fP object\&. "
.ti -1c
.RI "\fBService\fP ()=delete"
.br
.RI "Forbid default constructing\&. "
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.RI "Init the \fBService\fP\&. "
.ti -1c
.RI "void \fBdestroy\fP ()"
.br
.RI "Destroy the \fBService\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Request, typename Response>
.br
class apollo::cyber::Service< Request, Response >"
\fBService\fP handles \fCRequest\fP from the \fBClient\fP, and send a \fCResponse\fP to it\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIRequest\fP the request type 
.br
\fIResponse\fP the response type 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Request , typename Response > \fBapollo::cyber::Service\fP< Request, Response >::\fBService\fP (const std::string & node_name, const std::string & service_name, const ServiceCallback & service_callback)\fC [inline]\fP"

.PP
Construct a new \fBService\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP used to fill RoleAttribute when join the topology 
.br
\fIservice_name\fP the service name we provide 
.br
\fIservice_callback\fP reference of \fCServiceCallback\fP object 
.RE
.PP

.SS "template<typename Request , typename Response > \fBapollo::cyber::Service\fP< Request, Response >::\fBService\fP (const std::string & node_name, const std::string & service_name, ServiceCallback && service_callback)\fC [inline]\fP"

.PP
Construct a new \fBService\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP used to fill RoleAttribute when join the topology 
.br
\fIservice_name\fP the service name we provide 
.br
\fIservice_callback\fP rvalue reference of \fCServiceCallback\fP object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
