.TH "apollo::cyber::record::Chunk" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::Chunk
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (const \fBproto::SingleMessage\fP &message)"
.br
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::mutex \fBmutex_\fP"
.br
.ti -1c
.RI "\fBproto::ChunkHeader\fP \fBheader_\fP"
.br
.ti -1c
.RI "std::unique_ptr< \fBproto::ChunkBody\fP > \fBbody_\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
