.TH "apollo::cyber::event::TransportEvent" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::event::TransportEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::event::EventBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBSerializeToString\fP () override"
.br
.ti -1c
.RI "void \fBset_msg_seq\fP (uint64_t msg_seq) override"
.br
.ti -1c
.RI "void \fBset_channel_id\fP (uint64_t channel_id) override"
.br
.ti -1c
.RI "void \fBset_adder\fP (const std::string &adder) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBShowTransPerf\fP (TransPerf type)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
