.TH "apollo::cyber::Component< M0, NullType, NullType, NullType >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Component< M0, NullType, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::ComponentBase\fP\&.
.PP
Inherited by \fBapollo::cyber::Component_A< M0, M1, M2, M3 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInitialize\fP (const ComponentConfig &config) override"
.br
.ti -1c
.RI "bool \fBProcess\fP (const std::shared_ptr< M0 > &msg)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
