.TH "apollo::cyber::scheduler::ProcessorContext" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::scheduler::ProcessorContext
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::scheduler::ChoreographyContext\fP, and \fBapollo::cyber::scheduler::ClassicContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBShutdown\fP ()"
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBCRoutine\fP > \fBNextRoutine\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBWait\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fBstop_\fP {false}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
