.TH "apollo::cyber::Rate" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Rate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRate\fP (double frequency)"
.br
.ti -1c
.RI "\fBRate\fP (uint64_t nanoseconds)"
.br
.ti -1c
.RI "\fBRate\fP (const \fBDuration\fP &)"
.br
.ti -1c
.RI "void \fBSleep\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "\fBDuration\fP \fBCycleTime\fP () const"
.br
.ti -1c
.RI "\fBDuration\fP \fBExpectedCycleTime\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
