.TH "apollo::cyber::transport::Identity" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Identity
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdentity\fP (bool need_generate=true)"
.br
.ti -1c
.RI "\fBIdentity\fP (const \fBIdentity\fP &another)"
.br
.ti -1c
.RI "\fBIdentity\fP & \fBoperator=\fP (const \fBIdentity\fP &another)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIdentity\fP &another) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBIdentity\fP &another) const"
.br
.ti -1c
.RI "std::string \fBToString\fP () const"
.br
.ti -1c
.RI "size_t \fBLength\fP () const"
.br
.ti -1c
.RI "uint64_t \fBHashValue\fP () const"
.br
.ti -1c
.RI "const char * \fBdata\fP () const"
.br
.ti -1c
.RI "void \fBset_data\fP (const char *data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
