.TH "apollo::simulation::Scenario_TL::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::simulation::Scenario_TL::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBScenario_TL\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::Scenario_TL_Location\fP & \fBlocation\fP (const \fBScenario_TL\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_location\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_trigger_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_trigger_value\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::Scenario_TL_State\fP & \fBinitial_state\fP (const \fBScenario_TL\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_initial_state\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
