.TH "apollo::drivers::Vehicle4_5f3::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle4_5f3::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicle4_5f3\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_range_r2m\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_range_m2t\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_range_1\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_mtg_space_ver\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_mtg_space_hor\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_tgt_mtg_offset\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_align_samp_req\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_align_max_nt\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_align_cmd_2\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_fac_align_cmd_1\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
