.TH "apollo::cyber::base::ObjectPool< T >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::ObjectPool< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::enable_shared_from_this< ObjectPool< T > >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBInitFunc\fP = std::function< void(T *)>"
.br
.ti -1c
.RI "using \fBObjectPoolPtr\fP = std::shared_ptr< \fBObjectPool\fP< T > >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBObjectPool\fP (uint32_t num_objects, Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBObjectPool\fP (uint32_t num_objects, InitFunc f, Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "std::shared_ptr< T > \fBGetObject\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
