.TH "apollo::cyber::blocker::BlockerManager" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::blocker::BlockerManager
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBlockerMap\fP = std::unordered_map< std::string, std::shared_ptr< \fBBlockerBase\fP > >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > bool \fBPublish\fP (const std::string &channel_name, const typename \fBBlocker\fP< T >::MessagePtr &msg)"
.br
.ti -1c
.RI "template<typename T > bool \fBPublish\fP (const std::string &channel_name, const typename \fBBlocker\fP< T >::MessageType &msg)"
.br
.ti -1c
.RI "template<typename T > bool \fBSubscribe\fP (const std::string &channel_name, size_t capacity, const std::string &callback_id, const typename \fBBlocker\fP< T >::Callback &callback)"
.br
.ti -1c
.RI "template<typename T > bool \fBUnsubscribe\fP (const std::string &channel_name, const std::string &callback_id)"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBBlocker\fP< T > > \fBGetBlocker\fP (const std::string &channel_name)"
.br
.ti -1c
.RI "template<typename T > std::shared_ptr< \fBBlocker\fP< T > > \fBGetOrCreateBlocker\fP (const \fBBlockerAttr\fP &attr)"
.br
.ti -1c
.RI "void \fBObserve\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const std::shared_ptr< \fBBlockerManager\fP > & \fBInstance\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
