.TH "apollo::canbus::Eps::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Eps::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBEps\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_eps_fail\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_eps_control_state\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_eps_driver_hand_torq\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_steering_angle_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_steering_angle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_steering_angle_spd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_trimming_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_calibration_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_failure_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_allow_enter_autonomous_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_driving_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_steering_angle_cmd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle_speed\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_epas_torque\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_steering_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_driver_override\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_driver_activity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_watchdog_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_channel_1_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_channel_2_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_calibration_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_connector_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_timestamp_65\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_major_version\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_minor_version\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_build_number\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
