.TH "apollo::cyber::base::BusySpinWaitStrategy" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::BusySpinWaitStrategy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::base::WaitStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEmptyWait\fP () override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
