.TH "apollo::cyber::Component< M0, M1, M2, M3 >::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::Component< M0, M1, M2, M3 >::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBComponent\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBsummary\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_summary\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBprocess_status\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_process_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBchannel_status\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_channel_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBresource_status\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_resource_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBother_status\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_other_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::monitor::ComponentStatus\fP & \fBmodule_status\fP (const \fBComponent\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_module_status\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
