.TH "apollo::cyber::record::PlayTaskProducer" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::PlayTaskProducer
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBNodePtr\fP = std::shared_ptr< \fBNode\fP >"
.br
.ti -1c
.RI "using \fBThreadPtr\fP = std::unique_ptr< std::thread >"
.br
.ti -1c
.RI "using \fBTaskBufferPtr\fP = std::shared_ptr< \fBPlayTaskBuffer\fP >"
.br
.ti -1c
.RI "using \fBRecordReaderPtr\fP = std::shared_ptr< \fBRecordReader\fP >"
.br
.ti -1c
.RI "using \fBWriterPtr\fP = std::shared_ptr< \fBWriter\fP< \fBmessage::RawMessage\fP > >"
.br
.ti -1c
.RI "using \fBWriterMap\fP = std::unordered_map< std::string, WriterPtr >"
.br
.ti -1c
.RI "using \fBMessageTypeMap\fP = std::unordered_map< std::string, std::string >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayTaskProducer\fP (const TaskBufferPtr &task_buffer, const \fBPlayParam\fP &play_param)"
.br
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "const \fBPlayParam\fP & \fBplay_param\fP () const"
.br
.ti -1c
.RI "bool \fBis_stopped\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
