.TH "apollo::planning::RSSInfo::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::RSSInfo::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBRSSInfo\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_rss_safe\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_cur_dist_lon\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_rss_safe_dist_lon\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lon_range_minimum\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lon_range_maximum\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lat_left_range_minimum\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lat_left_range_maximum\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lat_right_range_minimum\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_acc_lat_right_range_maximum\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
