.TH "apollo::cyber::service_discovery::Graph" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::service_discovery::Graph
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBVerticeSet\fP = std::unordered_map< std::string, \fBVertice\fP >"
.br
.ti -1c
.RI "using \fBAdjacencyList\fP = std::unordered_map< std::string, VerticeSet >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInsert\fP (const \fBEdge\fP &e)"
.br
.ti -1c
.RI "void \fBDelete\fP (const \fBEdge\fP &e)"
.br
.ti -1c
.RI "uint32_t \fBGetNumOfEdge\fP ()"
.br
.ti -1c
.RI "FlowDirection \fBGetDirectionOf\fP (const \fBVertice\fP &lhs, const \fBVertice\fP &rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
