.TH "apollo::planning_internal::SmootherDebug" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning_internal::SmootherDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkReasonFieldNumber\fP = 3, \fBkIsSmoothedFieldNumber\fP = 1, \fBkTypeFieldNumber\fP = 2 }"
.br
.ti -1c
.RI "typedef SmootherDebug_SmootherType \fBSmootherType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBSmootherDebug\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBSmootherDebug\fP (const \fBSmootherDebug\fP &from)"
.br
.ti -1c
.RI "\fBSmootherDebug\fP (\fBSmootherDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBSmootherDebug\fP & \fBoperator=\fP (const \fBSmootherDebug\fP &from)"
.br
.ti -1c
.RI "\fBSmootherDebug\fP & \fBoperator=\fP (\fBSmootherDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBSmootherDebug\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBSmootherDebug\fP *other)"
.br
.ti -1c
.RI "\fBSmootherDebug\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBSmootherDebug\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBSmootherDebug\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_reason\fP () const"
.br
.ti -1c
.RI "void \fBclear_reason\fP ()"
.br
.ti -1c
.RI "const std::string & \fBreason\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_reason\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_reason\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_reason\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_reason\fP (std::string *reason)"
.br
.ti -1c
.RI "bool \fBhas_is_smoothed\fP () const"
.br
.ti -1c
.RI "void \fBclear_is_smoothed\fP ()"
.br
.ti -1c
.RI "bool \fBis_smoothed\fP () const"
.br
.ti -1c
.RI "void \fBset_is_smoothed\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_type\fP ()"
.br
.ti -1c
.RI "::apollo::planning_internal::SmootherDebug_SmootherType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBset_type\fP (::apollo::planning_internal::SmootherDebug_SmootherType value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_reason\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBSmootherDebug\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBSmootherDebug\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBSmootherType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBSmootherType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBSmootherType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBSmootherType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SmootherType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr SmootherType \fBSMOOTHER_NONE\fP"
.br
.ti -1c
.RI "static constexpr SmootherType \fBSMOOTHER_CLOSE_STOP\fP"
.br
.ti -1c
.RI "static constexpr SmootherType \fBSmootherType_MIN\fP"
.br
.ti -1c
.RI "static constexpr SmootherType \fBSmootherType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBSmootherType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSmootherDebug\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fplanning_5finternal_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBSmootherDebug\fP &a, \fBSmootherDebug\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning_internal::SmootherDebug::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SmootherDebug::MergeImpl
}
.fi
.SS "constexpr int apollo::planning_internal::SmootherDebug::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    18
.fi
.SS "constexpr SmootherDebug_SmootherType apollo::planning_internal::SmootherDebug::SMOOTHER_CLOSE_STOP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    SmootherDebug_SmootherType_SMOOTHER_CLOSE_STOP
.fi
.SS "constexpr SmootherDebug_SmootherType apollo::planning_internal::SmootherDebug::SMOOTHER_NONE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    SmootherDebug_SmootherType_SMOOTHER_NONE
.fi
.SS "constexpr int apollo::planning_internal::SmootherDebug::SmootherType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    SmootherDebug_SmootherType_SmootherType_ARRAYSIZE
.fi
.SS "constexpr SmootherDebug_SmootherType apollo::planning_internal::SmootherDebug::SmootherType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    SmootherDebug_SmootherType_SmootherType_MAX
.fi
.SS "constexpr SmootherDebug_SmootherType apollo::planning_internal::SmootherDebug::SmootherType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    SmootherDebug_SmootherType_SmootherType_MIN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
