.TH "apollo::cyber::base::UnboundedQueue< T >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::UnboundedQueue< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnboundedQueue\fP & \fBoperator=\fP (const \fBUnboundedQueue\fP &other)=delete"
.br
.ti -1c
.RI "\fBUnboundedQueue\fP (const \fBUnboundedQueue\fP &other)=delete"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBEnqueue\fP (const T &element)"
.br
.ti -1c
.RI "bool \fBDequeue\fP (T *element)"
.br
.ti -1c
.RI "size_t \fBSize\fP ()"
.br
.ti -1c
.RI "bool \fBEmpty\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
