.TH "apollo::cyber::transport::History< MessageT >::CachedMessage" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::History< MessageT >::CachedMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCachedMessage\fP (const MessagePtr &message, const \fBMessageInfo\fP &message_info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MessagePtr \fBmsg\fP"
.br
.ti -1c
.RI "\fBMessageInfo\fP \fBmsg_info\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
