.TH "apollo::canbus::Gas::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Gas::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBGas\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_gas_pedal_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_gas_pedal_pressed_more\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_gas_pedal_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_gas_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_input\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_cmd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_output\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_watchdog_source\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_enabled\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_driver_override\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_driver_activity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_watchdog_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_channel_1_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_channel_2_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_connector_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accelerator_pedal\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_accelerator_pedal_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_major_version\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_minor_version\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_build_number\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
