.TH "apollo::cyber::transport::Dispatcher" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Dispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::transport::IntraDispatcher\fP, \fBapollo::cyber::transport::RtpsDispatcher\fP, and \fBapollo::cyber::transport::ShmDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBShutdown\fP ()"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const RoleAttributes &self_attr, const MessageListener< MessageT > &listener)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const RoleAttributes &self_attr, const RoleAttributes &opposite_attr, const MessageListener< MessageT > &listener)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBRemoveListener\fP (const RoleAttributes &self_attr)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBRemoveListener\fP (const RoleAttributes &self_attr, const RoleAttributes &opposite_attr)"
.br
.ti -1c
.RI "bool \fBHasChannel\fP (uint64_t channel_id)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fBis_shutdown_\fP"
.br
.ti -1c
.RI "\fBAtomicHashMap\fP< uint64_t, ListenerHandlerBasePtr > \fBmsg_listeners_\fP"
.br
.ti -1c
.RI "\fBbase::AtomicRWLock\fP \fBrw_lock_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
