.TH "apollo::planning_internal::PlanningData::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning_internal::PlanningData::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBPlanningData\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::localization::LocalizationEstimate\fP & \fBadc_position\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_adc_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Chassis\fP & \fBchassis\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_chassis\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::routing::RoutingResponse\fP & \fBrouting\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_routing\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::TrajectoryPoint\fP & \fBinit_point\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_init_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBprediction_header\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_prediction_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::SignalLightDebug\fP & \fBsignal_light\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_signal_light\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::DpPolyGraphDebug\fP & \fBdp_poly_graph\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_dp_poly_graph\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::LatticeStTraining\fP & \fBlattice_st_image\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lattice_st_image\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::relative_map::MapMsg\fP & \fBrelative_map\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_relative_map\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::AutoTuningTrainingData\fP & \fBauto_tuning_training_data\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_auto_tuning_training_data\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_front_clear_distance\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::ScenarioDebug\fP & \fBscenario\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_scenario\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::OpenSpaceDebug\fP & \fBopen_space\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_open_space\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::SmootherDebug\fP & \fBsmoother\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_smoother\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::PullOverDebug\fP & \fBpull_over\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_pull_over\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning_internal::HybridModelDebug\fP & \fBhybrid_model\fP (const \fBPlanningData\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_hybrid_model\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
