.TH "apollo::cyber::transport::Receiver< M >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Receiver< M >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Endpoint\fP\&.
.PP
Inherited by \fBapollo::cyber::transport::HybridReceiver< M >\fP, \fBapollo::cyber::transport::IntraReceiver< M >\fP, \fBapollo::cyber::transport::RtpsReceiver< M >\fP, and \fBapollo::cyber::transport::ShmReceiver< M >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< M >"
.br
.ti -1c
.RI "using \fBMessageListener\fP = std::function< void(const MessagePtr &, const \fBMessageInfo\fP &, const RoleAttributes &)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReceiver\fP (const RoleAttributes &attr, const MessageListener &msg_listener)"
.br
.ti -1c
.RI "virtual void \fBEnable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDisable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBEnable\fP (const RoleAttributes &opposite_attr)=0"
.br
.ti -1c
.RI "virtual void \fBDisable\fP (const RoleAttributes &opposite_attr)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnNewMessage\fP (const MessagePtr &msg, const \fBMessageInfo\fP &msg_info)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MessageListener \fBmsg_listener_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
