.TH "apollo::cyber::record::RecordMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::RecordMessage \- Basic data struct of record message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <record_message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecordMessage\fP ()"
.br
.RI "The constructor\&. "
.ti -1c
.RI "\fBRecordMessage\fP (const std::string &name, const std::string &message, uint64_t msg_time)"
.br
.RI "The constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel_name\fP"
.br
.RI "The channel name of the message\&. "
.ti -1c
.RI "std::string \fBcontent\fP"
.br
.RI "The content of the message\&. "
.ti -1c
.RI "uint64_t \fBtime\fP"
.br
.RI "The time (nanosecond) of the message\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basic data struct of record message\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::record::RecordMessage::RecordMessage (const std::string & name, const std::string & message, uint64_t msg_time)\fC [inline]\fP"

.PP
The constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.br
\fImessage\fP 
.br
\fImsg_time\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
