.TH "apollo::cyber::PyParameter" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyParameter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyParameter\fP (\fBParameter\fP *param)"
.br
.ti -1c
.RI "\fBPyParameter\fP (const std::string &name, const int64_t int_value)"
.br
.ti -1c
.RI "\fBPyParameter\fP (const std::string &name, const double double_value)"
.br
.ti -1c
.RI "\fBPyParameter\fP (const std::string &name, const std::string &string_value)"
.br
.ti -1c
.RI "\fBPyParameter\fP (const std::string &name, const std::string &msg_str, const std::string &full_name, const std::string &proto_desc)"
.br
.ti -1c
.RI "uint \fBtype\fP ()"
.br
.ti -1c
.RI "std::string \fBtype_name\fP ()"
.br
.ti -1c
.RI "std::string \fBdescriptor\fP ()"
.br
.ti -1c
.RI "std::string \fBname\fP ()"
.br
.ti -1c
.RI "int64_t \fBas_int64\fP ()"
.br
.ti -1c
.RI "double \fBas_double\fP ()"
.br
.ti -1c
.RI "std::string \fBas_string\fP ()"
.br
.ti -1c
.RI "std::string \fBdebug_string\fP ()"
.br
.ti -1c
.RI "\fBParameter\fP & \fBget_param\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
