.TH "apollo::drivers::DelphiESR::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::DelphiESR::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBDelphiESR\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status9_5e8\fP & \fBesr_status9_5e8\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status9_5e8\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status6_5e5\fP & \fBesr_status6_5e5\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status6_5e5\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status5_5e4\fP & \fBesr_status5_5e4\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status5_5e4\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status3_4e2\fP & \fBesr_status3_4e2\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status3_4e2\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status4_4e3\fP & \fBesr_status4_4e3\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status4_4e3\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Acm_inst_req_7e0\fP & \fBacm_inst_req_7e0\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_acm_inst_req_7e0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_valid1_5d0\fP & \fBesr_valid1_5d0\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_valid1_5d0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_valid2_5d1\fP & \fBesr_valid2_5d1\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_valid2_5d1\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Acm_inst_resp_7e4\fP & \fBacm_inst_resp_7e4\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_acm_inst_resp_7e4\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle2_4f1\fP & \fBvehicle2_4f1\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle2_4f1\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle1_4f0\fP & \fBvehicle1_4f0\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle1_4f0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_sim1_5c0\fP & \fBesr_sim1_5c0\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_sim1_5c0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status1_4e0\fP & \fBesr_status1_4e0\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status1_4e0\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status2_4e1\fP & \fBesr_status2_4e1\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status2_4e1\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status8_5e7\fP & \fBesr_status8_5e7\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status8_5e7\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Esr_status7_5e6\fP & \fBesr_status7_5e6\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esr_status7_5e6\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle3_5f2\fP & \fBvehicle3_5f2\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle3_5f2\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle4_5f3\fP & \fBvehicle4_5f3\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle4_5f3\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle5_5f4\fP & \fBvehicle5_5f4\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle5_5f4\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Vehicle6_5f5\fP & \fBvehicle6_5f5\fP (const \fBDelphiESR\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle6_5f5\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
