.TH "apollo::storytelling::CloseToJunction" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::storytelling::CloseToJunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkIdFieldNumber\fP = 1, \fBkTypeFieldNumber\fP = 2, \fBkDistanceFieldNumber\fP = 3 }"
.br
.ti -1c
.RI "typedef CloseToJunction_JunctionType \fBJunctionType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBCloseToJunction\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBCloseToJunction\fP (const \fBCloseToJunction\fP &from)"
.br
.ti -1c
.RI "\fBCloseToJunction\fP (\fBCloseToJunction\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBCloseToJunction\fP & \fBoperator=\fP (const \fBCloseToJunction\fP &from)"
.br
.ti -1c
.RI "\fBCloseToJunction\fP & \fBoperator=\fP (\fBCloseToJunction\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBCloseToJunction\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBCloseToJunction\fP *other)"
.br
.ti -1c
.RI "\fBCloseToJunction\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBCloseToJunction\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBCloseToJunction\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_id\fP ()"
.br
.ti -1c
.RI "const std::string & \fBid\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_id\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_id\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_id\fP (std::string *id)"
.br
.ti -1c
.RI "bool \fBhas_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_type\fP ()"
.br
.ti -1c
.RI "::apollo::storytelling::CloseToJunction_JunctionType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBset_type\fP (::apollo::storytelling::CloseToJunction_JunctionType value)"
.br
.ti -1c
.RI "bool \fBhas_distance\fP () const"
.br
.ti -1c
.RI "void \fBclear_distance\fP ()"
.br
.ti -1c
.RI "double \fBdistance\fP () const"
.br
.ti -1c
.RI "void \fBset_distance\fP (double value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_id\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBCloseToJunction\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBCloseToJunction\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBJunctionType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBJunctionType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBJunctionType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBJunctionType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, JunctionType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr JunctionType \fBPNC_JUNCTION\fP"
.br
.ti -1c
.RI "static constexpr JunctionType \fBJUNCTION\fP"
.br
.ti -1c
.RI "static constexpr JunctionType \fBJunctionType_MIN\fP"
.br
.ti -1c
.RI "static constexpr JunctionType \fBJunctionType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBJunctionType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCloseToJunction\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fstorytelling_5fmsgs_2fstory_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCloseToJunction\fP &a, \fBCloseToJunction\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::storytelling::CloseToJunction::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    CloseToJunction::MergeImpl
}
.fi
.SS "constexpr CloseToJunction_JunctionType apollo::storytelling::CloseToJunction::JUNCTION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    CloseToJunction_JunctionType_JUNCTION
.fi
.SS "constexpr int apollo::storytelling::CloseToJunction::JunctionType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    CloseToJunction_JunctionType_JunctionType_ARRAYSIZE
.fi
.SS "constexpr CloseToJunction_JunctionType apollo::storytelling::CloseToJunction::JunctionType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    CloseToJunction_JunctionType_JunctionType_MAX
.fi
.SS "constexpr CloseToJunction_JunctionType apollo::storytelling::CloseToJunction::JunctionType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    CloseToJunction_JunctionType_JunctionType_MIN
.fi
.SS "constexpr int apollo::storytelling::CloseToJunction::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi
.SS "constexpr CloseToJunction_JunctionType apollo::storytelling::CloseToJunction::PNC_JUNCTION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    CloseToJunction_JunctionType_PNC_JUNCTION
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
