.TH "apollo::task_manager::ParkingRoutingTask" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::task_manager::ParkingRoutingTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkRoutingRequestFieldNumber\fP = 2, \fBkLaneWidthFieldNumber\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBParkingRoutingTask\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBParkingRoutingTask\fP (const \fBParkingRoutingTask\fP &from)"
.br
.ti -1c
.RI "\fBParkingRoutingTask\fP (\fBParkingRoutingTask\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBParkingRoutingTask\fP & \fBoperator=\fP (const \fBParkingRoutingTask\fP &from)"
.br
.ti -1c
.RI "\fBParkingRoutingTask\fP & \fBoperator=\fP (\fBParkingRoutingTask\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBParkingRoutingTask\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBParkingRoutingTask\fP *other)"
.br
.ti -1c
.RI "\fBParkingRoutingTask\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBParkingRoutingTask\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBParkingRoutingTask\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_routing_request\fP () const"
.br
.ti -1c
.RI "void \fBclear_routing_request\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::routing::RoutingRequest\fP & \fBrouting_request\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::routing::RoutingRequest\fP * \fBrelease_routing_request\fP ()"
.br
.ti -1c
.RI "::\fBapollo::routing::RoutingRequest\fP * \fBmutable_routing_request\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_routing_request\fP (::\fBapollo::routing::RoutingRequest\fP *routing_request)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_routing_request\fP (::\fBapollo::routing::RoutingRequest\fP *routing_request)"
.br
.ti -1c
.RI "::\fBapollo::routing::RoutingRequest\fP * \fBunsafe_arena_release_routing_request\fP ()"
.br
.ti -1c
.RI "bool \fBhas_lane_width\fP () const"
.br
.ti -1c
.RI "void \fBclear_lane_width\fP ()"
.br
.ti -1c
.RI "double \fBlane_width\fP () const"
.br
.ti -1c
.RI "void \fBset_lane_width\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBParkingRoutingTask\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBParkingRoutingTask\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBParkingRoutingTask\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBParkingRoutingTask\fP &a, \fBParkingRoutingTask\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::task_manager::ParkingRoutingTask::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ParkingRoutingTask::MergeImpl
}
.fi
.SS "constexpr int apollo::task_manager::ParkingRoutingTask::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    1
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
