.TH "apollo::perception::TrafficLightDebug::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::TrafficLightDebug::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBTrafficLightDebug\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::perception::TrafficLightBox\fP & \fBcropbox\fP (const \fBTrafficLightDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_cropbox\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_signal_num\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_valid_pos\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_ts_diff_pos\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_ts_diff_sys\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_project_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_distance_to_stop_line\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_camera_id\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
