.TH "apollo::cyber::proto::ShmConf::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::ShmConf::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBShmConf\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_notifier_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_shm_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ShmMulticastLocator\fP & \fBshm_locator\fP (const \fBShmConf\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_shm_locator\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
