.TH "apollo::planning_internal::StGraphBoundaryDebug" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning_internal::StGraphBoundaryDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkPointFieldNumber\fP = 2, \fBkNameFieldNumber\fP = 1, \fBkTypeFieldNumber\fP = 3 }"
.br
.ti -1c
.RI "typedef StGraphBoundaryDebug_StBoundaryType \fBStBoundaryType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBStGraphBoundaryDebug\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP (const \fBStGraphBoundaryDebug\fP &from)"
.br
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP (\fBStGraphBoundaryDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP & \fBoperator=\fP (const \fBStGraphBoundaryDebug\fP &from)"
.br
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP & \fBoperator=\fP (\fBStGraphBoundaryDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBStGraphBoundaryDebug\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBStGraphBoundaryDebug\fP *other)"
.br
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBStGraphBoundaryDebug\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBStGraphBoundaryDebug\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBpoint_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_point\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::SpeedPoint\fP * \fBmutable_point\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SpeedPoint\fP > * \fBmutable_point\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::SpeedPoint\fP & \fBpoint\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::common::SpeedPoint\fP * \fBadd_point\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SpeedPoint\fP > & \fBpoint\fP () const"
.br
.ti -1c
.RI "bool \fBhas_name\fP () const"
.br
.ti -1c
.RI "void \fBclear_name\fP ()"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_name\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_name\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_name\fP (std::string *name)"
.br
.ti -1c
.RI "bool \fBhas_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_type\fP ()"
.br
.ti -1c
.RI "::apollo::planning_internal::StGraphBoundaryDebug_StBoundaryType \fBtype\fP () const"
.br
.ti -1c
.RI "void \fBset_type\fP (::apollo::planning_internal::StGraphBoundaryDebug_StBoundaryType value)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBStGraphBoundaryDebug\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBStGraphBoundaryDebug\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBStBoundaryType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBStBoundaryType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBStBoundaryType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBStBoundaryType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, StBoundaryType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_UNKNOWN\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_STOP\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_FOLLOW\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_YIELD\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_OVERTAKE\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_KEEP_CLEAR\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBST_BOUNDARY_TYPE_DRIVABLE_REGION\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBStBoundaryType_MIN\fP"
.br
.ti -1c
.RI "static constexpr StBoundaryType \fBStBoundaryType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBStBoundaryType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBStGraphBoundaryDebug\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fplanning_5finternal_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBStGraphBoundaryDebug\fP &a, \fBStGraphBoundaryDebug\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning_internal::StGraphBoundaryDebug::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    StGraphBoundaryDebug::MergeImpl
}
.fi
.SS "constexpr int apollo::planning_internal::StGraphBoundaryDebug::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_DRIVABLE_REGION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_DRIVABLE_REGION
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_FOLLOW\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_FOLLOW
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_KEEP_CLEAR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_KEEP_CLEAR
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_OVERTAKE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_OVERTAKE
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_STOP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_STOP
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_UNKNOWN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_UNKNOWN
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::ST_BOUNDARY_TYPE_YIELD\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_ST_BOUNDARY_TYPE_YIELD
.fi
.SS "constexpr int apollo::planning_internal::StGraphBoundaryDebug::StBoundaryType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_StBoundaryType_ARRAYSIZE
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::StBoundaryType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_StBoundaryType_MAX
.fi
.SS "constexpr StGraphBoundaryDebug_StBoundaryType apollo::planning_internal::StGraphBoundaryDebug::StBoundaryType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    StGraphBoundaryDebug_StBoundaryType_StBoundaryType_MIN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
