.TH "apollo::cyber::PyRate" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyRate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyRate\fP (uint64_t nanoseconds)"
.br
.ti -1c
.RI "void \fBsleep\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP () const"
.br
.ti -1c
.RI "uint64_t \fBget_cycle_time\fP () const"
.br
.ti -1c
.RI "uint64_t \fBget_expected_cycle_time\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
