.TH "apollo::cyber::transport::DispatcherTest" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::DispatcherTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBattr_num_\fP"
.br
.ti -1c
.RI "\fBDispatcher\fP \fBdispatcher_\fP"
.br
.ti -1c
.RI "std::vector< RoleAttributes > \fBself_attrs_\fP"
.br
.ti -1c
.RI "std::vector< RoleAttributes > \fBoppo_attrs_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
