.TH "apollo::common::VehicleParam::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::common::VehicleParam::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicleParam\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_brand\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::VehicleID\fP & \fBvehicle_id\fP (const \fBVehicleParam\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_front_edge_to_center\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_back_edge_to_center\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_left_edge_to_center\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_right_edge_to_center\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_length\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_width\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_height\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_min_turn_radius\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_acceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_deceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_steer_angle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_steer_angle_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_min_steer_angle_rate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_steer_ratio\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_base\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_rolling_radius\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_abs_speed_when_stopped\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_brake_deadzone\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_deadzone\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::LatencyParam\fP & \fBsteering_latency_param\fP (const \fBVehicleParam\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_latency_param\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::LatencyParam\fP & \fBthrottle_latency_param\fP (const \fBVehicleParam\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_throttle_latency_param\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::LatencyParam\fP & \fBbrake_latency_param\fP (const \fBVehicleParam\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_latency_param\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
