.TH "apollo::drivers::Acm_inst_resp_7e4" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Acm_inst_resp_7e4
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkData7FieldNumber\fP = 1, \fBkData6FieldNumber\fP = 2, \fBkData5FieldNumber\fP = 3, \fBkData4FieldNumber\fP = 4, \fBkData3FieldNumber\fP = 5, \fBkRtnCmdCounterFieldNumber\fP = 6, \fBkCommandReturnCodeFieldNumber\fP = 7, \fBkPidFieldNumber\fP = 8 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBAcm_inst_resp_7e4\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP (const \fBAcm_inst_resp_7e4\fP &from)"
.br
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP (\fBAcm_inst_resp_7e4\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP & \fBoperator=\fP (const \fBAcm_inst_resp_7e4\fP &from)"
.br
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP & \fBoperator=\fP (\fBAcm_inst_resp_7e4\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBAcm_inst_resp_7e4\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBAcm_inst_resp_7e4\fP *other)"
.br
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBAcm_inst_resp_7e4\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBAcm_inst_resp_7e4\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_data_7\fP () const"
.br
.ti -1c
.RI "void \fBclear_data_7\fP ()"
.br
.ti -1c
.RI "int32_t \fBdata_7\fP () const"
.br
.ti -1c
.RI "void \fBset_data_7\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_data_6\fP () const"
.br
.ti -1c
.RI "void \fBclear_data_6\fP ()"
.br
.ti -1c
.RI "int32_t \fBdata_6\fP () const"
.br
.ti -1c
.RI "void \fBset_data_6\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_data_5\fP () const"
.br
.ti -1c
.RI "void \fBclear_data_5\fP ()"
.br
.ti -1c
.RI "int32_t \fBdata_5\fP () const"
.br
.ti -1c
.RI "void \fBset_data_5\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_data_4\fP () const"
.br
.ti -1c
.RI "void \fBclear_data_4\fP ()"
.br
.ti -1c
.RI "int32_t \fBdata_4\fP () const"
.br
.ti -1c
.RI "void \fBset_data_4\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_data_3\fP () const"
.br
.ti -1c
.RI "void \fBclear_data_3\fP ()"
.br
.ti -1c
.RI "int32_t \fBdata_3\fP () const"
.br
.ti -1c
.RI "void \fBset_data_3\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_rtn_cmd_counter\fP () const"
.br
.ti -1c
.RI "void \fBclear_rtn_cmd_counter\fP ()"
.br
.ti -1c
.RI "int32_t \fBrtn_cmd_counter\fP () const"
.br
.ti -1c
.RI "void \fBset_rtn_cmd_counter\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_command_return_code\fP () const"
.br
.ti -1c
.RI "void \fBclear_command_return_code\fP ()"
.br
.ti -1c
.RI "int32_t \fBcommand_return_code\fP () const"
.br
.ti -1c
.RI "void \fBset_command_return_code\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_pid\fP () const"
.br
.ti -1c
.RI "void \fBclear_pid\fP ()"
.br
.ti -1c
.RI "int32_t \fBpid\fP () const"
.br
.ti -1c
.RI "void \fBset_pid\fP (int32_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBAcm_inst_resp_7e4\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBAcm_inst_resp_7e4\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAcm_inst_resp_7e4\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBAcm_inst_resp_7e4\fP &a, \fBAcm_inst_resp_7e4\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Acm_inst_resp_7e4::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Acm_inst_resp_7e4::MergeImpl
}
.fi
.SS "constexpr int apollo::drivers::Acm_inst_resp_7e4::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    11
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
