.TH "apollo::cyber::scheduler::ClassicContext" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::scheduler::ClassicContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::scheduler::ProcessorContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassicContext\fP (const std::string &group_name)"
.br
.ti -1c
.RI "std::shared_ptr< \fBCRoutine\fP > \fBNextRoutine\fP () override"
.br
.ti -1c
.RI "void \fBWait\fP () override"
.br
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBNotify\fP (const std::string &group_name)"
.br
.ti -1c
.RI "static bool \fBRemoveCRoutine\fP (const std::shared_ptr< \fBCRoutine\fP > &cr)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static CR_GROUP \fBcr_group_\fP"
.br
.ti -1c
.RI "static RQ_LOCK_GROUP \fBrq_locks_\fP"
.br
.ti -1c
.RI "static GRP_WQ_CV \fBcv_wq_\fP"
.br
.ti -1c
.RI "static GRP_WQ_MUTEX \fBmtx_wq_\fP"
.br
.ti -1c
.RI "static NOTIFY_GRP \fBnotify_grp_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
