.TH "apollo::cyber::logger::LogFileObject" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::logger::LogFileObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgoogle::base::Logger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogFileObject\fP (LogSeverity severity, const char *base_filename)"
.br
.ti -1c
.RI "void \fBWrite\fP (bool force_flush, time_t timestamp, const char *message, int message_len) override"
.br
.ti -1c
.RI "void \fBSetBasename\fP (const char *basename)"
.br
.ti -1c
.RI "void \fBSetExtension\fP (const char *ext)"
.br
.ti -1c
.RI "void \fBSetSymlinkBasename\fP (const char *symlink_basename)"
.br
.ti -1c
.RI "void \fBFlush\fP () override"
.br
.ti -1c
.RI "uint32 \fBLogSize\fP () override"
.br
.ti -1c
.RI "void \fBFlushUnlocked\fP ()"
.br
.ti -1c
.RI "const string & \fBhostname\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
