.TH "apollo::cyber::event::SchedEvent" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::event::SchedEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::event::EventBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBSerializeToString\fP () override"
.br
.ti -1c
.RI "void \fBset_cr_id\fP (uint64_t cr_id) override"
.br
.ti -1c
.RI "void \fBset_cr_state\fP (int cr_state) override"
.br
.ti -1c
.RI "void \fBset_proc_id\fP (int proc_id) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
