.TH "apollo::localization::Uncertainty::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::localization::Uncertainty::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBUncertainty\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBposition_std_dev\fP (const \fBUncertainty\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_position_std_dev\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBorientation_std_dev\fP (const \fBUncertainty\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_orientation_std_dev\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBlinear_velocity_std_dev\fP (const \fBUncertainty\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_linear_velocity_std_dev\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBlinear_acceleration_std_dev\fP (const \fBUncertainty\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_linear_acceleration_std_dev\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBangular_velocity_std_dev\fP (const \fBUncertainty\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_angular_velocity_std_dev\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
