.TH "apollo::perception::SensorMeasurement::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::SensorMeasurement::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBSensorMeasurement\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_sensor_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBposition\fP (const \fBSensorMeasurement\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_theta\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_length\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_width\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_height\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point3D\fP & \fBvelocity\fP (const \fBSensorMeasurement\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_sub_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_timestamp\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::perception::BBox2D\fP & \fBbox\fP (const \fBSensorMeasurement\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_box\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
