.TH "apollo::cyber::transport::Participant" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Participant
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticipant\fP (const std::string &name, int send_port, eprosima::fastrtps::ParticipantListener *listener=nullptr)"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.ti -1c
.RI "eprosima::fastrtps::Participant * \fBfastrtps_participant\fP ()"
.br
.ti -1c
.RI "bool \fBis_shutdown\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
