.TH "apollo::cyber::base::WaitStrategy" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::WaitStrategy
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::base::BlockWaitStrategy\fP, \fBapollo::cyber::base::BusySpinWaitStrategy\fP, \fBapollo::cyber::base::SleepWaitStrategy\fP, \fBapollo::cyber::base::TimeoutBlockWaitStrategy\fP, and \fBapollo::cyber::base::YieldWaitStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBNotifyOne\fP ()"
.br
.ti -1c
.RI "virtual void \fBBreakAllWait\fP ()"
.br
.ti -1c
.RI "virtual bool \fBEmptyWait\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
