.TH "apollo::cyber::transport::NotifierBase" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::NotifierBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::transport::ConditionNotifier\fP, and \fBapollo::cyber::transport::MulticastNotifier\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBShutdown\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBNotify\fP (const \fBReadableInfo\fP &info)=0"
.br
.ti -1c
.RI "virtual bool \fBListen\fP (int timeout_ms, \fBReadableInfo\fP *info)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
