.TH "apollo::cyber::proto::CommunicationMode" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::CommunicationMode
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkDiffHostFieldNumber\fP = 3, \fBkSameProcFieldNumber\fP = 1, \fBkDiffProcFieldNumber\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBCommunicationMode\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBCommunicationMode\fP (const \fBCommunicationMode\fP &from)"
.br
.ti -1c
.RI "\fBCommunicationMode\fP (\fBCommunicationMode\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBCommunicationMode\fP & \fBoperator=\fP (const \fBCommunicationMode\fP &from)"
.br
.ti -1c
.RI "\fBCommunicationMode\fP & \fBoperator=\fP (\fBCommunicationMode\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBCommunicationMode\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBCommunicationMode\fP *other)"
.br
.ti -1c
.RI "\fBCommunicationMode\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBCommunicationMode\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBCommunicationMode\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_diff_host\fP () const"
.br
.ti -1c
.RI "void \fBclear_diff_host\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::OptionalMode \fBdiff_host\fP () const"
.br
.ti -1c
.RI "void \fBset_diff_host\fP (::apollo::cyber::proto::OptionalMode value)"
.br
.ti -1c
.RI "bool \fBhas_same_proc\fP () const"
.br
.ti -1c
.RI "void \fBclear_same_proc\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::OptionalMode \fBsame_proc\fP () const"
.br
.ti -1c
.RI "void \fBset_same_proc\fP (::apollo::cyber::proto::OptionalMode value)"
.br
.ti -1c
.RI "bool \fBhas_diff_proc\fP () const"
.br
.ti -1c
.RI "void \fBclear_diff_proc\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::OptionalMode \fBdiff_proc\fP () const"
.br
.ti -1c
.RI "void \fBset_diff_proc\fP (::apollo::cyber::proto::OptionalMode value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBCommunicationMode\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBCommunicationMode\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCommunicationMode\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_cyber_2fproto_2ftransport_5fconf_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCommunicationMode\fP &a, \fBCommunicationMode\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::cyber::proto::CommunicationMode::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    CommunicationMode::MergeImpl
}
.fi
.SS "constexpr int apollo::cyber::proto::CommunicationMode::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    3
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
