.TH "apollo::localization::MsfStatus" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::localization::MsfStatus
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLocalLidarConsistencyFieldNumber\fP = 1, \fBkGnssConsistencyFieldNumber\fP = 2, \fBkLocalLidarStatusFieldNumber\fP = 3, \fBkLocalLidarQualityFieldNumber\fP = 4, \fBkGnssposPositionTypeFieldNumber\fP = 5, \fBkMsfRunningStatusFieldNumber\fP = 6 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBMsfStatus\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBMsfStatus\fP (const \fBMsfStatus\fP &from)"
.br
.ti -1c
.RI "\fBMsfStatus\fP (\fBMsfStatus\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBMsfStatus\fP & \fBoperator=\fP (const \fBMsfStatus\fP &from)"
.br
.ti -1c
.RI "\fBMsfStatus\fP & \fBoperator=\fP (\fBMsfStatus\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBMsfStatus\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBMsfStatus\fP *other)"
.br
.ti -1c
.RI "\fBMsfStatus\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBMsfStatus\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBMsfStatus\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_local_lidar_consistency\fP () const"
.br
.ti -1c
.RI "void \fBclear_local_lidar_consistency\fP ()"
.br
.ti -1c
.RI "::apollo::localization::LocalLidarConsistency \fBlocal_lidar_consistency\fP () const"
.br
.ti -1c
.RI "void \fBset_local_lidar_consistency\fP (::apollo::localization::LocalLidarConsistency value)"
.br
.ti -1c
.RI "bool \fBhas_gnss_consistency\fP () const"
.br
.ti -1c
.RI "void \fBclear_gnss_consistency\fP ()"
.br
.ti -1c
.RI "::apollo::localization::GnssConsistency \fBgnss_consistency\fP () const"
.br
.ti -1c
.RI "void \fBset_gnss_consistency\fP (::apollo::localization::GnssConsistency value)"
.br
.ti -1c
.RI "bool \fBhas_local_lidar_status\fP () const"
.br
.ti -1c
.RI "void \fBclear_local_lidar_status\fP ()"
.br
.ti -1c
.RI "::apollo::localization::LocalLidarStatus \fBlocal_lidar_status\fP () const"
.br
.ti -1c
.RI "void \fBset_local_lidar_status\fP (::apollo::localization::LocalLidarStatus value)"
.br
.ti -1c
.RI "bool \fBhas_local_lidar_quality\fP () const"
.br
.ti -1c
.RI "void \fBclear_local_lidar_quality\fP ()"
.br
.ti -1c
.RI "::apollo::localization::LocalLidarQuality \fBlocal_lidar_quality\fP () const"
.br
.ti -1c
.RI "void \fBset_local_lidar_quality\fP (::apollo::localization::LocalLidarQuality value)"
.br
.ti -1c
.RI "bool \fBhas_gnsspos_position_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_gnsspos_position_type\fP ()"
.br
.ti -1c
.RI "::apollo::localization::GnssPositionType \fBgnsspos_position_type\fP () const"
.br
.ti -1c
.RI "void \fBset_gnsspos_position_type\fP (::apollo::localization::GnssPositionType value)"
.br
.ti -1c
.RI "bool \fBhas_msf_running_status\fP () const"
.br
.ti -1c
.RI "void \fBclear_msf_running_status\fP ()"
.br
.ti -1c
.RI "::apollo::localization::MsfRunningStatus \fBmsf_running_status\fP () const"
.br
.ti -1c
.RI "void \fBset_msf_running_status\fP (::apollo::localization::MsfRunningStatus value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBMsfStatus\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBMsfStatus\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMsfStatus\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_5fstatus_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBMsfStatus\fP &a, \fBMsfStatus\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::localization::MsfStatus::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    MsfStatus::MergeImpl
}
.fi
.SS "constexpr int apollo::localization::MsfStatus::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    1
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
