.TH "apollo::cyber::data::DataNotifier" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::DataNotifier
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBNotifyVector\fP = std::vector< std::shared_ptr< \fBNotifier\fP > >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddNotifier\fP (uint64_t channel_id, const std::shared_ptr< \fBNotifier\fP > &notifier)"
.br
.ti -1c
.RI "bool \fBNotify\fP (const uint64_t channel_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
