.TH "apollo::drivers::Vehicle5_5f4" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle5_5f4
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkCanRxSteeringGearRatioFieldNumber\fP = 2, \fBkCanRxWheelbaseFieldNumber\fP = 3, \fBkCanRxDistanceRearAxleFieldNumber\fP = 4, \fBkCanRxCwBlockageThresholdFieldNumber\fP = 5, \fBkCanRxYawRateBiasShiftFieldNumber\fP = 1, \fBkCanRxOversteerUndersteerFieldNumber\fP = 9, \fBkCanRxFunnelOffsetRightFieldNumber\fP = 6, \fBkCanRxFunnelOffsetLeftFieldNumber\fP = 7, \fBkCanRxBeamwidthVertFieldNumber\fP = 8 }"
.br
.ti -1c
.RI "typedef Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType \fBCan_rx_yaw_rate_bias_shiftType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBVehicle5_5f4\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBVehicle5_5f4\fP (const \fBVehicle5_5f4\fP &from)"
.br
.ti -1c
.RI "\fBVehicle5_5f4\fP (\fBVehicle5_5f4\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBVehicle5_5f4\fP & \fBoperator=\fP (const \fBVehicle5_5f4\fP &from)"
.br
.ti -1c
.RI "\fBVehicle5_5f4\fP & \fBoperator=\fP (\fBVehicle5_5f4\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBVehicle5_5f4\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBVehicle5_5f4\fP *other)"
.br
.ti -1c
.RI "\fBVehicle5_5f4\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBVehicle5_5f4\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBVehicle5_5f4\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_can_rx_steering_gear_ratio\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_steering_gear_ratio\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_steering_gear_ratio\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_steering_gear_ratio\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_wheelbase\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_wheelbase\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_wheelbase\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_wheelbase\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_distance_rear_axle\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_distance_rear_axle\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_distance_rear_axle\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_distance_rear_axle\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_cw_blockage_threshold\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_cw_blockage_threshold\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_cw_blockage_threshold\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_cw_blockage_threshold\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_yaw_rate_bias_shift\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_yaw_rate_bias_shift\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType \fBcan_rx_yaw_rate_bias_shift\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_yaw_rate_bias_shift\fP (::apollo::drivers::Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_oversteer_understeer\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_oversteer_understeer\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_oversteer_understeer\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_oversteer_understeer\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_funnel_offset_right\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_funnel_offset_right\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_funnel_offset_right\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_funnel_offset_right\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_funnel_offset_left\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_funnel_offset_left\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_funnel_offset_left\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_funnel_offset_left\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_beamwidth_vert\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_beamwidth_vert\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_beamwidth_vert\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_beamwidth_vert\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBVehicle5_5f4\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBVehicle5_5f4\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBCan_rx_yaw_rate_bias_shiftType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_rx_yaw_rate_bias_shiftType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_rx_yaw_rate_bias_shiftType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_rx_yaw_rate_bias_shiftType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_rx_yaw_rate_bias_shiftType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_yaw_rate_bias_shiftType \fBCAN_RX_YAW_RATE_BIAS_SHIFT_NO_DETECT\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_yaw_rate_bias_shiftType \fBCAN_RX_YAW_RATE_BIAS_SHIFT_DETECT\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_yaw_rate_bias_shiftType \fBCan_rx_yaw_rate_bias_shiftType_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_yaw_rate_bias_shiftType \fBCan_rx_yaw_rate_bias_shiftType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_rx_yaw_rate_bias_shiftType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVehicle5_5f4\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBVehicle5_5f4\fP &a, \fBVehicle5_5f4\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Vehicle5_5f4::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Vehicle5_5f4::MergeImpl
}
.fi
.SS "constexpr Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType apollo::drivers::Vehicle5_5f4::CAN_RX_YAW_RATE_BIAS_SHIFT_DETECT\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType_CAN_RX_YAW_RATE_BIAS_SHIFT_DETECT
.fi
.SS "constexpr Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType apollo::drivers::Vehicle5_5f4::CAN_RX_YAW_RATE_BIAS_SHIFT_NO_DETECT\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType_CAN_RX_YAW_RATE_BIAS_SHIFT_NO_DETECT
.fi
.SS "constexpr int apollo::drivers::Vehicle5_5f4::Can_rx_yaw_rate_bias_shiftType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType_Can_rx_yaw_rate_bias_shiftType_ARRAYSIZE
.fi
.SS "constexpr Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType apollo::drivers::Vehicle5_5f4::Can_rx_yaw_rate_bias_shiftType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType_Can_rx_yaw_rate_bias_shiftType_MAX
.fi
.SS "constexpr Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType apollo::drivers::Vehicle5_5f4::Can_rx_yaw_rate_bias_shiftType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType_Can_rx_yaw_rate_bias_shiftType_MIN
.fi
.SS "constexpr int apollo::drivers::Vehicle5_5f4::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    21
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
