.TH "apollo::drivers::Details_73a" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Details_73a
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkObstacleLengthFieldNumber\fP = 1, \fBkObstacleWidthFieldNumber\fP = 2, \fBkObstacleAgeFieldNumber\fP = 3, \fBkObstacleLaneFieldNumber\fP = 4, \fBkRadarPosXFieldNumber\fP = 7, \fBkRadarVelXFieldNumber\fP = 8, \fBkCipvFlagFieldNumber\fP = 5, \fBkReserved5FieldNumber\fP = 6, \fBkReserved6FieldNumber\fP = 10, \fBkReserved7FieldNumber\fP = 12, \fBkRadarMatchConfidenceFieldNumber\fP = 9, \fBkMatchedRadarIdFieldNumber\fP = 11 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBDetails_73a\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBDetails_73a\fP (const \fBDetails_73a\fP &from)"
.br
.ti -1c
.RI "\fBDetails_73a\fP (\fBDetails_73a\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBDetails_73a\fP & \fBoperator=\fP (const \fBDetails_73a\fP &from)"
.br
.ti -1c
.RI "\fBDetails_73a\fP & \fBoperator=\fP (\fBDetails_73a\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBDetails_73a\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBDetails_73a\fP *other)"
.br
.ti -1c
.RI "\fBDetails_73a\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBDetails_73a\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBDetails_73a\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_obstacle_length\fP () const"
.br
.ti -1c
.RI "void \fBclear_obstacle_length\fP ()"
.br
.ti -1c
.RI "double \fBobstacle_length\fP () const"
.br
.ti -1c
.RI "void \fBset_obstacle_length\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_obstacle_width\fP () const"
.br
.ti -1c
.RI "void \fBclear_obstacle_width\fP ()"
.br
.ti -1c
.RI "double \fBobstacle_width\fP () const"
.br
.ti -1c
.RI "void \fBset_obstacle_width\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_obstacle_age\fP () const"
.br
.ti -1c
.RI "void \fBclear_obstacle_age\fP ()"
.br
.ti -1c
.RI "int32_t \fBobstacle_age\fP () const"
.br
.ti -1c
.RI "void \fBset_obstacle_age\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_obstacle_lane\fP () const"
.br
.ti -1c
.RI "void \fBclear_obstacle_lane\fP ()"
.br
.ti -1c
.RI "int32_t \fBobstacle_lane\fP () const"
.br
.ti -1c
.RI "void \fBset_obstacle_lane\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_radar_pos_x\fP () const"
.br
.ti -1c
.RI "void \fBclear_radar_pos_x\fP ()"
.br
.ti -1c
.RI "double \fBradar_pos_x\fP () const"
.br
.ti -1c
.RI "void \fBset_radar_pos_x\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_radar_vel_x\fP () const"
.br
.ti -1c
.RI "void \fBclear_radar_vel_x\fP ()"
.br
.ti -1c
.RI "double \fBradar_vel_x\fP () const"
.br
.ti -1c
.RI "void \fBset_radar_vel_x\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_cipv_flag\fP () const"
.br
.ti -1c
.RI "void \fBclear_cipv_flag\fP ()"
.br
.ti -1c
.RI "bool \fBcipv_flag\fP () const"
.br
.ti -1c
.RI "void \fBset_cipv_flag\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_reserved_5\fP () const"
.br
.ti -1c
.RI "void \fBclear_reserved_5\fP ()"
.br
.ti -1c
.RI "bool \fBreserved_5\fP () const"
.br
.ti -1c
.RI "void \fBset_reserved_5\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_reserved_6\fP () const"
.br
.ti -1c
.RI "void \fBclear_reserved_6\fP ()"
.br
.ti -1c
.RI "bool \fBreserved_6\fP () const"
.br
.ti -1c
.RI "void \fBset_reserved_6\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_reserved_7\fP () const"
.br
.ti -1c
.RI "void \fBclear_reserved_7\fP ()"
.br
.ti -1c
.RI "bool \fBreserved_7\fP () const"
.br
.ti -1c
.RI "void \fBset_reserved_7\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_radar_match_confidence\fP () const"
.br
.ti -1c
.RI "void \fBclear_radar_match_confidence\fP ()"
.br
.ti -1c
.RI "int32_t \fBradar_match_confidence\fP () const"
.br
.ti -1c
.RI "void \fBset_radar_match_confidence\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_matched_radar_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_matched_radar_id\fP ()"
.br
.ti -1c
.RI "int32_t \fBmatched_radar_id\fP () const"
.br
.ti -1c
.RI "void \fBset_matched_radar_id\fP (int32_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBDetails_73a\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBDetails_73a\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBDetails_73a\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fmobileye_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBDetails_73a\fP &a, \fBDetails_73a\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Details_73a::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Details_73a::MergeImpl
}
.fi
.SS "constexpr int apollo::drivers::Details_73a::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    12
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
