.TH "apollo::cyber::service_discovery::ServiceManager" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::service_discovery::ServiceManager \- Topology \fBManager\fP of \fBService\fP related\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <service_manager\&.h>\fP
.PP
Inherits \fBapollo::cyber::service_discovery::Manager\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBRoleAttrVec\fP = std::vector< \fBRoleAttributes\fP >"
.br
.ti -1c
.RI "using \fBServerWarehouse\fP = \fBSingleValueWarehouse\fP"
.br
.ti -1c
.RI "using \fBClientWarehouse\fP = \fBMultiValueWarehouse\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServiceManager\fP ()"
.br
.RI "Construct a new \fBService\fP \fBManager\fP object\&. "
.ti -1c
.RI "virtual \fB~ServiceManager\fP ()"
.br
.RI "Destroy the \fBService\fP \fBManager\fP object\&. "
.ti -1c
.RI "bool \fBHasService\fP (const std::string &service_name)"
.br
.RI "Inquire whether \fCservice_name\fP exists in topology\&. "
.ti -1c
.RI "void \fBGetServers\fP (RoleAttrVec *servers)"
.br
.RI "Get the All Server in the topology\&. "
.ti -1c
.RI "void \fBGetClients\fP (const std::string &service_name, RoleAttrVec *clients)"
.br
.RI "Get the Clients object that subscribes \fCservice_name\fP "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTopologyManager\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Topology \fBManager\fP of \fBService\fP related\&. 
.SH "Member Function Documentation"
.PP 
.SS "void apollo::cyber::service_discovery::ServiceManager::GetClients (const std::string & service_name, RoleAttrVec * clients)"

.PP
Get the Clients object that subscribes \fCservice_name\fP 
.PP
\fBParameters\fP
.RS 4
\fIservice_name\fP Name of service you want to get 
.br
\fIclients\fP result vector 
.RE
.PP

.SS "void apollo::cyber::service_discovery::ServiceManager::GetServers (RoleAttrVec * servers)"

.PP
Get the All Server in the topology\&. 
.PP
\fBParameters\fP
.RS 4
\fIservers\fP result RoleAttr vector 
.RE
.PP

.SS "bool apollo::cyber::service_discovery::ServiceManager::HasService (const std::string & service_name)"

.PP
Inquire whether \fCservice_name\fP exists in topology\&. 
.PP
\fBParameters\fP
.RS 4
\fIservice_name\fP the name we inquire 
.RE
.PP
\fBReturns\fP
.RS 4
true if service exists 
.PP
false if service not exists 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
