.TH "apollo::cyber::scheduler::ChoreographyContext" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::scheduler::ChoreographyContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::scheduler::ProcessorContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBRemoveCRoutine\fP (uint64_t crid)"
.br
.ti -1c
.RI "std::shared_ptr< \fBCRoutine\fP > \fBNextRoutine\fP () override"
.br
.ti -1c
.RI "bool \fBEnqueue\fP (const std::shared_ptr< \fBCRoutine\fP > &)"
.br
.ti -1c
.RI "void \fBNotify\fP ()"
.br
.ti -1c
.RI "void \fBWait\fP () override"
.br
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
