.TH "apollo::canbus::Wheel_speed_rpt_7a::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Wheel_speed_rpt_7a::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBWheel_speed_rpt_7a\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_wheel_spd_rear_right\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_rear_left\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_front_right\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_spd_front_left\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
