.TH "apollo::cyber::transport::History< MessageT >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::History< MessageT >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCachedMessage\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< MessageT >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistory\fP (const \fBHistoryAttributes\fP &attr)"
.br
.ti -1c
.RI "void \fBEnable\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const MessagePtr &msg, const \fBMessageInfo\fP &msg_info)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBGetCachedMessage\fP (std::vector< \fBCachedMessage\fP > *msgs) const"
.br
.ti -1c
.RI "size_t \fBGetSize\fP () const"
.br
.ti -1c
.RI "uint32_t \fBdepth\fP () const"
.br
.ti -1c
.RI "uint32_t \fBmax_depth\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
