.TH "apollo::cyber::proto::TransportConf::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::TransportConf::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBTransportConf\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ShmConf\fP & \fBshm_conf\fP (const \fBTransportConf\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_shm_conf\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::RtpsParticipantAttr\fP & \fBparticipant_attr\fP (const \fBTransportConf\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_participant_attr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::CommunicationMode\fP & \fBcommunication_mode\fP (const \fBTransportConf\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_communication_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::ResourceLimit\fP & \fBresource_limit\fP (const \fBTransportConf\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_resource_limit\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
