.TH "apollo::simulation::Scenario::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::simulation::Scenario::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBScenario\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_name\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_description\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::Scenario_Point\fP & \fBstart\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_start\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::Scenario_Point\fP & \fBend\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_end\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::Scenario_Point\fP & \fBparking_point\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_parking_point\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_log_file_start_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_log_file_end_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::routing::RoutingRequest\fP & \fBrouting_request\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_routing_request\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_map_dir\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::GradingConfig\fP & \fBgrade_config\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_grade_config\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::simulation::FuzzingConfig\fP & \fBfuzzing_config\fP (const \fBScenario\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_fuzzing_config\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_simulator_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_start_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_start_acceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_base_grade_config_file\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_detect_distance\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_default_light_behavior\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_red_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_green_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_yellow_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_backtrack_time\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_traffic_flow\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
