.TH "apollo::canbus::ChassisDetail::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::ChassisDetail::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBChassisDetail\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_car_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::BasicInfo\fP & \fBbasic\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_basic\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Safety\fP & \fBsafety\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_safety\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Gear\fP & \fBgear\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_gear\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Ems\fP & \fBems\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_ems\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Esp\fP & \fBesp\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_esp\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Gas\fP & \fBgas\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_gas\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Epb\fP & \fBepb\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_epb\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake\fP & \fBbrake\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Deceleration\fP & \fBdeceleration\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_deceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::VehicleSpd\fP & \fBvehicle_spd\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle_spd\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Eps\fP & \fBeps\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_eps\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Light\fP & \fBlight\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_light\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Battery\fP & \fBbattery\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_battery\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::CheckResponseSignal\fP & \fBcheck_response\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_check_response\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::License\fP & \fBlicense\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_license\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Surround\fP & \fBsurround\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_surround\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::VehicleID\fP & \fBvehicle_id\fP (const \fBChassisDetail\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle_id\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
