.TH "apollo::cyber::transport::HybridTransmitter< M >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::HybridTransmitter< M >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Transmitter< M >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< M >"
.br
.ti -1c
.RI "using \fBHistoryPtr\fP = std::shared_ptr< \fBHistory\fP< M > >"
.br
.ti -1c
.RI "using \fBTransmitterPtr\fP = std::shared_ptr< \fBTransmitter\fP< M > >"
.br
.ti -1c
.RI "using \fBTransmitterMap\fP = std::unordered_map< OptionalMode, TransmitterPtr, std::hash< int > >"
.br
.ti -1c
.RI "using \fBReceiverMap\fP = std::unordered_map< OptionalMode, std::set< uint64_t >, std::hash< int > >"
.br
.ti -1c
.RI "using \fBCommunicationModePtr\fP = std::shared_ptr< \fBproto::CommunicationMode\fP >"
.br
.ti -1c
.RI "using \fBMappingTable\fP = std::unordered_map< Relation, OptionalMode, std::hash< int > >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHybridTransmitter\fP (const \fBRoleAttributes\fP &attr, const ParticipantPtr &participant)"
.br
.ti -1c
.RI "void \fBEnable\fP () override"
.br
.ti -1c
.RI "void \fBDisable\fP () override"
.br
.ti -1c
.RI "void \fBEnable\fP (const \fBRoleAttributes\fP &opposite_attr) override"
.br
.ti -1c
.RI "void \fBDisable\fP (const \fBRoleAttributes\fP &opposite_attr) override"
.br
.ti -1c
.RI "bool \fBTransmit\fP (const MessagePtr &msg, const \fBMessageInfo\fP &msg_info) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
