.TH "apollo::cyber::ReaderConfig" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::ReaderConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReaderConfig\fP ()"
.br
.RI "< configurations for a \fBReader\fP "
.ti -1c
.RI "\fBReaderConfig\fP (const \fBReaderConfig\fP &other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel_name\fP"
.br
.ti -1c
.RI "proto::QosProfile \fBqos_profile\fP"
.br
.ti -1c
.RI "uint32_t \fBpending_queue_size\fP"
.br
.RI "configuration for responding ChannelBuffer\&. Older messages will dropped if you have no time to handle "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
