.TH "apollo::drivers::Esr_status9_5e8" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Esr_status9_5e8
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkCanTxPathIdAcc3FieldNumber\fP = 1, \fBkCanTxPathIdAcc2FieldNumber\fP = 2, \fBkCanTxFilteredXohpAccCipvFieldNumber\fP = 3, \fBkCanTxWaterSprayTargetIdFieldNumber\fP = 4, \fBkCanTxSerialNum3RdByteFieldNumber\fP = 5, \fBkCanTxSideslipAngleFieldNumber\fP = 6, \fBkCanTxAvgPwrCwblkgFieldNumber\fP = 7 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBEsr_status9_5e8\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBEsr_status9_5e8\fP (const \fBEsr_status9_5e8\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status9_5e8\fP (\fBEsr_status9_5e8\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBEsr_status9_5e8\fP & \fBoperator=\fP (const \fBEsr_status9_5e8\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status9_5e8\fP & \fBoperator=\fP (\fBEsr_status9_5e8\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBEsr_status9_5e8\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBEsr_status9_5e8\fP *other)"
.br
.ti -1c
.RI "\fBEsr_status9_5e8\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBEsr_status9_5e8\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBEsr_status9_5e8\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_can_tx_path_id_acc_3\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_path_id_acc_3\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_path_id_acc_3\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_path_id_acc_3\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_path_id_acc_2\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_path_id_acc_2\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_path_id_acc_2\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_path_id_acc_2\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_filtered_xohp_acc_cipv\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_filtered_xohp_acc_cipv\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_filtered_xohp_acc_cipv\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_filtered_xohp_acc_cipv\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_water_spray_target_id\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_water_spray_target_id\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_water_spray_target_id\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_water_spray_target_id\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_serial_num_3rd_byte\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_serial_num_3rd_byte\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_serial_num_3rd_byte\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_serial_num_3rd_byte\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_sideslip_angle\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_sideslip_angle\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_sideslip_angle\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_sideslip_angle\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_avg_pwr_cwblkg\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_avg_pwr_cwblkg\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_avg_pwr_cwblkg\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_avg_pwr_cwblkg\fP (int32_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status9_5e8\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status9_5e8\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBEsr_status9_5e8\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBEsr_status9_5e8\fP &a, \fBEsr_status9_5e8\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Esr_status9_5e8::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Esr_status9_5e8::MergeImpl
}
.fi
.SS "constexpr int apollo::drivers::Esr_status9_5e8::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
