.TH "apollo::cyber::transport::ShmConf" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::ShmConf
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShmConf\fP (const uint64_t &real_msg_size)"
.br
.ti -1c
.RI "void \fBUpdate\fP (const uint64_t &real_msg_size)"
.br
.ti -1c
.RI "const uint64_t & \fBceiling_msg_size\fP ()"
.br
.ti -1c
.RI "const uint64_t & \fBblock_buf_size\fP ()"
.br
.ti -1c
.RI "const uint32_t & \fBblock_num\fP ()"
.br
.ti -1c
.RI "const uint64_t & \fBmanaged_shm_size\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
