.TH "apollo::cyber::event::PerfEventCache" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::event::PerfEventCache
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBEventBasePtr\fP = std::shared_ptr< \fBEventBase\fP >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddSchedEvent\fP (const SchedPerf event_id, const uint64_t cr_id, const int proc_id, const int cr_state=\-1)"
.br
.ti -1c
.RI "void \fBAddTransportEvent\fP (const TransPerf event_id, const uint64_t channel_id, const uint64_t msg_seq, const uint64_t stamp=0, const std::string &adder='\-')"
.br
.ti -1c
.RI "std::string \fBPerfFile\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
