.TH "apollo::drivers::Vehicle3_5f2::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle3_5f2::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicle3_5f2\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_can_rx_serv_align_updates_need\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_serv_align_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_serv_align_enable\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_aalign_avg_ctr_total\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_auto_align_converged\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_auto_align_disable\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_angle_mounting_offset\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_wheel_slip\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_radar_height\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_radar_fov_mr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_radar_fov_lr\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_long_accel_validity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_long_accel\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_lat_accel_validity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_lat_accel\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
