.TH "apollo::canbus::Ems::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Ems::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBEms\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_engine_acc_available\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_engine_acc_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_engine_state\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_max_engine_torq_percent\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_min_engine_torq_percent\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_base_engine_torq_constant\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_engine_speed_error\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_engine_speed\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_engine_torque\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_over_engine_torque\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_engine_rpm\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
