.TH "apollo::cyber::base::Connection< Args >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::Connection< Args >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBSlotPtr\fP = std::shared_ptr< \fBSlot\fP< Args\&.\&.\&. > >"
.br
.ti -1c
.RI "using \fBSignalPtr\fP = \fBSignal\fP< Args\&.\&.\&. > *"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnection\fP (const SlotPtr &slot, const \fBSignalPtr\fP &signal)"
.br
.ti -1c
.RI "\fBConnection\fP & \fBoperator=\fP (const \fBConnection\fP &another)"
.br
.ti -1c
.RI "bool \fBHasSlot\fP (const SlotPtr &slot) const"
.br
.ti -1c
.RI "bool \fBIsConnected\fP () const"
.br
.ti -1c
.RI "bool \fBDisconnect\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
