.TH "apollo::planning::ObjectStatus::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::ObjectStatus::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBObjectStatus\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectMotionType\fP & \fBmotion_type\fP (const \fBObjectStatus\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_motion_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::ObjectDecisionType\fP & \fBdecision_type\fP (const \fBObjectStatus\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_decision_type\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
