.TH "apollo::cyber::data::fusion::DataFusion< M0, M1, NullType, NullType >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::fusion::DataFusion< M0, M1, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBFusion\fP (uint64_t *index, std::shared_ptr< M0 > &m0, std::shared_ptr< M1 > &m1)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
