.TH "apollo::cyber::PyNodeUtils" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyNodeUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< std::string > \fBget_active_nodes\fP (uint8_t sleep_s=2)"
.br
.ti -1c
.RI "static std::string \fBget_node_attr\fP (const std::string &node_name, uint8_t sleep_s=2)"
.br
.ti -1c
.RI "static std::vector< std::string > \fBget_readersofnode\fP (const std::string &node_name, uint8_t sleep_s=2)"
.br
.ti -1c
.RI "static std::vector< std::string > \fBget_writersofnode\fP (const std::string &node_name, uint8_t sleep_s=2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
