.TH "apollo::cyber::transport::UnderlayMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::UnderlayMessage \- This class represents the structure \fBUnderlayMessage\fP defined by the user in the IDL file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <underlay_message\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnderlayMessage\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fB~UnderlayMessage\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "\fBUnderlayMessage\fP (const \fBUnderlayMessage\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBUnderlayMessage\fP (\fBUnderlayMessage\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "\fBUnderlayMessage\fP & \fBoperator=\fP (const \fBUnderlayMessage\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "\fBUnderlayMessage\fP & \fBoperator=\fP (\fBUnderlayMessage\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "void \fBtimestamp\fP (int32_t _timestamp)"
.br
.RI "This function sets a value in member timestamp\&. "
.ti -1c
.RI "int32_t \fBtimestamp\fP () const"
.br
.RI "This function returns the value of member timestamp\&. "
.ti -1c
.RI "int32_t & \fBtimestamp\fP ()"
.br
.RI "This function returns a reference to member timestamp\&. "
.ti -1c
.RI "void \fBseq\fP (int32_t _seq)"
.br
.RI "This function sets a value in member seq\&. "
.ti -1c
.RI "int32_t \fBseq\fP () const"
.br
.RI "This function returns the value of member seq\&. "
.ti -1c
.RI "int32_t & \fBseq\fP ()"
.br
.RI "This function returns a reference to member seq\&. "
.ti -1c
.RI "void \fBdata\fP (const std::string &_data)"
.br
.RI "This function copies the value in member data\&. "
.ti -1c
.RI "void \fBdata\fP (std::string &&_data)"
.br
.RI "This function moves the value in member data\&. "
.ti -1c
.RI "const std::string & \fBdata\fP () const"
.br
.RI "This function returns a constant reference to member data\&. "
.ti -1c
.RI "std::string & \fBdata\fP ()"
.br
.RI "This function returns a reference to member data\&. "
.ti -1c
.RI "void \fBdatatype\fP (const std::string &_datatype)"
.br
.RI "This function copies the value in member datatype\&. "
.ti -1c
.RI "void \fBdatatype\fP (std::string &&_datatype)"
.br
.RI "This function moves the value in member datatype\&. "
.ti -1c
.RI "const std::string & \fBdatatype\fP () const"
.br
.RI "This function returns a constant reference to member datatype\&. "
.ti -1c
.RI "std::string & \fBdatatype\fP ()"
.br
.RI "This function returns a reference to member datatype\&. "
.ti -1c
.RI "void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static size_t \fBgetCdrSerializedSize\fP (const \fBUnderlayMessage\fP &\fBdata\fP, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class represents the structure \fBUnderlayMessage\fP defined by the user in the IDL file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::transport::UnderlayMessage::UnderlayMessage (const \fBUnderlayMessage\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBUnderlayMessage\fP that will be copied\&. 
.RE
.PP

.SS "apollo::cyber::transport::UnderlayMessage::UnderlayMessage (\fBUnderlayMessage\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBUnderlayMessage\fP that will be copied\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string& apollo::cyber::transport::UnderlayMessage::data ()\fC [inline]\fP"

.PP
This function returns a reference to member data\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member data 
.RE
.PP

.SS "const std::string& apollo::cyber::transport::UnderlayMessage::data () const\fC [inline]\fP"

.PP
This function returns a constant reference to member data\&. 
.PP
\fBReturns\fP
.RS 4
Constant reference to member data 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::data (const std::string & _data)\fC [inline]\fP"

.PP
This function copies the value in member data\&. 
.PP
\fBParameters\fP
.RS 4
\fI_data\fP New value to be copied in member data 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::data (std::string && _data)\fC [inline]\fP"

.PP
This function moves the value in member data\&. 
.PP
\fBParameters\fP
.RS 4
\fI_data\fP New value to be moved in member data 
.RE
.PP

.SS "std::string& apollo::cyber::transport::UnderlayMessage::datatype ()\fC [inline]\fP"

.PP
This function returns a reference to member datatype\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member datatype 
.RE
.PP

.SS "const std::string& apollo::cyber::transport::UnderlayMessage::datatype () const\fC [inline]\fP"

.PP
This function returns a constant reference to member datatype\&. 
.PP
\fBReturns\fP
.RS 4
Constant reference to member datatype 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::datatype (const std::string & _datatype)\fC [inline]\fP"

.PP
This function copies the value in member datatype\&. 
.PP
\fBParameters\fP
.RS 4
\fI_datatype\fP New value to be copied in member datatype 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::datatype (std::string && _datatype)\fC [inline]\fP"

.PP
This function moves the value in member datatype\&. 
.PP
\fBParameters\fP
.RS 4
\fI_datatype\fP New value to be moved in member datatype 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "size_t apollo::cyber::transport::UnderlayMessage::getCdrSerializedSize (const \fBUnderlayMessage\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "size_t apollo::cyber::transport::UnderlayMessage::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "size_t apollo::cyber::transport::UnderlayMessage::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "\fBUnderlayMessage\fP & apollo::cyber::transport::UnderlayMessage::operator= (const \fBUnderlayMessage\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBUnderlayMessage\fP that will be copied\&. 
.RE
.PP

.SS "\fBUnderlayMessage\fP & apollo::cyber::transport::UnderlayMessage::operator= (\fBUnderlayMessage\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBUnderlayMessage\fP that will be copied\&. 
.RE
.PP

.SS "int32_t& apollo::cyber::transport::UnderlayMessage::seq ()\fC [inline]\fP"

.PP
This function returns a reference to member seq\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member seq 
.RE
.PP

.SS "int32_t apollo::cyber::transport::UnderlayMessage::seq () const\fC [inline]\fP"

.PP
This function returns the value of member seq\&. 
.PP
\fBReturns\fP
.RS 4
Value of member seq 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::seq (int32_t _seq)\fC [inline]\fP"

.PP
This function sets a value in member seq\&. 
.PP
\fBParameters\fP
.RS 4
\fI_seq\fP New value for member seq 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "int32_t& apollo::cyber::transport::UnderlayMessage::timestamp ()\fC [inline]\fP"

.PP
This function returns a reference to member timestamp\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member timestamp 
.RE
.PP

.SS "int32_t apollo::cyber::transport::UnderlayMessage::timestamp () const\fC [inline]\fP"

.PP
This function returns the value of member timestamp\&. 
.PP
\fBReturns\fP
.RS 4
Value of member timestamp 
.RE
.PP

.SS "void apollo::cyber::transport::UnderlayMessage::timestamp (int32_t _timestamp)\fC [inline]\fP"

.PP
This function sets a value in member timestamp\&. 
.PP
\fBParameters\fP
.RS 4
\fI_timestamp\fP New value for member timestamp 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
