.TH "apollo::cyber::transport::MulticastNotifier" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::MulticastNotifier
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::NotifierBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShutdown\fP () override"
.br
.ti -1c
.RI "bool \fBNotify\fP (const \fBReadableInfo\fP &info) override"
.br
.ti -1c
.RI "bool \fBListen\fP (int timeout_ms, \fBReadableInfo\fP *info) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBType\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
