.TH "apollo::cyber::blocker::Blocker< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::blocker::Blocker< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::blocker::BlockerBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessageType\fP = T"
.br
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< T >"
.br
.ti -1c
.RI "using \fBMessageQueue\fP = std::list< MessagePtr >"
.br
.ti -1c
.RI "using \fBCallback\fP = std::function< void(const MessagePtr &)>"
.br
.ti -1c
.RI "using \fBCallbackMap\fP = std::unordered_map< std::string, Callback >"
.br
.ti -1c
.RI "using \fBIterator\fP = typename std::list< std::shared_ptr< T > >::const_iterator"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlocker\fP (const \fBBlockerAttr\fP &attr)"
.br
.ti -1c
.RI "void \fBPublish\fP (const MessageType &msg)"
.br
.ti -1c
.RI "void \fBPublish\fP (const MessagePtr &msg)"
.br
.ti -1c
.RI "void \fBClearObserved\fP () override"
.br
.ti -1c
.RI "void \fBClearPublished\fP () override"
.br
.ti -1c
.RI "void \fBObserve\fP () override"
.br
.ti -1c
.RI "bool \fBIsObservedEmpty\fP () const override"
.br
.ti -1c
.RI "bool \fBIsPublishedEmpty\fP () const override"
.br
.ti -1c
.RI "bool \fBSubscribe\fP (const std::string &callback_id, const Callback &callback)"
.br
.ti -1c
.RI "bool \fBUnsubscribe\fP (const std::string &callback_id) override"
.br
.ti -1c
.RI "const MessageType & \fBGetLatestObserved\fP () const"
.br
.ti -1c
.RI "const MessagePtr \fBGetLatestObservedPtr\fP () const"
.br
.ti -1c
.RI "const MessagePtr \fBGetOldestObservedPtr\fP () const"
.br
.ti -1c
.RI "const MessagePtr \fBGetLatestPublishedPtr\fP () const"
.br
.ti -1c
.RI "Iterator \fBObservedBegin\fP () const"
.br
.ti -1c
.RI "Iterator \fBObservedEnd\fP () const"
.br
.ti -1c
.RI "size_t \fBcapacity\fP () const override"
.br
.ti -1c
.RI "void \fBset_capacity\fP (size_t capacity) override"
.br
.ti -1c
.RI "const std::string & \fBchannel_name\fP () const override"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBBlockerManager\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
