.TH "apollo::perception::camera::LaneLineCubicCurve" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::camera::LaneLineCubicCurve
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLongitudeMinFieldNumber\fP = 1, \fBkLongitudeMaxFieldNumber\fP = 2, \fBkAFieldNumber\fP = 3, \fBkBFieldNumber\fP = 4, \fBkCFieldNumber\fP = 5, \fBkDFieldNumber\fP = 6 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBLaneLineCubicCurve\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBLaneLineCubicCurve\fP (const \fBLaneLineCubicCurve\fP &from)"
.br
.ti -1c
.RI "\fBLaneLineCubicCurve\fP (\fBLaneLineCubicCurve\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBLaneLineCubicCurve\fP & \fBoperator=\fP (const \fBLaneLineCubicCurve\fP &from)"
.br
.ti -1c
.RI "\fBLaneLineCubicCurve\fP & \fBoperator=\fP (\fBLaneLineCubicCurve\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBLaneLineCubicCurve\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBLaneLineCubicCurve\fP *other)"
.br
.ti -1c
.RI "\fBLaneLineCubicCurve\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBLaneLineCubicCurve\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBLaneLineCubicCurve\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_longitude_min\fP () const"
.br
.ti -1c
.RI "void \fBclear_longitude_min\fP ()"
.br
.ti -1c
.RI "float \fBlongitude_min\fP () const"
.br
.ti -1c
.RI "void \fBset_longitude_min\fP (float value)"
.br
.ti -1c
.RI "bool \fBhas_longitude_max\fP () const"
.br
.ti -1c
.RI "void \fBclear_longitude_max\fP ()"
.br
.ti -1c
.RI "float \fBlongitude_max\fP () const"
.br
.ti -1c
.RI "void \fBset_longitude_max\fP (float value)"
.br
.ti -1c
.RI "bool \fBhas_a\fP () const"
.br
.ti -1c
.RI "void \fBclear_a\fP ()"
.br
.ti -1c
.RI "float \fBa\fP () const"
.br
.ti -1c
.RI "void \fBset_a\fP (float value)"
.br
.ti -1c
.RI "bool \fBhas_b\fP () const"
.br
.ti -1c
.RI "void \fBclear_b\fP ()"
.br
.ti -1c
.RI "float \fBb\fP () const"
.br
.ti -1c
.RI "void \fBset_b\fP (float value)"
.br
.ti -1c
.RI "bool \fBhas_c\fP () const"
.br
.ti -1c
.RI "void \fBclear_c\fP ()"
.br
.ti -1c
.RI "float \fBc\fP () const"
.br
.ti -1c
.RI "void \fBset_c\fP (float value)"
.br
.ti -1c
.RI "bool \fBhas_d\fP () const"
.br
.ti -1c
.RI "void \fBclear_d\fP ()"
.br
.ti -1c
.RI "float \fBd\fP () const"
.br
.ti -1c
.RI "void \fBset_d\fP (float value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBLaneLineCubicCurve\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBLaneLineCubicCurve\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLaneLineCubicCurve\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fperception_5fmsgs_2fperception_5fcamera_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBLaneLineCubicCurve\fP &a, \fBLaneLineCubicCurve\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::perception::camera::LaneLineCubicCurve::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LaneLineCubicCurve::MergeImpl
}
.fi
.SS "constexpr int apollo::perception::camera::LaneLineCubicCurve::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
