.TH "apollo::cyber::NodeServiceImpl" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::NodeServiceImpl \- The implementation for \fBNode\fP to create Objects connected by Param\&. e\&.g\&. Param Server and \fBClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node_service_impl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeServiceImpl\fP (const std::string &node_name)"
.br
.RI "Construct a new \fBNode\fP \fBService\fP Impl object\&. "
.ti -1c
.RI "\fBNodeServiceImpl\fP ()=delete"
.br
.RI "Forbid default-constructor\&. "
.ti -1c
.RI "\fB~NodeServiceImpl\fP ()"
.br
.RI "Destroy the \fBNode\fP \fBService\fP Impl object\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The implementation for \fBNode\fP to create Objects connected by Param\&. e\&.g\&. Param Server and \fBClient\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::NodeServiceImpl::NodeServiceImpl (const std::string & node_name)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Construct a new \fBNode\fP \fBService\fP Impl object\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP node name 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
