.TH "apollo::dreamview::HMIStatus::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::dreamview::HMIStatus::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBHMIStatus\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBHMIStatus\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_map\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_vehicle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_docker_image\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_utm_zone_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_passenger_msg\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_scenario_set_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_scenario_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_dynamic_model\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_record_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_vehicle_type\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_camera_sensor_channel\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_current_point_cloud_channel\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
