.TH "apollo::cyber::mainboard::ModuleArgument" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::mainboard::ModuleArgument
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDisplayUsage\fP ()"
.br
.ti -1c
.RI "void \fBParseArgument\fP (int argc, char *const argv[])"
.br
.ti -1c
.RI "void \fBGetOptions\fP (const int argc, char *const argv[])"
.br
.ti -1c
.RI "const std::string & \fBGetBinaryName\fP () const"
.br
.ti -1c
.RI "const std::string & \fBGetProcessGroup\fP () const"
.br
.ti -1c
.RI "const std::string & \fBGetSchedName\fP () const"
.br
.ti -1c
.RI "const std::list< std::string > & \fBGetDAGConfList\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
