.TH "apollo::cyber::service_discovery::RoleWriter" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::service_discovery::RoleWriter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::service_discovery::RoleBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoleWriter\fP (const \fBproto::RoleAttributes\fP &attr, uint64_t timestamp_ns=0)"
.br
.ti -1c
.RI "bool \fBMatch\fP (const \fBproto::RoleAttributes\fP &target_attr) const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
