.TH "apollo::cyber::WriterBase" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::WriterBase \- \fBBase\fP class for a \fBWriter\fP\&. A \fBWriter\fP is an object to send messages through a 'Channel'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <writer_base\&.h>\fP
.PP
Inherited by \fBapollo::cyber::Writer< MessageT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriterBase\fP (const proto::RoleAttributes &role_attr)"
.br
.RI "Construct a new \fBWriter\fP \fBBase\fP object\&. "
.ti -1c
.RI "virtual bool \fBInit\fP ()=0"
.br
.RI "Init the \fBWriter\fP\&. "
.ti -1c
.RI "virtual void \fBShutdown\fP ()=0"
.br
.RI "Shutdown the \fBWriter\fP\&. "
.ti -1c
.RI "virtual bool \fBHasReader\fP ()"
.br
.RI "Is there any \fBReader\fP that subscribes our Channel? You can publish message when this return true\&. "
.ti -1c
.RI "virtual void \fBGetReaders\fP (std::vector< proto::RoleAttributes > *readers)"
.br
.RI "Get all Readers that subscriber our writing channel\&. "
.ti -1c
.RI "const std::string & \fBGetChannelName\fP () const"
.br
.RI "Get \fBWriter\fP's Channel name\&. "
.ti -1c
.RI "bool \fBIsInit\fP () const"
.br
.RI "Is \fBWriter\fP initialized? "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "proto::RoleAttributes \fBrole_attr_\fP"
.br
.ti -1c
.RI "std::mutex \fBlock_\fP"
.br
.ti -1c
.RI "bool \fBinit_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBase\fP class for a \fBWriter\fP\&. A \fBWriter\fP is an object to send messages through a 'Channel'\&. 


.PP
\fBWarning\fP
.RS 4
One \fBWriter\fP can only write one channel\&. But different writers can write through the same channel 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::WriterBase::WriterBase (const proto::RoleAttributes & role_attr)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Construct a new \fBWriter\fP \fBBase\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrole_attr\fP role attributes for this \fBWriter\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "const std::string& apollo::cyber::WriterBase::GetChannelName () const\fC [inline]\fP"

.PP
Get \fBWriter\fP's Channel name\&. 
.PP
\fBReturns\fP
.RS 4
const std::string& const reference to the channel name 
.RE
.PP

.SS "virtual void apollo::cyber::WriterBase::GetReaders (std::vector< proto::RoleAttributes > * readers)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get all Readers that subscriber our writing channel\&. 
.PP
\fBParameters\fP
.RS 4
\fIreaders\fP result vector of RoleAttributes 
.RE
.PP

.PP
Reimplemented in \fBapollo::cyber::Writer< MessageT >\fP\&.
.SS "virtual bool apollo::cyber::WriterBase::HasReader ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Is there any \fBReader\fP that subscribes our Channel? You can publish message when this return true\&. 
.PP
\fBReturns\fP
.RS 4
true if the channel has reader 
.PP
false if the channel has no reader 
.RE
.PP

.PP
Reimplemented in \fBapollo::cyber::Writer< MessageT >\fP\&.
.SS "virtual bool apollo::cyber::WriterBase::Init ()\fC [pure virtual]\fP"

.PP
Init the \fBWriter\fP\&. 
.PP
\fBReturns\fP
.RS 4
true if init success 
.PP
false if init failed 
.RE
.PP

.PP
Implemented in \fBapollo::cyber::Writer< MessageT >\fP, and \fBapollo::cyber::blocker::IntraWriter< MessageT >\fP\&.
.SS "bool apollo::cyber::WriterBase::IsInit () const\fC [inline]\fP"

.PP
Is \fBWriter\fP initialized? 
.PP
\fBReturns\fP
.RS 4
true if the \fBWriter\fP is inited 
.PP
false if the Write is not inited 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
