.TH "apollo::cyber::transport::ShmTransceiverTest" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::ShmTransceiverTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Protected Types"

.in +1c
.ti -1c
.RI "using \fBTransmitterPtr\fP = std::shared_ptr< \fBTransmitter\fP< proto::UnitTest > >"
.br
.ti -1c
.RI "using \fBReceiverPtr\fP = std::shared_ptr< \fBReceiver\fP< proto::UnitTest > >"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel_name_\fP"
.br
.ti -1c
.RI "TransmitterPtr \fBtransmitter_a_\fP = nullptr"
.br
.ti -1c
.RI "TransmitterPtr \fBtransmitter_b_\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
