.TH "apollo::cyber::TimerOption" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::TimerOption \- The options of timer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimerOption\fP (uint32_t \fBperiod\fP, std::function< void()> \fBcallback\fP, bool \fBoneshot\fP)"
.br
.RI "Construct a new \fBTimer\fP Option object\&. "
.ti -1c
.RI "\fBTimerOption\fP ()"
.br
.RI "Default constructor for initializer list\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBperiod\fP = 0"
.br
.RI "The period of the timer, unit is ms max: 512 * 64 min: 1\&. "
.ti -1c
.RI "std::function< void()> \fBcallback\fP"
.br
.ti -1c
.RI "bool \fBoneshot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The options of timer\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "apollo::cyber::TimerOption::TimerOption (uint32_t period, std::function< void()> callback, bool oneshot)\fC [inline]\fP"

.PP
Construct a new \fBTimer\fP Option object\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP The period of the timer, unit is ms 
.br
\fIcallback\fP The task that the timer needs to perform 
.br
\fIoneshot\fP Oneshot or period 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "std::function<void()> apollo::cyber::TimerOption::callback"
The task that the timer needs to perform 
.SS "bool apollo::cyber::TimerOption::oneshot"
True: perform the callback only after the first timing cycle False: perform the callback every timed period 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
