.TH "apollo::cyber::transport::Transmitter< M >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::Transmitter< M >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Endpoint\fP\&.
.PP
Inherited by \fBapollo::cyber::transport::HybridTransmitter< M >\fP, \fBapollo::cyber::transport::IntraTransmitter< M >\fP, \fBapollo::cyber::transport::RtpsTransmitter< M >\fP, and \fBapollo::cyber::transport::ShmTransmitter< M >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< M >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransmitter\fP (const \fBRoleAttributes\fP &attr)"
.br
.ti -1c
.RI "virtual void \fBEnable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDisable\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBEnable\fP (const \fBRoleAttributes\fP &opposite_attr)"
.br
.ti -1c
.RI "virtual void \fBDisable\fP (const \fBRoleAttributes\fP &opposite_attr)"
.br
.ti -1c
.RI "virtual bool \fBTransmit\fP (const MessagePtr &msg)"
.br
.ti -1c
.RI "virtual bool \fBTransmit\fP (const MessagePtr &msg, const \fBMessageInfo\fP &msg_info)=0"
.br
.ti -1c
.RI "uint64_t \fBNextSeqNum\fP ()"
.br
.ti -1c
.RI "uint64_t \fBseq_num\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBseq_num_\fP"
.br
.ti -1c
.RI "\fBMessageInfo\fP \fBmsg_info_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
