.TH "apollo::canbus::Gem::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Gem::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBGem\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::canbus::Global_rpt_6a\fP & \fBglobal_rpt_6a\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_global_rpt_6a\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake_cmd_6b\fP & \fBbrake_cmd_6b\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_cmd_6b\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake_rpt_6c\fP & \fBbrake_rpt_6c\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_rpt_6c\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Steering_cmd_6d\fP & \fBsteering_cmd_6d\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_cmd_6d\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Steering_rpt_1_6e\fP & \fBsteering_rpt_1_6e\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_rpt_1_6e\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Wheel_speed_rpt_7a\fP & \fBwheel_speed_rpt_7a\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_wheel_speed_rpt_7a\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Date_time_rpt_83\fP & \fBdate_time_rpt_83\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_date_time_rpt_83\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake_motor_rpt_1_70\fP & \fBbrake_motor_rpt_1_70\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_motor_rpt_1_70\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Headlight_rpt_77\fP & \fBheadlight_rpt_77\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_headlight_rpt_77\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Accel_rpt_68\fP & \fBaccel_rpt_68\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_accel_rpt_68\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Steering_motor_rpt_3_75\fP & \fBsteering_motor_rpt_3_75\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_motor_rpt_3_75\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Turn_cmd_63\fP & \fBturn_cmd_63\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_turn_cmd_63\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Turn_rpt_64\fP & \fBturn_rpt_64\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_turn_rpt_64\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Shift_cmd_65\fP & \fBshift_cmd_65\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_shift_cmd_65\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Shift_rpt_66\fP & \fBshift_rpt_66\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_shift_rpt_66\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Accel_cmd_67\fP & \fBaccel_cmd_67\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_accel_cmd_67\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Lat_lon_heading_rpt_82\fP & \fBlat_lon_heading_rpt_82\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lat_lon_heading_rpt_82\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Global_cmd_69\fP & \fBglobal_cmd_69\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_global_cmd_69\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Parking_brake_status_rpt_80\fP & \fBparking_brake_status_rpt_80\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_parking_brake_status_rpt_80\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Yaw_rate_rpt_81\fP & \fByaw_rate_rpt_81\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_yaw_rate_rpt_81\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Horn_rpt_79\fP & \fBhorn_rpt_79\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_horn_rpt_79\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Horn_cmd_78\fP & \fBhorn_cmd_78\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_horn_cmd_78\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Wiper_rpt_91\fP & \fBwiper_rpt_91\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_wiper_rpt_91\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Vehicle_speed_rpt_6f\fP & \fBvehicle_speed_rpt_6f\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_vehicle_speed_rpt_6f\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Headlight_cmd_76\fP & \fBheadlight_cmd_76\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_headlight_cmd_76\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Steering_motor_rpt_2_74\fP & \fBsteering_motor_rpt_2_74\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_motor_rpt_2_74\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake_motor_rpt_2_71\fP & \fBbrake_motor_rpt_2_71\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_motor_rpt_2_71\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Steering_motor_rpt_1_73\fP & \fBsteering_motor_rpt_1_73\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_steering_motor_rpt_1_73\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Wiper_cmd_90\fP & \fBwiper_cmd_90\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_wiper_cmd_90\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::canbus::Brake_motor_rpt_3_72\fP & \fBbrake_motor_rpt_3_72\fP (const \fBGem\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_brake_motor_rpt_3_72\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
