.TH "apollo::canbus::WheelSpeed" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::WheelSpeed
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkWheelSpdRrFieldNumber\fP = 3, \fBkWheelSpdRlFieldNumber\fP = 6, \fBkWheelSpdFrFieldNumber\fP = 9, \fBkWheelSpdFlFieldNumber\fP = 12, \fBkIsWheelSpdRrValidFieldNumber\fP = 1, \fBkIsWheelSpdRlValidFieldNumber\fP = 4, \fBkIsWheelSpdFrValidFieldNumber\fP = 7, \fBkIsWheelSpdFlValidFieldNumber\fP = 10, \fBkWheelDirectionRrFieldNumber\fP = 2, \fBkWheelDirectionRlFieldNumber\fP = 5, \fBkWheelDirectionFrFieldNumber\fP = 8, \fBkWheelDirectionFlFieldNumber\fP = 11 }"
.br
.ti -1c
.RI "typedef WheelSpeed_WheelSpeedType \fBWheelSpeedType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBWheelSpeed\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBWheelSpeed\fP (const \fBWheelSpeed\fP &from)"
.br
.ti -1c
.RI "\fBWheelSpeed\fP (\fBWheelSpeed\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBWheelSpeed\fP & \fBoperator=\fP (const \fBWheelSpeed\fP &from)"
.br
.ti -1c
.RI "\fBWheelSpeed\fP & \fBoperator=\fP (\fBWheelSpeed\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBWheelSpeed\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBWheelSpeed\fP *other)"
.br
.ti -1c
.RI "\fBWheelSpeed\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBWheelSpeed\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBWheelSpeed\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_wheel_spd_rr\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_spd_rr\fP ()"
.br
.ti -1c
.RI "double \fBwheel_spd_rr\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_spd_rr\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_spd_rl\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_spd_rl\fP ()"
.br
.ti -1c
.RI "double \fBwheel_spd_rl\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_spd_rl\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_spd_fr\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_spd_fr\fP ()"
.br
.ti -1c
.RI "double \fBwheel_spd_fr\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_spd_fr\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_spd_fl\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_spd_fl\fP ()"
.br
.ti -1c
.RI "double \fBwheel_spd_fl\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_spd_fl\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_is_wheel_spd_rr_valid\fP () const"
.br
.ti -1c
.RI "void \fBclear_is_wheel_spd_rr_valid\fP ()"
.br
.ti -1c
.RI "bool \fBis_wheel_spd_rr_valid\fP () const"
.br
.ti -1c
.RI "void \fBset_is_wheel_spd_rr_valid\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_is_wheel_spd_rl_valid\fP () const"
.br
.ti -1c
.RI "void \fBclear_is_wheel_spd_rl_valid\fP ()"
.br
.ti -1c
.RI "bool \fBis_wheel_spd_rl_valid\fP () const"
.br
.ti -1c
.RI "void \fBset_is_wheel_spd_rl_valid\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_is_wheel_spd_fr_valid\fP () const"
.br
.ti -1c
.RI "void \fBclear_is_wheel_spd_fr_valid\fP ()"
.br
.ti -1c
.RI "bool \fBis_wheel_spd_fr_valid\fP () const"
.br
.ti -1c
.RI "void \fBset_is_wheel_spd_fr_valid\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_is_wheel_spd_fl_valid\fP () const"
.br
.ti -1c
.RI "void \fBclear_is_wheel_spd_fl_valid\fP ()"
.br
.ti -1c
.RI "bool \fBis_wheel_spd_fl_valid\fP () const"
.br
.ti -1c
.RI "void \fBset_is_wheel_spd_fl_valid\fP (bool value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_direction_rr\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_direction_rr\fP ()"
.br
.ti -1c
.RI "::apollo::canbus::WheelSpeed_WheelSpeedType \fBwheel_direction_rr\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_direction_rr\fP (::apollo::canbus::WheelSpeed_WheelSpeedType value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_direction_rl\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_direction_rl\fP ()"
.br
.ti -1c
.RI "::apollo::canbus::WheelSpeed_WheelSpeedType \fBwheel_direction_rl\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_direction_rl\fP (::apollo::canbus::WheelSpeed_WheelSpeedType value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_direction_fr\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_direction_fr\fP ()"
.br
.ti -1c
.RI "::apollo::canbus::WheelSpeed_WheelSpeedType \fBwheel_direction_fr\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_direction_fr\fP (::apollo::canbus::WheelSpeed_WheelSpeedType value)"
.br
.ti -1c
.RI "bool \fBhas_wheel_direction_fl\fP () const"
.br
.ti -1c
.RI "void \fBclear_wheel_direction_fl\fP ()"
.br
.ti -1c
.RI "::apollo::canbus::WheelSpeed_WheelSpeedType \fBwheel_direction_fl\fP () const"
.br
.ti -1c
.RI "void \fBset_wheel_direction_fl\fP (::apollo::canbus::WheelSpeed_WheelSpeedType value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBWheelSpeed\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBWheelSpeed\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBWheelSpeedType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBWheelSpeedType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBWheelSpeedType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBWheelSpeedType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, WheelSpeedType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBFORWARD\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBBACKWARD\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBSTANDSTILL\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBINVALID\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBWheelSpeedType_MIN\fP"
.br
.ti -1c
.RI "static constexpr WheelSpeedType \fBWheelSpeedType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBWheelSpeedType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBWheelSpeed\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fchassis_5fmsgs_2fchassis_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBWheelSpeed\fP &a, \fBWheelSpeed\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::canbus::WheelSpeed::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    WheelSpeed::MergeImpl
}
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::BACKWARD\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_BACKWARD
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::FORWARD\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_FORWARD
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::INVALID\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_INVALID
.fi
.SS "constexpr int apollo::canbus::WheelSpeed::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::STANDSTILL\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_STANDSTILL
.fi
.SS "constexpr int apollo::canbus::WheelSpeed::WheelSpeedType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_WheelSpeedType_ARRAYSIZE
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::WheelSpeedType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_WheelSpeedType_MAX
.fi
.SS "constexpr WheelSpeed_WheelSpeedType apollo::canbus::WheelSpeed::WheelSpeedType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    WheelSpeed_WheelSpeedType_WheelSpeedType_MIN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
