.TH "apollo::cyber::proto::QosProfile" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::QosProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkMpsFieldNumber\fP = 3, \fBkHistoryFieldNumber\fP = 1, \fBkDepthFieldNumber\fP = 2, \fBkReliabilityFieldNumber\fP = 4, \fBkDurabilityFieldNumber\fP = 5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBQosProfile\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBQosProfile\fP (const \fBQosProfile\fP &from)"
.br
.ti -1c
.RI "\fBQosProfile\fP (\fBQosProfile\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBQosProfile\fP & \fBoperator=\fP (const \fBQosProfile\fP &from)"
.br
.ti -1c
.RI "\fBQosProfile\fP & \fBoperator=\fP (\fBQosProfile\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBQosProfile\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBQosProfile\fP *other)"
.br
.ti -1c
.RI "\fBQosProfile\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBQosProfile\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBQosProfile\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_mps\fP () const"
.br
.ti -1c
.RI "void \fBclear_mps\fP ()"
.br
.ti -1c
.RI "uint32_t \fBmps\fP () const"
.br
.ti -1c
.RI "void \fBset_mps\fP (uint32_t value)"
.br
.ti -1c
.RI "bool \fBhas_history\fP () const"
.br
.ti -1c
.RI "void \fBclear_history\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::QosHistoryPolicy \fBhistory\fP () const"
.br
.ti -1c
.RI "void \fBset_history\fP (::apollo::cyber::proto::QosHistoryPolicy value)"
.br
.ti -1c
.RI "bool \fBhas_depth\fP () const"
.br
.ti -1c
.RI "void \fBclear_depth\fP ()"
.br
.ti -1c
.RI "uint32_t \fBdepth\fP () const"
.br
.ti -1c
.RI "void \fBset_depth\fP (uint32_t value)"
.br
.ti -1c
.RI "bool \fBhas_reliability\fP () const"
.br
.ti -1c
.RI "void \fBclear_reliability\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::QosReliabilityPolicy \fBreliability\fP () const"
.br
.ti -1c
.RI "void \fBset_reliability\fP (::apollo::cyber::proto::QosReliabilityPolicy value)"
.br
.ti -1c
.RI "bool \fBhas_durability\fP () const"
.br
.ti -1c
.RI "void \fBclear_durability\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::QosDurabilityPolicy \fBdurability\fP () const"
.br
.ti -1c
.RI "void \fBset_durability\fP (::apollo::cyber::proto::QosDurabilityPolicy value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBQosProfile\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBQosProfile\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQosProfile\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_cyber_2fproto_2fqos_5fprofile_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBQosProfile\fP &a, \fBQosProfile\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::cyber::proto::QosProfile::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    QosProfile::MergeImpl
}
.fi
.SS "constexpr int apollo::cyber::proto::QosProfile::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
