.TH "apollo::cyber::transport::IntraDispatcher" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::IntraDispatcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Dispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename MessageT > void \fBOnMessage\fP (uint64_t channel_id, const std::shared_ptr< MessageT > &message, const \fBMessageInfo\fP &message_info)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const RoleAttributes &self_attr, const MessageListener< MessageT > &listener)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBAddListener\fP (const RoleAttributes &self_attr, const RoleAttributes &opposite_attr, const MessageListener< MessageT > &listener)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBRemoveListener\fP (const RoleAttributes &self_attr)"
.br
.ti -1c
.RI "template<typename MessageT > void \fBRemoveListener\fP (const RoleAttributes &self_attr, const RoleAttributes &opposite_attr)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
