.TH "apollo::cyber::record::PlayParam" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::PlayParam
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBis_play_all_channels\fP = false"
.br
.ti -1c
.RI "bool \fBis_loop_playback\fP = false"
.br
.ti -1c
.RI "double \fBplay_rate\fP = 1\&.0"
.br
.ti -1c
.RI "uint64_t \fBbegin_time_ns\fP = 0"
.br
.ti -1c
.RI "uint64_t \fBend_time_ns\fP = std::numeric_limits<uint64_t>::max()"
.br
.ti -1c
.RI "uint64_t \fBstart_time_s\fP = 0"
.br
.ti -1c
.RI "uint64_t \fBdelay_time_s\fP = 0"
.br
.ti -1c
.RI "uint32_t \fBpreload_time_s\fP = 3"
.br
.ti -1c
.RI "std::set< std::string > \fBfiles_to_play\fP"
.br
.ti -1c
.RI "std::set< std::string > \fBchannels_to_play\fP"
.br
.ti -1c
.RI "std::set< std::string > \fBblack_channels\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
