.TH "apollo::common::GaussianInfo" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::common::GaussianInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkSigmaXFieldNumber\fP = 1, \fBkSigmaYFieldNumber\fP = 2, \fBkCorrelationFieldNumber\fP = 3, \fBkAreaProbabilityFieldNumber\fP = 4, \fBkEllipseAFieldNumber\fP = 5, \fBkEllipseBFieldNumber\fP = 6, \fBkThetaAFieldNumber\fP = 7 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBGaussianInfo\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBGaussianInfo\fP (const \fBGaussianInfo\fP &from)"
.br
.ti -1c
.RI "\fBGaussianInfo\fP (\fBGaussianInfo\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBGaussianInfo\fP & \fBoperator=\fP (const \fBGaussianInfo\fP &from)"
.br
.ti -1c
.RI "\fBGaussianInfo\fP & \fBoperator=\fP (\fBGaussianInfo\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBGaussianInfo\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBGaussianInfo\fP *other)"
.br
.ti -1c
.RI "\fBGaussianInfo\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBGaussianInfo\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBGaussianInfo\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_sigma_x\fP () const"
.br
.ti -1c
.RI "void \fBclear_sigma_x\fP ()"
.br
.ti -1c
.RI "double \fBsigma_x\fP () const"
.br
.ti -1c
.RI "void \fBset_sigma_x\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_sigma_y\fP () const"
.br
.ti -1c
.RI "void \fBclear_sigma_y\fP ()"
.br
.ti -1c
.RI "double \fBsigma_y\fP () const"
.br
.ti -1c
.RI "void \fBset_sigma_y\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_correlation\fP () const"
.br
.ti -1c
.RI "void \fBclear_correlation\fP ()"
.br
.ti -1c
.RI "double \fBcorrelation\fP () const"
.br
.ti -1c
.RI "void \fBset_correlation\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_area_probability\fP () const"
.br
.ti -1c
.RI "void \fBclear_area_probability\fP ()"
.br
.ti -1c
.RI "double \fBarea_probability\fP () const"
.br
.ti -1c
.RI "void \fBset_area_probability\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_ellipse_a\fP () const"
.br
.ti -1c
.RI "void \fBclear_ellipse_a\fP ()"
.br
.ti -1c
.RI "double \fBellipse_a\fP () const"
.br
.ti -1c
.RI "void \fBset_ellipse_a\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_ellipse_b\fP () const"
.br
.ti -1c
.RI "void \fBclear_ellipse_b\fP ()"
.br
.ti -1c
.RI "double \fBellipse_b\fP () const"
.br
.ti -1c
.RI "void \fBset_ellipse_b\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_theta_a\fP () const"
.br
.ti -1c
.RI "void \fBclear_theta_a\fP ()"
.br
.ti -1c
.RI "double \fBtheta_a\fP () const"
.br
.ti -1c
.RI "void \fBset_theta_a\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBGaussianInfo\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBGaussianInfo\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBGaussianInfo\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fpnc_5fpoint_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBGaussianInfo\fP &a, \fBGaussianInfo\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::common::GaussianInfo::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GaussianInfo::MergeImpl
}
.fi
.SS "constexpr int apollo::common::GaussianInfo::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    9
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
