.TH "apollo::control::Debug::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::control::Debug::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBDebug\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::control::SimpleLongitudinalDebug\fP & \fBsimple_lon_debug\fP (const \fBDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_simple_lon_debug\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::control::SimpleLateralDebug\fP & \fBsimple_lat_debug\fP (const \fBDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_simple_lat_debug\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::control::InputDebug\fP & \fBinput_debug\fP (const \fBDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_input_debug\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::control::SimpleMPCDebug\fP & \fBsimple_mpc_debug\fP (const \fBDebug\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_simple_mpc_debug\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
