.TH "apollo::drivers::Vehicle2_4f1::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle2_4f1::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBVehicle2_4f1\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_can_rx_volvo_short_track_roc\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_mr_only_transmit\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_lr_only_transmit\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_high_yaw_angle\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_clear_faults\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_use_angle_misalignment\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_turn_signal_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_blockage_disable\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_vehicle_speed_validity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_mmr_upside_down\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_wiper_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_raw_data_enable\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_radar_cmd_radiate\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_grouping_mode\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_maximum_tracks\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_lateral_mounting_offset\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_angle_misalignment\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_can_rx_scan_index_ack\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
