.TH "apollo::planning::MainEmergencyStop" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::MainEmergencyStop
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTaskCase\fP { \fBkHardBrake\fP = 3, \fBkCruiseToStop\fP = 4, \fBTASK_NOT_SET\fP = 0 }"
.br
.ti -1c
.RI "enum : int { \fBkReasonFieldNumber\fP = 2, \fBkReasonCodeFieldNumber\fP = 1, \fBkHardBrakeFieldNumber\fP = 3, \fBkCruiseToStopFieldNumber\fP = 4 }"
.br
.ti -1c
.RI "typedef MainEmergencyStop_ReasonCode \fBReasonCode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBMainEmergencyStop\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBMainEmergencyStop\fP (const \fBMainEmergencyStop\fP &from)"
.br
.ti -1c
.RI "\fBMainEmergencyStop\fP (\fBMainEmergencyStop\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBMainEmergencyStop\fP & \fBoperator=\fP (const \fBMainEmergencyStop\fP &from)"
.br
.ti -1c
.RI "\fBMainEmergencyStop\fP & \fBoperator=\fP (\fBMainEmergencyStop\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBMainEmergencyStop\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBMainEmergencyStop\fP *other)"
.br
.ti -1c
.RI "\fBMainEmergencyStop\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBMainEmergencyStop\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBMainEmergencyStop\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_reason\fP () const"
.br
.ti -1c
.RI "void \fBclear_reason\fP ()"
.br
.ti -1c
.RI "const std::string & \fBreason\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_reason\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_reason\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_reason\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_reason\fP (std::string *reason)"
.br
.ti -1c
.RI "bool \fBhas_reason_code\fP () const"
.br
.ti -1c
.RI "void \fBclear_reason_code\fP ()"
.br
.ti -1c
.RI "::apollo::planning::MainEmergencyStop_ReasonCode \fBreason_code\fP () const"
.br
.ti -1c
.RI "void \fBset_reason_code\fP (::apollo::planning::MainEmergencyStop_ReasonCode value)"
.br
.ti -1c
.RI "bool \fBhas_hard_brake\fP () const"
.br
.ti -1c
.RI "void \fBclear_hard_brake\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::planning::EmergencyStopHardBrake\fP & \fBhard_brake\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::planning::EmergencyStopHardBrake\fP * \fBrelease_hard_brake\fP ()"
.br
.ti -1c
.RI "::\fBapollo::planning::EmergencyStopHardBrake\fP * \fBmutable_hard_brake\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_hard_brake\fP (::\fBapollo::planning::EmergencyStopHardBrake\fP *hard_brake)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_hard_brake\fP (::\fBapollo::planning::EmergencyStopHardBrake\fP *hard_brake)"
.br
.ti -1c
.RI "::\fBapollo::planning::EmergencyStopHardBrake\fP * \fBunsafe_arena_release_hard_brake\fP ()"
.br
.ti -1c
.RI "bool \fBhas_cruise_to_stop\fP () const"
.br
.ti -1c
.RI "void \fBclear_cruise_to_stop\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::planning::EmergencyStopCruiseToStop\fP & \fBcruise_to_stop\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::planning::EmergencyStopCruiseToStop\fP * \fBrelease_cruise_to_stop\fP ()"
.br
.ti -1c
.RI "::\fBapollo::planning::EmergencyStopCruiseToStop\fP * \fBmutable_cruise_to_stop\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_cruise_to_stop\fP (::\fBapollo::planning::EmergencyStopCruiseToStop\fP *cruise_to_stop)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_cruise_to_stop\fP (::\fBapollo::planning::EmergencyStopCruiseToStop\fP *cruise_to_stop)"
.br
.ti -1c
.RI "::\fBapollo::planning::EmergencyStopCruiseToStop\fP * \fBunsafe_arena_release_cruise_to_stop\fP ()"
.br
.ti -1c
.RI "void \fBclear_task\fP ()"
.br
.ti -1c
.RI "TaskCase \fBtask_case\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_reason\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBMainEmergencyStop\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBMainEmergencyStop\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBReasonCode_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBReasonCode_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBReasonCode_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBReasonCode_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ReasonCode *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBESTOP_REASON_INTERNAL_ERR\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBESTOP_REASON_COLLISION\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBESTOP_REASON_ST_FIND_PATH\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBESTOP_REASON_ST_MAKE_DECISION\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBESTOP_REASON_SENSOR_ERROR\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBReasonCode_MIN\fP"
.br
.ti -1c
.RI "static constexpr ReasonCode \fBReasonCode_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBReasonCode_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMainEmergencyStop\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fdecision_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBMainEmergencyStop\fP &a, \fBMainEmergencyStop\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning::MainEmergencyStop::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    MainEmergencyStop::MergeImpl
}
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ESTOP_REASON_COLLISION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ESTOP_REASON_COLLISION
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ESTOP_REASON_INTERNAL_ERR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ESTOP_REASON_INTERNAL_ERR
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ESTOP_REASON_SENSOR_ERROR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ESTOP_REASON_SENSOR_ERROR
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ESTOP_REASON_ST_FIND_PATH\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ESTOP_REASON_ST_FIND_PATH
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ESTOP_REASON_ST_MAKE_DECISION\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ESTOP_REASON_ST_MAKE_DECISION
.fi
.SS "constexpr int apollo::planning::MainEmergencyStop::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    19
.fi
.SS "constexpr int apollo::planning::MainEmergencyStop::ReasonCode_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ReasonCode_ARRAYSIZE
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ReasonCode_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ReasonCode_MAX
.fi
.SS "constexpr MainEmergencyStop_ReasonCode apollo::planning::MainEmergencyStop::ReasonCode_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    MainEmergencyStop_ReasonCode_ReasonCode_MIN
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
