.TH "apollo::common::Quaternion" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::common::Quaternion
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkQxFieldNumber\fP = 1, \fBkQyFieldNumber\fP = 2, \fBkQzFieldNumber\fP = 3, \fBkQwFieldNumber\fP = 4 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBQuaternion\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBQuaternion\fP (const \fBQuaternion\fP &from)"
.br
.ti -1c
.RI "\fBQuaternion\fP (\fBQuaternion\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBQuaternion\fP & \fBoperator=\fP (const \fBQuaternion\fP &from)"
.br
.ti -1c
.RI "\fBQuaternion\fP & \fBoperator=\fP (\fBQuaternion\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBQuaternion\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBQuaternion\fP *other)"
.br
.ti -1c
.RI "\fBQuaternion\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBQuaternion\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBQuaternion\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_qx\fP () const"
.br
.ti -1c
.RI "void \fBclear_qx\fP ()"
.br
.ti -1c
.RI "double \fBqx\fP () const"
.br
.ti -1c
.RI "void \fBset_qx\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_qy\fP () const"
.br
.ti -1c
.RI "void \fBclear_qy\fP ()"
.br
.ti -1c
.RI "double \fBqy\fP () const"
.br
.ti -1c
.RI "void \fBset_qy\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_qz\fP () const"
.br
.ti -1c
.RI "void \fBclear_qz\fP ()"
.br
.ti -1c
.RI "double \fBqz\fP () const"
.br
.ti -1c
.RI "void \fBset_qz\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_qw\fP () const"
.br
.ti -1c
.RI "void \fBclear_qw\fP ()"
.br
.ti -1c
.RI "double \fBqw\fP () const"
.br
.ti -1c
.RI "void \fBset_qw\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBQuaternion\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBQuaternion\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQuaternion\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBQuaternion\fP &a, \fBQuaternion\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::common::Quaternion::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Quaternion::MergeImpl
}
.fi
.SS "constexpr int apollo::common::Quaternion::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    4
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
