.TH "apollo::cyber::data::DataVisitor< M0, NullType, NullType, NullType >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::DataVisitor< M0, NullType, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::data::DataVisitorBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataVisitor\fP (const \fBVisitorConfig\fP &configs)"
.br
.ti -1c
.RI "\fBDataVisitor\fP (uint64_t channel_id, uint32_t queue_size)"
.br
.ti -1c
.RI "bool \fBTryFetch\fP (std::shared_ptr< M0 > &m0)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
