.TH "apollo::cyber::message::ErrorCollector" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::message::ErrorCollector
.SH SYNOPSIS
.br
.PP
.PP
Inherits google::protobuf::DescriptorPool::ErrorCollector\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
