.TH "apollo::cyber::transport::HistoryAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::HistoryAttributes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryAttributes\fP (const proto::QosHistoryPolicy &qos_history_policy, uint32_t history_depth)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "proto::QosHistoryPolicy \fBhistory_policy\fP"
.br
.ti -1c
.RI "uint32_t \fBdepth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
