.TH "apollo::cyber::transport::IntraTransmitter< M >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::IntraTransmitter< M >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Transmitter< M >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBMessagePtr\fP = std::shared_ptr< M >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraTransmitter\fP (const \fBRoleAttributes\fP &attr)"
.br
.ti -1c
.RI "void \fBEnable\fP () override"
.br
.ti -1c
.RI "void \fBDisable\fP () override"
.br
.ti -1c
.RI "bool \fBTransmit\fP (const MessagePtr &msg, const \fBMessageInfo\fP &msg_info) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
