.TH "apollo::perception::V2XInformation" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::perception::V2XInformation
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkV2XTypeFieldNumber\fP = 1 }"
.br
.ti -1c
.RI "typedef V2XInformation_V2XType \fBV2XType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBV2XInformation\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBV2XInformation\fP (const \fBV2XInformation\fP &from)"
.br
.ti -1c
.RI "\fBV2XInformation\fP (\fBV2XInformation\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBV2XInformation\fP & \fBoperator=\fP (const \fBV2XInformation\fP &from)"
.br
.ti -1c
.RI "\fBV2XInformation\fP & \fBoperator=\fP (\fBV2XInformation\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBV2XInformation\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBV2XInformation\fP *other)"
.br
.ti -1c
.RI "\fBV2XInformation\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBV2XInformation\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBV2XInformation\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBv2x_type_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_v2x_type\fP ()"
.br
.ti -1c
.RI "::apollo::perception::V2XInformation_V2XType \fBv2x_type\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_v2x_type\fP (int index, ::apollo::perception::V2XInformation_V2XType value)"
.br
.ti -1c
.RI "void \fBadd_v2x_type\fP (::apollo::perception::V2XInformation_V2XType value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int > & \fBv2x_type\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< int > * \fBmutable_v2x_type\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBV2XInformation\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBV2XInformation\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBV2XType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBV2XType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBV2XType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBV2XType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, V2XType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr V2XType \fBNONE\fP"
.br
.ti -1c
.RI "static constexpr V2XType \fBZOMBIES_CAR\fP"
.br
.ti -1c
.RI "static constexpr V2XType \fBBLIND_ZONE\fP"
.br
.ti -1c
.RI "static constexpr V2XType \fBV2XType_MIN\fP"
.br
.ti -1c
.RI "static constexpr V2XType \fBV2XType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBV2XType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBV2XInformation\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fperception_5fmsgs_2fperception_5fobstacle_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBV2XInformation\fP &a, \fBV2XInformation\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::perception::V2XInformation::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    V2XInformation::MergeImpl
}
.fi
.SS "constexpr V2XInformation_V2XType apollo::perception::V2XInformation::BLIND_ZONE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_BLIND_ZONE
.fi
.SS "constexpr int apollo::perception::V2XInformation::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    2
.fi
.SS "constexpr V2XInformation_V2XType apollo::perception::V2XInformation::NONE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_NONE
.fi
.SS "constexpr int apollo::perception::V2XInformation::V2XType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_V2XType_ARRAYSIZE
.fi
.SS "constexpr V2XInformation_V2XType apollo::perception::V2XInformation::V2XType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_V2XType_MAX
.fi
.SS "constexpr V2XInformation_V2XType apollo::perception::V2XInformation::V2XType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_V2XType_MIN
.fi
.SS "constexpr V2XInformation_V2XType apollo::perception::V2XInformation::ZOMBIES_CAR\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    V2XInformation_V2XType_ZOMBIES_CAR
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
