.TH "apollo::localization::Uncertainty" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::localization::Uncertainty
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkPositionStdDevFieldNumber\fP = 1, \fBkOrientationStdDevFieldNumber\fP = 2, \fBkLinearVelocityStdDevFieldNumber\fP = 3, \fBkLinearAccelerationStdDevFieldNumber\fP = 4, \fBkAngularVelocityStdDevFieldNumber\fP = 5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBUncertainty\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBUncertainty\fP (const \fBUncertainty\fP &from)"
.br
.ti -1c
.RI "\fBUncertainty\fP (\fBUncertainty\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBUncertainty\fP & \fBoperator=\fP (const \fBUncertainty\fP &from)"
.br
.ti -1c
.RI "\fBUncertainty\fP & \fBoperator=\fP (\fBUncertainty\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBUncertainty\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBUncertainty\fP *other)"
.br
.ti -1c
.RI "\fBUncertainty\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBUncertainty\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBUncertainty\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_position_std_dev\fP () const"
.br
.ti -1c
.RI "void \fBclear_position_std_dev\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBposition_std_dev\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_position_std_dev\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_position_std_dev\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_position_std_dev\fP (::\fBapollo::common::Point3D\fP *position_std_dev)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_position_std_dev\fP (::\fBapollo::common::Point3D\fP *position_std_dev)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_position_std_dev\fP ()"
.br
.ti -1c
.RI "bool \fBhas_orientation_std_dev\fP () const"
.br
.ti -1c
.RI "void \fBclear_orientation_std_dev\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBorientation_std_dev\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_orientation_std_dev\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_orientation_std_dev\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_orientation_std_dev\fP (::\fBapollo::common::Point3D\fP *orientation_std_dev)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_orientation_std_dev\fP (::\fBapollo::common::Point3D\fP *orientation_std_dev)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_orientation_std_dev\fP ()"
.br
.ti -1c
.RI "bool \fBhas_linear_velocity_std_dev\fP () const"
.br
.ti -1c
.RI "void \fBclear_linear_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBlinear_velocity_std_dev\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_linear_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_linear_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_linear_velocity_std_dev\fP (::\fBapollo::common::Point3D\fP *linear_velocity_std_dev)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_linear_velocity_std_dev\fP (::\fBapollo::common::Point3D\fP *linear_velocity_std_dev)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_linear_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "bool \fBhas_linear_acceleration_std_dev\fP () const"
.br
.ti -1c
.RI "void \fBclear_linear_acceleration_std_dev\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBlinear_acceleration_std_dev\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_linear_acceleration_std_dev\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_linear_acceleration_std_dev\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_linear_acceleration_std_dev\fP (::\fBapollo::common::Point3D\fP *linear_acceleration_std_dev)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_linear_acceleration_std_dev\fP (::\fBapollo::common::Point3D\fP *linear_acceleration_std_dev)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_linear_acceleration_std_dev\fP ()"
.br
.ti -1c
.RI "bool \fBhas_angular_velocity_std_dev\fP () const"
.br
.ti -1c
.RI "void \fBclear_angular_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBangular_velocity_std_dev\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_angular_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_angular_velocity_std_dev\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_angular_velocity_std_dev\fP (::\fBapollo::common::Point3D\fP *angular_velocity_std_dev)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_angular_velocity_std_dev\fP (::\fBapollo::common::Point3D\fP *angular_velocity_std_dev)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_angular_velocity_std_dev\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBUncertainty\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBUncertainty\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUncertainty\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2flocalization_5fmsgs_2flocalization_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBUncertainty\fP &a, \fBUncertainty\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::localization::Uncertainty::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Uncertainty::MergeImpl
}
.fi
.SS "constexpr int apollo::localization::Uncertainty::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
