.TH "apollo::drivers::LdwLane" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::LdwLane
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkLeftBoundaryFieldNumber\fP = 4, \fBkRightBoundaryFieldNumber\fP = 5, \fBkWidthFieldNumber\fP = 1, \fBkQualityFieldNumber\fP = 2, \fBkStyleFieldNumber\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBLdwLane\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBLdwLane\fP (const \fBLdwLane\fP &from)"
.br
.ti -1c
.RI "\fBLdwLane\fP (\fBLdwLane\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBLdwLane\fP & \fBoperator=\fP (const \fBLdwLane\fP &from)"
.br
.ti -1c
.RI "\fBLdwLane\fP & \fBoperator=\fP (\fBLdwLane\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBLdwLane\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBLdwLane\fP *other)"
.br
.ti -1c
.RI "\fBLdwLane\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBLdwLane\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBLdwLane\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_left_boundary\fP () const"
.br
.ti -1c
.RI "void \fBclear_left_boundary\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::drivers::LdwLaneBoundary\fP & \fBleft_boundary\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::drivers::LdwLaneBoundary\fP * \fBrelease_left_boundary\fP ()"
.br
.ti -1c
.RI "::\fBapollo::drivers::LdwLaneBoundary\fP * \fBmutable_left_boundary\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_left_boundary\fP (::\fBapollo::drivers::LdwLaneBoundary\fP *left_boundary)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_left_boundary\fP (::\fBapollo::drivers::LdwLaneBoundary\fP *left_boundary)"
.br
.ti -1c
.RI "::\fBapollo::drivers::LdwLaneBoundary\fP * \fBunsafe_arena_release_left_boundary\fP ()"
.br
.ti -1c
.RI "bool \fBhas_right_boundary\fP () const"
.br
.ti -1c
.RI "void \fBclear_right_boundary\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::drivers::LdwLaneBoundary\fP & \fBright_boundary\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::drivers::LdwLaneBoundary\fP * \fBrelease_right_boundary\fP ()"
.br
.ti -1c
.RI "::\fBapollo::drivers::LdwLaneBoundary\fP * \fBmutable_right_boundary\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_right_boundary\fP (::\fBapollo::drivers::LdwLaneBoundary\fP *right_boundary)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_right_boundary\fP (::\fBapollo::drivers::LdwLaneBoundary\fP *right_boundary)"
.br
.ti -1c
.RI "::\fBapollo::drivers::LdwLaneBoundary\fP * \fBunsafe_arena_release_right_boundary\fP ()"
.br
.ti -1c
.RI "bool \fBhas_width\fP () const"
.br
.ti -1c
.RI "void \fBclear_width\fP ()"
.br
.ti -1c
.RI "int32_t \fBwidth\fP () const"
.br
.ti -1c
.RI "void \fBset_width\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_quality\fP () const"
.br
.ti -1c
.RI "void \fBclear_quality\fP ()"
.br
.ti -1c
.RI "int32_t \fBquality\fP () const"
.br
.ti -1c
.RI "void \fBset_quality\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_style\fP () const"
.br
.ti -1c
.RI "void \fBclear_style\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::LdwLaneStyle \fBstyle\fP () const"
.br
.ti -1c
.RI "void \fBset_style\fP (::apollo::drivers::LdwLaneStyle value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBLdwLane\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBLdwLane\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLdwLane\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fsmartereye_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBLdwLane\fP &a, \fBLdwLane\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::LdwLane::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LdwLane::MergeImpl
}
.fi
.SS "constexpr int apollo::drivers::LdwLane::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    1
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
