.TH "apollo::cyber::PyClient" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::PyClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPyClient\fP (const std::string &name, const std::string &data_type, \fBNode\fP *node)"
.br
.ti -1c
.RI "std::string \fBsend_request\fP (std::string request)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
