.TH "apollo::cyber::data::DataDispatcher< T >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::DataDispatcher< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBBufferVector\fP = std::vector< std::weak_ptr< \fBCacheBuffer\fP< std::shared_ptr< T > >> >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddBuffer\fP (const \fBChannelBuffer\fP< T > &channel_buffer)"
.br
.ti -1c
.RI "bool \fBDispatch\fP (const uint64_t channel_id, const std::shared_ptr< T > &msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
