.TH "apollo::canbus::Deceleration::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Deceleration::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBDeceleration\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_is_deceleration_available\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_deceleration_active\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_deceleration\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_evb_fail\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_evb_pressure\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_brake_pressure\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_brake_pressure_spd\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
