.TH "apollo::canbus::Sonar" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::Sonar
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkTranslationFieldNumber\fP = 2, \fBkRotationFieldNumber\fP = 3, \fBkRangeFieldNumber\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBSonar\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBSonar\fP (const \fBSonar\fP &from)"
.br
.ti -1c
.RI "\fBSonar\fP (\fBSonar\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBSonar\fP & \fBoperator=\fP (const \fBSonar\fP &from)"
.br
.ti -1c
.RI "\fBSonar\fP & \fBoperator=\fP (\fBSonar\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBSonar\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBSonar\fP *other)"
.br
.ti -1c
.RI "\fBSonar\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBSonar\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBSonar\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_translation\fP () const"
.br
.ti -1c
.RI "void \fBclear_translation\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Point3D\fP & \fBtranslation\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Point3D\fP * \fBrelease_translation\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBmutable_translation\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_translation\fP (::\fBapollo::common::Point3D\fP *translation)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_translation\fP (::\fBapollo::common::Point3D\fP *translation)"
.br
.ti -1c
.RI "::\fBapollo::common::Point3D\fP * \fBunsafe_arena_release_translation\fP ()"
.br
.ti -1c
.RI "bool \fBhas_rotation\fP () const"
.br
.ti -1c
.RI "void \fBclear_rotation\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::Quaternion\fP & \fBrotation\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::common::Quaternion\fP * \fBrelease_rotation\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::Quaternion\fP * \fBmutable_rotation\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_rotation\fP (::\fBapollo::common::Quaternion\fP *rotation)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_rotation\fP (::\fBapollo::common::Quaternion\fP *rotation)"
.br
.ti -1c
.RI "::\fBapollo::common::Quaternion\fP * \fBunsafe_arena_release_rotation\fP ()"
.br
.ti -1c
.RI "bool \fBhas_range\fP () const"
.br
.ti -1c
.RI "void \fBclear_range\fP ()"
.br
.ti -1c
.RI "double \fBrange\fP () const"
.br
.ti -1c
.RI "void \fBset_range\fP (double value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBSonar\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBSonar\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSonar\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fchassis_5fmsgs_2fchassis_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBSonar\fP &a, \fBSonar\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::canbus::Sonar::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Sonar::MergeImpl
}
.fi
.SS "constexpr int apollo::canbus::Sonar::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    3
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
