.TH "apollo::cyber::transport::IntraTranceiverTest" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::IntraTranceiverTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Protected Types"

.in +1c
.ti -1c
.RI "using \fBTransmitterPtr\fP = std::shared_ptr< \fBTransmitter\fP< \fBproto::UnitTest\fP > >"
.br
.ti -1c
.RI "using \fBReceiverPtr\fP = std::shared_ptr< \fBReceiver\fP< \fBproto::UnitTest\fP > >"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBchannel_name_\fP"
.br
.ti -1c
.RI "TransmitterPtr \fBtransmitter_a_\fP = nullptr"
.br
.ti -1c
.RI "TransmitterPtr \fBtransmitter_b_\fP = nullptr"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
