.TH "apollo::cyber::record::Recorder" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::record::Recorder
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::enable_shared_from_this< Recorder >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRecorder\fP (const std::string &output, bool all_channels, const std::vector< std::string > &white_channels, const std::vector< std::string > &black_channels)"
.br
.ti -1c
.RI "\fBRecorder\fP (const std::string &output, bool all_channels, const std::vector< std::string > &white_channels, const std::vector< std::string > &black_channels, const \fBproto::Header\fP &header)"
.br
.ti -1c
.RI "bool \fBStart\fP ()"
.br
.ti -1c
.RI "bool \fBStop\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
