.TH "apollo::drivers::Mobileye::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Mobileye::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBMobileye\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::common::Header\fP & \fBheader\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_header\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Aftermarket_669\fP & \fBaftermarket_669\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_aftermarket_669\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Details_737\fP & \fBdetails_737\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_details_737\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Details_738\fP & \fBdetails_738\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_details_738\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Lka_766\fP & \fBlka_766\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lka_766\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Lka_767\fP & \fBlka_767\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lka_767\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Lka_768\fP & \fBlka_768\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lka_768\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Lka_769\fP & \fBlka_769\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_lka_769\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Reference_76a\fP & \fBreference_76a\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_reference_76a\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::Num_76b\fP & \fBnum_76b\fP (const \fBMobileye\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_num_76b\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
