.TH "apollo::cyber::transport::IntraReceiver< M >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::transport::IntraReceiver< M >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::transport::Receiver< M >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraReceiver\fP (const RoleAttributes &attr, const typename \fBReceiver\fP< M >::MessageListener &msg_listener)"
.br
.ti -1c
.RI "void \fBEnable\fP () override"
.br
.ti -1c
.RI "void \fBDisable\fP () override"
.br
.ti -1c
.RI "void \fBEnable\fP (const RoleAttributes &opposite_attr) override"
.br
.ti -1c
.RI "void \fBDisable\fP (const RoleAttributes &opposite_attr) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
