.TH "apollo::cyber::data::DataVisitor< M0, M1, NullType, NullType >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::data::DataVisitor< M0, M1, NullType, NullType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::data::DataVisitorBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataVisitor\fP (const std::vector< \fBVisitorConfig\fP > &configs)"
.br
.ti -1c
.RI "bool \fBTryFetch\fP (std::shared_ptr< M0 > &m0, std::shared_ptr< M1 > &m1)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
