.TH "apollo::planning_internal::SLFrameDebug" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning_internal::SLFrameDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkSampledSFieldNumber\fP = 2, \fBkStaticObstacleLowerBoundFieldNumber\fP = 3, \fBkDynamicObstacleLowerBoundFieldNumber\fP = 4, \fBkStaticObstacleUpperBoundFieldNumber\fP = 5, \fBkDynamicObstacleUpperBoundFieldNumber\fP = 6, \fBkMapLowerBoundFieldNumber\fP = 7, \fBkMapUpperBoundFieldNumber\fP = 8, \fBkSlPathFieldNumber\fP = 9, \fBkAggregatedBoundarySFieldNumber\fP = 10, \fBkAggregatedBoundaryLowFieldNumber\fP = 11, \fBkAggregatedBoundaryHighFieldNumber\fP = 12, \fBkNameFieldNumber\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBSLFrameDebug\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBSLFrameDebug\fP (const \fBSLFrameDebug\fP &from)"
.br
.ti -1c
.RI "\fBSLFrameDebug\fP (\fBSLFrameDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBSLFrameDebug\fP & \fBoperator=\fP (const \fBSLFrameDebug\fP &from)"
.br
.ti -1c
.RI "\fBSLFrameDebug\fP & \fBoperator=\fP (\fBSLFrameDebug\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBSLFrameDebug\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBSLFrameDebug\fP *other)"
.br
.ti -1c
.RI "\fBSLFrameDebug\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBSLFrameDebug\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBSLFrameDebug\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "int \fBsampled_s_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_sampled_s\fP ()"
.br
.ti -1c
.RI "double \fBsampled_s\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_sampled_s\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_sampled_s\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBsampled_s\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_sampled_s\fP ()"
.br
.ti -1c
.RI "int \fBstatic_obstacle_lower_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_static_obstacle_lower_bound\fP ()"
.br
.ti -1c
.RI "double \fBstatic_obstacle_lower_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_static_obstacle_lower_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_static_obstacle_lower_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBstatic_obstacle_lower_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_static_obstacle_lower_bound\fP ()"
.br
.ti -1c
.RI "int \fBdynamic_obstacle_lower_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_dynamic_obstacle_lower_bound\fP ()"
.br
.ti -1c
.RI "double \fBdynamic_obstacle_lower_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_dynamic_obstacle_lower_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_dynamic_obstacle_lower_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBdynamic_obstacle_lower_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_dynamic_obstacle_lower_bound\fP ()"
.br
.ti -1c
.RI "int \fBstatic_obstacle_upper_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_static_obstacle_upper_bound\fP ()"
.br
.ti -1c
.RI "double \fBstatic_obstacle_upper_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_static_obstacle_upper_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_static_obstacle_upper_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBstatic_obstacle_upper_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_static_obstacle_upper_bound\fP ()"
.br
.ti -1c
.RI "int \fBdynamic_obstacle_upper_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_dynamic_obstacle_upper_bound\fP ()"
.br
.ti -1c
.RI "double \fBdynamic_obstacle_upper_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_dynamic_obstacle_upper_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_dynamic_obstacle_upper_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBdynamic_obstacle_upper_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_dynamic_obstacle_upper_bound\fP ()"
.br
.ti -1c
.RI "int \fBmap_lower_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_map_lower_bound\fP ()"
.br
.ti -1c
.RI "double \fBmap_lower_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_map_lower_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_map_lower_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBmap_lower_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_map_lower_bound\fP ()"
.br
.ti -1c
.RI "int \fBmap_upper_bound_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_map_upper_bound\fP ()"
.br
.ti -1c
.RI "double \fBmap_upper_bound\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_map_upper_bound\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_map_upper_bound\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBmap_upper_bound\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_map_upper_bound\fP ()"
.br
.ti -1c
.RI "int \fBsl_path_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_sl_path\fP ()"
.br
.ti -1c
.RI "::\fBapollo::common::SLPoint\fP * \fBmutable_sl_path\fP (int index)"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SLPoint\fP > * \fBmutable_sl_path\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::common::SLPoint\fP & \fBsl_path\fP (int index) const"
.br
.ti -1c
.RI "::\fBapollo::common::SLPoint\fP * \fBadd_sl_path\fP ()"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::\fBapollo::common::SLPoint\fP > & \fBsl_path\fP () const"
.br
.ti -1c
.RI "int \fBaggregated_boundary_s_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_aggregated_boundary_s\fP ()"
.br
.ti -1c
.RI "double \fBaggregated_boundary_s\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_aggregated_boundary_s\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_aggregated_boundary_s\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBaggregated_boundary_s\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_aggregated_boundary_s\fP ()"
.br
.ti -1c
.RI "int \fBaggregated_boundary_low_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_aggregated_boundary_low\fP ()"
.br
.ti -1c
.RI "double \fBaggregated_boundary_low\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_aggregated_boundary_low\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_aggregated_boundary_low\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBaggregated_boundary_low\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_aggregated_boundary_low\fP ()"
.br
.ti -1c
.RI "int \fBaggregated_boundary_high_size\fP () const"
.br
.ti -1c
.RI "void \fBclear_aggregated_boundary_high\fP ()"
.br
.ti -1c
.RI "double \fBaggregated_boundary_high\fP (int index) const"
.br
.ti -1c
.RI "void \fBset_aggregated_boundary_high\fP (int index, double value)"
.br
.ti -1c
.RI "void \fBadd_aggregated_boundary_high\fP (double value)"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > & \fBaggregated_boundary_high\fP () const"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::RepeatedField< double > * \fBmutable_aggregated_boundary_high\fP ()"
.br
.ti -1c
.RI "bool \fBhas_name\fP () const"
.br
.ti -1c
.RI "void \fBclear_name\fP ()"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "template<typename ArgT0  = const std::string&, typename\&.\&.\&. ArgT> void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.ti -1c
.RI "std::string * \fBmutable_name\fP ()"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD std::string * \fBrelease_name\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_name\fP (std::string *name)"
.br
.ti -1c
.RI "template<typename ArgT0 , typename\&.\&.\&. ArgT> PROTOBUF_ALWAYS_INLINE void \fBset_name\fP (ArgT0 &&arg0, ArgT\&.\&.\&. args)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBSLFrameDebug\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBSLFrameDebug\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSLFrameDebug\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fplanning_5fmsgs_2fplanning_5finternal_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBSLFrameDebug\fP &a, \fBSLFrameDebug\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::planning_internal::SLFrameDebug::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SLFrameDebug::MergeImpl
}
.fi
.SS "constexpr int apollo::planning_internal::SLFrameDebug::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    3
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
