.TH "apollo::cyber::proto::CyberConfig::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::CyberConfig::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBCyberConfig\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::SchedulerConf\fP & \fBscheduler_conf\fP (const \fBCyberConfig\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_scheduler_conf\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::TransportConf\fP & \fBtransport_conf\fP (const \fBCyberConfig\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_transport_conf\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::RunModeConf\fP & \fBrun_mode_conf\fP (const \fBCyberConfig\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_run_mode_conf\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::cyber::proto::PerfConf\fP & \fBperf_conf\fP (const \fBCyberConfig\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_perf_conf\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
