.TH "apollo::drivers::RadarObstacle::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::RadarObstacle::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBRadarObstacle\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_id\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point2D\fP & \fBrelative_position\fP (const \fBRadarObstacle\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_relative_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point2D\fP & \fBrelative_velocity\fP (const \fBRadarObstacle\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_relative_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_rcs\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_moving_status\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_width\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_length\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_height\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_theta\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point2D\fP & \fBabsolute_position\fP (const \fBRadarObstacle\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_absolute_position\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::common::Point2D\fP & \fBabsolute_velocity\fP (const \fBRadarObstacle\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_absolute_velocity\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_count\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_moving_frames_count\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_status\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
