.TH "apollo::cyber::proto::ChangeMsg" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::proto::ChangeMsg
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkRoleAttrFieldNumber\fP = 5, \fBkTimestampFieldNumber\fP = 1, \fBkRoleTypeFieldNumber\fP = 4, \fBkChangeTypeFieldNumber\fP = 2, \fBkOperateTypeFieldNumber\fP = 3 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBChangeMsg\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBChangeMsg\fP (const \fBChangeMsg\fP &from)"
.br
.ti -1c
.RI "\fBChangeMsg\fP (\fBChangeMsg\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBChangeMsg\fP & \fBoperator=\fP (const \fBChangeMsg\fP &from)"
.br
.ti -1c
.RI "\fBChangeMsg\fP & \fBoperator=\fP (\fBChangeMsg\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBChangeMsg\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBChangeMsg\fP *other)"
.br
.ti -1c
.RI "\fBChangeMsg\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBChangeMsg\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBChangeMsg\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_role_attr\fP () const"
.br
.ti -1c
.RI "void \fBclear_role_attr\fP ()"
.br
.ti -1c
.RI "const ::\fBapollo::cyber::proto::RoleAttributes\fP & \fBrole_attr\fP () const"
.br
.ti -1c
.RI "PROTOBUF_NODISCARD ::\fBapollo::cyber::proto::RoleAttributes\fP * \fBrelease_role_attr\fP ()"
.br
.ti -1c
.RI "::\fBapollo::cyber::proto::RoleAttributes\fP * \fBmutable_role_attr\fP ()"
.br
.ti -1c
.RI "void \fBset_allocated_role_attr\fP (::\fBapollo::cyber::proto::RoleAttributes\fP *role_attr)"
.br
.ti -1c
.RI "void \fBunsafe_arena_set_allocated_role_attr\fP (::\fBapollo::cyber::proto::RoleAttributes\fP *role_attr)"
.br
.ti -1c
.RI "::\fBapollo::cyber::proto::RoleAttributes\fP * \fBunsafe_arena_release_role_attr\fP ()"
.br
.ti -1c
.RI "bool \fBhas_timestamp\fP () const"
.br
.ti -1c
.RI "void \fBclear_timestamp\fP ()"
.br
.ti -1c
.RI "uint64_t \fBtimestamp\fP () const"
.br
.ti -1c
.RI "void \fBset_timestamp\fP (uint64_t value)"
.br
.ti -1c
.RI "bool \fBhas_role_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_role_type\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::RoleType \fBrole_type\fP () const"
.br
.ti -1c
.RI "void \fBset_role_type\fP (::apollo::cyber::proto::RoleType value)"
.br
.ti -1c
.RI "bool \fBhas_change_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_change_type\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::ChangeType \fBchange_type\fP () const"
.br
.ti -1c
.RI "void \fBset_change_type\fP (::apollo::cyber::proto::ChangeType value)"
.br
.ti -1c
.RI "bool \fBhas_operate_type\fP () const"
.br
.ti -1c
.RI "void \fBclear_operate_type\fP ()"
.br
.ti -1c
.RI "::apollo::cyber::proto::OperateType \fBoperate_type\fP () const"
.br
.ti -1c
.RI "void \fBset_operate_type\fP (::apollo::cyber::proto::OperateType value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBChangeMsg\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBChangeMsg\fP * \fBinternal_default_instance\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeMsg\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_cyber_2fproto_2ftopology_5fchange_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBChangeMsg\fP &a, \fBChangeMsg\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::cyber::proto::ChangeMsg::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ChangeMsg::MergeImpl
}
.fi
.SS "constexpr int apollo::cyber::proto::ChangeMsg::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    0
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
