.TH "apollo::drivers::LdwLane::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::LdwLane::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBLdwLane\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_width\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_quality\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_style\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::LdwLaneBoundary\fP & \fBleft_boundary\fP (const \fBLdwLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_left_boundary\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static const ::\fBapollo::drivers::LdwLaneBoundary\fP & \fBright_boundary\fP (const \fBLdwLane\fP *msg)"
.br
.ti -1c
.RI "static void \fBset_has_right_boundary\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
