.TH "apollo::drivers::Vehicle4_5f3" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Vehicle4_5f3
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkCanRxFacTgtRangeR2MFieldNumber\fP = 1, \fBkCanRxFacTgtRangeM2TFieldNumber\fP = 2, \fBkCanRxFacTgtRange1FieldNumber\fP = 3, \fBkCanRxFacTgtMtgSpaceVerFieldNumber\fP = 4, \fBkCanRxFacTgtMtgSpaceHorFieldNumber\fP = 5, \fBkCanRxFacTgtMtgOffsetFieldNumber\fP = 6, \fBkCanRxFacAlignSampReqFieldNumber\fP = 7, \fBkCanRxFacAlignMaxNtFieldNumber\fP = 8, \fBkCanRxFacAlignCmd2FieldNumber\fP = 9, \fBkCanRxFacAlignCmd1FieldNumber\fP = 10 }"
.br
.ti -1c
.RI "typedef Vehicle4_5f3_Can_rx_fac_align_cmd_2Type \fBCan_rx_fac_align_cmd_2Type\fP"
.br
.ti -1c
.RI "typedef Vehicle4_5f3_Can_rx_fac_align_cmd_1Type \fBCan_rx_fac_align_cmd_1Type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBVehicle4_5f3\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBVehicle4_5f3\fP (const \fBVehicle4_5f3\fP &from)"
.br
.ti -1c
.RI "\fBVehicle4_5f3\fP (\fBVehicle4_5f3\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBVehicle4_5f3\fP & \fBoperator=\fP (const \fBVehicle4_5f3\fP &from)"
.br
.ti -1c
.RI "\fBVehicle4_5f3\fP & \fBoperator=\fP (\fBVehicle4_5f3\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBVehicle4_5f3\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBVehicle4_5f3\fP *other)"
.br
.ti -1c
.RI "\fBVehicle4_5f3\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBVehicle4_5f3\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBVehicle4_5f3\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_range_r2m\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_range_r2m\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_fac_tgt_range_r2m\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_range_r2m\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_range_m2t\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_range_m2t\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_fac_tgt_range_m2t\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_range_m2t\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_range_1\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_range_1\fP ()"
.br
.ti -1c
.RI "double \fBcan_rx_fac_tgt_range_1\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_range_1\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_mtg_space_ver\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_mtg_space_ver\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_fac_tgt_mtg_space_ver\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_mtg_space_ver\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_mtg_space_hor\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_mtg_space_hor\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_fac_tgt_mtg_space_hor\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_mtg_space_hor\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_tgt_mtg_offset\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_tgt_mtg_offset\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_fac_tgt_mtg_offset\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_tgt_mtg_offset\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_align_samp_req\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_align_samp_req\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_fac_align_samp_req\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_align_samp_req\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_align_max_nt\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_align_max_nt\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_rx_fac_align_max_nt\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_align_max_nt\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_align_cmd_2\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_align_cmd_2\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Vehicle4_5f3_Can_rx_fac_align_cmd_2Type \fBcan_rx_fac_align_cmd_2\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_align_cmd_2\fP (::apollo::drivers::Vehicle4_5f3_Can_rx_fac_align_cmd_2Type value)"
.br
.ti -1c
.RI "bool \fBhas_can_rx_fac_align_cmd_1\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_rx_fac_align_cmd_1\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Vehicle4_5f3_Can_rx_fac_align_cmd_1Type \fBcan_rx_fac_align_cmd_1\fP () const"
.br
.ti -1c
.RI "void \fBset_can_rx_fac_align_cmd_1\fP (::apollo::drivers::Vehicle4_5f3_Can_rx_fac_align_cmd_1Type value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBVehicle4_5f3\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBVehicle4_5f3\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBCan_rx_fac_align_cmd_2Type_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_rx_fac_align_cmd_2Type_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_rx_fac_align_cmd_2Type_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_rx_fac_align_cmd_2Type_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_rx_fac_align_cmd_2Type *value)"
.br
.ti -1c
.RI "static bool \fBCan_rx_fac_align_cmd_1Type_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_rx_fac_align_cmd_1Type_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_rx_fac_align_cmd_1Type_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_rx_fac_align_cmd_1Type_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_rx_fac_align_cmd_1Type *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_2Type \fBCAN_RX_FAC_ALIGN_CMD_2_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_2Type \fBCAN_RX_FAC_ALIGN_CMD_2_ON\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_2Type \fBCan_rx_fac_align_cmd_2Type_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_2Type \fBCan_rx_fac_align_cmd_2Type_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_rx_fac_align_cmd_2Type_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_1Type \fBCAN_RX_FAC_ALIGN_CMD_1_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_1Type \fBCAN_RX_FAC_ALIGN_CMD_1_ON\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_1Type \fBCan_rx_fac_align_cmd_1Type_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_rx_fac_align_cmd_1Type \fBCan_rx_fac_align_cmd_1Type_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_rx_fac_align_cmd_1Type_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBVehicle4_5f3\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBVehicle4_5f3\fP &a, \fBVehicle4_5f3\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Vehicle4_5f3::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Vehicle4_5f3::MergeImpl
}
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_1Type apollo::drivers::Vehicle4_5f3::CAN_RX_FAC_ALIGN_CMD_1_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_1Type_CAN_RX_FAC_ALIGN_CMD_1_OFF
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_1Type apollo::drivers::Vehicle4_5f3::CAN_RX_FAC_ALIGN_CMD_1_ON\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_1Type_CAN_RX_FAC_ALIGN_CMD_1_ON
.fi
.SS "constexpr int apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_1Type_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_1Type_Can_rx_fac_align_cmd_1Type_ARRAYSIZE
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_1Type apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_1Type_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_1Type_Can_rx_fac_align_cmd_1Type_MAX
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_1Type apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_1Type_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_1Type_Can_rx_fac_align_cmd_1Type_MIN
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_2Type apollo::drivers::Vehicle4_5f3::CAN_RX_FAC_ALIGN_CMD_2_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_2Type_CAN_RX_FAC_ALIGN_CMD_2_OFF
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_2Type apollo::drivers::Vehicle4_5f3::CAN_RX_FAC_ALIGN_CMD_2_ON\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_2Type_CAN_RX_FAC_ALIGN_CMD_2_ON
.fi
.SS "constexpr int apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_2Type_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_2Type_Can_rx_fac_align_cmd_2Type_ARRAYSIZE
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_2Type apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_2Type_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_2Type_Can_rx_fac_align_cmd_2Type_MAX
.fi
.SS "constexpr Vehicle4_5f3_Can_rx_fac_align_cmd_2Type apollo::drivers::Vehicle4_5f3::Can_rx_fac_align_cmd_2Type_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Vehicle4_5f3_Can_rx_fac_align_cmd_2Type_Can_rx_fac_align_cmd_2Type_MIN
.fi
.SS "constexpr int apollo::drivers::Vehicle4_5f3::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    20
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
