.TH "apollo::canbus::ChassisGPS::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::canbus::ChassisGPS::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBHasBits\fP = decltype(std::declval< \fBChassisGPS\fP >()\&._has_bits_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_has_latitude\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_longitude\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_gps_valid\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_year\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_month\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_day\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_hours\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_minutes\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_seconds\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_compass_direction\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_pdop\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_gps_fault\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_is_inferred\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_altitude\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_heading\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_hdop\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_vdop\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_quality\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_num_satellites\fP (HasBits *has_bits)"
.br
.ti -1c
.RI "static void \fBset_has_gps_speed\fP (HasBits *has_bits)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
