.TH "apollo::cyber::base::ThreadSafeQueue< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::cyber::base::ThreadSafeQueue< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadSafeQueue\fP & \fBoperator=\fP (const \fBThreadSafeQueue\fP &other)=delete"
.br
.ti -1c
.RI "\fBThreadSafeQueue\fP (const \fBThreadSafeQueue\fP &other)=delete"
.br
.ti -1c
.RI "void \fBEnqueue\fP (const T &element)"
.br
.ti -1c
.RI "bool \fBDequeue\fP (T *element)"
.br
.ti -1c
.RI "bool \fBWaitDequeue\fP (T *element)"
.br
.ti -1c
.RI "std::queue< T >::size_type \fBSize\fP ()"
.br
.ti -1c
.RI "bool \fBEmpty\fP ()"
.br
.ti -1c
.RI "void \fBBreakAllWait\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
