.TH "apollo::drivers::Esr_status6_5e5" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::drivers::Esr_status6_5e5
.SH SYNOPSIS
.br
.PP
.PP
Inherits PROTOBUF_NAMESPACE_ID::Message\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_Internal\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum : int { \fBkCanTxSwVersionDsp3RdByteFieldNumber\fP = 1, \fBkCanTxVerticalAlignUpdatedFieldNumber\fP = 2, \fBkCanTxVerticalMisalignmentFieldNumber\fP = 3, \fBkCanTxServAlignUpdatesDoneFieldNumber\fP = 4, \fBkCanTxFoundTargetFieldNumber\fP = 5, \fBkCanTxFactoryMisalignmentFieldNumber\fP = 6, \fBkCanTxFactoryAlignStatus2FieldNumber\fP = 7, \fBkCanTxFactoryAlignStatus1FieldNumber\fP = 8, \fBkCanTxRecommendUnconvergeFieldNumber\fP = 9, \fBkCanTxWaveDiffA2DFieldNumber\fP = 10, \fBkCanTxSystemPowerModeFieldNumber\fP = 11, \fBkCanTxSupplyN5VA2DFieldNumber\fP = 12, \fBkCanTxSupply1P8VA2DFieldNumber\fP = 13 }"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_vertical_align_updatedType \fBCan_tx_vertical_align_updatedType\fP"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_found_targetType \fBCan_tx_found_targetType\fP"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_factory_align_status_2Type \fBCan_tx_factory_align_status_2Type\fP"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_factory_align_status_1Type \fBCan_tx_factory_align_status_1Type\fP"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_recommend_unconvergeType \fBCan_tx_recommend_unconvergeType\fP"
.br
.ti -1c
.RI "typedef Esr_status6_5e5_Can_tx_system_power_modeType \fBCan_tx_system_power_modeType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBEsr_status6_5e5\fP (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)"
.br
.ti -1c
.RI "\fBEsr_status6_5e5\fP (const \fBEsr_status6_5e5\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status6_5e5\fP (\fBEsr_status6_5e5\fP &&from) noexcept"
.br
.ti -1c
.RI "\fBEsr_status6_5e5\fP & \fBoperator=\fP (const \fBEsr_status6_5e5\fP &from)"
.br
.ti -1c
.RI "\fBEsr_status6_5e5\fP & \fBoperator=\fP (\fBEsr_status6_5e5\fP &&from) noexcept"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet & \fBunknown_fields\fP () const"
.br
.ti -1c
.RI "inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet * \fBmutable_unknown_fields\fP ()"
.br
.ti -1c
.RI "void \fBSwap\fP (\fBEsr_status6_5e5\fP *other)"
.br
.ti -1c
.RI "void \fBUnsafeArenaSwap\fP (\fBEsr_status6_5e5\fP *other)"
.br
.ti -1c
.RI "\fBEsr_status6_5e5\fP * \fBNew\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (const \fBEsr_status6_5e5\fP &from)"
.br
.ti -1c
.RI "void \fBMergeFrom\fP (const \fBEsr_status6_5e5\fP &from)"
.br
.ti -1c
.RI "PROTOBUF_ATTRIBUTE_REINITIALIZES void \fBClear\fP () final"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP () const final"
.br
.ti -1c
.RI "size_t \fBByteSizeLong\fP () const final"
.br
.ti -1c
.RI "const char * \fB_InternalParse\fP (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final"
.br
.ti -1c
.RI "uint8_t * \fB_InternalSerialize\fP (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final"
.br
.ti -1c
.RI "int \fBGetCachedSize\fP () const final"
.br
.ti -1c
.RI "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * \fBGetClassData\fP () const final"
.br
.ti -1c
.RI "::PROTOBUF_NAMESPACE_ID::Metadata \fBGetMetadata\fP () const final"
.br
.ti -1c
.RI "bool \fBhas_can_tx_sw_version_dsp_3rd_byte\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_sw_version_dsp_3rd_byte\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_sw_version_dsp_3rd_byte\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_sw_version_dsp_3rd_byte\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_vertical_align_updated\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_vertical_align_updated\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_vertical_align_updatedType \fBcan_tx_vertical_align_updated\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_vertical_align_updated\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_vertical_align_updatedType value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_vertical_misalignment\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_vertical_misalignment\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_vertical_misalignment\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_vertical_misalignment\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_serv_align_updates_done\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_serv_align_updates_done\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_serv_align_updates_done\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_serv_align_updates_done\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_found_target\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_found_target\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_found_targetType \fBcan_tx_found_target\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_found_target\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_found_targetType value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_factory_misalignment\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_factory_misalignment\fP ()"
.br
.ti -1c
.RI "double \fBcan_tx_factory_misalignment\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_factory_misalignment\fP (double value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_factory_align_status_2\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_factory_align_status_2\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_factory_align_status_2Type \fBcan_tx_factory_align_status_2\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_factory_align_status_2\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_factory_align_status_2Type value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_factory_align_status_1\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_factory_align_status_1\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_factory_align_status_1Type \fBcan_tx_factory_align_status_1\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_factory_align_status_1\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_factory_align_status_1Type value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_recommend_unconverge\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_recommend_unconverge\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_recommend_unconvergeType \fBcan_tx_recommend_unconverge\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_recommend_unconverge\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_recommend_unconvergeType value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_wave_diff_a2d\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_wave_diff_a2d\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_wave_diff_a2d\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_wave_diff_a2d\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_system_power_mode\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_system_power_mode\fP ()"
.br
.ti -1c
.RI "::apollo::drivers::Esr_status6_5e5_Can_tx_system_power_modeType \fBcan_tx_system_power_mode\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_system_power_mode\fP (::apollo::drivers::Esr_status6_5e5_Can_tx_system_power_modeType value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_supply_n5v_a2d\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_supply_n5v_a2d\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_supply_n5v_a2d\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_supply_n5v_a2d\fP (int32_t value)"
.br
.ti -1c
.RI "bool \fBhas_can_tx_supply_1p8v_a2d\fP () const"
.br
.ti -1c
.RI "void \fBclear_can_tx_supply_1p8v_a2d\fP ()"
.br
.ti -1c
.RI "int32_t \fBcan_tx_supply_1p8v_a2d\fP () const"
.br
.ti -1c
.RI "void \fBset_can_tx_supply_1p8v_a2d\fP (int32_t value)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBdescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Descriptor * \fBGetDescriptor\fP ()"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::Reflection * \fBGetReflection\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status6_5e5\fP & \fBdefault_instance\fP ()"
.br
.ti -1c
.RI "static const \fBEsr_status6_5e5\fP * \fBinternal_default_instance\fP ()"
.br
.ti -1c
.RI "static bool \fBCan_tx_vertical_align_updatedType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_vertical_align_updatedType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_vertical_align_updatedType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_vertical_align_updatedType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_vertical_align_updatedType *value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_found_targetType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_found_targetType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_found_targetType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_found_targetType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_found_targetType *value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_factory_align_status_2Type_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_factory_align_status_2Type_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_factory_align_status_2Type_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_factory_align_status_2Type_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_factory_align_status_2Type *value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_factory_align_status_1Type_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_factory_align_status_1Type_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_factory_align_status_1Type_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_factory_align_status_1Type_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_factory_align_status_1Type *value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_recommend_unconvergeType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_recommend_unconvergeType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_recommend_unconvergeType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_recommend_unconvergeType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_recommend_unconvergeType *value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_system_power_modeType_IsValid\fP (int value)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor * \fBCan_tx_system_power_modeType_descriptor\fP ()"
.br
.ti -1c
.RI "template<typename T > static const std::string & \fBCan_tx_system_power_modeType_Name\fP (T enum_t_value)"
.br
.ti -1c
.RI "static bool \fBCan_tx_system_power_modeType_Parse\fP (::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Can_tx_system_power_modeType *value)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBkIndexInFileMessages\fP"
.br
.ti -1c
.RI "static const ClassData \fB_class_data_\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_vertical_align_updatedType \fBCAN_TX_VERTICAL_ALIGN_UPDATED_NOT_UPDATED\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_vertical_align_updatedType \fBCAN_TX_VERTICAL_ALIGN_UPDATED_UPDATED\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_vertical_align_updatedType \fBCan_tx_vertical_align_updatedType_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_vertical_align_updatedType \fBCan_tx_vertical_align_updatedType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_vertical_align_updatedType_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_found_targetType \fBCAN_TX_FOUND_TARGET_NOT_FOUND\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_found_targetType \fBCAN_TX_FOUND_TARGET_FOUND\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_found_targetType \fBCan_tx_found_targetType_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_found_targetType \fBCan_tx_found_targetType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_found_targetType_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_BUSY\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_SUCCESS\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_NO_TARGET\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_DEV_TOO_LARGE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_VAR_TOO_LARGE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCan_tx_factory_align_status_2Type_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_2Type \fBCan_tx_factory_align_status_2Type_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_factory_align_status_2Type_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_BUSY\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_SUCCESS\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_NO_TARGET\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_DEV_TOO_LARGE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_VAR_TOO_LARGE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCan_tx_factory_align_status_1Type_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_factory_align_status_1Type \fBCan_tx_factory_align_status_1Type_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_factory_align_status_1Type_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_recommend_unconvergeType \fBCAN_TX_RECOMMEND_UNCONVERGE_NOT_RECOMMEND\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_recommend_unconvergeType \fBCAN_TX_RECOMMEND_UNCONVERGE_RECOMMEND\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_recommend_unconvergeType \fBCan_tx_recommend_unconvergeType_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_recommend_unconvergeType \fBCan_tx_recommend_unconvergeType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_recommend_unconvergeType_ARRAYSIZE\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_DSP_INIT\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_RADIATE_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_RADIATE_ON\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_DSP_SHUTDOWN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_DSP_OFF\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_HOST_SHUTDOWN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_TEST\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCAN_TX_SYSTEM_POWER_MODE_7INVALID\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCan_tx_system_power_modeType_MIN\fP"
.br
.ti -1c
.RI "static constexpr Can_tx_system_power_modeType \fBCan_tx_system_power_modeType_MAX\fP"
.br
.ti -1c
.RI "static constexpr int \fBCan_tx_system_power_modeType_ARRAYSIZE\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBEsr_status6_5e5\fP (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata\fP"
.br
.ti -1c
.RI "template<typename T > class \fB::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper\fP"
.br
.ti -1c
.RI "struct \fB::TableStruct_modules_2fcommon_5fmsgs_2fsensor_5fmsgs_2fdelphi_5fesr_2eproto\fP"
.br
.ti -1c
.RI "void \fBswap\fP (\fBEsr_status6_5e5\fP &a, \fBEsr_status6_5e5\fP &b)"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const ::PROTOBUF_NAMESPACE_ID::Message::ClassData apollo::drivers::Esr_status6_5e5::_class_data_\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Esr_status6_5e5::MergeImpl
}
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_BUSY\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_BUSY
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_DEV_TOO_LARGE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_DEV_TOO_LARGE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_NO_TARGET\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_NO_TARGET
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_VAR_TOO_LARGE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_FAIL_VAR_TOO_LARGE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_OFF
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_1_SUCCESS\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_CAN_TX_FACTORY_ALIGN_STATUS_1_SUCCESS
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_1Type_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_Can_tx_factory_align_status_1Type_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_1Type_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_Can_tx_factory_align_status_1Type_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_1Type apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_1Type_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_1Type_Can_tx_factory_align_status_1Type_MIN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_BUSY\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_BUSY
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_DEV_TOO_LARGE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_DEV_TOO_LARGE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_NO_TARGET\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_NO_TARGET
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_VAR_TOO_LARGE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_FAIL_VAR_TOO_LARGE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_OFF
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::CAN_TX_FACTORY_ALIGN_STATUS_2_SUCCESS\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_CAN_TX_FACTORY_ALIGN_STATUS_2_SUCCESS
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_2Type_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_Can_tx_factory_align_status_2Type_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_2Type_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_Can_tx_factory_align_status_2Type_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_factory_align_status_2Type apollo::drivers::Esr_status6_5e5::Can_tx_factory_align_status_2Type_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_factory_align_status_2Type_Can_tx_factory_align_status_2Type_MIN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_found_targetType apollo::drivers::Esr_status6_5e5::CAN_TX_FOUND_TARGET_FOUND\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_found_targetType_CAN_TX_FOUND_TARGET_FOUND
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_found_targetType apollo::drivers::Esr_status6_5e5::CAN_TX_FOUND_TARGET_NOT_FOUND\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_found_targetType_CAN_TX_FOUND_TARGET_NOT_FOUND
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_found_targetType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_found_targetType_Can_tx_found_targetType_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_found_targetType apollo::drivers::Esr_status6_5e5::Can_tx_found_targetType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_found_targetType_Can_tx_found_targetType_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_found_targetType apollo::drivers::Esr_status6_5e5::Can_tx_found_targetType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_found_targetType_Can_tx_found_targetType_MIN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_recommend_unconvergeType apollo::drivers::Esr_status6_5e5::CAN_TX_RECOMMEND_UNCONVERGE_NOT_RECOMMEND\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_recommend_unconvergeType_CAN_TX_RECOMMEND_UNCONVERGE_NOT_RECOMMEND
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_recommend_unconvergeType apollo::drivers::Esr_status6_5e5::CAN_TX_RECOMMEND_UNCONVERGE_RECOMMEND\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_recommend_unconvergeType_CAN_TX_RECOMMEND_UNCONVERGE_RECOMMEND
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_recommend_unconvergeType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_recommend_unconvergeType_Can_tx_recommend_unconvergeType_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_recommend_unconvergeType apollo::drivers::Esr_status6_5e5::Can_tx_recommend_unconvergeType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_recommend_unconvergeType_Can_tx_recommend_unconvergeType_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_recommend_unconvergeType apollo::drivers::Esr_status6_5e5::Can_tx_recommend_unconvergeType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_recommend_unconvergeType_Can_tx_recommend_unconvergeType_MIN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_7INVALID\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_7INVALID
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_DSP_INIT\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_DSP_INIT
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_DSP_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_DSP_OFF
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_DSP_SHUTDOWN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_DSP_SHUTDOWN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_HOST_SHUTDOWN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_HOST_SHUTDOWN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_RADIATE_OFF\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_RADIATE_OFF
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_RADIATE_ON\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_RADIATE_ON
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::CAN_TX_SYSTEM_POWER_MODE_TEST\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_CAN_TX_SYSTEM_POWER_MODE_TEST
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_system_power_modeType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_Can_tx_system_power_modeType_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::Can_tx_system_power_modeType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_Can_tx_system_power_modeType_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_system_power_modeType apollo::drivers::Esr_status6_5e5::Can_tx_system_power_modeType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_system_power_modeType_Can_tx_system_power_modeType_MIN
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_vertical_align_updatedType apollo::drivers::Esr_status6_5e5::CAN_TX_VERTICAL_ALIGN_UPDATED_NOT_UPDATED\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_vertical_align_updatedType_CAN_TX_VERTICAL_ALIGN_UPDATED_NOT_UPDATED
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_vertical_align_updatedType apollo::drivers::Esr_status6_5e5::CAN_TX_VERTICAL_ALIGN_UPDATED_UPDATED\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_vertical_align_updatedType_CAN_TX_VERTICAL_ALIGN_UPDATED_UPDATED
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::Can_tx_vertical_align_updatedType_ARRAYSIZE\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_vertical_align_updatedType_Can_tx_vertical_align_updatedType_ARRAYSIZE
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_vertical_align_updatedType apollo::drivers::Esr_status6_5e5::Can_tx_vertical_align_updatedType_MAX\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_vertical_align_updatedType_Can_tx_vertical_align_updatedType_MAX
.fi
.SS "constexpr Esr_status6_5e5_Can_tx_vertical_align_updatedType apollo::drivers::Esr_status6_5e5::Can_tx_vertical_align_updatedType_MIN\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    Esr_status6_5e5_Can_tx_vertical_align_updatedType_Can_tx_vertical_align_updatedType_MIN
.fi
.SS "constexpr int apollo::drivers::Esr_status6_5e5::kIndexInFileMessages\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP
.PP
.nf
=
    1
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
