.TH "apollo::planning::MainDecision::_Internal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apollo::planning::MainDecision::_Internal
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::\fBapollo::planning::MainCruise\fP & \fBcruise\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainStop\fP & \fBstop\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainEmergencyStop\fP & \fBestop\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainChangeLane\fP & \fBchange_lane\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainMissionComplete\fP & \fBmission_complete\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainNotReady\fP & \fBnot_ready\fP (const \fBMainDecision\fP *msg)"
.br
.ti -1c
.RI "static const ::\fBapollo::planning::MainParking\fP & \fBparking\fP (const \fBMainDecision\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
