.TH "third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/resources/AsyncWriterThread.h" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/resources/AsyncWriterThread.h
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include <list>\fP
.br
\fC#include <fastrtps/rtps/resources/AsyncInterestTree\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::AsyncWriterThread\fP"
.br
.RI "This static class owns a thread that manages asynchronous writes\&. Asynchronous writes happen directly (when using an async writer) and indirectly (when responding to a NACK)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBeprosima\fP"
.br
.RI "Maximum payload is maximum of UDP packet size minus 536bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) With those 536 bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) bytes is posible to send RTPS Header plus RTPS Data submessage plus RTPS Heartbeat submessage\&. "
.ti -1c
.RI " \fBeprosima::fastrtps\fP"
.br
.ti -1c
.RI " \fBeprosima::fastrtps::rtps\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
