.TH "Base" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBApple\fP, \fBBanana\fP, \fBCircle\fP, \fBPeach\fP, \fBPear\fP, \fBRect\fP, \fBStar\fP, and \fBTriangle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDoSomething\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
