.TH "BUILTIN_MODULE" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BUILTIN_MODULE \- Builtin Protocols Module
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::BuiltinProtocols\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::ParticipantProxyData\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::ReaderProxyData\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::WriterProxyData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This module contains the general Builtin Protocols\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
