.TH "third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/CacheChange.h" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/CacheChange.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Types\&.h'\fP
.br
\fC#include 'WriteParams\&.h'\fP
.br
\fC#include 'SerializedPayload\&.h'\fP
.br
\fC#include 'Time_t\&.h'\fP
.br
\fC#include 'InstanceHandle\&.h'\fP
.br
\fC#include <fastrtps/rtps/common/FragmentNumber\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::CacheChange_t\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::ChangeForReader_t\fP"
.br
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::ChangeForReaderCmp\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::ChangeFromWriter_t\fP"
.br
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::ChangeFromWriterCmp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBeprosima\fP"
.br
.RI "Maximum payload is maximum of UDP packet size minus 536bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) With those 536 bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) bytes is posible to send RTPS Header plus RTPS Data submessage plus RTPS Heartbeat submessage\&. "
.ti -1c
.RI " \fBeprosima::fastrtps\fP"
.br
.ti -1c
.RI " \fBeprosima::fastrtps::rtps\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBeprosima::fastrtps::rtps::ChangeKind_t\fP { \fBeprosima::fastrtps::rtps::ALIVE\fP, \fBeprosima::fastrtps::rtps::NOT_ALIVE_DISPOSED\fP, \fBeprosima::fastrtps::rtps::NOT_ALIVE_UNREGISTERED\fP, \fBeprosima::fastrtps::rtps::NOT_ALIVE_DISPOSED_UNREGISTERED\fP }"
.br
.ti -1c
.RI "enum \fBChangeFragmentStatus_t\fP { \fBNOT_PRESENT\fP = 0, \fBPRESENT\fP = 1 }"
.br
.ti -1c
.RI "enum \fBeprosima::fastrtps::rtps::ChangeForReaderStatus_t\fP { \fBeprosima::fastrtps::rtps::UNSENT\fP = 0, \fBeprosima::fastrtps::rtps::UNACKNOWLEDGED\fP = 1, \fBeprosima::fastrtps::rtps::REQUESTED\fP = 2, \fBeprosima::fastrtps::rtps::ACKNOWLEDGED\fP = 3, \fBeprosima::fastrtps::rtps::UNDERWAY\fP = 4 }"
.br
.ti -1c
.RI "enum \fBeprosima::fastrtps::rtps::ChangeFromWriterStatus_t\fP { \fBUNKNOWN\fP = 0, \fBMISSING\fP = 1, \fBRECEIVED\fP = 2, \fBLOST\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
