.TH "third_party/fast-rtps-1.5.0-1/include/fastrtps/log/Colors.h" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/include/fastrtps/log/Colors.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBC_DEF\fP   '\\033[m'"
.br
.ti -1c
.RI "#define \fBC_RED\fP   '\\033[31m'"
.br
.ti -1c
.RI "#define \fBC_B_RED\fP   '\\033[31;1m'"
.br
.ti -1c
.RI "#define \fBC_GREEN\fP   '\\033[32m'"
.br
.ti -1c
.RI "#define \fBC_B_GREEN\fP   '\\033[32;1m'"
.br
.ti -1c
.RI "#define \fBC_YELLOW\fP   '\\033[33m'"
.br
.ti -1c
.RI "#define \fBC_B_YELLOW\fP   '\\033[33;1m'"
.br
.ti -1c
.RI "#define \fBC_BLUE\fP   '\\033[34m'"
.br
.ti -1c
.RI "#define \fBC_B_BLUE\fP   '\\033[34;1m'"
.br
.ti -1c
.RI "#define \fBC_MAGENTA\fP   '\\033[35m'"
.br
.ti -1c
.RI "#define \fBC_B_MAGENTA\fP   '\\033[35;1m'"
.br
.ti -1c
.RI "#define \fBC_CYAN\fP   '\\033[36m'"
.br
.ti -1c
.RI "#define \fBC_B_CYAN\fP   '\\033[36;1m'"
.br
.ti -1c
.RI "#define \fBC_WHITE\fP   '\\033[37m'"
.br
.ti -1c
.RI "#define \fBC_B_WHITE\fP   '\\033[37;1m'"
.br
.ti -1c
.RI "#define \fBC_BRIGHT\fP   '\\033[1m'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
