.TH "CommonComponentSample" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonComponentSample
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::Component< Driver, Driver >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInit\fP () override"
.br
.ti -1c
.RI "bool \fBProc\fP (const std::shared_ptr< Driver > &msg0, const std::shared_ptr< Driver > &msg1) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
