.TH "cyber_channel.CyberChannelecho" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_channel.CyberChannelecho
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, channel_name)"
.br
.ti -1c
.RI "def \fBcallback\fP (self, raw_data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchannel_name\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def cyber_channel\&.CyberChannelecho\&.callback ( self,  raw_data)"

.PP
.nf
Channel echo callback.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
