.TH "CyberTopologyMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CyberTopologyMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderableMessage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCyberTopologyMessage\fP (const std::string &channel)"
.br
.ti -1c
.RI "int \fBRender\fP (const \fBScreen\fP *s, int key) override"
.br
.ti -1c
.RI "\fBRenderableMessage\fP * \fBChild\fP (int index) const override"
.br
.ti -1c
.RI "void \fBTopologyChanged\fP (const \fBapollo::cyber::proto::ChangeMsg\fP &change_msg)"
.br
.ti -1c
.RI "void \fBAddReaderWriter\fP (const \fBapollo::cyber::proto::RoleAttributes\fP &role, bool isWriter)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
