.TH "cyber_py3.record.RecordReader" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.record.RecordReader
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, file_name)"
.br
.RI "the constructor function\&. "
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBread_messages\fP (self, start_time=0, end_time=18446744073709551615)"
.br
.RI "Read message from bag file\&. "
.ti -1c
.RI "def \fBget_messagenumber\fP (self, channel_name)"
.br
.RI "Return message count of the channel in current record file\&. "
.ti -1c
.RI "def \fBget_messagetype\fP (self, channel_name)"
.br
.RI "Get the corresponding message type of channel\&. "
.ti -1c
.RI "def \fBget_protodesc\fP (self, channel_name)"
.br
.ti -1c
.RI "def \fBget_headerstring\fP (self)"
.br
.ti -1c
.RI "def \fBreset\fP (self)"
.br
.ti -1c
.RI "def \fBget_channellist\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrecord_reader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for cyber RecordReader wrapper.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cyber_py3\&.record\&.RecordReader\&.__init__ ( self,  file_name)"

.PP
the constructor function\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile_name\fP the record file name\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.record\&.RecordReader\&.get_channellist ( self)"

.PP
.nf
Return current channel names list.

.fi
.PP
 
.SS "def cyber_py3\&.record\&.RecordReader\&.get_headerstring ( self)"

.PP
.nf
Return message header string.

.fi
.PP
 
.SS "def cyber_py3\&.record\&.RecordReader\&.get_messagenumber ( self,  channel_name)"

.PP
Return message count of the channel in current record file\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel_name\fP the channel name\&.
.RE
.PP
\fBReturns\fP
.RS 4
return the message count\&. 
.RE
.PP

.SS "def cyber_py3\&.record\&.RecordReader\&.get_messagetype ( self,  channel_name)"

.PP
Get the corresponding message type of channel\&. 
.PP
\fBParameters\fP
.RS 4
\fIchannel_name\fP channel name\&.
.RE
.PP
\fBReturns\fP
.RS 4
return the name of ther string type\&. 
.RE
.PP

.SS "def cyber_py3\&.record\&.RecordReader\&.get_protodesc ( self,  channel_name)"

.PP
.nf
Return message protodesc.

.fi
.PP
 
.SS "def cyber_py3\&.record\&.RecordReader\&.read_messages ( self,  start_time = \fC0\fP,  end_time = \fC18446744073709551615\fP)"

.PP
Read message from bag file\&. 
.PP
\fBParameters\fP
.RS 4
\fIstart_time\fP the start time to read\&. 
.br
\fIend_time\fP the end time to read\&.
.RE
.PP
\fBReturns\fP
.RS 4
return (channnel, data, data_type, timestamp) 
.RE
.PP

.SS "def cyber_py3\&.record\&.RecordReader\&.reset ( self)"

.PP
.nf
Return reset.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
