.TH "cyber_test.TestCyber" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_test.TestCyber
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_read_write\fP (self)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBcallback\fP (data)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for node unit test.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def cyber_test\&.TestCyber\&.callback ( data)\fC [static]\fP"

.PP
.nf
Reader callback.

.fi
.PP
 
.SS "def cyber_test\&.TestCyber\&.test_read_write ( self)"

.PP
.nf
Unit test of reader.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
