.TH "cyber_py3.cyber_timer.Timer" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber_timer.Timer
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, period=None, callback=None, oneshot=None)"
.br
.RI "Used to perform oneshot or periodic timing tasks\&. "
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBset_option\fP (self, period, callback, oneshot=0)"
.br
.RI "set the option of timer\&. "
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.RI "start the timer "
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.RI "stop the timer "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtimer\fP"
.br
.ti -1c
.RI "\fBtimer_cb\fP"
.br
.ti -1c
.RI "\fBf_ptr_cb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for cyber timer wrapper.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cyber_py3\&.cyber_timer\&.Timer\&.__init__ ( self,  period = \fCNone\fP,  callback = \fCNone\fP,  oneshot = \fCNone\fP)"

.PP
Used to perform oneshot or periodic timing tasks\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP The period of the timer, unit is ms\&. 
.br
\fIcallback\fP The tasks that the timer needs to perform\&. 
.br
\fIoneshot\fP 1:perform the callback only after the first timing cycle 0:perform the callback every timed period 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber_timer\&.Timer\&.set_option ( self,  period,  callback,  oneshot = \fC0\fP)"

.PP
set the option of timer\&. 
.PP
\fBParameters\fP
.RS 4
\fIperiod\fP The period of the timer, unit is ms\&. 
.br
\fIcallback\fP The tasks that the timer needs to perform\&. 
.br
\fIoneshot\fP 1:perform the callback only after the first timing cycle 0:perform the callback every timed period 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
