.TH "cyber_time_test.TestTime" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_time_test.TestTime
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUpClass\fP (cls)"
.br
.ti -1c
.RI "def \fBtearDownClass\fP (cls)"
.br
.ti -1c
.RI "def \fBtest_time\fP (self)"
.br
.ti -1c
.RI "def \fBtest_duration\fP (self)"
.br
.ti -1c
.RI "def \fBtest_rate\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for node unit test.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
