.TH "cyber_py3.cyber.NodeUtils" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber.NodeUtils
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_nodes\fP (sleep_s=2)"
.br
.RI "Get all active node names\&. "
.ti -1c
.RI "def \fBget_node_attr\fP (node_name, sleep_s=2)"
.br
.RI "Get node attribute by the node name\&. "
.ti -1c
.RI "def \fBget_readersofnode\fP (node_name, sleep_s=2)"
.br
.RI "Get node's reader channel names\&. "
.ti -1c
.RI "def \fBget_writersofnode\fP (node_name, sleep_s=2)"
.br
.RI "Get node's writer channel names\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber\&.NodeUtils\&.get_node_attr ( node_name,  sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get node attribute by the node name\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP node name\&. 
.br
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
the node's attribute\&. 
.RE
.PP

.SS "def cyber_py3\&.cyber\&.NodeUtils\&.get_nodes ( sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get all active node names\&. 
.PP
\fBParameters\fP
.RS 4
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
all active node names\&. 
.RE
.PP

.SS "def cyber_py3\&.cyber\&.NodeUtils\&.get_readersofnode ( node_name,  sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get node's reader channel names\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP the node name\&. 
.br
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
node's reader channel names\&. 
.RE
.PP

.SS "def cyber_py3\&.cyber\&.NodeUtils\&.get_writersofnode ( node_name,  sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get node's writer channel names\&. 
.PP
\fBParameters\fP
.RS 4
\fInode_name\fP the node name\&. 
.br
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
node's writer channel names\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
