.TH "cyber_py3.cyber.Client" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber.Client
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, client, data_type)"
.br
.ti -1c
.RI "def \fBsend_request\fP (self, data)"
.br
.RI "send request message to service\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclient\fP"
.br
.ti -1c
.RI "\fBdata_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for cyber service client wrapper.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber\&.Client\&.send_request ( self,  data)"

.PP
send request message to service\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP is a message type\&.
.RE
.PP
\fBReturns\fP
.RS 4
None or response from service\&.
.RE
.PP
.PP
.nf
send request to service
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
