.TH "cyber_channel.CyberChannelHz" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_channel.CyberChannelHz
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, window_size)"
.br
.ti -1c
.RI "def \fBcallback_hz\fP (self, m)"
.br
.ti -1c
.RI "def \fBprint_hz\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlock\fP"
.br
.ti -1c
.RI "\fBlast_printed_tn\fP"
.br
.ti -1c
.RI "\fBmsg_t0\fP"
.br
.ti -1c
.RI "\fBmsg_tn\fP"
.br
.ti -1c
.RI "\fBtimes\fP"
.br
.ti -1c
.RI "\fBwindow_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
CyberChannelHz receives messages for a topic and computes frequency stats

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def cyber_channel\&.CyberChannelHz\&.print_hz ( self)"

.PP
.nf
print the average publishing rate to screen

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
