.TH "cyber_py3.cyber.ServiceUtils" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber.ServiceUtils
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_services\fP (sleep_s=2)"
.br
.RI "Get all active service names\&. "
.ti -1c
.RI "def \fBget_service_attr\fP (service_name, sleep_s=2)"
.br
.RI "Get service attribute by the service name\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber\&.ServiceUtils\&.get_service_attr ( service_name,  sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get service attribute by the service name\&. 
.PP
\fBParameters\fP
.RS 4
\fIservice_name\fP service name\&. 
.br
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
the service's attribute\&. 
.RE
.PP

.SS "def cyber_py3\&.cyber\&.ServiceUtils\&.get_services ( sleep_s = \fC2\fP)\fC [static]\fP"

.PP
Get all active service names\&. 
.PP
\fBParameters\fP
.RS 4
\fIsleep_s\fP wait time for topo discovery\&.
.RE
.PP
\fBReturns\fP
.RS 4
all active service names\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
