.TH "cyber_launch.ColoredFormatter" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_launch.ColoredFormatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits logging\&.Formatter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, msg)"
.br
.ti -1c
.RI "def \fBformat\fP (self, record)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
