.TH "cyber_channel.CyberChannelBw" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_channel.CyberChannelBw
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, window_size=100)"
.br
.ti -1c
.RI "def \fBcallback_bw\fP (self, rawdata)"
.br
.ti -1c
.RI "def \fBprint_bw\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlock\fP"
.br
.ti -1c
.RI "\fBsizes\fP"
.br
.ti -1c
.RI "\fBtimes\fP"
.br
.ti -1c
.RI "\fBwindow_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
