.TH "cyber_py3.cyber_time.Rate" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber_time.Rate
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, other)"
.br
.RI "Constructor, creates a \fBRate\fP\&. "
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBsleep\fP (self)"
.br
.ti -1c
.RI "def \fBreset\fP (self)"
.br
.ti -1c
.RI "def \fBget_cycle_time\fP (self)"
.br
.ti -1c
.RI "def \fBget_expected_cycle_time\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrate_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for cyber Rate wrapper. Help run loops at a desired frequency.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cyber_py3\&.cyber_time\&.Rate\&.__init__ ( self,  other)"

.PP
Constructor, creates a \fBRate\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP float means frequency the desired rate to run at in Hz\&. int means the expected_cycle_time\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber_time\&.Rate\&.get_cycle_time ( self)"

.PP
.nf
Get the actual run time of a cycle from start to sleep.

.fi
.PP
 
.SS "def cyber_py3\&.cyber_time\&.Rate\&.get_expected_cycle_time ( self)"

.PP
.nf
Get the expected cycle time.

.fi
.PP
 
.SS "def cyber_py3\&.cyber_time\&.Rate\&.reset ( self)"

.PP
.nf
Sets the start time for the rate to now.

.fi
.PP
 
.SS "def cyber_py3\&.cyber_time\&.Rate\&.sleep ( self)"

.PP
.nf
Sleeps for any leftover time in a cycle.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
