.TH "cyber_py3.parameter.ParameterClient" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.parameter.ParameterClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, node, server_node_name)"
.br
.RI "constructor the \fBParameterClient\fP by a node and the parameter server node name\&. "
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBset_parameter\fP (self, param)"
.br
.ti -1c
.RI "def \fBget_parameter\fP (self, param_name)"
.br
.ti -1c
.RI "def \fBget_paramslist\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBparam_clt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for ParameterClient wrapper.

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def cyber_py3\&.parameter\&.ParameterClient\&.__init__ ( self,  node,  server_node_name)"

.PP
constructor the \fBParameterClient\fP by a node and the parameter server node name\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP a node to create client\&. 
.br
\fIserver_node_name\fP the parameter server's node name\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.parameter\&.ParameterClient\&.get_parameter ( self,  param_name)"

.PP
.nf
get Parameter by param name param_name.

.fi
.PP
 
.SS "def cyber_py3\&.parameter\&.ParameterClient\&.get_paramslist ( self)"

.PP
.nf
get all params of the server_node_name parameterserver.

.fi
.PP
 
.SS "def cyber_py3\&.parameter\&.ParameterClient\&.set_parameter ( self,  param)"

.PP
.nf
set parameter, param is Parameter.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
