.TH "cyber_py3.cyber_time.Duration" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber_py3.cyber_time.Duration
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBsleep\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.ti -1c
.RI "def \fBto_sec\fP (self)"
.br
.ti -1c
.RI "def \fBto_nsec\fP (self)"
.br
.ti -1c
.RI "def \fBiszero\fP (self)"
.br
.ti -1c
.RI "def \fB__add__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__radd__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__sub__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__lt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__gt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__le__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ge__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ne__\fP (self, other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnanoseconds_\fP"
.br
.ti -1c
.RI "\fBduration_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for cyber Duration wrapper.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def cyber_py3\&.cyber_time\&.Duration\&.sleep ( self)"

.PP
.nf
sleep for the amount of time specified by the duration.

.fi
.PP
 
.SS "def cyber_py3\&.cyber_time\&.Duration\&.to_nsec ( self)"

.PP
.nf
convert to nanosecond.

.fi
.PP
 
.SS "def cyber_py3\&.cyber_time\&.Duration\&.to_sec ( self)"

.PP
.nf
convert to second.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
