.TH "DISCOVERY_MODULE" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DISCOVERY_MODULE \- Discovery Module
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::EDP\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::EDPSimple\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::EDPStaticProperty\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::PDPSimple\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::PDPSimpleListener\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::RemoteParticipantLeaseDuration\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::rtps::ResendParticipantProxyDataPeriod\fP"
.br
.ti -1c
.RI "class \fBeprosima::fastrtps::xmlparser::StaticRTPSParticipantInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This module contains the classes associated with the Discovery Protocols\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
