.TH "eprosima::fastrtps::rtps::WriterProxyData" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::WriterProxyData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RTPS_DllAPI \fBWriterProxyData\fP (const \fBWriterProxyData\fP &writerInfo)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBWriterProxyData\fP & \fBoperator=\fP (const \fBWriterProxyData\fP &writerInfo)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBguid\fP (const \fBGUID_t\fP &guid)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBguid\fP (\fBGUID_t\fP &&guid)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBGUID_t\fP \fBguid\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBGUID_t\fP & \fBguid\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBunicastLocatorList\fP (const \fBLocatorList_t\fP &unicastLocatorList)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBunicastLocatorList\fP (\fBLocatorList_t\fP &&unicastLocatorList)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP \fBunicastLocatorList\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP & \fBunicastLocatorList\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBmulticastLocatorList\fP (const \fBLocatorList_t\fP &multicastLocatorList)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBmulticastLocatorList\fP (\fBLocatorList_t\fP &&multicastLocatorList)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP \fBmulticastLocatorList\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP & \fBmulticastLocatorList\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBkey\fP (const \fBInstanceHandle_t\fP &key)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBkey\fP (\fBInstanceHandle_t\fP &&key)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBInstanceHandle_t\fP \fBkey\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBInstanceHandle_t\fP & \fBkey\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBRTPSParticipantKey\fP (const \fBInstanceHandle_t\fP &RTPSParticipantKey)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBRTPSParticipantKey\fP (\fBInstanceHandle_t\fP &&RTPSParticipantKey)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBInstanceHandle_t\fP \fBRTPSParticipantKey\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBInstanceHandle_t\fP & \fBRTPSParticipantKey\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtypeName\fP (const std::string &typeName)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtypeName\fP (std::string &&typeName)"
.br
.ti -1c
.RI "RTPS_DllAPI std::string \fBtypeName\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI std::string & \fBtypeName\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtopicName\fP (const std::string &topicName)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtopicName\fP (std::string &&topicName)"
.br
.ti -1c
.RI "RTPS_DllAPI std::string \fBtopicName\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI std::string & \fBtopicName\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBuserDefinedId\fP (uint16_t userDefinedId)"
.br
.ti -1c
.RI "RTPS_DllAPI uint16_t \fBuserDefinedId\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI uint16_t & \fBuserDefinedId\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtypeMaxSerialized\fP (uint32_t typeMaxSerialized)"
.br
.ti -1c
.RI "RTPS_DllAPI uint32_t \fBtypeMaxSerialized\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI uint32_t & \fBtypeMaxSerialized\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBisAlive\fP (bool isAlive)"
.br
.ti -1c
.RI "RTPS_DllAPI bool \fBisAlive\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI bool & \fBisAlive\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBtopicKind\fP (\fBTopicKind_t\fP topicKind)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBTopicKind_t\fP \fBtopicKind\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI \fBTopicKind_t\fP & \fBtopicKind\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "Clear the information and return the object to the default state\&. "
.ti -1c
.RI "void \fBupdate\fP (\fBWriterProxyData\fP *rdata)"
.br
.RI "Update certain parameters from another object\&. "
.ti -1c
.RI "void \fBcopy\fP (\fBWriterProxyData\fP *rdata)"
.br
.RI "Copy all information from another object\&. "
.ti -1c
.RI "bool \fBtoParameterList\fP ()"
.br
.RI "Convert the information to a parameter list to be send in a \fBCDRMessage\fP\&. "
.ti -1c
.RI "RTPS_DllAPI bool \fBreadFromCDRMessage\fP (\fBCDRMessage_t\fP *msg)"
.br
.RI "Read a parameter list from a \fBCDRMessage_t\fP\&. "
.ti -1c
.RI "\fBRemoteWriterAttributes\fP & \fBtoRemoteWriterAttributes\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWriterQos\fP \fBm_qos\fP"
.br
.RI "WriterQOS\&. "
.ti -1c
.RI "\fBParameterList_t\fP \fBm_parameterList\fP"
.br
.ti -1c
.RI "\fBRemoteWriterAttributes\fP \fBm_remoteAtt\fP"
.br
.RI "Remote Attributes associated with this proxy data\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBRemoteWriterAttributes\fP& eprosima::fastrtps::rtps::WriterProxyData::toRemoteWriterAttributes ()"
Convert the ProxyData information to \fBRemoteWriterAttributes\fP object\&. 
.PP
\fBReturns\fP
.RS 4
Reference to the \fBRemoteWriterAttributes\fP object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
