.TH "eprosima::fastrtps::rtps::RTPSParticipantAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RTPSParticipantAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSParticipantAttributes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetName\fP (const char *nam)"
.br
.RI "Set the name of the participant\&. "
.ti -1c
.RI "const char * \fBgetName\fP () const"
.br
.RI "Get the name of the participant\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocatorList_t\fP \fBdefaultUnicastLocatorList\fP"
.br
.ti -1c
.RI "\fBLocatorList_t\fP \fBdefaultMulticastLocatorList\fP"
.br
.ti -1c
.RI "\fBLocatorList_t\fP \fBdefaultOutLocatorList\fP"
.br
.ti -1c
.RI "uint32_t \fBdefaultSendPort\fP"
.br
.ti -1c
.RI "uint32_t \fBsendSocketBufferSize\fP"
.br
.RI "Send socket buffer size for the send resource\&. Zero value indicates to use default system buffer size\&. Default value: 0\&. "
.ti -1c
.RI "uint32_t \fBlistenSocketBufferSize\fP"
.br
.ti -1c
.RI "\fBBuiltinAttributes\fP \fBbuiltin\fP"
.br
.RI "Builtin parameters\&. "
.ti -1c
.RI "\fBPortParameters\fP \fBport\fP"
.br
.RI "Port Parameters\&. "
.ti -1c
.RI "std::vector< octet > \fBuserData\fP"
.br
.RI "User Data of the participant\&. "
.ti -1c
.RI "int32_t \fBparticipantID\fP"
.br
.RI "\fBParticipant\fP ID\&. "
.ti -1c
.RI "bool \fBuse_IP4_to_send\fP"
.br
.RI "Use IP4 to send messages\&. "
.ti -1c
.RI "bool \fBuse_IP6_to_send\fP"
.br
.RI "Use IP6 to send messages\&. "
.ti -1c
.RI "\fBThroughputControllerDescriptor\fP \fBthroughputController\fP"
.br
.RI "Throughput controller parameters\&. Leave default for uncontrolled flow\&. "
.ti -1c
.RI "std::vector< std::shared_ptr< \fBTransportDescriptorInterface\fP > > \fBuserTransports\fP"
.br
.RI "User defined transports to use alongside or in place of builtins\&. "
.ti -1c
.RI "bool \fBuseBuiltinTransports\fP"
.br
.RI "Set as false to disable the default UDPv4 implementation\&. "
.ti -1c
.RI "\fBPropertyPolicy\fP \fBproperties\fP"
.br
.RI "\fBProperty\fP policies\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBRTPSParticipantAttributes\fP used to define different aspects of a \fBRTPSParticipant\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBLocatorList_t\fP eprosima::fastrtps::rtps::RTPSParticipantAttributes::defaultMulticastLocatorList"
Default list of Multicast Locators to be used for any \fBEndpoint\fP defined inside this \fBRTPSParticipant\fP in the case that it was defined with NO UnicastLocators\&. This is usually left empty\&. 
.SS "\fBLocatorList_t\fP eprosima::fastrtps::rtps::RTPSParticipantAttributes::defaultOutLocatorList"
Default list of Locators used to send messages through\&. Used to link with SenderResources in the case and \fBEndpoint\fP is created with NO outLocators\&. This list contains the default outLocators for the Transports implemented by eProsima\&. 
.SS "uint32_t eprosima::fastrtps::rtps::RTPSParticipantAttributes::defaultSendPort"
Default send port that all Endpoints in the \fBRTPSParticipant\fP would use to send messages, default value 10040\&. In this release all Endpoints use the same resource (socket) to send messages\&. 
.SS "\fBLocatorList_t\fP eprosima::fastrtps::rtps::RTPSParticipantAttributes::defaultUnicastLocatorList"
Default list of Unicast Locators to be used for any \fBEndpoint\fP defined inside this \fBRTPSParticipant\fP in the case that it was defined with NO UnicastLocators\&. At least ONE locator should be included in this list\&. 
.SS "uint32_t eprosima::fastrtps::rtps::RTPSParticipantAttributes::listenSocketBufferSize"
Listen socket buffer for all listen resources\&. Zero value indicates to use default system buffer size\&. Default value: 0\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
