.TH "eprosima::fastrtps::rtps::AsyncInterestTree" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::AsyncInterestTree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterInterest\fP (const \fBRTPSWriter\fP *)"
.br
.ti -1c
.RI "void \fBRegisterInterest\fP (const RTPSParticipantImpl *)"
.br
.ti -1c
.RI "void \fBSwap\fP ()"
.br
.ti -1c
.RI "std::set< const \fBRTPSWriter\fP * > \fBGetInterestedWriters\fP () const"
.br
.RI "Extracts from the visible set\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void eprosima::fastrtps::rtps::AsyncInterestTree::RegisterInterest (const RTPSParticipantImpl *)"
Registers all writers from participant in a hidden set\&. Threadsafe thanks to set swap\&. 
.SS "void eprosima::fastrtps::rtps::AsyncInterestTree::RegisterInterest (const \fBRTPSWriter\fP *)"
Registers a writer in a hidden set\&. Threadsafe thanks to set swap\&. 
.SS "void eprosima::fastrtps::rtps::AsyncInterestTree::Swap ()"
Clears the visible set and swaps with the hidden set\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
