.TH "eprosima::fastrtps::rtps::RTPSMessageCreator" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RTPSMessageCreator \- Class \fBRTPSMessageCreator\fP, allows the generation of serialized CDR RTPS Messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSMessageCreator\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBaddHeader\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &Prefix, \fBProtocolVersion_t\fP version, \fBVendorId_t\fP vendorId)"
.br
.ti -1c
.RI "static bool \fBaddHeader\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &Prefix)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageHeader\fP (\fBCDRMessage_t\fP *msg, octet id, octet flags, uint16_t size)"
.br
.in -1c
.PP
.RI "\fBCDR messages creation methods\&.\fP"
.br
These methods create a CDR message for different types Depending on the function a complete message (with RTPS Header is created) or only the submessage\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to where the message is going to be created and stored\&. 
.br
\fIguidPrefix\fP Guid Prefix of the \fBRTPSParticipant\fP\&. 
.br
\fIparam\fP Different parameters depending on the message\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.PP
.in +1c
.in +1c
.ti -1c
.RI "static bool \fBaddMessageData\fP (\fBCDRMessage_t\fP *msg, \fBGuidPrefix_t\fP &guidprefix, const \fBCacheChange_t\fP *change, \fBTopicKind_t\fP topicKind, const \fBEntityId_t\fP &readerId, bool expectsInlineQos, \fBParameterList_t\fP *inlineQos)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageData\fP (\fBCDRMessage_t\fP *msg, const \fBCacheChange_t\fP *change, \fBTopicKind_t\fP topicKind, const \fBEntityId_t\fP &readerId, bool expectsInlineQos, \fBParameterList_t\fP *inlineQos)"
.br
.ti -1c
.RI "static bool \fBaddMessageDataFrag\fP (\fBCDRMessage_t\fP *msg, \fBGuidPrefix_t\fP &guidprefix, const \fBCacheChange_t\fP *change, uint32_t fragment_number, \fBTopicKind_t\fP topicKind, const \fBEntityId_t\fP &readerId, bool expectsInlineQos, \fBParameterList_t\fP *inlineQos)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageDataFrag\fP (\fBCDRMessage_t\fP *msg, const \fBCacheChange_t\fP *change, uint32_t fragment_number, uint32_t sample_size, \fBTopicKind_t\fP topicKind, const \fBEntityId_t\fP &readerId, bool expectsInlineQos, \fBParameterList_t\fP *inlineQos)"
.br
.ti -1c
.RI "static bool \fBaddMessageGap\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBGuidPrefix_t\fP &remoteGuidPrefix, const \fBSequenceNumber_t\fP &seqNumFirst, const \fBSequenceNumberSet_t\fP &seqNumList, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageGap\fP (\fBCDRMessage_t\fP *msg, const \fBSequenceNumber_t\fP &seqNumFirst, const \fBSequenceNumberSet_t\fP &seqNumList, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId)"
.br
.ti -1c
.RI "static bool \fBaddMessageHeartbeat\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, const \fBSequenceNumber_t\fP &firstSN, const \fBSequenceNumber_t\fP &lastSN, Count_t count, bool isFinal, bool livelinessFlag)"
.br
.ti -1c
.RI "static bool \fBaddMessageHeartbeat\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBGuidPrefix_t\fP &remoteGuidprefix, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, const \fBSequenceNumber_t\fP &firstSN, const \fBSequenceNumber_t\fP &lastSN, Count_t count, bool isFinal, bool livelinessFlag)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageHeartbeat\fP (\fBCDRMessage_t\fP *msg, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, const \fBSequenceNumber_t\fP &firstSN, const \fBSequenceNumber_t\fP &lastSN, Count_t count, bool isFinal, bool livelinessFlag)"
.br
.ti -1c
.RI "static bool \fBaddMessageHeartbeatFrag\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumber_t\fP &firstSN, FragmentNumber_t &lastFN, Count_t count)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageHeartbeatFrag\fP (\fBCDRMessage_t\fP *msg, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumber_t\fP &firstSN, FragmentNumber_t &lastFN, Count_t count)"
.br
.ti -1c
.RI "static bool \fBaddMessageAcknack\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBGuidPrefix_t\fP &remoteGuidPrefix, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumberSet_t\fP &SNSet, int32_t count, bool finalFlag)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageAcknack\fP (\fBCDRMessage_t\fP *msg, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumberSet_t\fP &SNSet, int32_t count, bool finalFlag)"
.br
.ti -1c
.RI "static bool \fBaddMessageNackFrag\fP (\fBCDRMessage_t\fP *msg, const \fBGuidPrefix_t\fP &guidprefix, const \fBGuidPrefix_t\fP &remoteGuidPrefix, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumber_t\fP &writerSN, \fBFragmentNumberSet_t\fP fnState, int32_t count)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageNackFrag\fP (\fBCDRMessage_t\fP *msg, const \fBEntityId_t\fP &readerId, const \fBEntityId_t\fP &writerId, \fBSequenceNumber_t\fP &writerSN, \fBFragmentNumberSet_t\fP fnState, int32_t count)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageInfoTS\fP (\fBCDRMessage_t\fP *msg, \fBTime_t\fP &time, bool invalidateFlag)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageInfoTS_Now\fP (\fBCDRMessage_t\fP *msg, bool invalidateFlag)"
.br
.ti -1c
.RI "static bool \fBaddSubmessageInfoDST\fP (\fBCDRMessage_t\fP *msg, \fBGuidPrefix_t\fP guidP)"
.br
.in -1c
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCDRMessage_t\fP \fBrtpsmc_submsgElem\fP"
.br
.ti -1c
.RI "\fBCDRMessage_t\fP \fBrtpsmc_submsgHeader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBRTPSMessageCreator\fP, allows the generation of serialized CDR RTPS Messages\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool eprosima::fastrtps::rtps::RTPSMessageCreator::addHeader (\fBCDRMessage_t\fP * msg, const \fBGuidPrefix_t\fP & Prefix)\fC [static]\fP"
Create a Header to the serialized message\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to the Message\&. 
.br
\fIPrefix\fP \fBRTPSParticipant\fP prefix of the message\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "static bool eprosima::fastrtps::rtps::RTPSMessageCreator::addHeader (\fBCDRMessage_t\fP * msg, const \fBGuidPrefix_t\fP & Prefix, \fBProtocolVersion_t\fP version, \fBVendorId_t\fP vendorId)\fC [static]\fP"
Create a Header to the serialized message\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to the Message\&. 
.br
\fIPrefix\fP \fBRTPSParticipant\fP prefix of the message\&. 
.br
\fIversion\fP Protocol version\&. 
.br
\fIvendorId\fP Vendor Id\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "static bool eprosima::fastrtps::rtps::RTPSMessageCreator::addSubmessageHeader (\fBCDRMessage_t\fP * msg, octet id, octet flags, uint16_t size)\fC [static]\fP"
Create SubmessageHeader\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to the \fBCDRMessage\fP\&. 
.br
\fIid\fP SubMessage Id\&. 
.br
\fIflags\fP Submessage flags\&. 
.br
\fIsize\fP Submessage size\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
