.TH "eprosima::fastrtps::rtps::security::CryptoTransform" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::CryptoTransform
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBencode_serialized_payload\fP (std::vector< uint8_t > &encoded_buffer, std::vector< uint8_t > &extra_inline_qos, const std::vector< uint8_t > &plain_buffer, \fBDatawriterCryptoHandle\fP &sending_datawriter_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBencode_datawriter_submessage\fP (std::vector< uint8_t > &encoded_rtps_submessage, const std::vector< uint8_t > &plain_rtps_submessage, \fBDatawriterCryptoHandle\fP &sending_datawriter_crypto, std::vector< \fBDatareaderCryptoHandle\fP * > &receiving_datareader_crypto_list, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBencode_datareader_submessage\fP (std::vector< uint8_t > &encoded_rtps_submessage, const std::vector< uint8_t > &plain_rtps_submessage, \fBDatareaderCryptoHandle\fP &sending_datareader_crypto, std::vector< \fBDatawriterCryptoHandle\fP * > &receiving_datawriter_crypto_list, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBencode_rtps_message\fP (std::vector< uint8_t > &encoded_rtps_message, const std::vector< uint8_t > &plain_rtps_message, \fBParticipantCryptoHandle\fP &sending_crypto, const std::vector< \fBParticipantCryptoHandle\fP * > &receiving_crypto_list, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBdecode_rtps_message\fP (std::vector< uint8_t > &plain_buffer, const std::vector< uint8_t > &encoded_buffer, const \fBParticipantCryptoHandle\fP &receiving_crypto, const \fBParticipantCryptoHandle\fP &sending_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBpreprocess_secure_submsg\fP (\fBDatawriterCryptoHandle\fP **datawriter_crypto, \fBDatareaderCryptoHandle\fP **datareader_crypto, SecureSubmessageCategory_t &secure_submessage_category, const \fBCDRMessage_t\fP &encoded_rtps_submessage, \fBParticipantCryptoHandle\fP &receiving_crypto, \fBParticipantCryptoHandle\fP &sending_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBdecode_datawriter_submessage\fP (\fBCDRMessage_t\fP &plain_rtps_submessage, \fBCDRMessage_t\fP &encoded_rtps_submessage, \fBDatareaderCryptoHandle\fP &receiving_datareader_crypto, \fBDatawriterCryptoHandle\fP &sending_datawriter_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBdecode_datareader_submessage\fP (\fBCDRMessage_t\fP &plain_rtps_submessage, \fBCDRMessage_t\fP &encoded_rtps_submessage, \fBDatawriterCryptoHandle\fP &receiving_datawriter_crypto, \fBDatareaderCryptoHandle\fP &sending_datareader_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual bool \fBdecode_serialized_payload\fP (std::vector< uint8_t > &plain_buffer, const std::vector< uint8_t > &encoded_buffer, const std::vector< uint8_t > &inline_qos, \fBDatareaderCryptoHandle\fP &receiving_datareader_crypto, \fBDatawriterCryptoHandle\fP &sending_datawriter_crypto, \fBSecurityException\fP &exception)=0"
.br
.ti -1c
.RI "virtual uint32_t \fBcalculate_extra_size_for_rtps_message\fP (uint32_t number_discovered_participants) const =0"
.br
.ti -1c
.RI "virtual uint32_t \fBcalculate_extra_size_for_rtps_submessage\fP (uint32_t number_discovered_readers) const =0"
.br
.ti -1c
.RI "virtual uint32_t \fBcalculate_extra_size_for_encoded_payload\fP (uint32_t number_discovered_readers) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::decode_datareader_submessage (\fBCDRMessage_t\fP & plain_rtps_submessage, \fBCDRMessage_t\fP & encoded_rtps_submessage, \fBDatawriterCryptoHandle\fP & receiving_datawriter_crypto, \fBDatareaderCryptoHandle\fP & sending_datareader_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Called after preprocess_secure_submessage when the submessage category is DATAREADER_SUBMESSAGE 
.PP
\fBParameters\fP
.RS 4
\fIplain_rtps_submessage\fP (out) Result of the decryption 
.br
\fIencoded_rtps_submessage\fP Encoded message 
.br
\fIreceiving_datawriter_crypto\fP Crypto of the target datawriter 
.br
\fIsending_datareader_crypto\fP Crypto of the datareader that sent the message 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::decode_datawriter_submessage (\fBCDRMessage_t\fP & plain_rtps_submessage, \fBCDRMessage_t\fP & encoded_rtps_submessage, \fBDatareaderCryptoHandle\fP & receiving_datareader_crypto, \fBDatawriterCryptoHandle\fP & sending_datawriter_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Called after prprocess_secure_submessage when the submessage category is DATAWRITER_SUBMESSAGE 
.PP
\fBParameters\fP
.RS 4
\fIplain_rtps_message\fP (out) Result of the decryption 
.br
\fIencoded_rtps_submessage\fP Encoded message 
.br
\fIreceiving_datareader_crypto\fP Crypto of the target datareader 
.br
\fIsending_datawriter_crypto\fP Crypto of the datawriter that sent the message 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::decode_rtps_message (std::vector< uint8_t > & plain_buffer, const std::vector< uint8_t > & encoded_buffer, const \fBParticipantCryptoHandle\fP & receiving_crypto, const \fBParticipantCryptoHandle\fP & sending_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Reverses the transformation performed by encode_rtps_message\&. Decrypts the contents and veryfies MACs or digital signatures\&. 
.PP
\fBParameters\fP
.RS 4
\fIplain_buffer\fP (out) Decoded message 
.br
\fIencoded_buffer\fP Encoded message 
.br
\fIreceiving_crypto\fP Crypto of the \fBParticipant\fP that receives the message 
.br
\fIsending_crypto\fP Crypto of the \fBParticipant\fP that wrote the message 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE is successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::decode_serialized_payload (std::vector< uint8_t > & plain_buffer, const std::vector< uint8_t > & encoded_buffer, const std::vector< uint8_t > & inline_qos, \fBDatareaderCryptoHandle\fP & receiving_datareader_crypto, \fBDatawriterCryptoHandle\fP & sending_datawriter_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Undoes the decryption transformation made on the writer side\&. 
.PP
\fBParameters\fP
.RS 4
\fIplain_buffer\fP (out) Result of the decryption 
.br
\fIencoded_buffer\fP Encoded input buffer 
.br
\fIinline_qos\fP Coming from the data message that carries the target payload 
.br
\fIreceiving_datareader_crypto\fP Crypto of the target datareader 
.br
\fIsending_datawriter_crypto\fP Crypto of the datawriter that sent the message 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::encode_datareader_submessage (std::vector< uint8_t > & encoded_rtps_submessage, const std::vector< uint8_t > & plain_rtps_submessage, \fBDatareaderCryptoHandle\fP & sending_datareader_crypto, std::vector< \fBDatawriterCryptoHandle\fP * > & receiving_datawriter_crypto_list, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Encodes an AckNack or NackFrag 
.PP
\fBParameters\fP
.RS 4
\fIencoded_rtps_submessage\fP (out) Result of the encryption 
.br
\fIplain_rtps_submessage\fP Plain input buffer 
.br
\fIsending_datareader_crypto\fP Crypto of the sending datareader 
.br
\fIreceiving_datawriter_crypto_list\fP List with Crypto of the intended datawriter recipients 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::encode_datawriter_submessage (std::vector< uint8_t > & encoded_rtps_submessage, const std::vector< uint8_t > & plain_rtps_submessage, \fBDatawriterCryptoHandle\fP & sending_datawriter_crypto, std::vector< \fBDatareaderCryptoHandle\fP * > & receiving_datareader_crypto_list, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Encodes a Data, DataFrag, Gap, Heartbeat or HeartBeatFrag 
.PP
\fBParameters\fP
.RS 4
\fIencoded_rtps_submessage\fP (out) Result of the encryption 
.br
\fIplain_rtps_submessage\fP Plain input buffer 
.br
\fIsending_datawriter_crypto\fP Crypto of the datawriter that sends the message 
.br
\fIreceiving_datareader_crypto_list\fP Crypto of the datareaders the message is aimed at 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE is successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::encode_rtps_message (std::vector< uint8_t > & encoded_rtps_message, const std::vector< uint8_t > & plain_rtps_message, \fBParticipantCryptoHandle\fP & sending_crypto, const std::vector< \fBParticipantCryptoHandle\fP * > & receiving_crypto_list, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Encodes a full rtps message 
.PP
\fBParameters\fP
.RS 4
\fIencoded_rtps_message\fP (out) Result of the encryption 
.br
\fIplain_rtps_message\fP Plain input buffer 
.br
\fIsending_crypto\fP Crypto of the \fBParticipant\fP where the message originates from 
.br
\fIreceiving_crypto_list\fP Crypto of the Partipants the message is intended towards 
.br
\fIexception\fP (out) Security expcetion 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::encode_serialized_payload (std::vector< uint8_t > & encoded_buffer, std::vector< uint8_t > & extra_inline_qos, const std::vector< uint8_t > & plain_buffer, \fBDatawriterCryptoHandle\fP & sending_datawriter_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Serializes the payload sent by the user with a Datawriter\&. 
.PP
\fBParameters\fP
.RS 4
\fIencoded_buffer\fP (out) Result of the encryption 
.br
\fIextra_inline_qos\fP (out) Contains additional parameters to be added to the inlineQos of the submessage 
.br
\fIplain_buffer\fP Plain input buffer 
.br
\fIsending_datawriter_crypto\fP Returned by a prior call to register_local_datawriter 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP

.SS "virtual bool eprosima::fastrtps::rtps::security::CryptoTransform::preprocess_secure_submsg (\fBDatawriterCryptoHandle\fP ** datawriter_crypto, \fBDatareaderCryptoHandle\fP ** datareader_crypto, SecureSubmessageCategory_t & secure_submessage_category, const \fBCDRMessage_t\fP & encoded_rtps_submessage, \fBParticipantCryptoHandle\fP & receiving_crypto, \fBParticipantCryptoHandle\fP & sending_crypto, \fBSecurityException\fP & exception)\fC [pure virtual]\fP"
Determines whether the secure submessage comes from a datawriter or a data reader and extracts the required CryptoHandle to decode it\&. 
.PP
\fBParameters\fP
.RS 4
\fIdatawriter_crypt\fP (out) Crypto of the sending datawriter, if applicable 
.br
\fIdatareader_crypto\fP (out) Crypto of the sending datareader, if applicable 
.br
\fIsecure_submessage_category\fP (out) Specifies wether the message comes from a datawriter or from a datareader 
.br
\fIencoded_rtps_submessage\fP encoded input submessage 
.br
\fIreceiving_crypto\fP Crypto of the \fBParticipant\fP that receives the message 
.br
\fIsending_crypto\fP Crypto of the \fBParticipant\fP that sent the message 
.br
\fIexception\fP (out) Security exception 
.RE
.PP
\fBReturns\fP
.RS 4
TRUE if successful 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
