.TH "eprosima::fastrtps::rtps::Property" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::Property
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP (const \fBProperty\fP &property)"
.br
.ti -1c
.RI "\fBProperty\fP (\fBProperty\fP &&property)"
.br
.ti -1c
.RI "\fBProperty\fP (const std::string &name, const std::string &value)"
.br
.ti -1c
.RI "\fBProperty\fP (std::string &&name, std::string &&value)"
.br
.ti -1c
.RI "\fBProperty\fP & \fBoperator=\fP (const \fBProperty\fP &property)"
.br
.ti -1c
.RI "\fBProperty\fP & \fBoperator=\fP (\fBProperty\fP &&property)"
.br
.ti -1c
.RI "void \fBname\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBname\fP (std::string &&name)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "std::string & \fBname\fP ()"
.br
.ti -1c
.RI "void \fBvalue\fP (const std::string &value)"
.br
.ti -1c
.RI "void \fBvalue\fP (std::string &&value)"
.br
.ti -1c
.RI "const std::string & \fBvalue\fP () const"
.br
.ti -1c
.RI "std::string & \fBvalue\fP ()"
.br
.ti -1c
.RI "void \fBpropagate\fP (bool propagate)"
.br
.ti -1c
.RI "bool \fBpropagate\fP () const"
.br
.ti -1c
.RI "bool & \fBpropagate\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
