.TH "eprosima::fastrtps::rtps::security::SharedSecret::BinaryData" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::SharedSecret::BinaryData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryData\fP (const \fBBinaryData\fP &data)"
.br
.ti -1c
.RI "\fBBinaryData\fP (\fBBinaryData\fP &&data)"
.br
.ti -1c
.RI "\fBBinaryData\fP (const std::string &name, const std::vector< uint8_t > &value)"
.br
.ti -1c
.RI "\fBBinaryData\fP (std::string &&name, std::vector< uint8_t > &&value)"
.br
.ti -1c
.RI "\fBBinaryData\fP & \fBoperator=\fP (const \fBBinaryData\fP &data)"
.br
.ti -1c
.RI "\fBBinaryData\fP & \fBoperator=\fP (\fBBinaryData\fP &&data)"
.br
.ti -1c
.RI "void \fBname\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBname\fP (std::string &&name)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "std::string & \fBname\fP ()"
.br
.ti -1c
.RI "void \fBvalue\fP (const std::vector< uint8_t > &value)"
.br
.ti -1c
.RI "void \fBvalue\fP (std::vector< uint8_t > &&value)"
.br
.ti -1c
.RI "const std::vector< uint8_t > & \fBvalue\fP () const"
.br
.ti -1c
.RI "std::vector< uint8_t > & \fBvalue\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
