.TH "eprosima::fastcdr::FastCdr::state" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastcdr::FastCdr::state \- This class stores the current state of a CDR serialization\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FastCdr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstate\fP (const \fBFastCdr\fP &fastcdr)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBstate\fP (const \fBstate\fP &)"
.br
.RI "Copy constructor\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBFastCdr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class stores the current state of a CDR serialization\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
