.TH "eprosima::fastrtps::rtps::DataHolder" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::DataHolder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataHolder\fP (const \fBDataHolder\fP &data_holder)"
.br
.ti -1c
.RI "\fBDataHolder\fP (\fBDataHolder\fP &&data_holder)"
.br
.ti -1c
.RI "\fBDataHolder\fP & \fBoperator=\fP (const \fBDataHolder\fP &data_holder)"
.br
.ti -1c
.RI "\fBDataHolder\fP & \fBoperator=\fP (\fBDataHolder\fP &&data_holder)"
.br
.ti -1c
.RI "void \fBclass_id\fP (const std::string &class_id)"
.br
.ti -1c
.RI "void \fBclass_id\fP (std::string &&class_id)"
.br
.ti -1c
.RI "std::string & \fBclass_id\fP ()"
.br
.ti -1c
.RI "const std::string & \fBclass_id\fP () const"
.br
.ti -1c
.RI "const PropertySeq & \fBproperties\fP () const"
.br
.ti -1c
.RI "PropertySeq & \fBproperties\fP ()"
.br
.ti -1c
.RI "const BinaryPropertySeq & \fBbinary_properties\fP () const"
.br
.ti -1c
.RI "BinaryPropertySeq & \fBbinary_properties\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
