.TH "eprosima::fastrtps::rtps::BuiltinAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::BuiltinAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSParticipantAttributes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBgetStaticEndpointXMLFilename\fP ()"
.br
.ti -1c
.RI "void \fBsetStaticEndpointXMLFilename\fP (const char *str)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuse_SIMPLE_RTPSParticipantDiscoveryProtocol\fP"
.br
.ti -1c
.RI "bool \fBuse_WriterLivelinessProtocol\fP"
.br
.RI "Indicates to use the WriterLiveliness protocol\&. "
.ti -1c
.RI "bool \fBuse_SIMPLE_EndpointDiscoveryProtocol\fP"
.br
.ti -1c
.RI "bool \fBuse_STATIC_EndpointDiscoveryProtocol\fP"
.br
.ti -1c
.RI "uint32_t \fBdomainId\fP"
.br
.ti -1c
.RI "\fBDuration_t\fP \fBleaseDuration\fP"
.br
.RI "Lease Duration of the \fBRTPSParticipant\fP, indicating how much time remote RTPSParticipants should consider this \fBRTPSParticipant\fP alive\&. "
.ti -1c
.RI "\fBDuration_t\fP \fBleaseDuration_announcementperiod\fP"
.br
.ti -1c
.RI "\fBSimpleEDPAttributes\fP \fBm_simpleEDP\fP"
.br
.RI "Attributes of the SimpleEDP protocol\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBmetatrafficUnicastLocatorList\fP"
.br
.RI "Metatraffic Unicast Locator List\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBmetatrafficMulticastLocatorList\fP"
.br
.RI "Metatraffic Multicast Locator List\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBinitialPeersList\fP"
.br
.RI "Initial peers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBBuiltinAttributes\fP, to define the behavior of the \fBRTPSParticipant\fP builtin protocols\&. 
.SH "Member Function Documentation"
.PP 
.SS "const char* eprosima::fastrtps::rtps::BuiltinAttributes::getStaticEndpointXMLFilename ()\fC [inline]\fP"
Get the static endpoint XML filename 
.PP
\fBReturns\fP
.RS 4
Static endpoint XML filename 
.RE
.PP

.SS "void eprosima::fastrtps::rtps::BuiltinAttributes::setStaticEndpointXMLFilename (const char * str)\fC [inline]\fP"
Set the static endpoint XML filename 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP Static endpoint XML filename 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "uint32_t eprosima::fastrtps::rtps::BuiltinAttributes::domainId"
DomainId to be used by the \fBRTPSParticipant\fP (80 by default)\&. 
.SS "\fBDuration_t\fP eprosima::fastrtps::rtps::BuiltinAttributes::leaseDuration_announcementperiod"
The period for the \fBRTPSParticipant\fP to send its Discovery Message to all other discovered RTPSParticipants as well as to all Multicast ports\&. 
.SS "bool eprosima::fastrtps::rtps::BuiltinAttributes::use_SIMPLE_EndpointDiscoveryProtocol"
If set to true, SimpleEDP would be used\&. 
.SS "bool eprosima::fastrtps::rtps::BuiltinAttributes::use_SIMPLE_RTPSParticipantDiscoveryProtocol"
If set to false, NO discovery whatsoever would be used\&. \fBPublisher\fP and \fBSubscriber\fP defined with the same topic name would NOT be linked\&. All matching must be done manually through the addReaderLocator, addReaderProxy, addWriterProxy methods\&. 
.SS "bool eprosima::fastrtps::rtps::BuiltinAttributes::use_STATIC_EndpointDiscoveryProtocol"
If set to true, StaticEDP based on an XML file would be implemented\&. The XML filename must be provided\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
