.TH "eprosima::fastrtps::rtps::ReceiverResource" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::ReceiverResource
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReceiverResource\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBReceive\fP (octet *receiveBuffer, uint32_t receiveBufferCapacity, uint32_t &receiveBufferSize, \fBLocator_t\fP &originLocator)"
.br
.ti -1c
.RI "bool \fBSupportsLocator\fP (const \fBLocator_t\fP &localLocator)"
.br
.ti -1c
.RI "void \fBAbort\fP ()"
.br
.ti -1c
.RI "\fBReceiverResource\fP (\fBReceiverResource\fP &&)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNetworkFactory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII object that encapsulates the Receive operation over one chanel in an unknown transport\&. A Receiver resource is always univocally associated to a transport channel; the act of constructing a Receiver Resource opens the channel and its destruction closes it\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::ReceiverResource::ReceiverResource (\fBReceiverResource\fP &&)"
Resources can only be transfered through move semantics\&. Copy, assignment, and construction outside of the factory are forbidden\&. 
.SH "Member Function Documentation"
.PP 
.SS "void eprosima::fastrtps::rtps::ReceiverResource::Abort ()"
Aborts a blocking receive (thread safe)\&. 
.SS "bool eprosima::fastrtps::rtps::ReceiverResource::Receive (octet * receiveBuffer, uint32_t receiveBufferCapacity, uint32_t & receiveBufferSize, \fBLocator_t\fP & originLocator)"
Performs a blocking receive through the channel managed by this resource, notifying about the origin locator\&. 
.PP
\fBParameters\fP
.RS 4
\fIreceiveBuffer\fP Pointer to a buffer where to store the received message\&. 
.br
\fIreceiveBufferCapacity\fP Capacity of the reception buffer\&. Will be used as a boundary check for the previous parameter\&. 
.br
\fIreceiveBufferSize\fP Final size of the received message\&. 
.br
\fIoriginLocator\fP Address of the remote sender\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Success of the managed Receive operation\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::ReceiverResource::SupportsLocator (const \fBLocator_t\fP & localLocator)"
Reports whether this resource supports the given local locator (i\&.e\&., said locator maps to the transport channel managed by this resource)\&. 
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBNetworkFactory\fP\fC [friend]\fP"
Only \fBNetworkFactory\fP is ever allowed to construct a \fBReceiverResource\fP from scratch\&. In doing so, it guarantees the transport and channel are in a valid state for this resource to exist\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
