.TH "eprosima::fastrtps::rtps::RTPSParticipantDiscoveryInfo" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RTPSParticipantDiscoveryInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSParticipantDiscoveryInfo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDISCOVERY_STATUS\fP \fBm_status\fP"
.br
.RI "Status\&. "
.ti -1c
.RI "\fBGUID_t\fP \fBm_guid\fP"
.br
.RI "Associated GUID\&. "
.ti -1c
.RI "PropertyList \fBm_propertyList\fP"
.br
.RI "\fBProperty\fP list\&. "
.ti -1c
.RI "UserData \fBm_userData\fP"
.br
.RI "User data\&. "
.ti -1c
.RI "std::string \fBm_RTPSParticipantName\fP"
.br
.RI "\fBParticipant\fP name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBRTPSParticipantDiscoveryInfo\fP with discovery information of the RTPS \fBParticipant\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
