.TH "EprosimaServer" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EprosimaServer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOperationListener\fP"
.br
.ti -1c
.RI "class \fBResultListener\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBserve\fP ()"
.br
.ti -1c
.RI "void \fBserve\fP (uint32_t samples)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBm_n_served\fP"
.br
.ti -1c
.RI "\fBEprosimaServer::OperationListener\fP \fBm_operationsListener\fP"
.br
.ti -1c
.RI "\fBEprosimaServer::ResultListener\fP \fBm_resultsListener\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBOperationListener\fP"
.br
.ti -1c
.RI "class \fBResultListener\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
