.TH "eprosima::fastrtps::rtps::SimpleEDPAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::SimpleEDPAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSParticipantAttributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuse_PublicationWriterANDSubscriptionReader\fP"
.br
.RI "Default value true\&. "
.ti -1c
.RI "bool \fBuse_PublicationReaderANDSubscriptionWriter\fP"
.br
.RI "Default value true\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBSimpleEDPAttributes\fP, to define the attributes of the Simple \fBEndpoint\fP Discovery Protocol\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
