.TH "eprosima::fastrtps::rtps::Locator_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::Locator_t \- Class \fBLocator_t\fP, uniquely identifies a communication channel for a particular transport\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Locator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocator_t\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBLocator_t\fP (\fBLocator_t\fP &&loc)"
.br
.ti -1c
.RI "\fBLocator_t\fP (const \fBLocator_t\fP &loc)"
.br
.ti -1c
.RI "\fBLocator_t\fP (uint32_t portin)"
.br
.ti -1c
.RI "\fBLocator_t\fP & \fBoperator=\fP (const \fBLocator_t\fP &loc)"
.br
.ti -1c
.RI "bool \fBset_IP4_address\fP (octet o1, octet o2, octet o3, octet o4)"
.br
.ti -1c
.RI "bool \fBset_IP4_address\fP (const std::string &in_address)"
.br
.ti -1c
.RI "std::string \fBto_IP4_string\fP () const"
.br
.ti -1c
.RI "uint32_t \fBto_IP4_long\fP ()"
.br
.ti -1c
.RI "bool \fBset_IP6_address\fP (uint16_t group0, uint16_t group1, uint16_t group2, uint16_t group3, uint16_t group4, uint16_t group5, uint16_t group6, uint16_t group7)"
.br
.ti -1c
.RI "std::string \fBto_IP6_string\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBkind\fP"
.br
.RI "Specifies the locator type\&. Valid values are: LOCATOR_KIND_UDPv4 LOCATOR_KIND_UDPv6\&. "
.ti -1c
.RI "uint32_t \fBport\fP"
.br
.ti -1c
.RI "octet \fBaddress\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBLocator_t\fP, uniquely identifies a communication channel for a particular transport\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
