.TH "eprosima::fastrtps::Participant" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::Participant
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Participant\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBGUID_t\fP & \fBgetGuid\fP () const"
.br
.ti -1c
.RI "const \fBParticipantAttributes\fP & \fBgetAttributes\fP ()"
.br
.ti -1c
.RI "bool \fBnewRemoteEndpointDiscovered\fP (const \fBGUID_t\fP &partguid, uint16_t userId, \fBEndpointKind_t\fP kind)"
.br
.ti -1c
.RI "std::pair< \fBStatefulReader\fP *, \fBStatefulReader\fP * > \fBgetEDPReaders\fP ()"
.br
.ti -1c
.RI "std::vector< std::string > \fBgetParticipantNames\fP ()"
.br
.ti -1c
.RI "bool \fBget_remote_writer_info\fP (const \fBGUID_t\fP &writerGuid, \fBWriterProxyData\fP &returnedInfo)"
.br
.ti -1c
.RI "bool \fBget_remote_reader_info\fP (const \fBGUID_t\fP &readerGuid, \fBReaderProxyData\fP &returnedInfo)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDomain\fP"
.br
.ti -1c
.RI "class \fBParticipantImpl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBParticipant\fP used to group Publishers and Subscribers into a single working unit\&. 
.SH "Member Function Documentation"
.PP 
.SS "const \fBParticipantAttributes\fP& eprosima::fastrtps::Participant::getAttributes ()"
Get the \fBParticipantAttributes\fP\&. 
.PP
\fBReturns\fP
.RS 4
\fBParticipantAttributes\fP\&. 
.RE
.PP

.SS "std::pair<\fBStatefulReader\fP*,\fBStatefulReader\fP*> eprosima::fastrtps::Participant::getEDPReaders ()"
This method returns a pointer to the Endpoint Discovery Protocol Readers (when not in Static mode) SimpleEDP creates two readers, one for Publishers and one for Subscribers, and they are both returned as a std::pair of pointers\&. These readers in particular have modified listeners that allow a slave listener to attach its callbach to the original one, allowing for the addition of logging elements\&.
.PP
\fBReturns\fP
.RS 4
std::pair of pointers to the EDP Readers 
.RE
.PP

.SS "const \fBGUID_t\fP& eprosima::fastrtps::Participant::getGuid () const"
Get the GUID_t of the associated RTPSParticipant\&. 
.PP
\fBReturns\fP
.RS 4
GUID_t 
.RE
.PP

.SS "bool eprosima::fastrtps::Participant::newRemoteEndpointDiscovered (const \fBGUID_t\fP & partguid, uint16_t userId, \fBEndpointKind_t\fP kind)"
Called when using a StaticEndpointDiscovery mechanism different that the one included in FastRTPS, for example when communicating with other implementations\&. It indicates to the \fBParticipant\fP that an Endpoint from the XML has been discovered and should be activated\&. 
.PP
\fBParameters\fP
.RS 4
\fIpartguid\fP \fBParticipant\fP GUID_t\&. 
.br
\fIuserId\fP User defined ID as shown in the XML file\&. 
.br
\fIkind\fP EndpointKind (WRITER or READER) 
.RE
.PP
\fBReturns\fP
.RS 4
True if correctly found and activated\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
