.TH "eprosima::fastrtps::rtps::ReaderAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::ReaderAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReaderAttributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEndpointAttributes\fP \fBendpoint\fP"
.br
.RI "Attributes of the associated endpoint\&. "
.ti -1c
.RI "\fBReaderTimes\fP \fBtimes\fP"
.br
.RI "Times associated with this reader\&. "
.ti -1c
.RI "bool \fBexpectsInlineQos\fP"
.br
.RI "Indicates if the reader expects Inline qos, default value 0\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBReaderAttributes\fP, to define the attributes of a \fBRTPSReader\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
