.TH "eprosima::fastrtps::rtps::HistoryAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::HistoryAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HistoryAttributes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistoryAttributes\fP (\fBMemoryManagementPolicy_t\fP \fBmemoryPolicy\fP, uint32_t payload, int32_t initial, int32_t maxRes)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryManagementPolicy_t\fP \fBmemoryPolicy\fP"
.br
.RI "Memory management policy\&. "
.ti -1c
.RI "uint32_t \fBpayloadMaxSize\fP"
.br
.RI "Maximum payload size of the history, default value 500\&. "
.ti -1c
.RI "int32_t \fBinitialReservedCaches\fP"
.br
.RI "Number of the initial Reserved Caches, default value 500\&. "
.ti -1c
.RI "int32_t \fBmaximumReservedCaches\fP"
.br
.RI "Maximum number of reserved caches\&. Default value is 0 that indicates to keep reserving until something breaks\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBHistoryAttributes\fP, to specify the attributes of a \fBWriterHistory\fP or a \fBReaderHistory\fP\&. This class is only intended to be used with the RTPS API\&. The Publsiher-Subscriber API has other fields to define this values (\fBHistoryQosPolicy\fP and \fBResourceLimitsQosPolicy\fP)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::HistoryAttributes::HistoryAttributes (\fBMemoryManagementPolicy_t\fP memoryPolicy, uint32_t payload, int32_t initial, int32_t maxRes)\fC [inline]\fP"
Constructor 
.PP
\fBParameters\fP
.RS 4
\fImemoryPolicy\fP Set wether memory can be dynamically reallocated or not 
.br
\fIpayload\fP Maximum payload size\&. It is used when memory management polycy is PREALLOCATED_MEMORY_MODE or PREALLOCATED_WITH_REALLOC_MEMORY_MODE\&. 
.br
\fIinitial\fP Initial reserved caches\&. It is used when memory management policy is PREALLOCATED_MEMORY_MODE or PREALLOCATED_WITH_REALLOC_MEMORY_MODE\&. 
.br
\fImaxRes\fP Maximum reserved caches\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
