.TH "eprosima::fastrtps::rtps::SampleIdentity" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::SampleIdentity \- This class is used to specify a sample\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SampleIdentity\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleIdentity\fP ()"
.br
.RI "Default constructor\&. Constructs an unknown \fBSampleIdentity\fP\&. "
.ti -1c
.RI "\fBSampleIdentity\fP (const \fBSampleIdentity\fP &sample_id)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBSampleIdentity\fP (\fBSampleIdentity\fP &&sample_id)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "\fBSampleIdentity\fP & \fBoperator=\fP (const \fBSampleIdentity\fP &sample_id)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fBSampleIdentity\fP & \fBoperator=\fP (\fBSampleIdentity\fP &&sample_id)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSampleIdentity\fP &sample_id) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBSampleIdentity\fP &sample_id) const"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBwriter_guid\fP (const \fBGUID_t\fP &guid)"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBwriter_guid\fP (\fBGUID_t\fP &&guid)"
.br
.ti -1c
.RI "const \fBGUID_t\fP & \fBwriter_guid\fP () const"
.br
.ti -1c
.RI "\fBGUID_t\fP & \fBwriter_guid\fP ()"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBsequence_number\fP (const \fBSequenceNumber_t\fP &seq)"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBsequence_number\fP (\fBSequenceNumber_t\fP &&seq)"
.br
.ti -1c
.RI "const \fBSequenceNumber_t\fP & \fBsequence_number\fP () const"
.br
.ti -1c
.RI "\fBSequenceNumber_t\fP & \fBsequence_number\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSampleIdentity\fP \fBunknown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to specify a sample\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
