.TH "eprosima::fastrtps::ParticipantAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::ParticipantAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParticipantAttributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRTPSParticipantAttributes\fP \fBrtps\fP"
.br
.RI "Attributes of the associated RTPSParticipant\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBParticipantAttributes\fP, used by the user to define the attributes of a \fBParticipant\fP\&. The Participants in the Publisher-Subscriber layer are only a container to a RTPSParticipant, so their attributes are the same\&. Still to maintain the equivalence this class is used to define them\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
