.TH "eprosima::fastrtps::rtps::StatefulWriter" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::StatefulWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StatefulWriter\&.h>\fP
.PP
Inherits \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~StatefulWriter\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBunsent_change_added_to_history\fP (\fBCacheChange_t\fP *p)"
.br
.ti -1c
.RI "bool \fBchange_removed_by_history\fP (\fBCacheChange_t\fP *a_change)"
.br
.ti -1c
.RI "void \fBsend_any_unsent_changes\fP ()"
.br
.ti -1c
.RI "void \fBincrementHBCount\fP ()"
.br
.RI "Increment the HB count\&. "
.ti -1c
.RI "bool \fBmatched_reader_add\fP (\fBRemoteReaderAttributes\fP &ratt)"
.br
.ti -1c
.RI "bool \fBmatched_reader_remove\fP (\fBRemoteReaderAttributes\fP &ratt)"
.br
.ti -1c
.RI "bool \fBmatched_reader_is_matched\fP (\fBRemoteReaderAttributes\fP &ratt)"
.br
.ti -1c
.RI "bool \fBis_acked_by_all\fP (\fBCacheChange_t\fP *a_change)"
.br
.ti -1c
.RI "bool \fBwait_for_all_acked\fP (const \fBDuration_t\fP &max_wait)"
.br
.ti -1c
.RI "void \fBcheck_for_all_acked\fP ()"
.br
.ti -1c
.RI "bool \fBclean_history\fP (unsigned int max=0)"
.br
.ti -1c
.RI "void \fBupdateAttributes\fP (\fBWriterAttributes\fP &att)"
.br
.ti -1c
.RI "bool \fBmatched_reader_lookup\fP (\fBGUID_t\fP &readerGuid, \fBReaderProxy\fP **RP)"
.br
.ti -1c
.RI "Count_t \fBgetHeartbeatCount\fP () const"
.br
.ti -1c
.RI "\fBEntityId_t\fP \fBgetHBReaderEntityId\fP ()"
.br
.ti -1c
.RI "std::vector< \fBReaderProxy\fP * >::iterator \fBmatchedReadersBegin\fP ()"
.br
.ti -1c
.RI "std::vector< \fBReaderProxy\fP * >::iterator \fBmatchedReadersEnd\fP ()"
.br
.ti -1c
.RI "RTPSParticipantImpl * \fBgetRTPSParticipant\fP () const"
.br
.ti -1c
.RI "size_t \fBgetMatchedReadersSize\fP () const"
.br
.ti -1c
.RI "void \fBupdateTimes\fP (\fBWriterTimes\fP &times)"
.br
.ti -1c
.RI "void \fBadd_flow_controller\fP (std::unique_ptr< FlowController > controller)"
.br
.ti -1c
.RI "\fBSequenceNumber_t\fP \fBnext_sequence_number\fP () const"
.br
.ti -1c
.RI "void \fBsend_heartbeat_to_nts\fP (\fBReaderProxy\fP &remoteReaderProxy, bool final=false)"
.br
.RI "Sends a heartbeat to a remote reader\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPeriodicHeartbeat\fP * \fBmp_periodicHB\fP"
.br
.RI "Timed Event to manage the periodic HB to the Reader\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRTPSParticipantImpl\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBStatefulWriter\fP, specialization of \fBRTPSWriter\fP that maintains information of each matched Reader\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::rtps::StatefulWriter::change_removed_by_history (\fBCacheChange_t\fP * a_change)\fC [virtual]\fP"
Indicate the writer that a change has been removed by the history due to some HistoryQos requirement\&. 
.PP
\fBParameters\fP
.RS 4
\fIa_change\fP Pointer to the change that is going to be removed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if removed correctly\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "\fBEntityId_t\fP eprosima::fastrtps::rtps::StatefulWriter::getHBReaderEntityId ()\fC [inline]\fP"
Get heartbeat reader entity id 
.PP
\fBReturns\fP
.RS 4
heartbeat reader entity id 
.RE
.PP

.SS "Count_t eprosima::fastrtps::rtps::StatefulWriter::getHeartbeatCount () const\fC [inline]\fP"
Get count of heartbeats 
.PP
\fBReturns\fP
.RS 4
count of heartbeats 
.RE
.PP

.SS "size_t eprosima::fastrtps::rtps::StatefulWriter::getMatchedReadersSize () const\fC [inline]\fP"
Get the number of matched readers 
.PP
\fBReturns\fP
.RS 4
Number of the matched readers 
.RE
.PP

.SS "RTPSParticipantImpl* eprosima::fastrtps::rtps::StatefulWriter::getRTPSParticipant () const\fC [inline]\fP"
Get the RTPS participant 
.PP
\fBReturns\fP
.RS 4
RTPS participant 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::StatefulWriter::is_acked_by_all (\fBCacheChange_t\fP * a_change)\fC [virtual]\fP"
Remove the change with the minimum SequenceNumber 
.PP
\fBReturns\fP
.RS 4
True if removed\&. 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "bool eprosima::fastrtps::rtps::StatefulWriter::matched_reader_add (\fBRemoteReaderAttributes\fP & ratt)\fC [virtual]\fP"
Add a matched reader\&. 
.PP
\fBParameters\fP
.RS 4
\fIratt\fP Attributes of the reader to add\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if added\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "bool eprosima::fastrtps::rtps::StatefulWriter::matched_reader_is_matched (\fBRemoteReaderAttributes\fP & ratt)\fC [virtual]\fP"
Tells us if a specific Reader is matched against this writer 
.PP
\fBParameters\fP
.RS 4
\fIratt\fP Attributes of the reader to remove\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if it was matched\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "bool eprosima::fastrtps::rtps::StatefulWriter::matched_reader_lookup (\fBGUID_t\fP & readerGuid, \fBReaderProxy\fP ** RP)"
Find a Reader Proxy in this writer\&. 
.PP
\fBParameters\fP
.RS 4
\fIreaderGuid\fP The \fBGUID_t\fP of the reader\&. 
.br
\fIRP\fP Pointer to pointer to return the \fBReaderProxy\fP\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::StatefulWriter::matched_reader_remove (\fBRemoteReaderAttributes\fP & ratt)\fC [virtual]\fP"
Remove a matched reader\&. 
.PP
\fBParameters\fP
.RS 4
\fIratt\fP Attributes of the reader to remove\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if removed\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "std::vector<\fBReaderProxy\fP*>::iterator eprosima::fastrtps::rtps::StatefulWriter::matchedReadersBegin ()\fC [inline]\fP"
Get the begin of the matched readers 
.PP
\fBReturns\fP
.RS 4
A vector iterator pointing to de begin of the matched readers list 
.RE
.PP

.SS "std::vector<\fBReaderProxy\fP*>::iterator eprosima::fastrtps::rtps::StatefulWriter::matchedReadersEnd ()\fC [inline]\fP"
Get the end of the matched readers 
.PP
\fBReturns\fP
.RS 4
A vector iterator pointing to de end of the matched readers list 
.RE
.PP

.SS "void eprosima::fastrtps::rtps::StatefulWriter::send_any_unsent_changes ()\fC [virtual]\fP"
Method to indicate that there are changes not sent in some of all \fBReaderProxy\fP\&. 
.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "void eprosima::fastrtps::rtps::StatefulWriter::send_heartbeat_to_nts (\fBReaderProxy\fP & remoteReaderProxy, bool final = \fCfalse\fP)"

.PP
Sends a heartbeat to a remote reader\&. 
.PP
\fBRemarks\fP
.RS 4
This function is non thread-safe\&. 
.RE
.PP

.SS "void eprosima::fastrtps::rtps::StatefulWriter::unsent_change_added_to_history (\fBCacheChange_t\fP * p)\fC [virtual]\fP"
Add a specific change to all ReaderLocators\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP Pointer to the change\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "void eprosima::fastrtps::rtps::StatefulWriter::updateAttributes (\fBWriterAttributes\fP & att)\fC [virtual]\fP"
Update the Attributes of the Writer\&. 
.PP
\fBParameters\fP
.RS 4
\fIatt\fP New attributes 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::RTPSWriter\fP\&.
.SS "void eprosima::fastrtps::rtps::StatefulWriter::updateTimes (\fBWriterTimes\fP & times)"
Update the \fBWriterTimes\fP attributes of all associated \fBReaderProxy\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fItimes\fP \fBWriterTimes\fP parameter\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
