.TH "eprosima::fastrtps::xmlparser::XMLProfileParser" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::xmlparser::XMLProfileParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <XMLProfileParser\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBloadDefaultXMLFile\fP ()"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBloadXMLFile\fP (const std::string &filename)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBfillParticipantAttributes\fP (const std::string &profile_name, \fBParticipantAttributes\fP &atts)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBfillPublishertAttributes\fP (const std::string &profile_name, \fBPublisherAttributes\fP &atts)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBfillSubscribertAttributes\fP (const std::string &profile_name, \fBSubscriberAttributes\fP &atts)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBparseXMLParticipantProf\fP (XMLElement *p_profile, \fBParticipantAttributes\fP &participant_atts, std::string &profile_name)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBparseXMLPublisherProf\fP (XMLElement *p_profile, \fBPublisherAttributes\fP &publisher_atts, std::string &profile_name)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBparseXMLSubscriberProf\fP (XMLElement *p_profile, \fBSubscriberAttributes\fP &subscriber_atts, std::string &profile_name)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLPropertiesPolicy\fP (XMLElement *elem, \fBPropertyPolicy\fP &propertiesPolicy, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLHistoryMemoryPolicy\fP (XMLElement *elem, \fBMemoryManagementPolicy_t\fP &historyMemoryPolicy, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLLocatorList\fP (XMLElement *elem, \fBLocatorList_t\fP &locatorList, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLWriterTimes\fP (XMLElement *elem, \fBWriterTimes\fP &times, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLReaderTimes\fP (XMLElement *elem, \fBReaderTimes\fP &times, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLDuration\fP (XMLElement *elem, \fBDuration_t\fP &duration, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLWriterQosPolicies\fP (XMLElement *elem, \fBWriterQos\fP &qos, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLReaderQosPolicies\fP (XMLElement *elem, \fBReaderQos\fP &qos, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLPublishModeQos\fP (XMLElement *elem, \fBPublishModeQosPolicy\fP &publishMode, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLGroupDataQos\fP (XMLElement *elem, \fBGroupDataQosPolicy\fP &groupData, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLTopicDataQos\fP (XMLElement *elem, \fBTopicDataQosPolicy\fP &topicData, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLPartitionQos\fP (XMLElement *elem, \fBPartitionQosPolicy\fP &partition, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLPresentationQos\fP (XMLElement *elem, \fBPresentationQosPolicy\fP &presentation, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLDestinationOrderQos\fP (XMLElement *elem, \fBDestinationOrderQosPolicy\fP &destinationOrder, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLOwnershipStrengthQos\fP (XMLElement *elem, \fBOwnershipStrengthQosPolicy\fP &ownershipStrength, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLOwnershipQos\fP (XMLElement *elem, \fBOwnershipQosPolicy\fP &ownership, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLTimeBasedFilterQos\fP (XMLElement *elem, \fBTimeBasedFilterQosPolicy\fP &timeBasedFilter, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLUserDataQos\fP (XMLElement *elem, \fBUserDataQosPolicy\fP &userData, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLLifespanQos\fP (XMLElement *elem, \fBLifespanQosPolicy\fP &lifespan, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLReliabilityQos\fP (XMLElement *elem, \fBReliabilityQosPolicy\fP &reliability, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLLivelinessQos\fP (XMLElement *elem, \fBLivelinessQosPolicy\fP &liveliness, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLLatencyBudgetQos\fP (XMLElement *elem, \fBLatencyBudgetQosPolicy\fP &latencyBudget, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLDeadlineQos\fP (XMLElement *elem, \fBDeadlineQosPolicy\fP &deadline, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLDurabilityServiceQos\fP (XMLElement *elem, \fBDurabilityServiceQosPolicy\fP &durabilityService, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLDurabilityQos\fP (XMLElement *elem, \fBDurabilityQosPolicy\fP &durability, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLTopicAttributes\fP (XMLElement *elem, \fBTopicAttributes\fP &topic, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLHistoryQosPolicy\fP (XMLElement *elem, \fBHistoryQosPolicy\fP &historyQos, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLResourceLimitsQos\fP (XMLElement *elem, \fBResourceLimitsQosPolicy\fP &resourceLimitsQos, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLThroughputController\fP (XMLElement *elem, \fBThroughputControllerDescriptor\fP &throughputController, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLPortParameters\fP (XMLElement *elem, \fBPortParameters\fP &port, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLBuiltinAttributes\fP (XMLElement *elem, \fBBuiltinAttributes\fP &builtin, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLOctetVector\fP (XMLElement *elem, std::vector< octet > &octetVector, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLInt\fP (XMLElement *elem, int *i, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLUint\fP (XMLElement *elem, unsigned int *ui, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLUint\fP (XMLElement *elem, uint16_t *ui16, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLBool\fP (XMLElement *elem, bool *b, uint8_t ident)"
.br
.ti -1c
.RI "static RTPS_DllAPI XMLP_ret \fBgetXMLString\fP (XMLElement *elem, std::string *s, uint8_t ident)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBXMLProfileParser\fP, used to load profiles from XML file\&. 
.SH "Member Function Documentation"
.PP 
.SS "static RTPS_DllAPI XMLP_ret eprosima::fastrtps::xmlparser::XMLProfileParser::fillParticipantAttributes (const std::string & profile_name, \fBParticipantAttributes\fP & atts)\fC [static]\fP"
Search for the profile specified and fill the structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIprofile_name\fP Name for the profile to be used to fill the structure\&. 
.br
\fIatts\fP Structure to be filled\&. 
.RE
.PP
\fBReturns\fP
.RS 4
XMLP_ret::XML_OK on success, XMLP_ret::XML_ERROR in other case\&. 
.RE
.PP

.SS "static RTPS_DllAPI XMLP_ret eprosima::fastrtps::xmlparser::XMLProfileParser::fillPublishertAttributes (const std::string & profile_name, \fBPublisherAttributes\fP & atts)\fC [static]\fP"
Search for the profile specified and fill the structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIprofile_name\fP Name for the profile to be used to fill the structure\&. 
.br
\fIatts\fP Structure to be filled\&. 
.RE
.PP
\fBReturns\fP
.RS 4
XMLP_ret::XML_OK on success, XMLP_ret::XML_ERROR in other case\&. 
.RE
.PP

.SS "static RTPS_DllAPI XMLP_ret eprosima::fastrtps::xmlparser::XMLProfileParser::fillSubscribertAttributes (const std::string & profile_name, \fBSubscriberAttributes\fP & atts)\fC [static]\fP"
Search for the profile specified and fill the structure\&. 
.PP
\fBParameters\fP
.RS 4
\fIprofile_name\fP Name for the profile to be used to fill the structure\&. 
.br
\fIatts\fP Structure to be filled\&. 
.RE
.PP
\fBReturns\fP
.RS 4
XMLP_ret::XML_OK on success, XMLP_ret::XML_ERROR in other case\&. 
.RE
.PP

.SS "static RTPS_DllAPI XMLP_ret eprosima::fastrtps::xmlparser::XMLProfileParser::loadDefaultXMLFile ()\fC [static]\fP"
Load the default profiles XML file\&. 
.PP
\fBReturns\fP
.RS 4
XMLP_ret::XML_OK on success, XMLP_ret::XML_ERROR in other case\&. 
.RE
.PP

.SS "static RTPS_DllAPI XMLP_ret eprosima::fastrtps::xmlparser::XMLProfileParser::loadXMLFile (const std::string & filename)\fC [static]\fP"
Load a profiles XML file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP Name for the file to be loaded\&. 
.RE
.PP
\fBReturns\fP
.RS 4
XMLP_ret::XML_OK on success, XMLP_ret::XML_ERROR in other case\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
