.TH "eprosima::fastrtps::PublisherListener" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::PublisherListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PublisherListener\&.h>\fP
.PP
Inherited by \fBEprosimaServer::ResultListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBonPublicationMatched\fP (\fBPublisher\fP *pub, \fBMatchingInfo\fP &info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBPublisherListener\fP, allows the end user to implement callbacks triggered by certain events\&.
.PP
.PP
.nf
.fi
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void eprosima::fastrtps::PublisherListener::onPublicationMatched (\fBPublisher\fP * pub, \fBMatchingInfo\fP & info)\fC [inline]\fP, \fC [virtual]\fP"
This method is called when the \fBPublisher\fP is matched (or unmatched) against an endpoint\&. 
.PP
\fBParameters\fP
.RS 4
\fIpub\fP Pointer to the associated \fBPublisher\fP 
.br
\fIinfo\fP Information regarding the matched subscriber 
.RE
.PP

.PP
Reimplemented in \fBEprosimaServer::ResultListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
