.TH "eprosima::fastrtps::rtps::security::HandleImpl< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::HandleImpl< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeprosima::fastrtps::rtps::security::Handle\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBtype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBnil\fP () const"
.br
.ti -1c
.RI "T * \fBoperator*\fP ()"
.br
.ti -1c
.RI "const T * \fBoperator*\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBHandleImpl\fP< T > & \fBnarrow\fP (\fBHandle\fP &handle)"
.br
.ti -1c
.RI "static const \fBHandleImpl\fP< T > & \fBnarrow\fP (const \fBHandle\fP &handle)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBHandleImpl\fP< T > \fBnil_handle\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
