.TH "eprosima::fastrtps::SampleInfo_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::SampleInfo_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SampleInfo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChangeKind_t\fP \fBsampleKind\fP"
.br
.RI "Sample kind\&. "
.ti -1c
.RI "uint16_t \fBownershipStrength\fP"
.br
.RI "Ownership Strength of the writer of the sample (0 if the ownership kind is set to SHARED_OWNERSHIP_QOS)\&. "
.ti -1c
.RI "\fBTime_t\fP \fBsourceTimestamp\fP"
.br
.RI "Source timestamp of the sample\&. "
.ti -1c
.RI "\fBInstanceHandle_t\fP \fBiHandle\fP"
.br
.RI "InstanceHandle of the data\&. "
.ti -1c
.RI "\fBSampleIdentity\fP \fBsample_identity\fP"
.br
.ti -1c
.RI "\fBSampleIdentity\fP \fBrelated_sample_identity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBSampleInfo_t\fP with information that is provided along a sample when reading data from a \fBSubscriber\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
