.TH "eprosima::fastrtps::rtps::BuiltinProtocols" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::BuiltinProtocols
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BuiltinProtocols\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitBuiltinProtocols\fP (RTPSParticipantImpl *p_part, \fBBuiltinAttributes\fP &attributes)"
.br
.ti -1c
.RI "bool \fBupdateMetatrafficLocators\fP (\fBLocatorList_t\fP &loclist)"
.br
.ti -1c
.RI "bool \fBaddLocalWriter\fP (\fBRTPSWriter\fP *w, \fBTopicAttributes\fP &topicAtt, \fBWriterQos\fP &wqos)"
.br
.ti -1c
.RI "bool \fBaddLocalReader\fP (\fBRTPSReader\fP *R, \fBTopicAttributes\fP &topicAtt, \fBReaderQos\fP &rqos)"
.br
.ti -1c
.RI "bool \fBupdateLocalWriter\fP (\fBRTPSWriter\fP *W, \fBWriterQos\fP &wqos)"
.br
.ti -1c
.RI "bool \fBupdateLocalReader\fP (\fBRTPSReader\fP *R, \fBReaderQos\fP &qos)"
.br
.ti -1c
.RI "bool \fBremoveLocalWriter\fP (\fBRTPSWriter\fP *W)"
.br
.ti -1c
.RI "bool \fBremoveLocalReader\fP (\fBRTPSReader\fP *R)"
.br
.ti -1c
.RI "void \fBannounceRTPSParticipantState\fP ()"
.br
.RI "Announce RTPSParticipantState (force the sending of a DPD message\&.) "
.ti -1c
.RI "void \fBstopRTPSParticipantAnnouncement\fP ()"
.br
.RI "Stop the \fBRTPSParticipant\fP Announcement (used in tests to avoid multiple packets being send) "
.ti -1c
.RI "void \fBresetRTPSParticipantAnnouncement\fP ()"
.br
.RI "Reset to timer to make periodic \fBRTPSParticipant\fP Announcements\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBuiltinAttributes\fP \fBm_att\fP"
.br
.RI "\fBBuiltinAttributes\fP of the builtin protocols\&. "
.ti -1c
.RI "RTPSParticipantImpl * \fBmp_participantImpl\fP"
.br
.RI "Pointer to the RTPSParticipantImpl\&. "
.ti -1c
.RI "\fBPDPSimple\fP * \fBmp_PDP\fP"
.br
.RI "Pointer to the \fBPDPSimple\fP\&. "
.ti -1c
.RI "\fBWLP\fP * \fBmp_WLP\fP"
.br
.RI "Pointer to the \fBWLP\fP\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBm_metatrafficMulticastLocatorList\fP"
.br
.RI "Locator list for metatraffic\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBm_metatrafficUnicastLocatorList\fP"
.br
.RI "Locator List for metatraffic unicast\&. "
.ti -1c
.RI "\fBLocatorList_t\fP \fBm_initialPeersList\fP"
.br
.RI "Initial peers\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBRTPSParticipantImpl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBBuiltinProtocols\fP that contains builtin endpoints implementing the discovery and liveliness protocols\&.
.IP "\(bu" 2

.PP

.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::addLocalReader (\fBRTPSReader\fP * R, \fBTopicAttributes\fP & topicAtt, \fBReaderQos\fP & rqos)"
Add a local Reader to the \fBBuiltinProtocols\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIR\fP Pointer to the \fBRTPSReader\fP\&. 
.br
\fItopicAtt\fP Attributes of the associated topic 
.br
\fIrqos\fP QoS policies dictated by the subscriber 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::addLocalWriter (\fBRTPSWriter\fP * w, \fBTopicAttributes\fP & topicAtt, \fBWriterQos\fP & wqos)"
Add a local Writer to the \fBBuiltinProtocols\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIw\fP Pointer to the \fBRTPSWriter\fP 
.br
\fItopicAtt\fP Attributes of the associated topic 
.br
\fIwqos\fP QoS policies dictated by the publisher 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::initBuiltinProtocols (RTPSParticipantImpl * p_part, \fBBuiltinAttributes\fP & attributes)"
Initialize the builtin protocols\&. 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP Discovery configuration attributes 
.br
\fIp_part\fP Pointer to the \fBParticipant\fP implementation 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::removeLocalReader (\fBRTPSReader\fP * R)"
Remove a local Reader from the builtinProtocols\&. 
.PP
\fBParameters\fP
.RS 4
\fIR\fP Pointer to the reader\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correctly removed\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::removeLocalWriter (\fBRTPSWriter\fP * W)"
Remove a local Writer from the builtinProtocols\&. 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Pointer to the writer\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correctly removed\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::updateLocalReader (\fBRTPSReader\fP * R, \fBReaderQos\fP & qos)"
Update a local Reader QOS 
.PP
\fBParameters\fP
.RS 4
\fIR\fP Reader to update 
.br
\fIqos\fP New Reader QoS 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::updateLocalWriter (\fBRTPSWriter\fP * W, \fBWriterQos\fP & wqos)"
Update a local Writer QOS 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Writer to update 
.br
\fIwqos\fP New Writer QoS 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::BuiltinProtocols::updateMetatrafficLocators (\fBLocatorList_t\fP & loclist)"
Update the metatraffic locatorlist after it was created\&. Because when you create the \fBEDP\fP readers you are not sure the selected endpoints can be used\&. 
.PP
\fBParameters\fP
.RS 4
\fIloclist\fP LocatorList to update 
.RE
.PP
\fBReturns\fP
.RS 4
True on success 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
