.TH "eprosima::fastrtps::rtps::WriteParams" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::WriteParams \- This class contains additional information of a CacheChange\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WriteParams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteParams\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBWriteParams\fP (const \fBWriteParams\fP &wparam)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBWriteParams\fP (\fBWriteParams\fP &&wparam)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "\fBWriteParams\fP & \fBoperator=\fP (const \fBWriteParams\fP &wparam)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fBWriteParams\fP & \fBoperator=\fP (\fBWriteParams\fP &&wparam)"
.br
.RI "Assignment operator\&. "
.ti -1c
.RI "\fBWriteParams\fP & \fBsample_identity\fP (const \fBSampleIdentity\fP &sample_id)"
.br
.ti -1c
.RI "\fBWriteParams\fP & \fBsample_identity\fP (\fBSampleIdentity\fP &&sample_id)"
.br
.ti -1c
.RI "const \fBSampleIdentity\fP & \fBsample_identity\fP () const"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBsample_identity\fP ()"
.br
.ti -1c
.RI "\fBWriteParams\fP & \fBrelated_sample_identity\fP (const \fBSampleIdentity\fP &sample_id)"
.br
.ti -1c
.RI "\fBWriteParams\fP & \fBrelated_sample_identity\fP (\fBSampleIdentity\fP &&sample_id)"
.br
.ti -1c
.RI "const \fBSampleIdentity\fP & \fBrelated_sample_identity\fP () const"
.br
.ti -1c
.RI "\fBSampleIdentity\fP & \fBrelated_sample_identity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class contains additional information of a CacheChange\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
