.TH "eprosima::fastrtps::rtps::RTPSMessageGroup" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RTPSMessageGroup
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSMessageGroup\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBENDPOINT_TYPE\fP { \fBWRITER\fP, \fBREADER\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRTPSMessageGroup\fP (RTPSParticipantImpl *participant, \fBEndpoint\fP *endpoint, ENDPOINT_TYPE, \fBRTPSMessageGroup_t\fP &msg_group)"
.br
.ti -1c
.RI "bool \fBadd_data\fP (const \fBCacheChange_t\fP &change, const std::vector< \fBGUID_t\fP > &remote_readers, const \fBLocatorList_t\fP &locators, bool expectsInlineQos)"
.br
.ti -1c
.RI "bool \fBadd_data_frag\fP (const \fBCacheChange_t\fP &change, const uint32_t fragment_number, const std::vector< \fBGUID_t\fP > &remote_readers, const \fBLocatorList_t\fP &locators, bool expectsInlineQos)"
.br
.ti -1c
.RI "bool \fBadd_heartbeat\fP (const std::vector< \fBGUID_t\fP > &remote_readers, const \fBSequenceNumber_t\fP &firstSN, const \fBSequenceNumber_t\fP &lastSN, Count_t count, bool isFinal, bool livelinessFlag, const \fBLocatorList_t\fP &locators)"
.br
.ti -1c
.RI "bool \fBadd_gap\fP (std::set< \fBSequenceNumber_t\fP > &changesSeqNum, const std::vector< \fBGUID_t\fP > &remote_readers, const \fBLocatorList_t\fP &locators)"
.br
.ti -1c
.RI "bool \fBadd_acknack\fP (const \fBGUID_t\fP &remote_writer, \fBSequenceNumberSet_t\fP &SNSet, int32_t count, bool finalFlag, const \fBLocatorList_t\fP &locators)"
.br
.ti -1c
.RI "bool \fBadd_nackfrag\fP (const \fBGUID_t\fP &remote_writer, \fBSequenceNumber_t\fP &writerSN, \fBFragmentNumberSet_t\fP fnState, int32_t count, const \fBLocatorList_t\fP locators)"
.br
.ti -1c
.RI "uint32_t \fBget_current_bytes_processed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRTPSMessageGroup\fP Class used to construct a RTPS message\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
