.TH "eprosima::fastrtps::StdoutConsumer" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::StdoutConsumer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeprosima::fastrtps::LogConsumer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual RTPS_DllAPI void \fBConsume\fP (const \fBLog::Entry\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
