.TH "eprosima::fastrtps::rtps::FragmentNumberSet_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::FragmentNumberSet_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FragmentNumber\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFragmentNumberSet_t\fP & \fBoperator=\fP (const \fBFragmentNumberSet_t\fP &set2)"
.br
.ti -1c
.RI "\fBFragmentNumberSet_t\fP (const std::set< FragmentNumber_t > &set2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFragmentNumberSet_t\fP &other)"
.br
.ti -1c
.RI "bool \fBadd\fP (FragmentNumber_t in)"
.br
.ti -1c
.RI "bool \fBisSetEmpty\fP () const"
.br
.ti -1c
.RI "std::set< FragmentNumber_t >::const_iterator \fBget_begin\fP () const"
.br
.ti -1c
.RI "std::set< FragmentNumber_t >::const_iterator \fBget_end\fP () const"
.br
.ti -1c
.RI "size_t \fBget_size\fP ()"
.br
.ti -1c
.RI "std::string \fBprint\fP ()"
.br
.ti -1c
.RI "\fBFragmentNumberSet_t\fP & \fBoperator\-=\fP (const \fBFragmentNumberSet_t\fP &rhs)"
.br
.ti -1c
.RI "\fBFragmentNumberSet_t\fP & \fBoperator\-=\fP (const FragmentNumber_t &fragment_number)"
.br
.ti -1c
.RI "\fBFragmentNumberSet_t\fP & \fBoperator+=\fP (const \fBFragmentNumberSet_t\fP &rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FragmentNumber_t \fBbase\fP"
.br
.RI "\fBBase\fP fragment number\&. "
.ti -1c
.RI "std::set< FragmentNumber_t > \fBset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBFragmentNumberSet_t\fP, contains a group of fragmentnumbers\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::rtps::FragmentNumberSet_t::add (FragmentNumber_t in)\fC [inline]\fP"
Add a fragment number to the set 
.PP
\fBParameters\fP
.RS 4
\fIin\fP \fBFragmentNumberSet_t\fP to add 
.RE
.PP
\fBReturns\fP
.RS 4
True on success 
.RE
.PP

.SS "std::set<FragmentNumber_t>::const_iterator eprosima::fastrtps::rtps::FragmentNumberSet_t::get_begin () const\fC [inline]\fP"
Get the begin of the set 
.PP
\fBReturns\fP
.RS 4
Vector iterator pointing to the begin of the set 
.RE
.PP

.SS "std::set<FragmentNumber_t>::const_iterator eprosima::fastrtps::rtps::FragmentNumberSet_t::get_end () const\fC [inline]\fP"
Get the end of the set 
.PP
\fBReturns\fP
.RS 4
Vector iterator pointing to the end of the set 
.RE
.PP

.SS "size_t eprosima::fastrtps::rtps::FragmentNumberSet_t::get_size ()\fC [inline]\fP"
Get the number of FragmentNumbers in the set 
.PP
\fBReturns\fP
.RS 4
Size of the set 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::FragmentNumberSet_t::isSetEmpty () const\fC [inline]\fP"
Check if the set is empty 
.PP
\fBReturns\fP
.RS 4
True if the set is empty 
.RE
.PP

.SS "\fBFragmentNumberSet_t\fP& eprosima::fastrtps::rtps::FragmentNumberSet_t::operator= (const \fBFragmentNumberSet_t\fP & set2)\fC [inline]\fP"
Assignment operator 
.PP
\fBParameters\fP
.RS 4
\fIset2\fP \fBFragmentNumberSet_t\fP to copy the data from 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::FragmentNumberSet_t::operator== (const \fBFragmentNumberSet_t\fP & other)\fC [inline]\fP"
Compares object with other \fBFragmentNumberSet_t\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP \fBFragmentNumberSet_t\fP to compare 
.RE
.PP
\fBReturns\fP
.RS 4
True if equal 
.RE
.PP

.SS "std::string eprosima::fastrtps::rtps::FragmentNumberSet_t::print ()\fC [inline]\fP"
Get a string representation of the set 
.PP
\fBReturns\fP
.RS 4
string representation of the set 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
