.TH "eprosima::fastrtps::rtps::Header_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::Header_t \- Structure \fBHeader_t\fP, RTPS Message Header Structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPS_messages\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProtocolVersion_t\fP \fBversion\fP"
.br
.RI "Protocol version\&. "
.ti -1c
.RI "\fBVendorId_t\fP \fBvendorId\fP"
.br
.RI "Vendor ID\&. "
.ti -1c
.RI "\fBGuidPrefix_t\fP \fBguidPrefix\fP"
.br
.RI "GUID prefix\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBHeader_t\fP, RTPS Message Header Structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
