.TH "eprosima::fastrtps::IPFinder::info_IP" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::IPFinder::info_IP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IPFinder\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIPTYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBscope_id\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBLocator_t\fP \fBlocator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBinfo_IP\fP with information about a specific IP obtained from a NIC\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
