.TH "eprosima::fastrtps::ParameterList_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::ParameterList_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParameterList\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterList_t\fP (const \fBParameterList_t\fP &plist)"
.br
.ti -1c
.RI "void \fBdeleteParams\fP ()"
.br
.ti -1c
.RI "void \fBresetList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBParameter_t\fP * > \fBm_parameters\fP"
.br
.RI "Vector of the pointers to the parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBParameterList_t\fP class, used to store multiple parameters as a vector of pointers to the base class\&. 
.SH "Member Function Documentation"
.PP 
.SS "void eprosima::fastrtps::ParameterList_t::deleteParams ()\fC [inline]\fP"
Delete all parameters in the list\&. 
.SS "void eprosima::fastrtps::ParameterList_t::resetList ()\fC [inline]\fP"
Reset the list of parameters (without deleting them, since they can be in use in another list)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
