.TH "eprosima::fastrtps::rtps::RemoteWriterAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RemoteWriterAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReaderAttributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEndpointAttributes\fP \fBendpoint\fP"
.br
.RI "Attributes of the associated endpoint\&. "
.ti -1c
.RI "\fBGUID_t\fP \fBguid\fP"
.br
.RI "\fBGUID_t\fP of the writer, can be unknown if the reader is best effort\&. "
.ti -1c
.RI "\fBDuration_t\fP \fBlivelinessLeaseDuration\fP"
.br
.RI "Liveliness lease duration, default value c_TimeInfinite\&. "
.ti -1c
.RI "uint16_t \fBownershipStrength\fP"
.br
.RI "Ownership Strength of the associated writer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBRemoteWriterAttributes\fP, to define the attributes of a Remote Writer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
