.TH "EprosimaClientTest" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EprosimaClientTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBrun\fP (int samples)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEprosimaClient\fP \fBm_client\fP"
.br
.ti -1c
.RI "\fBeClock\fP \fBm_clock\fP"
.br
.ti -1c
.RI "\fBTime_t\fP \fBm_t1\fP"
.br
.ti -1c
.RI "\fBTime_t\fP \fBm_t2\fP"
.br
.ti -1c
.RI "double \fBm_overhead\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
