.TH "eprosima::fastrtps::rtps::ProtocolVersion_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::ProtocolVersion_t \- Structure \fBProtocolVersion_t\fP, contains the protocol version\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProtocolVersion_t\fP (octet maj, octet min)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "octet \fBm_major\fP"
.br
.ti -1c
.RI "octet \fBm_minor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBProtocolVersion_t\fP, contains the protocol version\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
