.TH "eprosima::fastrtps::rtps::LocatorList_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::LocatorList_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Locator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP (const \fBLocatorList_t\fP &list)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP (\fBLocatorList_t\fP &&list)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP & \fBoperator=\fP (const \fBLocatorList_t\fP &list)"
.br
.ti -1c
.RI "RTPS_DllAPI \fBLocatorList_t\fP & \fBoperator=\fP (\fBLocatorList_t\fP &&list)"
.br
.ti -1c
.RI "RTPS_DllAPI bool \fBoperator==\fP (const \fBLocatorList_t\fP &locator_list) const"
.br
.ti -1c
.RI "RTPS_DllAPI LocatorListIterator \fBbegin\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI LocatorListIterator \fBend\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI LocatorListConstIterator \fBbegin\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI LocatorListConstIterator \fBend\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI size_t \fBsize\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBclear\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBreserve\fP (size_t num)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBresize\fP (size_t num)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBpush_back\fP (const \fBLocator_t\fP &loc)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBpush_back\fP (const \fBLocatorList_t\fP &locList)"
.br
.ti -1c
.RI "RTPS_DllAPI bool \fBempty\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBerase\fP (const \fBLocator_t\fP &loc)"
.br
.ti -1c
.RI "RTPS_DllAPI bool \fBcontains\fP (const \fBLocator_t\fP &loc)"
.br
.ti -1c
.RI "RTPS_DllAPI bool \fBisValid\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBswap\fP (\fBLocatorList_t\fP &locatorList)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &output, const \fBLocatorList_t\fP &loc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBLocatorList_t\fP, a \fBLocator_t\fP vector that doesn't avoid duplicates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
