.TH "eprosima::fastcdr::FastBuffer" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastcdr::FastBuffer \- This class represents a stream of bytes that contains (or will contain) serialized data\&. This class is used by the serializers to serialize or deserialize using their representation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FastBuffer\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fB_FastBuffer_iterator\fP \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFastBuffer\fP ()"
.br
.RI "This constructor creates an internal stream and assigns it to the eprosima::fastcdr::FastBuffers object\&. The user can obtain this internal stream using the function eprosima::fastcdr::FastBuffers::getBuffer()\&. Be careful because this internal stream is deleted in the destruction of the eprosima::fastcdr::FastBuffers object\&. "
.ti -1c
.RI "\fBFastBuffer\fP (char *const buffer, const size_t bufferSize)"
.br
.RI "This constructor assigns the user's stream of bytes to the eprosima::fastcdr::FastBuffers object\&. The user's stream will be used to serialize\&. "
.ti -1c
.RI "virtual \fB~FastBuffer\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "char * \fBgetBuffer\fP () const"
.br
.RI "This function returns the stream that the eprosima::fastcdr::FastBuffers uses to serialize data\&. "
.ti -1c
.RI "size_t \fBgetBufferSize\fP () const"
.br
.RI "This function returns the size of the allocated memory of the stream that the eprosima::fastcdr::FastBuffers uses to serialize data\&. "
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.RI "This function returns a iterator that points to the begining of the stream\&. "
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.RI "This function returns a iterator that points to the end of the stream\&. "
.ti -1c
.RI "bool \fBresize\fP (size_t minSizeInc)"
.br
.RI "This function resizes the raw buffer\&. It will call the user's defined function for this purpose\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class represents a stream of bytes that contains (or will contain) serialized data\&. This class is used by the serializers to serialize or deserialize using their representation\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastcdr::FastBuffer::FastBuffer (char *const buffer, const size_t bufferSize)"

.PP
This constructor assigns the user's stream of bytes to the eprosima::fastcdr::FastBuffers object\&. The user's stream will be used to serialize\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The user's buffer that will be used\&. This buffer is not deallocated in the object's destruction\&. Cannot be NULL\&. 
.br
\fIbufferSize\fP The length of user's buffer\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBiterator\fP eprosima::fastcdr::FastBuffer::begin ()\fC [inline]\fP"

.PP
This function returns a iterator that points to the begining of the stream\&. 
.PP
\fBReturns\fP
.RS 4
The new iterator\&. 
.RE
.PP

.SS "\fBiterator\fP eprosima::fastcdr::FastBuffer::end ()\fC [inline]\fP"

.PP
This function returns a iterator that points to the end of the stream\&. 
.PP
\fBReturns\fP
.RS 4
The new iterator\&. 
.RE
.PP

.SS "char* eprosima::fastcdr::FastBuffer::getBuffer () const\fC [inline]\fP"

.PP
This function returns the stream that the eprosima::fastcdr::FastBuffers uses to serialize data\&. 
.PP
\fBReturns\fP
.RS 4
The stream used by eprosima::fastcdr::FastBuffers to serialize data\&. 
.RE
.PP

.SS "size_t eprosima::fastcdr::FastBuffer::getBufferSize () const\fC [inline]\fP"

.PP
This function returns the size of the allocated memory of the stream that the eprosima::fastcdr::FastBuffers uses to serialize data\&. 
.PP
\fBReturns\fP
.RS 4
The size of the allocated memory of the stream used by the eprosima::fastcdr::FastBuffers to serialize data\&. 
.RE
.PP

.SS "bool eprosima::fastcdr::FastBuffer::resize (size_t minSizeInc)"

.PP
This function resizes the raw buffer\&. It will call the user's defined function for this purpose\&. 
.PP
\fBParameters\fP
.RS 4
\fIminSizeInc\fP The minimun growth expected of the current raw buffer\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if the operation works\&. False if it does not\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
