.TH "eprosima::fastrtps::rtps::RTPSMessageGroup_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::RTPSMessageGroup_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSMessageGroup\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRTPSMessageGroup_t\fP (uint32_t payload, \fBGuidPrefix_t\fP participant_guid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCDRMessage_t\fP \fBrtpsmsg_submessage_\fP"
.br
.ti -1c
.RI "\fBCDRMessage_t\fP \fBrtpsmsg_fullmsg_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBRTPSMessageGroup_t\fP that contains the messages used to send multiples changes as one message\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
