.TH "eprosima::fastrtps::rtps::BinaryProperty" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::BinaryProperty
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryProperty\fP (const \fBBinaryProperty\fP &property)"
.br
.ti -1c
.RI "\fBBinaryProperty\fP (\fBBinaryProperty\fP &&property)"
.br
.ti -1c
.RI "\fBBinaryProperty\fP (const std::string &name, const std::vector< uint8_t > &value)"
.br
.ti -1c
.RI "\fBBinaryProperty\fP (std::string &&name, std::vector< uint8_t > &&value)"
.br
.ti -1c
.RI "\fBBinaryProperty\fP & \fBoperator=\fP (const \fBBinaryProperty\fP &property)"
.br
.ti -1c
.RI "\fBBinaryProperty\fP & \fBoperator=\fP (\fBBinaryProperty\fP &&property)"
.br
.ti -1c
.RI "void \fBname\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBname\fP (std::string &&name)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const"
.br
.ti -1c
.RI "std::string & \fBname\fP ()"
.br
.ti -1c
.RI "void \fBvalue\fP (const std::vector< uint8_t > &value)"
.br
.ti -1c
.RI "void \fBvalue\fP (std::vector< uint8_t > &&value)"
.br
.ti -1c
.RI "const std::vector< uint8_t > & \fBvalue\fP () const"
.br
.ti -1c
.RI "std::vector< uint8_t > & \fBvalue\fP ()"
.br
.ti -1c
.RI "void \fBpropagate\fP (bool propagate)"
.br
.ti -1c
.RI "bool \fBpropagate\fP () const"
.br
.ti -1c
.RI "bool & \fBpropagate\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
