.TH "eprosima::fastrtps::TopicAttributes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::TopicAttributes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TopicAttributes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTopicAttributes\fP ()"
.br
.ti -1c
.RI "\fBTopicAttributes\fP (const char *name, const char *dataType, \fBTopicKind_t\fP tKind=NO_KEY)"
.br
.RI "Constructor, you need to provide the topic name and the topic data type\&. "
.ti -1c
.RI "const std::string & \fBgetTopicDataType\fP () const"
.br
.ti -1c
.RI "\fBTopicKind_t\fP \fBgetTopicKind\fP () const"
.br
.ti -1c
.RI "const std::string & \fBgetTopicName\fP () const"
.br
.ti -1c
.RI "bool \fBcheckQos\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTopicKind_t\fP \fBtopicKind\fP"
.br
.RI "TopicKind_t, default value NO_KEY\&. "
.ti -1c
.RI "std::string \fBtopicName\fP"
.br
.RI "Topic Name\&. "
.ti -1c
.RI "std::string \fBtopicDataType\fP"
.br
.RI "Topic Data Type\&. "
.ti -1c
.RI "\fBHistoryQosPolicy\fP \fBhistoryQos\fP"
.br
.RI "QOS Regarding the History to be saved\&. "
.ti -1c
.RI "\fBResourceLimitsQosPolicy\fP \fBresourceLimitsQos\fP"
.br
.RI "QOS Regarding the resources to allocate\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTopicAttributes\fP, used by the user to define the attributes of the topic associated with a \fBPublisher\fP or \fBSubscriber\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::TopicAttributes::TopicAttributes ()\fC [inline]\fP"
Default constructor 
.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::TopicAttributes::checkQos ()\fC [inline]\fP"
Method to check whether the defined QOS are correct\&. 
.PP
\fBReturns\fP
.RS 4
True if they are valid\&. 
.RE
.PP

.SS "const std::string& eprosima::fastrtps::TopicAttributes::getTopicDataType () const\fC [inline]\fP"
Get the topic data type 
.PP
\fBReturns\fP
.RS 4
Topic data type 
.RE
.PP

.SS "\fBTopicKind_t\fP eprosima::fastrtps::TopicAttributes::getTopicKind () const\fC [inline]\fP"
Get the topic kind 
.PP
\fBReturns\fP
.RS 4
Topic kind 
.RE
.PP

.SS "const std::string& eprosima::fastrtps::TopicAttributes::getTopicName () const\fC [inline]\fP"
Get the topic name 
.PP
\fBReturns\fP
.RS 4
Topic name 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
