.TH "eprosima::fastrtps::Semaphore" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::Semaphore
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemaphore\fP (size_t count=0)"
.br
.ti -1c
.RI "\fBSemaphore\fP (const \fBSemaphore\fP &)=delete"
.br
.ti -1c
.RI "\fBSemaphore\fP & \fBoperator=\fP (const \fBSemaphore\fP &)=delete"
.br
.ti -1c
.RI "void \fBpost\fP ()"
.br
.ti -1c
.RI "void \fBwait\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
