.TH "eprosima::fastrtps::rtps::ReaderTimes" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::ReaderTimes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ReaderAttributes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDuration_t\fP \fBinitialAcknackDelay\fP"
.br
.RI "Initial AckNack delay\&. Default value ~45ms\&. "
.ti -1c
.RI "\fBDuration_t\fP \fBheartbeatResponseDelay\fP"
.br
.RI "Delay to be applied when a hearbeat message is received, default value ~116ms\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBReaderTimes\fP, defining the times associated with the Reliable Readers events\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
