.TH "eprosima::fastrtps::rtps::security::SecurityException" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::SecurityException \- This class is thrown as an exception when there is an error in security module\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SecurityException\&.h>\fP
.PP
Inherits \fBeprosima::fastrtps::rtps::Exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "RTPS_DllAPI \fBSecurityException\fP (const std::string &message)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "RTPS_DllAPI \fBSecurityException\fP (const \fBSecurityException\fP &ex)"
.br
.RI "Default copy constructor\&. "
.ti -1c
.RI "RTPS_DllAPI \fBSecurityException\fP (\fBSecurityException\fP &&ex)"
.br
.RI "Default move constructor\&. "
.ti -1c
.RI "RTPS_DllAPI \fBSecurityException\fP & \fBoperator=\fP (const \fBSecurityException\fP &ex)"
.br
.RI "Assigment operation\&. "
.ti -1c
.RI "RTPS_DllAPI \fBSecurityException\fP & \fBoperator=\fP (\fBSecurityException\fP &&ex)"
.br
.RI "Assigment operation\&. "
.ti -1c
.RI "virtual RTPS_DllAPI \fB~SecurityException\fP ()  throw ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual RTPS_DllAPI void \fBraise\fP () const"
.br
.RI "This function throws the object as an exception\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class is thrown as an exception when there is an error in security module\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RTPS_DllAPI eprosima::fastrtps::rtps::security::SecurityException::SecurityException (const std::string & message)\fC [inline]\fP"

.PP
Default constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP An error message\&. This message is copied\&. 
.RE
.PP

.SS "RTPS_DllAPI eprosima::fastrtps::rtps::security::SecurityException::SecurityException (const \fBSecurityException\fP & ex)"

.PP
Default copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBSecurityException\fP that will be copied\&. 
.RE
.PP

.SS "RTPS_DllAPI eprosima::fastrtps::rtps::security::SecurityException::SecurityException (\fBSecurityException\fP && ex)"

.PP
Default move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBSecurityException\fP that will be moved\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "RTPS_DllAPI \fBSecurityException\fP& eprosima::fastrtps::rtps::security::SecurityException::operator= (const \fBSecurityException\fP & ex)"

.PP
Assigment operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBSecurityException\fP that will be copied\&. 
.RE
.PP

.SS "RTPS_DllAPI \fBSecurityException\fP& eprosima::fastrtps::rtps::security::SecurityException::operator= (\fBSecurityException\fP && ex)"

.PP
Assigment operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBSecurityException\fP that will be moved\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
