.TH "eprosima::fastrtps::rtps::DataHolderHelper" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::DataHolderHelper
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string * \fBfind_property_value\fP (\fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static const std::string * \fBfind_property_value\fP (const \fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static \fBProperty\fP * \fBfind_property\fP (\fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static const \fBProperty\fP * \fBfind_property\fP (const \fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static std::vector< uint8_t > * \fBfind_binary_property_value\fP (\fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static const std::vector< uint8_t > * \fBfind_binary_property_value\fP (const \fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static \fBBinaryProperty\fP * \fBfind_binary_property\fP (\fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static const \fBBinaryProperty\fP * \fBfind_binary_property\fP (const \fBDataHolder\fP &data_holder, const std::string &name)"
.br
.ti -1c
.RI "static size_t \fBserialized_size\fP (const \fBDataHolder\fP &data_holder, size_t current_alignment=0)"
.br
.ti -1c
.RI "static size_t \fBserialized_size\fP (const DataHolderSeq &data_holders, size_t current_alignment=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
