.TH "eprosima::fastrtps::rtps::security::Handle" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::Handle
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBeprosima::fastrtps::rtps::security::HandleImpl< T >\fP, and \fBeprosima::fastrtps::rtps::security::NilHandle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const std::string & \fBget_class_id\fP () const"
.br
.ti -1c
.RI "virtual bool \fBnil\fP () const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBHandle\fP (const std::string &class_id)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
