.TH "EprosimaServer::ResultListener" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EprosimaServer::ResultListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeprosima::fastrtps::PublisherListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResultListener\fP (\fBEprosimaServer\fP *up)"
.br
.ti -1c
.RI "void \fBonPublicationMatched\fP (\fBPublisher\fP *pub, \fBMatchingInfo\fP &info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEprosimaServer\fP * \fBmp_up\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void EprosimaServer::ResultListener::onPublicationMatched (\fBPublisher\fP * pub, \fBMatchingInfo\fP & info)\fC [virtual]\fP"
This method is called when the Publisher is matched (or unmatched) against an endpoint\&. 
.PP
\fBParameters\fP
.RS 4
\fIpub\fP Pointer to the associated Publisher 
.br
\fIinfo\fP Information regarding the matched subscriber 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::PublisherListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
