.TH "eprosima::fastrtps::QosList_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::QosList_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QosList\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBParameterList_t\fP \fBallQos\fP"
.br
.RI "All the Qos as a parameter list\&. "
.ti -1c
.RI "\fBParameterList_t\fP \fBinlineQos\fP"
.br
.RI "Only the Qos that can be sent as inline\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBQosList_t\fP class contains two QoS parameter lists: One for all Qos policies and another for those that can be sent inline\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
