.TH "eprosima::fastrtps::rtps::test_UDPv4TransportDescriptor" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::test_UDPv4TransportDescriptor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeprosima::fastrtps::rtps::TransportDescriptorInterface\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsendBufferSize\fP"
.br
.ti -1c
.RI "uint32_t \fBreceiveBufferSize\fP"
.br
.ti -1c
.RI "bool \fBgranularMode\fP"
.br
.ti -1c
.RI "uint8_t \fBdropDataMessagesPercentage\fP"
.br
.ti -1c
.RI "bool \fBdropParticipantBuiltinTopicData\fP"
.br
.ti -1c
.RI "bool \fBdropPublicationBuiltinTopicData\fP"
.br
.ti -1c
.RI "bool \fBdropSubscriptionBuiltinTopicData\fP"
.br
.ti -1c
.RI "uint8_t \fBdropDataFragMessagesPercentage\fP"
.br
.ti -1c
.RI "uint8_t \fBdropHeartbeatMessagesPercentage\fP"
.br
.ti -1c
.RI "uint8_t \fBdropAckNackMessagesPercentage\fP"
.br
.ti -1c
.RI "uint8_t \fBpercentageOfMessagesToDrop\fP"
.br
.ti -1c
.RI "std::vector< \fBSequenceNumber_t\fP > \fBsequenceNumberDataMessagesToDrop\fP"
.br
.ti -1c
.RI "uint32_t \fBdropLogLength\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
