.TH "eprosima::fastrtps::rtps::CDRMessagePool" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::CDRMessagePool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDRMessagePool\fP (uint32_t defaultGroupSize)"
.br
.ti -1c
.RI "\fBCDRMessage_t\fP & \fBreserve_CDRMsg\fP ()"
.br
.ti -1c
.RI "\fBCDRMessage_t\fP & \fBreserve_CDRMsg\fP (uint16_t payload)"
.br
.ti -1c
.RI "void \fBrelease_CDRMsg\fP (\fBCDRMessage_t\fP &obj)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBallocateGroup\fP ()"
.br
.ti -1c
.RI "void \fBallocateGroup\fP (uint16_t payload)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCDRMessage_t\fP * > \fBm_free_objects\fP"
.br
.ti -1c
.RI "std::vector< \fBCDRMessage_t\fP * > \fBm_all_objects\fP"
.br
.ti -1c
.RI "uint16_t \fBm_group_size\fP"
.br
.ti -1c
.RI "std::mutex * \fBmutex_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::CDRMessagePool::CDRMessagePool (uint32_t defaultGroupSize)"

.PP
\fBParameters\fP
.RS 4
\fIdefaultGroupSize\fP Number of messages per allocated group\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void eprosima::fastrtps::rtps::CDRMessagePool::release_CDRMsg (\fBCDRMessage_t\fP & obj)"

.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.RE
.PP

.SS "\fBCDRMessage_t\fP& eprosima::fastrtps::rtps::CDRMessagePool::reserve_CDRMsg (uint16_t payload)"

.PP
\fBParameters\fP
.RS 4
\fIpayload\fP Payload size for the reserved message\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
