.TH "eprosima::fastcdr::exception::NotEnoughMemoryException" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastcdr::exception::NotEnoughMemoryException \- This class is thrown as an exception when the buffer's internal memory reachs its size limit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NotEnoughMemoryException\&.h>\fP
.PP
Inherits \fBeprosima::fastcdr::exception::Exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Cdr_DllAPI \fBNotEnoughMemoryException\fP (const char *const &message)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "Cdr_DllAPI \fBNotEnoughMemoryException\fP (const \fBNotEnoughMemoryException\fP &ex)"
.br
.RI "Default copy constructor\&. "
.ti -1c
.RI "Cdr_DllAPI \fBNotEnoughMemoryException\fP (\fBNotEnoughMemoryException\fP &&ex)"
.br
.RI "Default move constructor\&. "
.ti -1c
.RI "Cdr_DllAPI \fBNotEnoughMemoryException\fP & \fBoperator=\fP (const \fBNotEnoughMemoryException\fP &ex)"
.br
.RI "Assigment operation\&. "
.ti -1c
.RI "Cdr_DllAPI \fBNotEnoughMemoryException\fP & \fBoperator=\fP (\fBNotEnoughMemoryException\fP &&ex)"
.br
.RI "Assigment operation\&. "
.ti -1c
.RI "virtual Cdr_DllAPI \fB~NotEnoughMemoryException\fP ()  throw ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "virtual Cdr_DllAPI void \fBraise\fP () const"
.br
.RI "This function throws the object as exception\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Cdr_DllAPI const char *const \fBNOT_ENOUGH_MEMORY_MESSAGE_DEFAULT\fP"
.br
.RI "Default message used in the library\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class is thrown as an exception when the buffer's internal memory reachs its size limit\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Cdr_DllAPI eprosima::fastcdr::exception::NotEnoughMemoryException::NotEnoughMemoryException (const char *const & message)"

.PP
Default constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP A error message\&. This message is copied\&. 
.RE
.PP

.SS "Cdr_DllAPI eprosima::fastcdr::exception::NotEnoughMemoryException::NotEnoughMemoryException (const \fBNotEnoughMemoryException\fP & ex)"

.PP
Default copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBNotEnoughMemoryException\fP that will be copied\&. 
.RE
.PP

.SS "Cdr_DllAPI eprosima::fastcdr::exception::NotEnoughMemoryException::NotEnoughMemoryException (\fBNotEnoughMemoryException\fP && ex)"

.PP
Default move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBNotEnoughMemoryException\fP that will be moved\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "Cdr_DllAPI \fBNotEnoughMemoryException\fP& eprosima::fastcdr::exception::NotEnoughMemoryException::operator= (const \fBNotEnoughMemoryException\fP & ex)"

.PP
Assigment operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBNotEnoughMemoryException\fP that will be copied\&. 
.RE
.PP

.SS "Cdr_DllAPI \fBNotEnoughMemoryException\fP& eprosima::fastcdr::exception::NotEnoughMemoryException::operator= (\fBNotEnoughMemoryException\fP && ex)"

.PP
Assigment operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIex\fP \fBNotEnoughMemoryException\fP that will be moved\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
