.TH "eprosima::fastrtps::rtps::security::ParticipantGenericMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::security::ParticipantGenericMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticipantGenericMessage\fP (const \fBParticipantGenericMessage\fP &message)"
.br
.ti -1c
.RI "\fBParticipantGenericMessage\fP (\fBParticipantGenericMessage\fP &&message)"
.br
.ti -1c
.RI "\fBParticipantGenericMessage\fP & \fBoperator=\fP (const \fBParticipantGenericMessage\fP &message)"
.br
.ti -1c
.RI "\fBParticipantGenericMessage\fP & \fBoperator=\fP (\fBParticipantGenericMessage\fP &&message)"
.br
.ti -1c
.RI "void \fBmessage_identity\fP (const \fBMessageIdentity\fP &message_identity)"
.br
.ti -1c
.RI "void \fBmessage_identity\fP (\fBMessageIdentity\fP &&message_identity)"
.br
.ti -1c
.RI "const \fBMessageIdentity\fP & \fBmessage_identity\fP () const"
.br
.ti -1c
.RI "\fBMessageIdentity\fP & \fBmessage_identity\fP ()"
.br
.ti -1c
.RI "void \fBrelated_message_identity\fP (const \fBMessageIdentity\fP &related_message_identity)"
.br
.ti -1c
.RI "void \fBrelated_message_identity\fP (\fBMessageIdentity\fP &&related_message_identity)"
.br
.ti -1c
.RI "const \fBMessageIdentity\fP & \fBrelated_message_identity\fP () const"
.br
.ti -1c
.RI "\fBMessageIdentity\fP & \fBrelated_message_identity\fP ()"
.br
.ti -1c
.RI "void \fBdestination_participant_key\fP (const \fBGUID_t\fP &destination_participant_key)"
.br
.ti -1c
.RI "void \fBdestination_participant_key\fP (\fBGUID_t\fP &&destination_participant_key)"
.br
.ti -1c
.RI "const \fBGUID_t\fP & \fBdestination_participant_key\fP () const"
.br
.ti -1c
.RI "\fBGUID_t\fP & \fBdestination_participant_key\fP ()"
.br
.ti -1c
.RI "void \fBdestination_endpoint_key\fP (const \fBGUID_t\fP &destination_endpoint_key)"
.br
.ti -1c
.RI "void \fBdestination_endpoint_key\fP (\fBGUID_t\fP &&destination_endpoint_key)"
.br
.ti -1c
.RI "const \fBGUID_t\fP & \fBdestination_endpoint_key\fP () const"
.br
.ti -1c
.RI "\fBGUID_t\fP & \fBdestination_endpoint_key\fP ()"
.br
.ti -1c
.RI "void \fBsource_endpoint_key\fP (const \fBGUID_t\fP &source_endpoint_key)"
.br
.ti -1c
.RI "void \fBsource_endpoint_key\fP (\fBGUID_t\fP &&source_endpoint_key)"
.br
.ti -1c
.RI "const \fBGUID_t\fP & \fBsource_endpoint_key\fP () const"
.br
.ti -1c
.RI "\fBGUID_t\fP & \fBsource_endpoint_key\fP ()"
.br
.ti -1c
.RI "void \fBmessage_class_id\fP (const std::string &message_class_id)"
.br
.ti -1c
.RI "void \fBmessage_class_id\fP (std::string &&message_class_id)"
.br
.ti -1c
.RI "const std::string & \fBmessage_class_id\fP () const"
.br
.ti -1c
.RI "std::string & \fBmessage_class_id\fP ()"
.br
.ti -1c
.RI "void \fBmessage_data\fP (const DataHolderSeq &message_data)"
.br
.ti -1c
.RI "void \fBmessage_data\fP (DataHolderSeq &&message_data)"
.br
.ti -1c
.RI "const DataHolderSeq & \fBmessage_data\fP () const"
.br
.ti -1c
.RI "DataHolderSeq & \fBmessage_data\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
