.TH "eprosima::fastrtps::xmlparser::StaticRTPSParticipantInfo" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::xmlparser::StaticRTPSParticipantInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <XMLEndpointParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_RTPSParticipantName\fP"
.br
.RI "RTPS PArticipant name\&. "
.ti -1c
.RI "std::vector< \fBrtps::ReaderProxyData\fP * > \fBm_readers\fP"
.br
.RI "Vector of ReaderProxyData pointer\&. "
.ti -1c
.RI "std::vector< \fBrtps::WriterProxyData\fP * > \fBm_writers\fP"
.br
.RI "Vector of ReaderProxyData pointer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBStaticRTPSParticipantInfo\fP, contains the information of writers and readers loaded from the XML file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
