.TH "eprosima::fastrtps::DBQueue< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::DBQueue< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DBQueue\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSwap\fP ()"
.br
.RI "Clears foreground queue and swaps queues\&. "
.ti -1c
.RI "void \fBPush\fP (const T &item)"
.br
.RI "Pushes to the background queue\&. "
.ti -1c
.RI "T & \fBFront\fP ()"
.br
.ti -1c
.RI "const T & \fBFront\fP () const"
.br
.ti -1c
.RI "void \fBPop\fP ()"
.br
.RI "Pops from the foreground queue\&. "
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.RI "Reports whether the foreground queue is empty\&. "
.ti -1c
.RI "size_t \fBSize\fP () const"
.br
.RI "Reports the size of the foreground queue\&. "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Clears foreground and background\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class eprosima::fastrtps::DBQueue< T >"
Double buffered, threadsafe queue for MPSC (multi-producer, single-consumer) comms\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class T > T& \fBeprosima::fastrtps::DBQueue\fP< T >::Front ()\fC [inline]\fP"
Returns a reference to the front element in the foregrund queue\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
