.TH "eprosima::fastrtps::rtps::PortParameters" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::PortParameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RTPSParticipantAttributes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBgetMulticastPort\fP (uint32_t domainId)"
.br
.ti -1c
.RI "uint32_t \fBgetUnicastPort\fP (uint32_t domainId, uint32_t RTPSParticipantID)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportBase\fP"
.br
.RI "PortBase, default value 7400\&. "
.ti -1c
.RI "uint16_t \fBdomainIDGain\fP"
.br
.RI "DomainID gain, default value 250\&. "
.ti -1c
.RI "uint16_t \fBparticipantIDGain\fP"
.br
.RI "ParticipantID gain, default value 2\&. "
.ti -1c
.RI "uint16_t \fBoffsetd0\fP"
.br
.RI "Offset d0, default value 0\&. "
.ti -1c
.RI "uint16_t \fBoffsetd1\fP"
.br
.RI "Offset d1, default value 10\&. "
.ti -1c
.RI "uint16_t \fBoffsetd2\fP"
.br
.RI "Offset d2, default value 1\&. "
.ti -1c
.RI "uint16_t \fBoffsetd3\fP"
.br
.RI "Offset d3, default value 11\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBPortParameters\fP, to define the port parameters and gains related with the RTPS protocol\&. 
.SH "Member Function Documentation"
.PP 
.SS "uint32_t eprosima::fastrtps::rtps::PortParameters::getMulticastPort (uint32_t domainId)\fC [inline]\fP"
Get a multicast port based on the domain ID\&.
.PP
\fBParameters\fP
.RS 4
\fIdomainId\fP \fBDomain\fP ID\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Multicast port 
.RE
.PP

.SS "uint32_t eprosima::fastrtps::rtps::PortParameters::getUnicastPort (uint32_t domainId, uint32_t RTPSParticipantID)\fC [inline]\fP"
Get a unicast port baes on the domain ID and the participant ID\&.
.PP
\fBParameters\fP
.RS 4
\fIdomainId\fP \fBDomain\fP ID\&. 
.br
\fIRTPSParticipantID\fP \fBParticipant\fP ID\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Unicast port 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
