.TH "eprosima::fastrtps::rtps::TransportDescriptorInterface" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::TransportDescriptorInterface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TransportInterface\&.h>\fP
.PP
Inherited by \fBeprosima::fastrtps::rtps::UDPv4TransportDescriptor\fP, \fBeprosima::fastrtps::rtps::UDPv6TransportDescriptor\fP, and \fBeprosima::fastrtps::rtps::test_UDPv4TransportDescriptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransportDescriptorInterface\fP (uint32_t maximumMessageSize)"
.br
.ti -1c
.RI "\fBTransportDescriptorInterface\fP (const \fBTransportDescriptorInterface\fP &t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmaxMessageSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Virtual base class for the data type used to define transport configuration\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
