.TH "eprosima::fastrtps::ParticipantListener" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::ParticipantListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParticipantListener\&.h>\fP
.PP
Inherited by \fBapollo::cyber::service_discovery::ParticipantListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBonParticipantDiscovery\fP (\fBParticipant\fP *p, \fBParticipantDiscoveryInfo\fP info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBParticipantListener\fP, overrides behaviour towards certain events\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void eprosima::fastrtps::ParticipantListener::onParticipantDiscovery (\fBParticipant\fP * p, \fBParticipantDiscoveryInfo\fP info)\fC [inline]\fP, \fC [virtual]\fP"
This method is called when a new \fBParticipant\fP is discovered, or a previously discovered participant changes its QOS or is removed\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP Pointer to the \fBParticipant\fP 
.br
\fIinfo\fP DiscoveryInfo\&. 
.RE
.PP

.PP
Reimplemented in \fBapollo::cyber::service_discovery::ParticipantListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
