.TH "eprosima::fastrtps::PartitionQosPolicy" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::PartitionQosPolicy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QosPolicies\&.h>\fP
.PP
Inherits \fBeprosima::fastrtps::Parameter_t\fP, and \fBeprosima::fastrtps::QosPolicy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBaddToCDRMessage\fP (\fBCDRMessage_t\fP *msg) override"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBpush_back\fP (const char *name)"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBclear\fP ()"
.br
.ti -1c
.RI "RTPS_DllAPI std::vector< std::string > \fBgetNames\fP () const"
.br
.ti -1c
.RI "RTPS_DllAPI void \fBsetNames\fP (std::vector< std::string > &nam)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBParameterList\fP"
.br
.ti -1c
.RI "class \fBrtps::EDP\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBPartitionQosPolicy\fP, to indicate the Partition Qos\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::PartitionQosPolicy::addToCDRMessage (\fBCDRMessage_t\fP * msg)\fC [override]\fP, \fC [virtual]\fP"
Appends QoS to the specified CDR message\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Message to append the QoS Policy to\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if the modified CDRMessage is valid\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::Parameter_t\fP\&.
.SS "RTPS_DllAPI void eprosima::fastrtps::PartitionQosPolicy::clear (void)\fC [inline]\fP"
Clears list of partition names 
.SS "RTPS_DllAPI std::vector<std::string> eprosima::fastrtps::PartitionQosPolicy::getNames () const\fC [inline]\fP"
Returns partition names\&. 
.PP
\fBReturns\fP
.RS 4
Vector of partition name strings\&. 
.RE
.PP

.SS "RTPS_DllAPI void eprosima::fastrtps::PartitionQosPolicy::push_back (const char * name)\fC [inline]\fP"
Appends a name to the list of partition names\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name to append\&. 
.RE
.PP

.SS "RTPS_DllAPI void eprosima::fastrtps::PartitionQosPolicy::setNames (std::vector< std::string > & nam)\fC [inline]\fP"
Overrides partition names 
.PP
\fBParameters\fP
.RS 4
\fInam\fP Vector of partition name strings\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
