.TH "eprosima::fastrtps::rtps::EDPStatic" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::EDPStatic
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EDPStatic\&.h>\fP
.PP
Inherits \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEDPStatic\fP (\fBPDPSimple\fP *p, RTPSParticipantImpl *part)"
.br
.ti -1c
.RI "bool \fBinitEDP\fP (\fBBuiltinAttributes\fP &attributes)"
.br
.ti -1c
.RI "void \fBassignRemoteEndpoints\fP (\fBParticipantProxyData\fP *pdata)"
.br
.ti -1c
.RI "bool \fBremoveLocalReader\fP (\fBRTPSReader\fP *R)"
.br
.ti -1c
.RI "bool \fBremoveLocalWriter\fP (\fBRTPSWriter\fP *W)"
.br
.ti -1c
.RI "bool \fBprocessLocalReaderProxyData\fP (\fBReaderProxyData\fP *rdata)"
.br
.ti -1c
.RI "bool \fBprocessLocalWriterProxyData\fP (\fBWriterProxyData\fP *wdata)"
.br
.ti -1c
.RI "bool \fBnewRemoteWriter\fP (\fBParticipantProxyData\fP *pdata, uint16_t userId, \fBEntityId_t\fP entId=c_EntityId_Unknown)"
.br
.ti -1c
.RI "bool \fBnewRemoteReader\fP (\fBParticipantProxyData\fP *pdata, uint16_t userId, \fBEntityId_t\fP entId=c_EntityId_Unknown)"
.br
.ti -1c
.RI "bool \fBcheckEntityId\fP (\fBReaderProxyData\fP *rdata)"
.br
.ti -1c
.RI "bool \fBcheckEntityId\fP (\fBWriterProxyData\fP *wdata)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBEDPStatic\fP, implements a static endpoint discovery module\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::EDPStatic::EDPStatic (\fBPDPSimple\fP * p, RTPSParticipantImpl * part)"
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP Pointer to the \fBPDPSimple\fP\&. 
.br
\fIpart\fP Pointer to the RTPSParticipantImpl\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void eprosima::fastrtps::rtps::EDPStatic::assignRemoteEndpoints (\fBParticipantProxyData\fP * pdata)\fC [virtual]\fP"
Abstract method that assigns remote endpoints when a new RTPSParticipantProxyData is discovered\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdata\fP Pointer to the \fBParticipantProxyData\fP\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "bool eprosima::fastrtps::rtps::EDPStatic::checkEntityId (\fBReaderProxyData\fP * rdata)"
This method checks the provided entityId against the topic type to see if it matches 
.PP
\fBParameters\fP
.RS 4
\fIrdata\fP Pointer to the readerProxyData 
.RE
.PP
\fBReturns\fP
.RS 4
True if its correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::EDPStatic::checkEntityId (\fBWriterProxyData\fP * wdata)"
This method checks the provided entityId against the topic type to see if it matches 
.PP
\fBParameters\fP
.RS 4
\fIwdata\fP Pointer to the writerProxyData 
.RE
.PP
\fBReturns\fP
.RS 4
True if its correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::EDPStatic::initEDP (\fBBuiltinAttributes\fP & attributes)\fC [virtual]\fP"
Abstract method to initialize the \fBEDP\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIattributes\fP DiscoveryAttributes structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "bool eprosima::fastrtps::rtps::EDPStatic::newRemoteReader (\fBParticipantProxyData\fP * pdata, uint16_t userId, \fBEntityId_t\fP entId = \fCc_EntityId_Unknown\fP)"
New Remote Reader has been found and this method process it and calls the pairing methods\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdata\fP Pointer to the RTPSParticipantProxyData object\&. 
.br
\fIuserId\fP UserId\&. 
.br
\fIentId\fP EntityId\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::EDPStatic::newRemoteWriter (\fBParticipantProxyData\fP * pdata, uint16_t userId, \fBEntityId_t\fP entId = \fCc_EntityId_Unknown\fP)"
New Remote Writer has been found and this method process it and calls the pairing methods\&. 
.PP
\fBParameters\fP
.RS 4
\fIpdata\fP Pointer to the RTPSParticipantProxyData object\&. 
.br
\fIuserId\fP UserId\&. 
.br
\fIentId\fP EntityId\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.SS "bool eprosima::fastrtps::rtps::EDPStatic::processLocalReaderProxyData (\fBReaderProxyData\fP * rdata)\fC [virtual]\fP"
After a new local \fBReaderProxyData\fP has been created some processing is needed (depends on the implementation)\&. 
.PP
\fBParameters\fP
.RS 4
\fIrdata\fP Pointer to the \fBReaderProxyData\fP object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "bool eprosima::fastrtps::rtps::EDPStatic::processLocalWriterProxyData (\fBWriterProxyData\fP * wdata)\fC [virtual]\fP"
After a new local \fBWriterProxyData\fP has been created some processing is needed (depends on the implementation)\&. 
.PP
\fBParameters\fP
.RS 4
\fIwdata\fP Pointer to the Writer ProxyData object\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "bool eprosima::fastrtps::rtps::EDPStatic::removeLocalReader (\fBRTPSReader\fP * R)\fC [virtual]\fP"
Abstract method that removes a local Reader from the discovery method 
.PP
\fBParameters\fP
.RS 4
\fIR\fP Pointer to the Reader to remove\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correctly removed\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.
.SS "bool eprosima::fastrtps::rtps::EDPStatic::removeLocalWriter (\fBRTPSWriter\fP * W)\fC [virtual]\fP"
Abstract method that removes a local Writer from the discovery method 
.PP
\fBParameters\fP
.RS 4
\fIW\fP Pointer to the Writer to remove\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correctly removed\&. 
.RE
.PP

.PP
Implements \fBeprosima::fastrtps::rtps::EDP\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
