.TH "eprosima::fastrtps::rtps::SequenceNumber_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::SequenceNumber_t \- Structure \fBSequenceNumber_t\fP, different for each change in the same writer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SequenceNumber\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSequenceNumber_t\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBSequenceNumber_t\fP (const \fBSequenceNumber_t\fP &seq)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBSequenceNumber_t\fP (int32_t hi, uint32_t lo)"
.br
.ti -1c
.RI "\fBSequenceNumber_t\fP & \fBoperator=\fP (const \fBSequenceNumber_t\fP &seq)"
.br
.ti -1c
.RI "\fBSequenceNumber_t\fP & \fBoperator++\fP ()"
.br
.RI "Increase SequenceNumber in 1\&. "
.ti -1c
.RI "\fBSequenceNumber_t\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBSequenceNumber_t\fP & \fBoperator+=\fP (int inc)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSequenceNumber_t\fP \fBunknown\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBhigh\fP"
.br
.ti -1c
.RI "uint32_t \fBlow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBSequenceNumber_t\fP, different for each change in the same writer\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::SequenceNumber_t::SequenceNumber_t (int32_t hi, uint32_t lo)\fC [inline]\fP"

.PP
\fBParameters\fP
.RS 4
\fIhi\fP 
.br
\fIlo\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBSequenceNumber_t\fP& eprosima::fastrtps::rtps::SequenceNumber_t::operator+= (int inc)\fC [inline]\fP"
Increase SequenceNumber\&. 
.PP
\fBParameters\fP
.RS 4
\fIinc\fP Number to add to the SequenceNumber 
.RE
.PP

.SS "\fBSequenceNumber_t\fP& eprosima::fastrtps::rtps::SequenceNumber_t::operator= (const \fBSequenceNumber_t\fP & seq)\fC [inline]\fP"
Assignment operator 
.PP
\fBParameters\fP
.RS 4
\fIseq\fP \fBSequenceNumber_t\fP to copy the data from 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
