.TH "eprosima::fastrtps::ParameterList" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::ParameterList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParameterList\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBwriteParameterListToCDRMsg\fP (\fBCDRMessage_t\fP *msg, \fBParameterList_t\fP *plist, bool use_encapsulation)"
.br
.ti -1c
.RI "static int32_t \fBreadParameterListfromCDRMsg\fP (\fBCDRMessage_t\fP *msg, \fBParameterList_t\fP *plist, \fBCacheChange_t\fP *change, bool encapsulation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBParameterList\fP class has static methods to update or read a \fBParameterList_t\fP 
.SH "Member Function Documentation"
.PP 
.SS "static int32_t eprosima::fastrtps::ParameterList::readParameterListfromCDRMsg (\fBCDRMessage_t\fP * msg, \fBParameterList_t\fP * plist, \fBCacheChange_t\fP * change, bool encapsulation)\fC [static]\fP"
Read a parameterList from a CDRMessage 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to the message (the pos should be correct, otherwise the behaviour is undefined)\&. 
.br
\fIplist\fP Pointer to the parameter list\&. 
.br
\fIchange\fP Pointer to the cache change\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Number of bytes of the parameter list\&. 
.RE
.PP

.SS "static bool eprosima::fastrtps::ParameterList::writeParameterListToCDRMsg (\fBCDRMessage_t\fP * msg, \fBParameterList_t\fP * plist, bool use_encapsulation)\fC [static]\fP"
Update the CDRMessage of a parameterList\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Pointer to the message (the pos should be correct, otherwise the behaviour is undefined)\&. 
.br
\fIplist\fP Pointer to the parameterList\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
