.TH "eprosima::fastrtps::rtps::CacheChange_t" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eprosima::fastrtps::rtps::CacheChange_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CacheChange\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCacheChange_t\fP ()"
.br
.RI "Default constructor\&. Creates an empty \fBCacheChange_t\fP\&. "
.ti -1c
.RI "\fBCacheChange_t\fP (const \fBCacheChange_t\fP &)=delete"
.br
.ti -1c
.RI "const \fBCacheChange_t\fP & \fBoperator=\fP (const \fBCacheChange_t\fP &)=delete"
.br
.ti -1c
.RI "\fBCacheChange_t\fP (uint32_t payload_size, bool is_untyped=false)"
.br
.ti -1c
.RI "bool \fBcopy\fP (const \fBCacheChange_t\fP *ch_ptr)"
.br
.ti -1c
.RI "void \fBcopy_not_memcpy\fP (const \fBCacheChange_t\fP *ch_ptr)"
.br
.ti -1c
.RI "uint32_t \fBgetFragmentCount\fP () const"
.br
.ti -1c
.RI "std::vector< uint32_t > * \fBgetDataFragments\fP ()"
.br
.ti -1c
.RI "uint16_t \fBgetFragmentSize\fP () const"
.br
.ti -1c
.RI "void \fBsetFragmentSize\fP (uint16_t fragment_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChangeKind_t\fP \fBkind\fP"
.br
.RI "Kind of change, default value ALIVE\&. "
.ti -1c
.RI "\fBGUID_t\fP \fBwriterGUID\fP"
.br
.RI "\fBGUID_t\fP of the writer that generated this change\&. "
.ti -1c
.RI "\fBInstanceHandle_t\fP \fBinstanceHandle\fP"
.br
.RI "Handle of the data associated wiht this change\&. "
.ti -1c
.RI "\fBSequenceNumber_t\fP \fBsequenceNumber\fP"
.br
.RI "SequenceNumber of the change\&. "
.ti -1c
.RI "\fBSerializedPayload_t\fP \fBserializedPayload\fP"
.br
.RI "Serialized Payload associated with the change\&. "
.ti -1c
.RI "bool \fBisRead\fP"
.br
.RI "Indicates if the cache has been read (only used in READERS) "
.ti -1c
.RI "\fBTime_t\fP \fBsourceTimestamp\fP"
.br
.RI "Source TimeStamp (only used in Readers) "
.ti -1c
.RI "\fBWriteParams\fP \fBwrite_params\fP"
.br
.ti -1c
.RI "bool \fBis_untyped_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure \fBCacheChange_t\fP, contains information on a specific CacheChange\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eprosima::fastrtps::rtps::CacheChange_t::CacheChange_t (uint32_t payload_size, bool is_untyped = \fCfalse\fP)\fC [inline]\fP"
Constructor with payload size 
.PP
\fBParameters\fP
.RS 4
\fIpayload_size\fP Serialized payload size 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool eprosima::fastrtps::rtps::CacheChange_t::copy (const \fBCacheChange_t\fP * ch_ptr)\fC [inline]\fP"
Copy a different change into this one\&. All the elements are copied, included the data, allocating new memory\&. 
.PP
\fBParameters\fP
.RS 4
\fIch_ptr\fP Pointer to the change\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if correct\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
