.TH "EprosimaClient" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EprosimaClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "Result::RESULTTYPE \fBcalculate\fP (Operation::OPERATIONTYPE type, int32_t num1, int32_t num2, int32_t *result)"
.br
.ti -1c
.RI "bool \fBisReady\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPublisher\fP * \fBmp_operation_pub\fP"
.br
.ti -1c
.RI "\fBSubscriber\fP * \fBmp_result_sub\fP"
.br
.ti -1c
.RI "\fBParticipant\fP * \fBmp_participant\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
