.TH "example_configuration" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
example_configuration
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Reliability_type \fBreliability\fP"
.br
.ti -1c
.RI "Durability_type \fBdurability\fP"
.br
.ti -1c
.RI "HistoryKind_type \fBhistorykind\fP"
.br
.ti -1c
.RI "Key_type \fBkeys\fP"
.br
.ti -1c
.RI "uint16_t \fBhistory_size\fP"
.br
.ti -1c
.RI "uint8_t \fBdepth\fP"
.br
.ti -1c
.RI "uint8_t \fBno_keys\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_samples_per_key\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
