.TH "FASTRTPS_GENERAL_API" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FASTRTPS_GENERAL_API \- eProsima Fast RTPS API Reference
.PP
 \- eProsima Fast RTPS API grouped in modules\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBRTPS\fP"
.br
.RI "RTPS API This is an implementation of the RTPS communication standard defined by the OMG\&. "
.ti -1c
.RI "\fBPublisher Subscriber Public API\fP"
.br
.RI "Publisher Subscriber Public API This Module contains the Publisher Subscriber Layer created to facilitate the use of the RTPS protocol\&. "
.ti -1c
.RI "\fBManagement Module\fP"
.br
.ti -1c
.RI "\fBShared Utilities\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
eProsima Fast RTPS API grouped in modules\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
