.TH "GeneralMessageBase" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneralMessageBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderableMessage\fP\&.
.PP
Inherited by \fBGeneralChannelMessage\fP, and \fBGeneralMessage\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBInsertRepeatedMessage\fP (int line_no, \fBGeneralMessageBase\fP *item)"
.br
.ti -1c
.RI "\fBRenderableMessage\fP * \fBChild\fP (int line_no) const override"
.br
.ti -1c
.RI "\fBGeneralMessageBase\fP (\fBRenderableMessage\fP *parent=nullptr)"
.br
.ti -1c
.RI "void \fBclear\fP (void)"
.br
.ti -1c
.RI "\fBGeneralMessageBase\fP (const \fBGeneralMessageBase\fP &)=delete"
.br
.ti -1c
.RI "\fBGeneralMessageBase\fP & \fBoperator=\fP (const \fBGeneralMessageBase\fP &)=delete"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrintMessage\fP (\fBGeneralMessageBase\fP *baseMsg, const google::protobuf::Message &msg, int *jump_lines, const \fBScreen\fP *s, int *line_no, int indent)"
.br
.ti -1c
.RI "static void \fBPrintField\fP (\fBGeneralMessageBase\fP *baseMsg, const google::protobuf::Message &msg, int *jump_lines, const \fBScreen\fP *s, int *line_no, int indent, const google::protobuf::Reflection *ref, const google::protobuf::FieldDescriptor *field, int index)"
.br
.ti -1c
.RI "static int \fBLineCount\fP (const google::protobuf::Message &msg, int screen_width)"
.br
.ti -1c
.RI "static int \fBLineCountOfField\fP (const google::protobuf::Message &msg, int screen_width, const google::protobuf::FieldDescriptor *field, const google::protobuf::Reflection *reflection, bool is_folded=true)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::map< const int, \fBGeneralMessageBase\fP * > \fBchildren_map_\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
