.TH "GeneralMessage" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneralMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGeneralMessageBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneralMessage\fP (\fBGeneralMessageBase\fP *parent, const google::protobuf::Message *msg, const google::protobuf::Reflection *reflection, const google::protobuf::FieldDescriptor *field)"
.br
.ti -1c
.RI "int \fBRender\fP (const \fBScreen\fP *s, int key) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
