.TH "google::LogMessage::LogStream" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::LogMessage::LogStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::ostream\&.
.PP
Inherited by \fBgoogle::NullStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogStream\fP (char *buf, int len, int ctr)"
.br
.ti -1c
.RI "int \fBctr\fP () const"
.br
.ti -1c
.RI "void \fBset_ctr\fP (int ctr)"
.br
.ti -1c
.RI "\fBLogStream\fP * \fBself\fP () const"
.br
.ti -1c
.RI "size_t \fBpcount\fP () const"
.br
.ti -1c
.RI "char * \fBpbase\fP () const"
.br
.ti -1c
.RI "char * \fBstr\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
