.TH "google::NullStream" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::NullStream
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgoogle::LogMessage::LogStream\fP\&.
.PP
Inherited by \fBgoogle::NullStreamFatal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullStream\fP (const char *, int, const \fBCheckOpString\fP &)"
.br
.ti -1c
.RI "\fBNullStream\fP & \fBstream\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
