.TH "google::base::CheckOpMessageBuilder" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::base::CheckOpMessageBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCheckOpMessageBuilder\fP (const char *exprtext)"
.br
.ti -1c
.RI "std::ostream * \fBForVar1\fP ()"
.br
.ti -1c
.RI "std::ostream * \fBForVar2\fP ()"
.br
.ti -1c
.RI "std::string * \fBNewString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
