.TH "google::LogMessageFatal" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::LogMessageFatal
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgoogle::LogMessage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogMessageFatal\fP (const char *file, int line)"
.br
.ti -1c
.RI "\fBLogMessageFatal\fP (const char *file, int line, const \fBCheckOpString\fP &result)"
.br
.ti -1c
.RI "\fB__attribute__\fP ((noreturn)) ~\fBLogMessageFatal\fP()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
