.TH "google::LogMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::LogMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgoogle::ErrnoLogMessage\fP, and \fBgoogle::LogMessageFatal\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogStream\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkNoLogPrefix\fP = -1 }"
.br
.ti -1c
.RI "typedef void(LogMessage::* \fBSendMethod\fP) ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, LogSeverity severity, int ctr, SendMethod send_method)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, LogSeverity severity)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, LogSeverity severity, \fBLogSink\fP *sink, bool also_send_to_log)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, LogSeverity severity, std::vector< std::string > *outvec)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, LogSeverity severity, std::string *message)"
.br
.ti -1c
.RI "\fBLogMessage\fP (const char *file, int line, const \fBCheckOpString\fP &result)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "void \fBSendToLog\fP ()"
.br
.ti -1c
.RI "void \fBSendToSyslogAndLog\fP ()"
.br
.ti -1c
.RI "std::ostream & \fBstream\fP ()"
.br
.ti -1c
.RI "int \fBpreserved_errno\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fB__attribute__\fP ((noreturn)) Fail()"
.br
.ti -1c
.RI "static int64 \fBnum_messages\fP (int severity)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBkMaxLogMessageLen\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBLogDestination\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
