.TH "google::base::Logger" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::base::Logger
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::logger::AsyncLogger\fP, \fBapollo::cyber::logger::LogFileObject\fP, and \fBapollo::cyber::logger::Logger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBWrite\fP (bool force_flush, time_t timestamp, const char *message, int message_len)=0"
.br
.ti -1c
.RI "virtual void \fBFlush\fP ()=0"
.br
.ti -1c
.RI "virtual uint32 \fBLogSize\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
