.TH "google::ErrnoLogMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
google::ErrnoLogMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgoogle::LogMessage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrnoLogMessage\fP (const char *file, int line, LogSeverity severity, int ctr, void(LogMessage::*send_method)())"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
