.TH "third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/Guid.h" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/Guid.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./fastrtps_dll\&.h'\fP
.br
\fC#include 'Types\&.h'\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::GuidPrefix_t\fP"
.br
.RI "Structure \fBGuidPrefix_t\fP, Guid Prefix of \fBGUID_t\fP\&. "
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::EntityId_t\fP"
.br
.RI "Structure \fBEntityId_t\fP, entity id part of \fBGUID_t\fP\&. "
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::GUID_t\fP"
.br
.RI "Structure \fBGUID_t\fP, entity identifier, unique in DDS-RTPS \fBDomain\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBeprosima\fP"
.br
.RI "Maximum payload is maximum of UDP packet size minus 536bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) With those 536 bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) bytes is posible to send RTPS Header plus RTPS Data submessage plus RTPS Heartbeat submessage\&. "
.ti -1c
.RI " \fBeprosima::fastrtps\fP"
.br
.ti -1c
.RI " \fBeprosima::fastrtps::rtps\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENTITYID_UNKNOWN\fP   0x00000000"
.br
.ti -1c
.RI "#define \fBENTITYID_RTPSParticipant\fP   0x000001c1"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_TOPIC_WRITER\fP   0x000002c2"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_TOPIC_READER\fP   0x000002c7"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_PUBLICATIONS_WRITER\fP   0x000003c2"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_PUBLICATIONS_READER\fP   0x000003c7"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_WRITER\fP   0x000004c2"
.br
.ti -1c
.RI "#define \fBENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_READER\fP   0x000004c7"
.br
.ti -1c
.RI "#define \fBENTITYID_SPDP_BUILTIN_RTPSParticipant_WRITER\fP   0x000100c2"
.br
.ti -1c
.RI "#define \fBENTITYID_SPDP_BUILTIN_RTPSParticipant_READER\fP   0x000100c7"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_WRITER\fP   0x000200C2"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_READER\fP   0x000200C7"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_WRITER\fP   0x000201C3"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_READER\fP   0x000201C4"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_WRITER\fP   0xff0202C3"
.br
.ti -1c
.RI "#define \fBENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_READER\fP   0xff0202C4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBeprosima::fastrtps::rtps::operator<<\fP (std::ostream &output, const GuidPrefix_t &guiP)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator==\fP (EntityId_t &id1, const uint32_t id2)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator==\fP (const EntityId_t &id1, const EntityId_t &id2)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator!=\fP (const EntityId_t &id1, const EntityId_t &id2)"
.br
.ti -1c
.RI "std::ostream & \fBeprosima::fastrtps::rtps::operator<<\fP (std::ostream &output, const EntityId_t &enI)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator==\fP (const GUID_t &g1, const GUID_t &g2)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator!=\fP (const GUID_t &g1, const GUID_t &g2)"
.br
.ti -1c
.RI "bool \fBeprosima::fastrtps::rtps::operator<\fP (const GUID_t &g1, const GUID_t &g2)"
.br
.ti -1c
.RI "std::ostream & \fBeprosima::fastrtps::rtps::operator<<\fP (std::ostream &output, const GUID_t &guid)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const GuidPrefix_t \fBeprosima::fastrtps::rtps::c_GuidPrefix_Unknown\fP"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_Unknown\fP = ENTITYID_UNKNOWN"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SPDPReader\fP = ENTITYID_SPDP_BUILTIN_RTPSParticipant_READER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SPDPWriter\fP = ENTITYID_SPDP_BUILTIN_RTPSParticipant_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SEDPPubWriter\fP = ENTITYID_SEDP_BUILTIN_PUBLICATIONS_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SEDPPubReader\fP = ENTITYID_SEDP_BUILTIN_PUBLICATIONS_READER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SEDPSubWriter\fP = ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_SEDPSubReader\fP = ENTITYID_SEDP_BUILTIN_SUBSCRIPTIONS_READER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_RTPSParticipant\fP = ENTITYID_RTPSParticipant"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_WriterLiveliness\fP = ENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::c_EntityId_ReaderLiveliness\fP = ENTITYID_P2P_BUILTIN_RTPSParticipant_MESSAGE_READER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::participant_stateless_message_writer_entity_id\fP = ENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::participant_stateless_message_reader_entity_id\fP = ENTITYID_P2P_BUILTIN_PARTICIPANT_STATELESS_READER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::participant_volatile_message_secure_writer_entity_id\fP = ENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_WRITER"
.br
.ti -1c
.RI "const EntityId_t \fBeprosima::fastrtps::rtps::participant_volatile_message_secure_reader_entity_id\fP = ENTITYID_P2P_BUILTIN_PARTICIPANT_VOLATILE_MESSAGE_SECURE_READER"
.br
.ti -1c
.RI "const GUID_t \fBeprosima::fastrtps::rtps::c_Guid_Unknown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
