.TH "third_party/fast-rtps-1.5.0-1/examples/C++/StaticHelloWorldExample/HelloWorld_main.cpp" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/examples/C++/StaticHelloWorldExample/HelloWorld_main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'HelloWorldPublisher\&.h'\fP
.br
\fC#include 'HelloWorldSubscriber\&.h'\fP
.br
\fC#include <fastrtps/Domain\&.h>\fP
.br
\fC#include <fastrtps/utils/eClock\&.h>\fP
.br
\fC#include <fastrtps/log/Log\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
