.TH "HelloWorldSubscriber" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelloWorldSubscriber
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSubListener\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "RUN the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run the subscriber until number samples have been recevied\&. "
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "RUN the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run the subscriber until number samples have been recevied\&. "
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "RUN the subscriber\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run the subscriber until number samples have been recevied\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHelloWorldSubscriber::SubListener\fP \fBm_listener\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
