.TH "HelloMsg" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelloMsg \- This class represents the structure \fBHelloMsg\fP defined by the user in the IDL file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deadlinepayload\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "eProsima_user_DllExport \fBHelloMsg\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~HelloMsg\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBHelloMsg\fP (const \fBHelloMsg\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBHelloMsg\fP (\fBHelloMsg\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBHelloMsg\fP & \fBoperator=\fP (const \fBHelloMsg\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBHelloMsg\fP & \fBoperator=\fP (\fBHelloMsg\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeadlinekey\fP (uint16_t _deadlinekey)"
.br
.RI "This function sets a value in member deadlinekey\&. "
.ti -1c
.RI "eProsima_user_DllExport uint16_t \fBdeadlinekey\fP () const"
.br
.RI "This function returns the value of member deadlinekey\&. "
.ti -1c
.RI "eProsima_user_DllExport uint16_t & \fBdeadlinekey\fP ()"
.br
.RI "This function returns a reference to member deadlinekey\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBpayload\fP (const std::string &_payload)"
.br
.RI "This function copies the value in member payload\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBpayload\fP (std::string &&_payload)"
.br
.RI "This function moves the value in member payload\&. "
.ti -1c
.RI "eProsima_user_DllExport const std::string & \fBpayload\fP () const"
.br
.RI "This function returns a constant reference to member payload\&. "
.ti -1c
.RI "eProsima_user_DllExport std::string & \fBpayload\fP ()"
.br
.RI "This function returns a reference to member payload\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBHelloMsg\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Key unsigned short \fBdeadlinekey\fP"
.br
.ti -1c
.RI "string< 256 > \fBpayload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the structure \fBHelloMsg\fP defined by the user in the IDL file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HelloMsg::HelloMsg (const \fBHelloMsg\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBHelloMsg\fP that will be copied\&. 
.RE
.PP

.SS "HelloMsg::HelloMsg (\fBHelloMsg\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBHelloMsg\fP that will be copied\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "eProsima_user_DllExport uint16_t& HelloMsg::deadlinekey ()\fC [inline]\fP"

.PP
This function returns a reference to member deadlinekey\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member deadlinekey 
.RE
.PP

.SS "eProsima_user_DllExport uint16_t HelloMsg::deadlinekey () const\fC [inline]\fP"

.PP
This function returns the value of member deadlinekey\&. 
.PP
\fBReturns\fP
.RS 4
Value of member deadlinekey 
.RE
.PP

.SS "eProsima_user_DllExport void HelloMsg::deadlinekey (uint16_t _deadlinekey)\fC [inline]\fP"

.PP
This function sets a value in member deadlinekey\&. 
.PP
\fBParameters\fP
.RS 4
\fI_deadlinekey\fP New value for member deadlinekey 
.RE
.PP

.SS "void HelloMsg::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "size_t HelloMsg::getCdrSerializedSize (const \fBHelloMsg\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "size_t HelloMsg::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "size_t HelloMsg::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "\fBHelloMsg\fP & HelloMsg::operator= (const \fBHelloMsg\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBHelloMsg\fP that will be copied\&. 
.RE
.PP

.SS "\fBHelloMsg\fP & HelloMsg::operator= (\fBHelloMsg\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object \fBHelloMsg\fP that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport std::string& HelloMsg::payload ()\fC [inline]\fP"

.PP
This function returns a reference to member payload\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member payload 
.RE
.PP

.SS "eProsima_user_DllExport const std::string& HelloMsg::payload () const\fC [inline]\fP"

.PP
This function returns a constant reference to member payload\&. 
.PP
\fBReturns\fP
.RS 4
Constant reference to member payload 
.RE
.PP

.SS "eProsima_user_DllExport void HelloMsg::payload (const std::string & _payload)\fC [inline]\fP"

.PP
This function copies the value in member payload\&. 
.PP
\fBParameters\fP
.RS 4
\fI_payload\fP New value to be copied in member payload 
.RE
.PP

.SS "eProsima_user_DllExport void HelloMsg::payload (std::string && _payload)\fC [inline]\fP"

.PP
This function moves the value in member payload\&. 
.PP
\fBParameters\fP
.RS 4
\fI_payload\fP New value to be moved in member payload 
.RE
.PP

.SS "void HelloMsg::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "void HelloMsg::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
