.TH "HelloWorldPublisher" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelloWorldPublisher
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize\&. "
.ti -1c
.RI "bool \fBpublish\fP ()"
.br
.RI "Publish a sample\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run for number samples\&. "
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize\&. "
.ti -1c
.RI "bool \fBpublish\fP ()"
.br
.RI "Publish a sample\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run for number samples\&. "
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.RI "Initialize\&. "
.ti -1c
.RI "bool \fBpublish\fP ()"
.br
.RI "Publish a sample\&. "
.ti -1c
.RI "void \fBrun\fP (uint32_t number)"
.br
.RI "Run for number samples\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
