.TH "HelloWorldSubscriber::SubListener" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelloWorldSubscriber::SubListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBeprosima::fastrtps::SubscriberListener\fP, \fBeprosima::fastrtps::SubscriberListener\fP, and \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonSubscriptionMatched\fP (\fBSubscriber\fP *sub, \fBMatchingInfo\fP &info)"
.br
.ti -1c
.RI "void \fBonNewDataMessage\fP (\fBSubscriber\fP *sub)"
.br
.ti -1c
.RI "void \fBonSubscriptionMatched\fP (\fBSubscriber\fP *sub, \fBMatchingInfo\fP &info)"
.br
.ti -1c
.RI "void \fBonNewDataMessage\fP (\fBSubscriber\fP *sub)"
.br
.ti -1c
.RI "void \fBonSubscriptionMatched\fP (\fBSubscriber\fP *sub, \fBMatchingInfo\fP &info)"
.br
.ti -1c
.RI "void \fBonNewDataMessage\fP (\fBSubscriber\fP *sub)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHelloWorld\fP \fBm_Hello\fP"
.br
.ti -1c
.RI "\fBSampleInfo_t\fP \fBm_info\fP"
.br
.ti -1c
.RI "int \fBn_matched\fP"
.br
.ti -1c
.RI "uint32_t \fBn_samples\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void HelloWorldSubscriber::SubListener::onNewDataMessage (\fBSubscriber\fP * sub)\fC [virtual]\fP"
Virtual function to be implemented by the user containing the actions to be performed when a new Data Message is received\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "void HelloWorldSubscriber::SubListener::onNewDataMessage (\fBSubscriber\fP * sub)\fC [virtual]\fP"
Virtual function to be implemented by the user containing the actions to be performed when a new Data Message is received\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "void HelloWorldSubscriber::SubListener::onNewDataMessage (\fBSubscriber\fP * sub)\fC [virtual]\fP"
Virtual function to be implemented by the user containing the actions to be performed when a new Data Message is received\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "void HelloWorldSubscriber::SubListener::onSubscriptionMatched (\fBSubscriber\fP * sub, \fBMatchingInfo\fP & info)\fC [virtual]\fP"
Virtual method to be called when the subscriber is matched with a new Writer (or unmatched); i\&.e\&., when a writer publishing in the same topic is discovered\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.br
\fIinfo\fP Matching information 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "void HelloWorldSubscriber::SubListener::onSubscriptionMatched (\fBSubscriber\fP * sub, \fBMatchingInfo\fP & info)\fC [virtual]\fP"
Virtual method to be called when the subscriber is matched with a new Writer (or unmatched); i\&.e\&., when a writer publishing in the same topic is discovered\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.br
\fIinfo\fP Matching information 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.
.SS "void HelloWorldSubscriber::SubListener::onSubscriptionMatched (\fBSubscriber\fP * sub, \fBMatchingInfo\fP & info)\fC [virtual]\fP"
Virtual method to be called when the subscriber is matched with a new Writer (or unmatched); i\&.e\&., when a writer publishing in the same topic is discovered\&. 
.PP
\fBParameters\fP
.RS 4
\fIsub\fP Subscriber 
.br
\fIinfo\fP Matching information 
.RE
.PP

.PP
Reimplemented from \fBeprosima::fastrtps::SubscriberListener\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
