.TH "init_test.TestInit" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init_test.TestInit
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_init\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for init unit test.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def init_test\&.TestInit\&.test_init ( self)"

.PP
.nf
Test cyber.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
