.TH "is_proto_enum< ::apollo::cyber::proto::RoleType >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_proto_enum< ::apollo::cyber::proto::RoleType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
