.TH "is_proto_enum< ::apollo::drivers::Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_proto_enum< ::apollo::drivers::Vehicle5_5f4_Can_rx_yaw_rate_bias_shiftType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
