.TH "cyber/logger/logger_util.h" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cyber/logger/logger_util.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/utsname\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'cyber/common/global_data\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBapollo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int64_t \fBapollo::cyber::logger::CycleClock_Now\fP ()"
.br
.ti -1c
.RI "int64_t \fBapollo::cyber::logger::UsecToCycles\fP (int64_t usec)"
.br
.ti -1c
.RI "int32_t \fBapollo::cyber::logger::GetMainThreadPid\fP ()"
.br
.ti -1c
.RI "bool \fBapollo::cyber::logger::PidHasChanged\fP ()"
.br
.ti -1c
.RI "int32_t \fBapollo::cyber::logger::MaxLogSize\fP ()"
.br
.ti -1c
.RI "void \fBapollo::cyber::logger::FindModuleName\fP (std::string *log_message, std::string *module_name)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
