.TH "md_cyber_examples_common_component_example_README" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_cyber_examples_common_component_example_README \- Common Component Example of the CyberRT framework 

.SH "How to Build"
.PP
.PP
.nf
\&./apollo\&.sh build cyber
.fi
.PP
.PP
Or if you use Bazel directly,
.PP
.PP
.nf
bazel build //cyber/examples/common_component_example/\&.\&.\&.
.fi
.PP
.SH "How to Run"
.PP
.SS "Enable logging to stderr"
.IP "\(bu" 2
Change \fCGLOG_alsologtostderr\fP from \fC0\fP to \fC1\fP in \fCcyber/setup\&.bash\fP
.IP "\(bu" 2
Run \fCsource cyber/setup\&.bash\fP in current console\&.
.PP
.PP
.PP
.nf
export GLOG_alsologtostderr=1
.fi
.PP
.SS "Start the sample component"
.PP
.nf
cyber_launch start cyber/examples/common_component_example/common\&.launch
.fi
.PP
.PP
Or
.PP
.PP
.nf
mainboard -d cyber/examples/common_component_example/common\&.dag
.fi
.PP
.SS "Start the writer nodes"
Open two more terminals, run the following commands respectively\&.
.PP
.PP
.nf
bazel run  //cyber/examples/common_component_example:channel_test_writer
.fi
.PP
.PP
and \&.\&.\&.
.PP
.PP
.nf
bazel run //cyber/examples/common_component_example:channel_prediction_writer
.fi
.PP
.PP
Now you should see console output of the \fC\fBCommonComponentSample\fP\fP example from the first terminal\&. 
