.TH "md_cyber_doxy_docs_source_CyberRT_Docker" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_cyber_doxy_docs_source_CyberRT_Docker \- How to Develop Cyber RT inside Docker on Both x86_64 and ARM64 
To make life easier, Apollo maintains Cyber Docker images and a number of scripts to help developers build and play with Cyber RT framework\&.
.PP
Cyber Docker images are built upon Ubuntu 18\&.04, and comes with full support for Cyber RT framework\&. For those who are interested in Cyber RT only, this would be the ideal point to start with\&.
.PP
\fBNote: Apollo team also maintains ARM64 Cyber Docker images which was tested on Jetson AGX Xavier\&. The same set of scripts are provided to run both on x86_64 and ARM64 platforms\&.\fP
.PP
In the next section, we will show you how to play with Cyber Docker images\&.
.SH "Build and Test Cyber RT inside Docker"
.PP
Run the following command to start Cyber Docker container:
.PP
.PP
.nf
bash docker/scripts/cyber_start\&.sh
.fi
.PP
.PP
Or if you are in China, run:
.PP
.PP
.nf
bash docker/scripts/cyber_start\&.sh -g cn
.fi
.PP
.PP
A Docker container named \fCapollo_cyber_$USER\fP will be started\&.
.PP
\fBNote\fP: You will lose all your previous changes in the container if you have ran this command before\&. Unless you would like to start a fresh Docker environment\&.
.PP
To log into the newly started Cyber container:
.PP
.PP
.nf
bash docker/scripts/cyber_into\&.sh
.fi
.PP
.PP
\fBNote\fP: you can login and logout Cyber container multiple times as you wish, the Docker environment will stay there until the next time you start another Cyber container\&.
.PP
To build Cyber RT only and run unit tests:
.PP
.PP
.nf
\&./apollo\&.sh build cyber
\&./apollo\&.sh test cyber
.fi
.PP
.PP
Or run with \fC--config=opt\fP for an optimized build/test\&.
.PP
.PP
.nf
\&./apollo\&.sh build --config=opt cyber
\&./apollo\&.sh test --config=opt cyber
.fi
.PP
.PP
You should be able to see that all the testcases passed\&. 
