.TH "md_third_party_include_gmock_internal_custom_README" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_third_party_include_gmock_internal_custom_README \- Customization Points 
The custom directory is an injection point for custom user configurations\&.
.SH "Header <tt>gmock-port\&.h</tt>"
.PP
The following macros can be defined:
.SS "Flag related macros:"
.IP "\(bu" 2
\fCGMOCK_DECLARE_bool_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DECLARE_int32_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DECLARE_string_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_bool_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_int32_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_string_(name, default_val, doc)\fP 
.PP

