.TH "md_third_party_include_gtest_internal_custom_README" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_third_party_include_gtest_internal_custom_README \- Customization Points 
The custom directory is an injection point for custom user configurations\&.
.SH "Header <tt>gtest\&.h</tt>"
.PP
.SS "The following macros can be defined:"
.IP "\(bu" 2
\fCGTEST_OS_STACK_TRACE_GETTER_\fP - The name of an implementation of \fCOsStackTraceGetterInterface\fP\&.
.IP "\(bu" 2
\fCGTEST_CUSTOM_TEMPDIR_FUNCTION_\fP - An override for \fCtesting::TempDir()\fP\&. See \fCtesting::TempDir\fP for semantics and signature\&.
.PP
.SH "Header <tt>gtest-port\&.h</tt>"
.PP
The following macros can be defined:
.SS "Flag related macros:"
.IP "\(bu" 2
\fCGTEST_FLAG(flag_name)\fP
.IP "\(bu" 2
\fCGTEST_USE_OWN_FLAGFILE_FLAG_\fP - Define to 0 when the system provides its own flagfile flag parsing\&.
.IP "\(bu" 2
\fCGTEST_DECLARE_bool_(name)\fP
.IP "\(bu" 2
\fCGTEST_DECLARE_int32_(name)\fP
.IP "\(bu" 2
\fCGTEST_DECLARE_string_(name)\fP
.IP "\(bu" 2
\fCGTEST_DEFINE_bool_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGTEST_DEFINE_int32_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGTEST_DEFINE_string_(name, default_val, doc)\fP
.PP
.SS "Logging:"
.IP "\(bu" 2
\fCGTEST_LOG_(severity)\fP
.IP "\(bu" 2
\fCGTEST_CHECK_(condition)\fP
.IP "\(bu" 2
Functions \fCLogToStderr()\fP and \fCFlushInfoLog()\fP have to be provided too\&.
.PP
.SS "Threading:"
.IP "\(bu" 2
\fCGTEST_HAS_NOTIFICATION_\fP - Enabled if Notification is already provided\&.
.IP "\(bu" 2
\fCGTEST_HAS_MUTEX_AND_THREAD_LOCAL_\fP - Enabled if \fCMutex\fP and \fCThreadLocal\fP are already provided\&. Must also provide \fCGTEST_DECLARE_STATIC_MUTEX_(mutex)\fP and \fCGTEST_DEFINE_STATIC_MUTEX_(mutex)\fP
.IP "\(bu" 2
\fCGTEST_EXCLUSIVE_LOCK_REQUIRED_(locks)\fP
.IP "\(bu" 2
\fCGTEST_LOCK_EXCLUDED_(locks)\fP
.PP
.SS "Underlying library support features"
.IP "\(bu" 2
\fCGTEST_HAS_CXXABI_H_\fP
.PP
.SS "Exporting API symbols:"
.IP "\(bu" 2
\fCGTEST_API_\fP - Specifier for exported symbols\&.
.PP
.SH "Header <tt>gtest-printers\&.h</tt>"
.PP
.IP "\(bu" 2
See documentation at \fC\fBgtest/gtest-printers\&.h\fP\fP for details on how to define a custom printer\&. 
.PP

