.TH "record_test.TestRecord" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
record_test.TestRecord
.SH SYNOPSIS
.br
.PP
.PP
Inherits unittest\&.TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_record_writer_read\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Class for record unit test.

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def record_test\&.TestRecord\&.test_record_writer_read ( self)"

.PP
.nf
unit test of record.

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
