.TH "RenderableMessage" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderableMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCyberTopologyMessage\fP, and \fBGeneralMessageBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderableMessage\fP (\fBRenderableMessage\fP *parent=nullptr, int line_no=0)"
.br
.ti -1c
.RI "virtual int \fBRender\fP (const \fBScreen\fP *s, int key)=0"
.br
.ti -1c
.RI "virtual \fBRenderableMessage\fP * \fBChild\fP (int) const =0"
.br
.ti -1c
.RI "virtual double \fBframe_ratio\fP (void)"
.br
.ti -1c
.RI "\fBRenderableMessage\fP * \fBparent\fP (void) const"
.br
.ti -1c
.RI "void \fBset_parent\fP (\fBRenderableMessage\fP *parent)"
.br
.ti -1c
.RI "int \fBpage_item_count\fP (void) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBFrameRatio_Precision\fP = 2"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int * \fBline_no\fP (void)"
.br
.ti -1c
.RI "void \fBset_line_no\fP (int line_no)"
.br
.ti -1c
.RI "void \fBreset_line_page\fP (void)"
.br
.ti -1c
.RI "void \fBSplitPages\fP (int key)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBline_no_\fP"
.br
.ti -1c
.RI "int \fBpages_\fP"
.br
.ti -1c
.RI "int \fBpage_index_\fP"
.br
.ti -1c
.RI "int \fBpage_item_count_\fP"
.br
.ti -1c
.RI "\fBRenderableMessage\fP * \fBparent_\fP"
.br
.ti -1c
.RI "double \fBframe_ratio_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBScreen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
