.TH "sample" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sample \- This class represents the structure sample defined by the user in the IDL file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sample\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fB~sample\fP ()"
.br
.RI "Default destructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (const \fBsample\fP &x)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP (\fBsample\fP &&x)"
.br
.RI "Move constructor\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (const \fBsample\fP &x)"
.br
.RI "Copy assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport \fBsample\fP & \fBoperator=\fP (\fBsample\fP &&x)"
.br
.RI "Move assignment\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBindex\fP (uint8_t _index)"
.br
.RI "This function sets a value in member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBindex\fP () const"
.br
.RI "This function returns the value of member index\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBindex\fP ()"
.br
.RI "This function returns a reference to member index\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBkey_value\fP (uint8_t _key_value)"
.br
.RI "This function sets a value in member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t \fBkey_value\fP () const"
.br
.RI "This function returns the value of member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport uint8_t & \fBkey_value\fP ()"
.br
.RI "This function returns a reference to member key_value\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBdeserialize\fP (\fBeprosima::fastcdr::Cdr\fP &cdr)"
.br
.RI "This function deserializes an object using CDR serialization\&. "
.ti -1c
.RI "eProsima_user_DllExport void \fBserializeKey\fP (\fBeprosima::fastcdr::Cdr\fP &cdr) const"
.br
.RI "This function serializes the key members of an object using CDR serialization\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetCdrSerializedSize\fP (const \fBsample\fP &data, size_t current_alignment=0)"
.br
.RI "This function returns the serialized size of a data depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport size_t \fBgetKeyMaxCdrSerializedSize\fP (size_t current_alignment=0)"
.br
.RI "This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. "
.ti -1c
.RI "static eProsima_user_DllExport bool \fBisKeyDefined\fP ()"
.br
.RI "This function tells you if the Key has been defined for this type\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "octet \fBindex\fP"
.br
.ti -1c
.RI "Key octet \fBkey_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents the structure sample defined by the user in the IDL file\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (const \fBsample\fP & x)"

.PP
Copy constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport sample::sample (\fBsample\fP && x)"

.PP
Move constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::deserialize (\fBeprosima::fastcdr::Cdr\fP & cdr)"

.PP
This function deserializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getCdrSerializedSize (const \fBsample\fP & data, size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the serialized size of a data depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Data which is calculated its serialized size\&. 
.br
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Serialized size\&. 
.RE
.PP

.SS "size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getKeyMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "static eProsima_user_DllExport size_t sample::getMaxCdrSerializedSize (size_t current_alignment = \fC0\fP)\fC [static]\fP"

.PP
This function returns the maximum serialized size of an object depending on the buffer alignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrent_alignment\fP Buffer alignment\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Maximum serialized size\&. 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::index ()\fC [inline]\fP"

.PP
This function returns a reference to member index\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::index () const\fC [inline]\fP"

.PP
This function returns the value of member index\&. 
.PP
\fBReturns\fP
.RS 4
Value of member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport void sample::index (uint8_t _index)\fC [inline]\fP"

.PP
This function sets a value in member index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_index\fP New value for member index 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t& sample::key_value ()\fC [inline]\fP"

.PP
This function returns a reference to member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Reference to member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport uint8_t sample::key_value () const\fC [inline]\fP"

.PP
This function returns the value of member key_value\&. 
.PP
\fBReturns\fP
.RS 4
Value of member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "eProsima_user_DllExport void sample::key_value (uint8_t _key_value)\fC [inline]\fP"

.PP
This function sets a value in member key_value\&. 
.PP
\fBParameters\fP
.RS 4
\fI_key_value\fP New value for member key_value 
.RE
.PP

.SS "\fBsample\fP & sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (const \fBsample\fP & x)"

.PP
Copy assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "\fBsample\fP & sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "eProsima_user_DllExport \fBsample\fP& sample::operator= (\fBsample\fP && x)"

.PP
Move assignment\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Reference to the object sample that will be copied\&. 
.RE
.PP

.SS "void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serialize (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP

.SS "eProsima_user_DllExport void sample::serializeKey (\fBeprosima::fastcdr::Cdr\fP & cdr) const"

.PP
This function serializes the key members of an object using CDR serialization\&. 
.PP
\fBParameters\fP
.RS 4
\fIcdr\fP CDR serialization object\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
