.TH "third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/SerializedPayload.h" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/include/fastrtps/rtps/common/SerializedPayload.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./fastrtps_dll\&.h'\fP
.br
\fC#include 'Types\&.h'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <new>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBeprosima::fastrtps::rtps::SerializedPayload_t\fP"
.br
.RI "Structure \fBSerializedPayload_t\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBeprosima\fP"
.br
.RI "Maximum payload is maximum of UDP packet size minus 536bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) With those 536 bytes (RTPSMESSAGE_COMMON_RTPS_PAYLOAD_SIZE) bytes is posible to send RTPS Header plus RTPS Data submessage plus RTPS Heartbeat submessage\&. "
.ti -1c
.RI " \fBeprosima::fastrtps\fP"
.br
.ti -1c
.RI " \fBeprosima::fastrtps::rtps\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCDR_BE\fP   0x0000"
.br
.ti -1c
.RI "#define \fBCDR_LE\fP   0x0001"
.br
.ti -1c
.RI "#define \fBPL_CDR_BE\fP   0x0002"
.br
.ti -1c
.RI "#define \fBPL_CDR_LE\fP   0x0003"
.br
.in -1c
.SH "Detailed Description"
.PP 

.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
