.TH "TableStruct_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fspeed_5fcontrol_2eproto" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableStruct_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fspeed_5fcontrol_2eproto
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[] \fBPROTOBUF_SECTION_VARIABLE\fP (protodesc_cold)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[] \fBPROTOBUF_SECTION_VARIABLE\fP (protodesc_cold)"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2] \fBPROTOBUF_SECTION_VARIABLE\fP (protodesc_cold)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata \fBfield_metadata\fP []"
.br
.ti -1c
.RI "static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable \fBserialization_table\fP []"
.br
.ti -1c
.RI "static const uint32_t \fBoffsets\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
