.TH "testing::internal::TestFactoryBase" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::internal::ParameterizedTestFactory< TestClass >\fP, and \fBtesting::internal::TestFactoryImpl< TestClass >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
