.TH "testing::internal::Random" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Random
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandom\fP (UInt32 seed)"
.br
.ti -1c
.RI "void \fBReseed\fP (UInt32 seed)"
.br
.ti -1c
.RI "UInt32 \fBGenerate\fP (UInt32 range)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const UInt32 \fBkMaxRange\fP = 1u << 31"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
