.TH "testing::Message" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Message
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (const \fBMessage\fP &msg)"
.br
.ti -1c
.RI "\fBMessage\fP (const char *str)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (const T &val)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (T *const &pointer)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (BasicNarrowIoManip val)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (bool b)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (const wchar_t *wide_c_str)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (wchar_t *wide_c_str)"
.br
.ti -1c
.RI "std::string \fBGetString\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
