.TH "testing::internal::NativeArray< Element >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::NativeArray< Element >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Element \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef Element * \fBiterator\fP"
.br
.ti -1c
.RI "typedef const Element * \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNativeArray\fP (const Element *array, size_t count, \fBRelationToSourceReference\fP)"
.br
.ti -1c
.RI "\fBNativeArray\fP (const Element *array, size_t count, \fBRelationToSourceCopy\fP)"
.br
.ti -1c
.RI "\fBNativeArray\fP (const \fBNativeArray\fP &rhs)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNativeArray\fP &rhs) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
