.TH "testing::ScopedTrace" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::ScopedTrace
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBScopedTrace\fP (const char *file, int line, const T &message)"
.br
.ti -1c
.RI "\fBScopedTrace\fP (const char *file, int line, const char *message)"
.br
.ti -1c
.RI "\fBScopedTrace\fP (const char *file, int line, const std::string &message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
