.TH "testing::internal::IgnoreResultAction< A >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IgnoreResultAction< A >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIgnoreResultAction\fP (const A &action)"
.br
.ti -1c
.RI "template<typename F > \fBoperator Action< F >\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
