.TH "testing::internal::ValueArray< Ts >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValueArray< Ts >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueArray\fP (Ts\&.\&.\&. v)"
.br
.ti -1c
.RI "template<typename T > \fBoperator ParamGenerator< T >\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
