.TH "testing::internal::CartesianProductHolder< Gen >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CartesianProductHolder< Gen >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCartesianProductHolder\fP (const Gen &\&.\&.\&. g)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> \fBoperator ParamGenerator<::std::tuple< T\&.\&.\&. >>\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
