.TH "testing::internal::SuiteApiResolver< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::SuiteApiResolver< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits T\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBTest\fP = typename std::conditional< sizeof(T) !=0, ::\fBtesting::Test\fP, void >::type"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static SetUpTearDownSuiteFuncType \fBGetSetUpCaseOrSuite\fP (const char *filename, int line_num)"
.br
.ti -1c
.RI "static SetUpTearDownSuiteFuncType \fBGetTearDownCaseOrSuite\fP (const char *filename, int line_num)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
