.TH "testing::Action< F >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Action< F >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBinternal::Function\fP< F >::Result \fBResult\fP"
.br
.ti -1c
.RI "typedef \fBinternal::Function\fP< F >::ArgumentTuple \fBArgumentTuple\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename G , typename  = typename ::std::enable_if<                ::std::is_constructible<::std::function<F>, G>::value>::type> \fBAction\fP (G &&fun)"
.br
.ti -1c
.RI "\fBAction\fP (\fBActionInterface\fP< F > *impl)"
.br
.ti -1c
.RI "template<typename Func > \fBAction\fP (const \fBAction\fP< Func > &action)"
.br
.ti -1c
.RI "bool \fBIsDoDefault\fP () const"
.br
.ti -1c
.RI "Result \fBPerform\fP (ArgumentTuple args) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
