.TH "testing::internal::ParameterizedTestSuiteInfoBase" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestSuiteInfoBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::internal::ParameterizedTestSuiteInfo< TestSuite >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const std::string & \fBGetTestSuiteName\fP () const =0"
.br
.ti -1c
.RI "virtual TypeId \fBGetTestSuiteTypeId\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBRegisterTests\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
