.TH "testing::TestProperty" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestProperty
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestProperty\fP (const std::string &a_key, const std::string &a_value)"
.br
.ti -1c
.RI "const char * \fBkey\fP () const"
.br
.ti -1c
.RI "const char * \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBSetValue\fP (const std::string &new_value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
