.TH "testing::internal::Function< R(Args...)>" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Function< R(Args...)>
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBResult\fP = R"
.br
.ti -1c
.RI "template<size_t I> using \fBArg\fP = \fBElemFromList\fP< I, typename \fBMakeIndexSequence\fP< sizeof\&.\&.\&.(Args)>::type, Args\&.\&.\&. >"
.br
.ti -1c
.RI "using \fBArgumentTuple\fP = std::tuple< Args\&.\&.\&. >"
.br
.ti -1c
.RI "using \fBArgumentMatcherTuple\fP = std::tuple< \fBMatcher\fP< Args >\&.\&.\&. >"
.br
.ti -1c
.RI "using \fBMakeResultVoid\fP = void(Args\&.\&.\&.)"
.br
.ti -1c
.RI "using \fBMakeResultIgnoredValue\fP = \fBIgnoredValue\fP(Args\&.\&.\&.)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBArgumentCount\fP = sizeof\&.\&.\&.(Args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
