.TH "testing::internal::ParamIterator< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamIterator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef const T & \fBreference\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBdifference_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamIterator\fP (const \fBParamIterator\fP &other)"
.br
.ti -1c
.RI "\fBParamIterator\fP & \fBoperator=\fP (const \fBParamIterator\fP &other)"
.br
.ti -1c
.RI "const T & \fBoperator*\fP () const"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBParamIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBParamIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBParamIterator\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBParamIterator\fP &other) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBParamGenerator< T >\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
