.TH "testing::internal::IsRecursiveContainer< C >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainer< C >
.SH SYNOPSIS
.br
.PP
.PP
Inherits IsRecursiveContainerImpl::type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
