.TH "testing::Test" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Test
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBapollo::cyber::ParameterClientTest\fP, \fBapollo::cyber::ParameterServerTest\fP, \fBapollo::cyber::ParameterTest\fP, \fBapollo::cyber::service_discovery::ChannelManagerTest\fP, \fBapollo::cyber::service_discovery::NodeManagerTest\fP, \fBapollo::cyber::service_discovery::ServiceManagerTest\fP, \fBapollo::cyber::service_discovery::TopologyTest\fP, \fBapollo::cyber::service_discovery::WarehouseTest\fP, \fBapollo::cyber::transport::DispatcherTest\fP, \fBapollo::cyber::transport::HybridTransceiverTest\fP, \fBapollo::cyber::transport::IntraTranceiverTest\fP, \fBapollo::cyber::transport::RtpsTransceiverTest\fP, \fBapollo::cyber::transport::ShmTransceiverTest\fP, and \fBtesting::TestWithParam< T >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBHasNonfatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBIsSkipped\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFailure\fP ()"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, const std::string &value)"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, int value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTestInfo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
