.TH "testing::WithParamInterface< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::WithParamInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::TestWithParam< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const ParamType & \fBGetParam\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class TestClass > class \fBinternal::ParameterizedTestFactory\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
