.TH "third_party/fast-rtps-1.5.0-1/examples/C++/RTPSTest_registered/TestReaderRegistered.cpp" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
third_party/fast-rtps-1.5.0-1/examples/C++/RTPSTest_registered/TestReaderRegistered.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TestReaderRegistered\&.h'\fP
.br
\fC#include 'fastrtps/rtps/reader/RTPSReader\&.h'\fP
.br
\fC#include 'fastrtps/rtps/participant/RTPSParticipant\&.h'\fP
.br
\fC#include 'fastrtps/rtps/RTPSDomain\&.h'\fP
.br
\fC#include 'fastrtps/rtps/attributes/RTPSParticipantAttributes\&.h'\fP
.br
\fC#include 'fastrtps/rtps/attributes/ReaderAttributes\&.h'\fP
.br
\fC#include 'fastrtps/rtps/attributes/HistoryAttributes\&.h'\fP
.br
\fC#include 'fastrtps/rtps/history/ReaderHistory\&.h'\fP
.br
\fC#include 'fastrtps/attributes/TopicAttributes\&.h'\fP
.br
\fC#include 'fastrtps/qos/ReaderQos\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
