.TH "testing::NaggyMock< MockClass >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::NaggyMock< MockClass >
.SH SYNOPSIS
.br
.PP
.PP
Inherits MockClass\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename A > \fBNaggyMock\fP (A &&arg)"
.br
.ti -1c
.RI "template<typename A1 , typename A2 , typename\&.\&.\&. An> \fBNaggyMock\fP (A1 &&arg1, A2 &&arg2, An &&\&.\&.\&. args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
