.TH "testing::internal::SetErrnoAndReturnAction< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::SetErrnoAndReturnAction< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetErrnoAndReturnAction\fP (int errno_value, T result)"
.br
.ti -1c
.RI "template<typename Result , typename ArgumentTuple > Result \fBPerform\fP (const ArgumentTuple &) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
