.TH "testing::DefaultValue< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::DefaultValue< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T(* \fBFactoryFunction\fP) ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSet\fP (T x)"
.br
.ti -1c
.RI "static void \fBSetFactory\fP (FactoryFunction factory)"
.br
.ti -1c
.RI "static void \fBClear\fP ()"
.br
.ti -1c
.RI "static bool \fBIsSet\fP ()"
.br
.ti -1c
.RI "static bool \fBExists\fP ()"
.br
.ti -1c
.RI "static T \fBGet\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
