.TH "testing::internal::CartesianProductGenerator< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CartesianProductGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::ParamGeneratorInterface<::std::tuple< T\&.\&.\&. > >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::std::tuple< T\&.\&.\&. > \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCartesianProductGenerator\fP (const std::tuple< \fBParamGenerator\fP< T >\&.\&.\&. > &g)"
.br
.ti -1c
.RI "\fBParamIteratorInterface\fP< ParamType > * \fBBegin\fP () const override"
.br
.ti -1c
.RI "\fBParamIteratorInterface\fP< ParamType > * \fBEnd\fP () const override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
