.TH "testing::internal::IgnoredValue" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IgnoredValue
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename std::enable_if<!std::is_convertible< T, Sink >::value, int >::type  = 0> \fBIgnoredValue\fP (const T &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
