.TH "testing::TestSuite" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestSuite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestSuite\fP (const char *name, const char *a_type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)"
.br
.ti -1c
.RI "const char * \fBname\fP () const"
.br
.ti -1c
.RI "const char * \fBtype_param\fP () const"
.br
.ti -1c
.RI "bool \fBshould_run\fP () const"
.br
.ti -1c
.RI "int \fBsuccessful_test_count\fP () const"
.br
.ti -1c
.RI "int \fBskipped_test_count\fP () const"
.br
.ti -1c
.RI "int \fBfailed_test_count\fP () const"
.br
.ti -1c
.RI "int \fBreportable_disabled_test_count\fP () const"
.br
.ti -1c
.RI "int \fBdisabled_test_count\fP () const"
.br
.ti -1c
.RI "int \fBreportable_test_count\fP () const"
.br
.ti -1c
.RI "int \fBtest_to_run_count\fP () const"
.br
.ti -1c
.RI "int \fBtotal_test_count\fP () const"
.br
.ti -1c
.RI "bool \fBPassed\fP () const"
.br
.ti -1c
.RI "bool \fBFailed\fP () const"
.br
.ti -1c
.RI "TimeInMillis \fBelapsed_time\fP () const"
.br
.ti -1c
.RI "TimeInMillis \fBstart_timestamp\fP () const"
.br
.ti -1c
.RI "const \fBTestInfo\fP * \fBGetTestInfo\fP (int i) const"
.br
.ti -1c
.RI "const \fBTestResult\fP & \fBad_hoc_test_result\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.ti -1c
.RI "class \fBinternal::UnitTestImpl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
