.TH "testing::TestEventListeners" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestEventListeners
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAppend\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBRelease\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_result_printer\fP () const"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_xml_generator\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTestSuite\fP"
.br
.ti -1c
.RI "class \fBTestInfo\fP"
.br
.ti -1c
.RI "class \fBinternal::DefaultGlobalTestPartResultReporter\fP"
.br
.ti -1c
.RI "class \fBinternal::NoExecDeathTest\fP"
.br
.ti -1c
.RI "class \fBinternal::TestEventListenersAccessor\fP"
.br
.ti -1c
.RI "class \fBinternal::UnitTestImpl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
