.TH "testing::internal::TestFactoryImpl< TestClass >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestFactoryImpl< TestClass >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::TestFactoryBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP * \fBCreateTest\fP () override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
