.TH "testing::internal::AssignAction< T1, T2 >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::AssignAction< T1, T2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssignAction\fP (T1 *ptr, T2 value)"
.br
.ti -1c
.RI "template<typename Result , typename ArgumentTuple > void \fBPerform\fP (const ArgumentTuple &) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
