.TH "testing::internal::TypeWithSize< 4 >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeWithSize< 4 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBInt\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUInt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
