.TH "testing::internal::RangeGenerator< T, IncrementT >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RangeGenerator< T, IncrementT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRangeGenerator\fP (T begin, T end, IncrementT step)"
.br
.ti -1c
.RI "\fBParamIteratorInterface\fP< T > * \fBBegin\fP () const override"
.br
.ti -1c
.RI "\fBParamIteratorInterface\fP< T > * \fBEnd\fP () const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
