.TH "testing::internal::ParamGeneratorInterface< T >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGeneratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::internal::RangeGenerator< T, IncrementT >\fP, and \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBBegin\fP () const =0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBEnd\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
