.TH "testing::internal::ParameterizedTestSuiteRegistry" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestSuiteRegistry
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class TestSuite > \fBParameterizedTestSuiteInfo\fP< \fBTestSuite\fP > * \fBGetTestSuitePatternHolder\fP (const char *test_suite_name, \fBCodeLocation\fP code_location)"
.br
.ti -1c
.RI "void \fBRegisterTests\fP ()"
.br
.ti -1c
.RI "template<class TestCase > \fBParameterizedTestCaseInfo\fP< TestCase > * \fBGetTestCasePatternHolder\fP (const char *test_case_name, \fBCodeLocation\fP code_location)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
