.TH "testing::internal::GTestLog" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::GTestLog
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGTestLog\fP (GTestLogSeverity severity, const char *file, int line)"
.br
.ti -1c
.RI "::std::ostream & \fBGetStream\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
