.TH "testing::TestEventListener" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestEventListener
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtesting::EmptyTestEventListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnTestProgramStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationStart\fP (const \fBUnitTest\fP &unit_test, int iteration)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestSuiteStart\fP (const \fBTestSuite\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseStart\fP (const TestCase &)"
.br
.ti -1c
.RI "virtual void \fBOnTestStart\fP (const \fBTestInfo\fP &test_info)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestPartResult\fP (const TestPartResult &test_part_result)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestEnd\fP (const \fBTestInfo\fP &test_info)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestSuiteEnd\fP (const \fBTestSuite\fP &)"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseEnd\fP (const TestCase &)"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (const \fBUnitTest\fP &unit_test, int iteration)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestProgramEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
