.TH "testing::internal::InvokeMethodWithoutArgsAction< Class, MethodPtr >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::InvokeMethodWithoutArgsAction< Class, MethodPtr >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBReturnType\fP = typename std::result_of< MethodPtr(Class *)>::type"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> ReturnType \fBoperator()\fP (const Args &\&.\&.\&.) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Class *const \fBobj_ptr\fP"
.br
.ti -1c
.RI "const MethodPtr \fBmethod_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
