.TH "testing::internal::TestMetaFactory< TestSuite >" 3 "Sun Sep 3 2023" "Version 8.0" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TestMetaFactory< TestSuite >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::internal::TestMetaFactoryBase< TestSuite::ParamType >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBParamType\fP = typename TestSuite::ParamType"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestFactoryBase\fP * \fBCreateTestFactory\fP (ParamType parameter) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
