.TH "TimerComponentSample" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimerComponentSample
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapollo::cyber::TimerComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInit\fP () override"
.br
.ti -1c
.RI "bool \fBProc\fP () override"
.br
.RI "The Proc logic of the component, which called by the CyberRT frame\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool TimerComponentSample::Proc ()\fC [override]\fP, \fC [virtual]\fP"

.PP
The Proc logic of the component, which called by the CyberRT frame\&. 
.PP
\fBReturns\fP
.RS 4
returns true if successful, otherwise returns false 
.RE
.PP

.PP
Implements \fBapollo::cyber::TimerComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
