.TH "Writer< MessageT >" 3 "Thu Aug 31 2023" "Cyber-Cmake" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Writer< MessageT > \- The Channel Writer has only one function: publish message through the channel pointed in its RoleAttributes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <writer\&.h>\fP
.SH "Detailed Description"
.PP 
The Channel Writer has only one function: publish message through the channel pointed in its RoleAttributes\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIMessageT\fP Message Type of the Writer handles 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Cyber-Cmake from the source code\&.
